### ISSUE TITLE
WebIDE Documentation needs to reference Android section

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1058]
Trying to get setup to use WebIDE, I run into a bunch of problems about not having `ANDROID` env variables set and such.

On closer inspection, the docs explain how to set this up, but in the Android section: http://webmaker-mobile-guide.mofodev.net/_docs/get_started/android.html

The Firefox WebIDE section should say something like, "make sure you go back and run through the android section, or you'll have trouble."

**Comment by secretrobotron** [comment]
Looks like the `brew install android-platform-tools` doesn't install the sdk where the docs suggest either. Currently trying the installer from http://developer.android.com/sdk/installing/index.html?pkg=studio.

**Comment by thisandagain** [comment]
:+1:

**Comment by secretrobotron** [comment]
Another little tip when trying to get Android Studio to run: http://stackoverflow.com/questions/27369269/android-studio-was-unable-to-find-a-valid-jvm-related-to-mac-os

**Comment by secretrobotron** [comment]
Also missing: install android-19 target.

**Comment by secretrobotron** [comment]
Also, a fun error when trying to run app on phone:
![screenshot 2015-02-12 12 33 22](https://cloud.githubusercontent.com/assets/403231/6173102/671f8a0c-b2b3-11e4-9e38-85db985a62c3.png)

**Comment by secretrobotron** [comment]
Pro-tip: remove `permissions` key (and value) from `webmaker-app-cordova/platforms/firefoxos/www/manifest.webapp`.

**Comment by thisandagain** [comment]
@Pomax is working on that last issue now.

**Comment by thisandagain** [comment]
Moving this along with a few other contributor / developer experience related tickets up to MWC. Thanks for pushing on this @secretrobotron ! :smile:
