### ISSUE TITLE
[MIGRATED] in the brick editor the word px is jargon

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1080]
Without starting a massive thread on font sizing, I'm pretty sure I can say that 99% of our users won't know what a px is.

**Comment by k88hudson** [comment]
This was mentioned in laura's research as well

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/25"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/25.
Please don't comment on it here.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/173"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/173.
Please don't comment on it here.
