### ISSUE TITLE
[MIGRATED] In the brick editor, showing the hex value of the color is odd/confusing to a a likely user

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1082]
Especially given the fact that we don't allow hex entry, I would argue that the simpler choice of only showing a swatch (and making it bigger) would make more sense.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/26"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/26.
Please don't comment on it here.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/174"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/174.
Please don't comment on it here.
