### ISSUE TITLE
investigate if we can make buttons vibrate the FFOS phone

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1103]
by default a FFOS phone will vibrate if you type on te keyboard or use certian buttons, it might be a useful thing to tap into the phone's settings and, if vibrate is on, vibrate the phone when any of the buttons in webmaker-app are pressed.

This might also make the issue of long activation times for buttons less problematic

**Comment by errietta** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/API/Vibration :open_mouth:

**Comment by gvn** [comment]
That sounds kind of annoying...but maybe that's just me.

**Comment by errietta** [comment]
On firefox os, the API will vibrate even if it's turned off in the device, but we can access the value of the vibration setting using https://developer.mozilla.org/en-US/docs/Web/API/Settings_API so we can probably avoid vibrating if it's turned off.
on chrome on android  (or at least in latest android lollipop / chrome 40), the vibration setting of the device is respected meaning if 'no interruptions' mode is on it won't vibrate.
on firefox on android we can neither access the setting nor does the browser prevent vibration if it's turned off in the os :cry:
