### ISSUE TITLE
[MIGRATED] RTL

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1151]
:point_left: :arrow_left: :point_left: :arrow_left::point_left: :arrow_left::point_left: :arrow_left: :point_left: :arrow_left: :point_left: :arrow_left::point_left: :arrow_left::point_left: :arrow_left: :point_left: :arrow_left: :point_left: :arrow_left::point_left: :arrow_left::point_left: :arrow_left: :point_left: :arrow_left: :point_left:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/27"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/27.
Please don't comment on it here.
