### ISSUE TITLE
Suggestions for string changes

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-android#1168]
In the en-US translation is seem everytime "App" is written its with a big "A" so maybe this show have big letter to:
"Open my app"

**Comment by scootergrisen** [comment]
In Firefox OS browser app when you want to add a bookmark on the homescreen it says:
"Add to home screen"

But in webmaker-app is says:
"Add to Homescreen"

So maybe those strings to be the same ?

**Comment by scootergrisen** [comment]
Maybe this string:
"You must include a text value"

Would be better with something like this:
"You must write some text"
or
"This field must have som text"

**Comment by scootergrisen** [comment]
It seems that some string are not on Transifex for me to translate.

Like the three buttons on the bottom "Discover", "Make", "My Apps".
The menu "Back to My Apps", "Share", "Delete".
"App Name", "From Scratch", "No data has been stored yet!", etc.

**Comment by scootergrisen** [comment]
Should "Discover" not be "Explore" like https://webmaker.org/en-US/explore ?

**Comment by thisandagain** [comment]
:+1: on s/Discover/Explore. Will try to unify after the design work week (next week).

**Comment by scootergrisen** [comment]
This string sounds like the person have to connect to the internet. But i'm guessing its the device that needs connecting:
"You need to connect to the Internet."

**Comment by scootergrisen** [comment]
Maybe this string should be something else, like internet connection instead of active connection:
"An active connection is needed to display the Discover Gallery"

Something like:
"Internet connection is needed to display the Discover Gallery".

And maybe Gallery should be with small g ?

**Comment by thisandagain** [comment]
Hey @scootergrisen closing this for now based on design changes, but would you be willing to advise us on strings for the updated version available on the `develop` branch? Installation instructions available here: http://mzl.la/webmaker-install

/cc @secretrobotron

**Comment by scootergrisen** [comment]
I just tested it in the simulator. I dont have a android phone.
There is not so much to test.
The 3 option in the menu in the top left corner did not work. Nothing happens if i select one of them.
