### ISSUE TITLE
Add "Feedback" button to profile view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1176]
I'd like to add a "Feedback" link to the profile view that provides an easy way for users to communicate with the product team. Ideally, this could be linked to desk.com but an email would be fine as a back-up.

I set-up an example [desk.com](http://www.desk.com/) account for reference / experimentation.

**Comment by gesa** [comment]
I'd love to add this view! Is there a design anywhere?

**Comment by thisandagain** [comment]
I'm on it!
