### ISSUE TITLE
[MIGRATED] Accessibility

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1213]
We need to do an accessibility (screen-reader) audit on the app prior to the 1.0 release.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/28"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/28.
Please don't comment on it here.
