### ISSUE TITLE
Share is publishing...

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/webmaker-android#1226]
When i make an app and select "Share" in the menu it says "Publishing...".
I would not expect that.

**Comment by thisandagain** [comment]
:+1: Great point. Ideas on alternate copy @k88hudson ?

**Comment by k88hudson** [comment]
@thisandagain what about something like "Preparing your app" or "Preparing to share"

**Comment by scootergrisen** [comment]
I havent fully tested the app but would it not be better to first save/publish the app.
And then afterwards have the option to share it, if you wish.
There dont seem to be a saving/publishing option.

**Comment by thisandagain** [comment]
@k88hudson :+1: on "Preparing..." or "Preparing to Share"

**Comment by alicoding** [comment]
@thisandagain @k88hudson I like the sound of `Preparing...` but it is a bit hard for some language since preparing doesn't use for these kind of terms much (tech related). What about `In progress...`, `Loading...` or just use some icon spinner to indicate that it's loading?
