### ISSUE TITLE
Standardize colour in Previews

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-android#1237]
As a user, I visit "My Apps". I get welcomed with a series of apps I've created in the past. I tap on one of them:

![screenshot 2015-02-19 11 44 56](https://cloud.githubusercontent.com/assets/1119821/6271137/be8f73e6-b82c-11e4-9138-bee1ac8f643a.png)

I press the "Back" arrow and choose to visit another app:

![screenshot 2015-02-19 11 45 38](https://cloud.githubusercontent.com/assets/1119821/6271150/d6f8e84a-b82c-11e4-90f1-d88e513189fa.png)

The section of colour is a challenge on both UX and UI.

- The user becomes confused as to why one is green and the other is yellow. Is one published and the other one not published?
- The different colours poses a challenge to the UI. The segmented control doesn't contrast enough when its yellow on yellow, as well as breaks the visual layout of the page.

**Proposed Improvement:**

Unify all Preview views to look like:

![screenshot 2015-02-19 11 50 42](https://cloud.githubusercontent.com/assets/1119821/6271259/8b06f0d4-b82d-11e4-9d21-1f28230d72e9.png)

- User is not confused anymore, everything is visually unified.
- The UI is actually consistent.

**Comment by thisandagain** [comment]
Any options for a compromise here? I'm wondering if we could stick with the black tint for the tab bar and navigational type but retain use of the user's color selection.
