### ISSUE TITLE
Display success message after installing

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#1257]
I installed webmaker on my Flame via mzl.la/installwm, and IT WORKED :+1: 

But, after the system said it installed successfully, I was left with a blue screen that said "installing..."

perhaps we need some kind of success message (if possible)?

similarly on android, it just says "downloading apk..." forever

**Comment by secretrobotron** [comment]
From @davidascher in #1291:
> If someone has never installed from a downloaded APK before, knowing that one has to scroll from the top and tap on the "Download Complete" notification may not be obvious.

> How about adding some language like:

> "Once the app has finished downloading, look in your notifications and tap on the notification to finish the installation process"?
