### ISSUE TITLE
Make it easier to add new icons / automate subsetting

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1261]
We should automate the building of our ionicon subset so it doesn't have to be done manually. It would also be nice to add our custom icons in (this is totally doable if they're formatted correctly)

**Comment by gvn** [comment]
I know there are at least Grunt plugins that do this, so I'm guessing it's do-able with Gulp.

If we do discover that app weight isn't a huge factor (eg: app is sideloaded) for our demographic then I'd recommend just loading the whole set.

**Comment by gvn** [comment]
Hopefully we can do something with less deps than:

`readline, sqlite, gdbm, openssl, python, libtool, gettext, libffi, glib, libpng, freetype, fontconfig, pixman, cairo, icu4c, harfbuzz, gobject-introspection, pango, zeromq, libsodium, cz, ruby, sass, xwindows`

![whaaa](https://cloud.githubusercontent.com/assets/206379/6307857/29a493f6-b8f4-11e4-9389-2590fdf7040a.gif)

**Comment by Pomax** [comment]
yo dawg, I heard you liked utilities
