### ISSUE TITLE
[MIGRATED] Build a notification system

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1282]
Especially until we get in the Play store, we'll have no way of communicating with users of the app until they get a new version (in particular, to let them know that a new version is available).  We should probably have a periodic check for a notice message and display of said notice message (once, or until dismissed).  I expect most of the time we'll use this to say things like "New beta version!", but who knows what we may end up needing to communicate w/ users.

We should have an l10n strategy for those notices as well.

/cc @thisandagain

**Comment by thisandagain** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/29"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/29.
Please don't comment on it here.
