### ISSUE TITLE
Document android installation with video tutorials

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1303]
We'd like to have some short video tutorials explaining how to get up and running on Android/cordova.

Let's scope this to installation instructions for now.

Topics:

### Install Android SDK/adb [*In progress*]
* install Android sdk tools via brew
* add to path
* check to make sure adb is running
* might want to let people know this will take a while
* non-verbal notes: installing brew, installing sdk tools through Android Studio (GUI)

### Install Android 19 SDK platform 
* type `android` in the terminal to open SDK manager
* check the `Android 4.4.2 (API 19)` box
* might want to let people know this will take a while
* notes: apps built with the `Android 19` platform will work on 5.0 devices, but I'm not 100% sure about 4.2. Can you verify this?

### Enable USB debugging on your device and connect to ADB
* record video of enabling USB debugging on device (4.4+) via https://play.google.com/store/apps/details?id=com.spectrl.rec
* record video of enabling USB debugging on device on 4.2 (someone with a 4.2 device will need to do this)
* allow the incoming connection on device (screenshot would probably be enough here)
* check that the device is connected via ADB (type `adb devices`)

### Remote debugging via Chrome dev tools (4.4 only)
* connect device via USB
* open Chrome (I find Canary is faster/better for remote debugging)
* open `chrome://inspect#devices`, click on 'Webmaker'
* you can now use the inspector, console, etc.

### Remote debugging via logcat (works on 4.2+)
* connect device via USB
* if you want ALL logs (from device features, etc.) type `adb logcat` when your app is running
* if you only want logs from cordova (i.e. what you'd expect in a web console, etc.) type `adb logcat CordovaLog:D *:S`

Other notes:

* Let's hold off on doing the webmaker-app/webmaker-app-cordova install stuff right now, since we're going to try to simplify this process soon
* Also hold off on weinre, emulator for now

**Comment by k88hudson** [comment]
cc @pippinlee

**Comment by pippinlee** [comment]
After doing some research, it looks like the Rec screen recorder app and a few others require a rooted phone. Will likely just use the `adb screenrecord` option for now 👍

[http://developer.android.com/tools/help/adb.html#screenrecord](http://developer.android.com/tools/help/adb.html#screenrecord)

**Comment by pippinlee** [comment]
Update with first versions cc @k88hudson

**Video 1: Developing on Android - Installing Android Debug Bridge (ADB)**

[<img src="https://cldup.com/lpsXElb4An.png">](https://www.youtube.com/watch?v=17g-pZM3rhU)

**Video 2: Developing on Android - Installing Android 19 SDK through SDK Manager**

[<img src="https://cldup.com/lpsXElb4An.png">](https://www.youtube.com/watch?v=yVFOKvT0xlk)

Feedback welcome!

**Comment by pippinlee** [comment]
Update:

**Video 3: Developing on Android - Enabling USB debugging on Android 4.4 and 4.2**

[<img src="https://cldup.com/lpsXElb4An.png">](https://www.youtube.com/watch?v=xZpqQ03pb60)

**Comment by pippinlee** [comment]
Update:

**Video 4: Developing on Android - Using Chrome's Inspector to debug Android apps**

[<img src="https://cldup.com/4iSJS_6PUT.png">](https://www.youtube.com/watch?v=2VAHnkdNuHk)

**Comment by pippinlee** [comment]
Update:

**Video 5: Developing on Android - Using logcat for remote debugging on Android 4.4 and 4.2**

[<img src="https://cldup.com/j6EESOwpdw.png">](https://www.youtube.com/watch?v=aXjZr2jkg3U)

In addition I added verbal note about pushing logs to a text file, which I thought should be useful.

Feedback welcome!

**Comment by thisandagain** [comment]
O_O This is incredible @pippinlee ! :+1:

**Comment by k88hudson** [comment]
Looking *awesome* so far pippin, thanks so much for working on this!

Specific feedback per video:

Video 1: Looks good to go I think!
Video 2: I would condense/shorten the content between 2:54 – 3:54, e.g. just cut out 2:54 – 3:17. All you really need to say here is that you need to select and install the Android 19 sdk tools, but if you want to save time just uncheck the default options. 
Video 3: This is great, it's missing one crucial step at the beginning though – turning on the developer tools menu. I think your phone already had them enabled which is why you didn't need to do it, but on 4.2+ you need to go to Settings > About phone and tap the Build number 7 times to enable the developer menu. Might be worth mentioning
Video 4: Haha, sweeeet. Love how you showed editing CSS. A couple of things 1) you should mention at the beginning that debugging via Chrome devtools is only available for devices running 4.4+, NOT 4.2. 2) I personally found the inspector is a little slow on Chrome stable, might be worth mentioning at the end if you're getting a lot of lag, try using Canary.
Video 5: Would be worth mentioning at the beginning of the video that logcat is the recommended method for debugging on 4.2, since you can't use Chrome devtools. The part where you play around with the app and look at corresponding logs runs a little long. Other than that, great!

General notes:
* Levels are a bit low in general, might be worth bumping up the volume (particularly for your first couple of videos)
* Would be nice to have Ricardo design a title screen – @vazquez do you think you could help with that when you get a chance?

Really excited to add these to the docs/share these around

**Comment by pippinlee** [comment]
Really appreciate the feedback notes! Super helpful.

Think most of these notes are fairly straightforward so shouldn't be a problem. Re-edits coming at you shortly 🙌

**Comment by vazquez** [comment]
Hey @pippinlee, what resolution do you need the title screen in?

**Comment by pippinlee** [comment]
1280x720 would be perfect @vazquez. Thanks!

**Comment by vazquez** [comment]
Okay here you go :)

![title-screen](https://cloud.githubusercontent.com/assets/1119821/6444104/619839b6-c0c9-11e4-944d-f310b6764674.png)


1280x720 - https://dl.dropboxusercontent.com/u/43783651/Mozilla/title-screen.png
2560x1440 (just in case you need retina support) - https://dl.dropboxusercontent.com/u/43783651/Mozilla/title-screen%402x.png

**Comment by pippinlee** [comment]
Oooooh looks good @vazquez

Adding in now 👌

**Comment by pippinlee** [comment]
New re-edits. Changelog:

**Video 1:  [Developing on Android - Installing Android Debug Bridge (ADB)](https://www.youtube.com/watch?v=USqpFEX_x80)**

* Increase levels (let me know if this is still too low)
* Update title screen


**Video 2:  [Developing on Android - Installing Android 19 SDK through SDK Manager ](https://www.youtube.com/watch?v=BBRrbtubZw4)**

* Increase levels
* Update title screen
* Make sdk package manager portion more concise

**Video 3:  [Developing on Android - Enabling USB debugging on Android 4.4 and 4.2  ](https://www.youtube.com/watch?v=idRdI2iN2Ek)**

* Update title screen
* Add video and verbal note about enabling developer mode on Android by tapping 7 times


Working on finishing video 4 and 5. *Feedback welcome*

Since I missed out on making a [levels](https://www.youtube.com/watch?v=_ovdm2yX4MA) joke earlier this will have to do.

![lvls](http://media.giphy.com/media/V1dIHQl5yQv1C/giphy.gif)

**Comment by pippinlee** [comment]
Last 2 re-edits. Changelog:

**Video 4:  [Developing on Android - Using Chrome's Inspector to debug Android 4.4 apps ](https://www.youtube.com/watch?v=JM1y3hyUU1Q)**

* Update title screen
* Add verbal note about how Chrome debug method only works on Android 4.4, not 4.2
* Add verbal note about Chrome Canary vs Chrome debug performance speeds



**Video 5:  [Developing on Android - Using logcat for remote debugging on Android 4.4 and 4.2 ](https://www.youtube.com/watch?v=FfgT4XtLuq4)**

* Update title screen
* Shorten time spend with logs and playing with the app
* Add verbal note mentioning `logcat` is only method to remote debug on Android 4.2 phones

**Comment by k88hudson** [comment]
1: levels still a bit low
2: levels jump up a lot around `0:52`. The cut works really well!
3: :dancer: 
4: add "on 4.4" to the end of the youtube title, just to make it even more clear. I'm actually thinking it might be worth adding some text to the screen to call out the 4.4 point even more, what do you think?
5: levels still a bit low

**Comment by pippinlee** [comment]
Thanks @k88hudson!

1: [re-recorded audio](https://www.youtube.com/watch?v=-d28E21PuRc)
2. [re-recorded audio](https://www.youtube.com/watch?v=10XXnYteAqA)

4. Going to pay attention to feedback we get and see if this necessary. Easy to add if we see it become a problem
5. [increased levels](https://www.youtube.com/watch?v=EPqz85xInQE)

I'll post the initial user feedback I received later today.

**Comment by pippinlee** [comment]
Notes from quick user test: [https://gist.github.com/pippinlee/638580690affb2c7eb3d](https://gist.github.com/pippinlee/638580690affb2c7eb3d)

Highlights:

* Working through videos takes ~40 minutes (excluding Android 19 download)
* It's more common to hear "Android 4.x" than "Android 19"
* Youtube videos should have links and add context to the contents of the videos
* Audio and video quality were fine for the most part
