### ISSUE TITLE
Text overflow on tab bar is awkward

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1309]
The best option visually here is to use ellipsis, but that would definitely affect the readability of the button. I think we should just tighten the line height and centre the text.

@vazquez what do you think?

![image](https://cloud.githubusercontent.com/assets/1455535/6353273/57849bca-bc16-11e4-80ab-f02f6265b6be.png)

**Comment by vazquez** [comment]
I think line-height and centering is definitely the way to go. :+1: However, we should still add a text-overflow ellipsis property as a fallback just to make sure that the view doesn't break.

**Comment by k88hudson** [comment]
Impossible to do on multi-line text, unfortunately... *cries*

**Comment by gesa** [comment]
I *might* have a css(-only) hack for multiline ellipsis. I'll take 15 min and see if i can make it happen.

**Comment by vazquez** [comment]
:jack_o_lantern: :+1:

**Comment by gesa** [comment]
okay false alarm couldn't pull it off. sorry @vazquez !

**Comment by vazquez** [comment]
Thanks so much for trying @gesa!

**Comment by gesa** [comment]
Assigning back to @vazquez for some design insight.

**Comment by gvn** [comment]
Maybe we could just get rid of the text and depend on icons only? We do this in other places...
