### ISSUE TITLE
Not able to add Screenshots from Firefox OS

### ISSUE THREAD

**Issue by viswaprasath** [mozilla/webmaker-android#1314]
I have added a small blog post
https://apps.mofostaging.net/p/-JiwMaBWYWlLlre-5VhJ/

But the problem is it is not accepting the screenshot which is taken in Firefox OS device.

Can you check it.
Firefox OS I am using is latest build updated today.
OS version 3.0.0.0
Build Number 39
build Identifier 20150224010314
Update Channel nightly

**Comment by thisandagain** [comment]
This is related to the way FFOS handles screenshots and internal / external storage. I will hunt down the corresponding Bugzilla ticket. Thanks for flagging @viswaprasath !
