### ISSUE TITLE
UI - Design icon for Android app

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1322]
It's not clear to me that the thread/needle logo is right. /cc @HPaulJohnson @thisandagain @cassiemc 

[not before MWC]

**Comment by thisandagain** [comment]
Not a P1 for this sprint, but I'd like to at least get some discussion rolling. 

/cc @vazquez @cassiemc @HPaulJohnson

**Comment by HPaulJohnson** [comment]
Quick take: Use the new/soon to-be-updated Mozilla icon. It has a much more contemporary look/feel and provides brand consistency.

**Comment by thisandagain** [comment]
@HPaulJohnson do we have any early / WIP visuals for that?

**Comment by HPaulJohnson** [comment]
Cassie and I got some previews a while back from Sean Martell. @cassiemc might have a more recent update and something shareable? If not, I can talk to Sean and share back.

**Comment by thisandagain** [comment]
@HPaulJohnson As @cassiemc is on PTO mind reaching out to Sean?

**Comment by HPaulJohnson** [comment]
Have reached out and will report back.

**Comment by HPaulJohnson** [comment]
Relevant excerpt from Sean's response re: timing of updated Mozilla branding: 

"I agree that updating the Webmaker branding would be the route to take.

As for the new Mozilla logomark, we're still in the works on that - with talks happening this week with the leadership team in Toronto - and we're looking at evolving the story behind it to make it more of an iconic snapshot of the health of the Web. We're now going forward looking into what that would involve.

We plan on having an internal unveil at Whistler, with the official launch in September with the updated Mozilla.org website.

I know that's well beyond the relaunch of Webmaker, so I'm not sure what we could do in the interim but great to get that conversation up n' running again."

Timing is less than ideal for us. I wonder if we should just use what we have until we can sync everything up in September?

**Comment by thisandagain** [comment]
Awesome. Thanks for the update... I'd recommend just a minimal iteration on the current logo then.

**Comment by cassiemc** [comment]
Wfm. My preference is toward the 1-color webmaker logo where possible (white on a colourful bkg), as it leans us toward a more neutral iteration, ripe for a rebrand, and is less interfering with the new UI aesthetic.

**Comment by thisandagain** [comment]
Sounds good @cassiemc . Can you post a link to an EPS / vector version of the 1-color logo?

**Comment by cassiemc** [comment]
Sure – it's on Drive: https://drive.google.com/a/mozilla.com/file/d/0BzfN9sXlOXt1b21XQW5ra2FaN1U/view?usp=sharing

Here's the flat: 
![webmaker_logo-one-colour](https://cloud.githubusercontent.com/assets/1186326/7138343/c234c0e2-e28d-11e4-90b7-7b11f67dfeb8.png)

**Comment by vazquez** [comment]
We have some colour options!

![ic_launcher 2](https://cloud.githubusercontent.com/assets/1119821/7238640/cdb84950-e771-11e4-895a-4a1db91e283f.png)

![ic_launcher 2](https://cloud.githubusercontent.com/assets/1119821/7238661/f4cb4c4a-e771-11e4-9091-a1057001d638.png)

![ic_launcher 2](https://cloud.githubusercontent.com/assets/1119821/7238691/1dbcac0c-e772-11e4-8d19-b4c6b664b9f4.png)

![ic_launcher 2](https://cloud.githubusercontent.com/assets/1119821/7238710/41742206-e772-11e4-811b-c34bdf32dbf9.png)

![ic_launcher 2](https://cloud.githubusercontent.com/assets/1119821/7238733/66d851ac-e772-11e4-9c7c-032f295c1410.png)

You can vote on Red Pen: https://redpen.io/hf4feefcc30f3f485d

**Comment by thisandagain** [comment]
Hard to evaluate out of context. Can you mock up on an Android (KitKat) home screen?

**Comment by cassiemc** [comment]
@vazquez where are the colours coming from? Would love to see some thoughts / rationale behind the choices and how they relate to the wider moz palette.

**Comment by vazquez** [comment]
Visit this Red Pen for a context view of the Android App Icon.

https://redpen.io/ax1de97055c7d5c3ff

@cassiemc You're right, I have adjusted the colour palette so that the icon aligns with the Mozilla palette.

**Comment by cassiemc** [comment]
Cool, thanks @vazquez. Would still love some rationale notes behind the colours. ie. what feeling are we trying to convey every time they touch the app icon? How do the colours work in various cultures? what does a colorblind person see? Just want to hear some thought around the decisions.

On the same note, feels like a missed opportunity (especially in context with the other app icons) to be a bit more conceptual and playful, and to refer to the theme of 'web making'. I'm okay with this simple logo as an interim solution, but I don't think it would take a long time to give this a bit more thought and make Webmaker stand out  more.

**Comment by xmatthewx** [comment]
> On the same note, feels like a missed opportunity

Agreed. 

@vazquez has his plate full completing the UI.

Here's a proposal: 
 - choose an icon for alpha/beta, and then 
 - fold icon design into a heartbeat for the new landing/download page, or a heartbeat for other brand work.

**Comment by xmatthewx** [comment]
To be included in SOW for contractor #1614

**Comment by thisandagain** [comment]
Tracking next steps in #2063
