### ISSUE TITLE
Duplicate share text on android when sharing using Textra SMS app

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#1325]
*OS:* Android 5.0.1

I can only get this to happen so far using the textra app on my phone. might be a bug in that app.

**Repro Steps:**
1. share app
2. select textra

**Expected:** generated share message + link in sms input area
**Actual:** see the share message + link twice in the text input area

**Comment by thisandagain** [comment]
Can't repro in the "SMS" or "Messages" apps, but will add to post-MWC backlog. Thanks @cadecairos
