### ISSUE TITLE
[MIGRATED] Would be really nice to have an image cropping function

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1330]
STR:
* add an image block
* pick an image from library
* oops, it's portrait, I just want a small bit of it, can I crop it?
* no i can't, gotta do all my image editing in separate apps, goshdarnit.

**Comment by davidascher** [comment]
http://mosch.github.io/react-avatar-editor/ might be quite handy here.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/30"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/30.
Please don't comment on it here.
