### ISSUE TITLE
something's generating the spinner twice, even when not used

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1334]
![screenshot 77](https://cloud.githubusercontent.com/assets/177243/6356864/3f383c3a-bc15-11e4-8f7e-f0cf9ba5527a.png)

reached this by going to "my apps" on Android and opening an app, then examining the DOM using chrome inspect

**Comment by k88hudson** [comment]
There are two cubes in the current design

**Comment by k88hudson** [comment]
Or did you mean something else?

**Comment by Pomax** [comment]
there are indeed. Notice the DOM has four. It has the two cubes twice.

**Comment by k88hudson** [comment]
Ah!! I see. That is indeed a bug ^_^

**Comment by Pomax** [comment]
closed because we don't have a spinner anymore
