### ISSUE TITLE
`gulp jscs` validation is inconsistent 

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-android#1339]
Sometimes builds succeed locally and on Travis when there are linting errors, which should have caused the test to fail.

See example scenario here:
https://github.com/mozilla/webmaker-app/issues/1218

**Comment by Pomax** [comment]
this isn't actually JSLint, but JSCS failing. `gulp lint` only tests for whether the code is potentially bad or broken, whereas JSCS tests code style. To verfiy correctness before a pull request, `gulp test` has to be run, rather than `gulp lint`.

**Comment by adamlofting** [comment]
Sorry, I think this is my misuse of terminology when I say 'linting is failing' (I couldn't personally tell you the difference between what jslint and jscs are doing).

The issue is that when I run `gulp test` before submitting a PR (and when Travis runs `gulp test` against my PR). A bunch of code style errors are not flagged up to me with any kind of warnings. But @gvn does see these warnings, after my code made it into master.

For example, if I swap the single quotes for double quotes in analytics.js, as flagged up by the error message in the linked bug, and then I run `gulp test` I don't get any errors.

If this is a non-issue, and I'm missing something, do just close this again though.

**Comment by Pomax** [comment]
ah, no if it's `gulp test` being nondeterministic, that's really bad and needs fixing. I don't suppose you'd have a reduced example of this?

**Comment by adamlofting** [comment]
Yes, playing around a bit further this morning this issue seems to be in `gulp jscs` rather than being caused by something in `gulp test`.

Scenario A: Swapping single quotes for double quotes in the first declaration in analytics.js doesn't flag any error when running `gulp jscs`

```
$ gulp jscs
[06:11:35] Using gulpfile ~/Sites/webmaker-app/gulpfile.js
[06:11:35] Starting 'jscs'...
[06:11:35] Finished 'jscs' after 323 ms
```

Scenario B: But, if I add a multiple var declaration, it does pick this up. (And doesn't flag the double quotes which can be seen in the output)

```
$ gulp jscs
[06:13:03] Using gulpfile ~/Sites/webmaker-app/gulpfile.js
[06:13:03] Starting 'jscs'...
[06:13:04] 'jscs' errored after 314 ms
[06:13:04] Error in plugin 'gulp-jscs'
Message:
    Multiple var declaration at lib/analytics.js :
     6 | */
     7 |
     8 |var a, b, c;
--------^
     9 |var xhr = require("xhr");
    10 |var localForage = require('localforage');
```

FWIW, here's my .jscsrc (pulled from master today)

```
{
    "preset": "crockford",
    "disallowDanglingUnderscores": null,
    "disallowMultipleVarDecl": true,
    "disallowSpacesInNamedFunctionExpression": null,
    "disallowSpacesInFunctionDeclaration": null,
    "requireLineFeedAtFileEnd": true,
    "maximumLineLength": {
        "value": 128,
        "allowComments": true,
        "allowRegex": true
    },
    "requireCurlyBraces": [
       "else",
       "for",
       "while",
       "do",
       "try",
       "catch"
    ],
    "requireMultipleVarDecl": null
}
```

**Comment by Pomax** [comment]
which versions of gulp and gulp-jscs are installed into your node_modules? While unlikely to be different, let's rule that part out. @gvn I guess same question for you?

**Comment by gvn** [comment]
"gulp-jscs": "1.3.1" (Per fixed version in `package.json`)

```bash
▶ gulp --version
[09:47:52] CLI version 3.8.8
[09:47:52] Local version undefined
```

**Comment by adamlofting** [comment]
Uppercase "Crockford" errors out:
```
AssertionError: Preset "Crockford" does not exist
```

adding `validateQuoteMarks: true` warns me about single quotes
```
Invalid quote mark found at lib/analytics.js :
     8 |var a, b, c;
     9 |var xhr = require("xhr");
    10 |var localForage = require('localforage');
----------------------------------^
```

adding `"validateQuoteMarks": "'"` reliably signals the quote symbols
```
Invalid quote mark found at lib/analytics.js :
     7 |
     8 |var a, b, c;
     9 |var xhr = require("xhr");
--------------------------^
    10 |var localForage = require('localforage');
    11 |var clone = require('clone');
```

Versions:
gulp-jscs: 1.3.1 (same as @gvn)

gulp is different though:
```
$ gulp --version
[12:50:08] CLI version 3.8.10
[12:50:08] Local version 3.8.11
```

**Comment by gvn** [comment]
We may want to consider locking the gulp version down in package.json.

**Comment by adamlofting** [comment]
I tried uninstalling gulp, and matching @gvn version numbers but that won't run for me.

```
$ gulp --version
[13:13:26] CLI version 3.8.8
[13:13:26] Local version undefined
$ gulp jscs
[13:13:32] Local gulp not found in ~/Sites/webmaker-app
[13:13:32] Try running: npm install gulp
```

Then I tried installing 3.8.8. to Local, but no luck either:

```
$ gulp --version
[13:15:54] CLI version 3.8.8
[13:15:54] Local version 3.8.8
$ gulp jscs
[13:15:58] Using gulpfile ~/Sites/webmaker-app/gulpfile.js
[13:15:58] Starting 'jscs'...
[13:15:58] Finished 'jscs' after 287 ms
```

**Comment by Pomax** [comment]
at this point it sounds like the simplest solution is to move away from the preset and simply take crockford's rules and put them in our .jscsrc file. That way we can also prune the rules we're currently marking as `null` because they're in crockford's preset but we don't want them.
