### ISSUE TITLE
Use case for app data not realized

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1358]
> I wanted to create a simple app that lets you set one goal for the day, together with a "reward" once you complete the goal.

> All I could do was to create a form that lets you submit the data, but you, as a user, can't easily see it -- and definitely not edit it.

> For reference, here is the published app: https://apps.mofostaging.net/p/-JixsgFtu31147T-yg17/

**Comment by crozzfire** [comment]
I am trying to figure out the same since hours now. For the prebuilt "Survey" app, for instance, what happens when I submit the data? Does it just get stored locally or POST to an http endpoint. Both have very strong usecases... Or perhaps I'm missing something here?

**Comment by secretrobotron** [comment]
> Does it just get stored locally or POST to an http endpoint.

It should provide the app's author with access to the data that was submitted. If you check out an app that you've created, you'll see an "App Data" tab, which will show you things that people who have used your app have submitted.

**Comment by crozzfire** [comment]
Got it, thanks!

**Comment by xmatthewx** [comment]
True. No longer relevant.
