### ISSUE TITLE
[MIGRATED] Contributor feedback: Stefan

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1359]
Several good points about UX and UI:

> I really like the design, although I do think that the bottom buttons could be a tad larger. Also, the fade in/out effect when switching (some) screens is a bit...I don't know, I did notice that this is a hybrid app it and the fadeout does make it feel more like a website than an app.

> For the record, I am using Moto G (2nd Generation) with the latest Android, so maybe it just clashes with the rest of the UI.

> That's really not a big deal, but the app does feel a bit clunky. At first I had problems using the "back" button (kind of like when you use a website and the "back" button doesn't actually get you to the previous page, because the site adds parameters to the URL, or something).

-
> I ended up with quite a few "Apps made from scratch" -- which also made me notice how difficult it is to delete multiple items: you have to click each, then open them, then click the delete button and confirm. I don't think people will often have to delete multiple apps, but still, something to maybe think about.

-
> Although, is it a good idea to add such functionality -- including the Make a Phone Call button? Seems like it would be too easy to abuse this by spammers.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/31"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/31.
Please don't comment on it here.
