### ISSUE TITLE
The Install Service Tucan Hates Linux

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#1401]
He won't tell me why I can't download Webmaker:

![tucan-sam is mean](https://cloud.githubusercontent.com/assets/438003/6419305/01e2b8ca-be8a-11e4-8dd2-ae7bbfd795e2.png)

It looks like the Fira Sans fonts from google are failing?

"downloadable font: maxp: bad max_zones: 0 (font-family: "Fira Sans" style:normal weight:normal stretch:normal src index:2) source: https://fonts.gstatic.com/s/firasans/v5/EjsrzDkQUQCDwsBtLpcVQVtXRa8TVwTICgirnJhmVJw.woff2"

**Comment by cadecairos** [comment]
also, we should avoid using Google fonts because it can be used by google to track people

**Comment by errietta** [comment]
@cadecairos  had the same problem before. Fira sans from Google is broken. I use the one from Mozilla CDN, i.e.:

        <link rel="stylesheet" href="//code.cdn.mozilla.net/fonts/fira.css">
