### ISSUE TITLE
Crash when trying to edit an app

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1402]
Trying to edit an existing app. Webmaker app says it can't find it, but there's a crash, and an error.

![screenshot 2015-02-27 14 06 50](https://cloud.githubusercontent.com/assets/403231/6419286/e34ce91c-be89-11e4-88a9-2fde4d09d5eb.png)

```
Uncaught TypeError: Cannot read property 'id' of null index.js:15860
```

App id is -Jj3xa33tb9ff_MTRMbz

**Comment by secretrobotron** [comment]
I'm only able to do this by typing in an app url manually.

**Comment by k88hudson** [comment]
This is because you're trying to edit a make from the `wm-app` db on the mofodev site that uses the `webmaker-app-dev` db

**Comment by secretrobotron** [comment]
Yeah, totally. I'm more interested in the crash though. Is that how you tell if something isn't in the db?

**Comment by k88hudson** [comment]
you're right, crash shouldn't throw. is the function local enough that it just borks this screen or can you get back to your profile ok?

**Comment by secretrobotron** [comment]
yep!
