### ISSUE TITLE
Random 404

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#1403]
On FirefoxOS 2.1 (Flame) using RC2 (I think)

STR:

1. Create an app from scratch
2. add text brick
3. edit text brick
4. without making any changes, try to save text brick by clicking the confirm button (it should turn grey)
5. keep pressing the confirm button until the entire app closes and you get back to the starting page.
6. Click from scratch
7. press the back button
8. See pretty red 404 page :)

**Comment by cadecairos** [comment]
Can't repro on Android 4.4.4

**Comment by gesa** [comment]
Repro'ed on Flame
