### ISSUE TITLE
Adding large image fails without notice

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1413]
Android 4.4.4

**Scenario**: Adding an image from device gallery works fine, except when I try to add a large 9.8mb animated gif. It fails. 
**Expected**: Notification that adding failed or image was too large. Suggestion to try again. 
**Actual**: App gracefully returns to the choice between camera and gallery, but doesn't include any info about failure.

**Comment by k88hudson** [comment]
Let's add an error message
