### ISSUE TITLE
lib/storage defines an object type App inline, instead of as a regular object type

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1425]
https://github.com/mozilla/webmaker-app/blob/master/lib/storage.js#L60 has a full object type with prototype inline-defined, which means it gets redefined, locally scoped, on each call. We should *really* rewrite that to be a lib-scoped single object `App`, with proper construction.

As is, JSCS will trip over the nested this/that/self bindings, and the only real way to fix that is by lifting this code to the correct depth (most of that can be fixed because almost all the `self` references inside App aren't actually necessary)

**Comment by gvn** [comment]
Maybe for now we should exclude this file from the linted group and do a follow on ticket to refactor it?

**Comment by Pomax** [comment]
I can clean it up *mostly*, leaving only the warning for `var that = this` so I'm okay with not excluding it for now, lifting out the `App` type is probably doable as part of the style cleanup

**Comment by thisandagain** [comment]
Great catch @Pomax :+1:

**Comment by Pomax** [comment]
cleaned it up a little more so that linting/tests pass, but `App` can be moved out easier. I'll do the actual moving out after #1426 lands.

**Comment by Pomax** [comment]
#1425 has landed. Let the App moving begin!
