### ISSUE TITLE
[MIGRATED] Marketing - Produce updated "trailer" video

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1456]
Produce updated trailer video that walks through some of the new features and UI developed for the release version of the Webmaker app. Old video: https://vimeo.com/101748208

- [ ] Write script
- [ ] Finalize assets for each screen (@vazquez)
- [ ] Select new music track
- [ ] Produce animation wireframe cut to music
- [ ] Drop-in final assets and render

**Comment by thisandagain** [comment]
Needs less corny music. :stuck_out_tongue_winking_eye:

**Comment by thisandagain** [comment]
Rough script outline. Thoughts @flukeout @xmatthewx @secretrobotron @vazquez @sabrinang @cassiemc ?

#### Features
- Discover
- Tile navigation (aerial)
- Editing tile
- Adding a component
- Editing a component
- Tinker mode
- Sharing
- Remix?

#### Outline
- Show icon on Android (KitKat) home screen
- Show launch screen (?)
- Show discover view
- User scrolls and selects a project
- ???? @flukeout 
- Show aerial view
- Show user navigating between tiles
- Show user remix the project
- Show user add a component
- Show user edit a component
- Show tinker mode
- Show sharing / publishing flow
- Show another device getting an SMS
- Show another device opening the project
- Mozilla (Webmaker?) brand mark

#### Questions
- First time use experience?
- Do we want to show a remix flow?

**Comment by xmatthewx** [comment]
I would add:
 - Show user add a button and link to another tile

Remix could be the final scene. Allude to it after the audience has a fuller understanding what they'd remix and why they would do it. 

There are a few important [FTU prompts](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-BtEXs64VAnY8MGkZxkK_mncXfzkVwf15pw8371exXw/edit#slide=id.gac9169e11_24_2) in the editor. We don't have FTU for nav, yet.

**Comment by thisandagain** [comment]
:+1: Good catch. Similar to the old video we could show the user share and then have the next device do the remix. I think the only question that raises is do we want to show the first user start from scratch?

**Comment by thisandagain** [comment]
Picking back up this thread. @xmatthewx and @vazquez do you folks feel like we have the UI at a place where we can get moving on this?

**Comment by xmatthewx** [comment]
Almost. We'll need content for the project made within the video.

Remix was interesting, but I wonder if the evolution toward pages would be better with:
 - user A makes a thing and shares it
 - user B links back to user A

@vazquez - take a look at the script outline above for missing bits. Let's talk content.

**Comment by xmatthewx** [comment]
cc @secretrobotron  re: content in video

**Comment by thisandagain** [comment]
Pushing this back until UI is stable.

**Comment by secretrobotron** [comment]
Reached out to MoCo creative team for some help here: https://bugzilla.mozilla.org/show_bug.cgi?id=1164079

**Comment by secretrobotron** [comment]
Happenin'. Will chat with Rainer next week.

**Comment by secretrobotron** [comment]
Filming today :).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/32"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/32.
Please don't comment on it here.
