### ISSUE TITLE
[MIGRATED] UI - First time use

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1459]
Design first time use (FTU) prompts and screens. Some initial work can be seen in the UI notebook: 
https://docs.google.com/a/mozillafoundation.org/presentation/d/1-BtEXs64VAnY8MGkZxkK_mncXfzkVwf15pw8371exXw/edit#slide=id.gac9169e11_24_2

- [x] Add a tile prompt
- [x] Edit a tile prompt
- [x] Move a tile prompt
- [x] Add an element prompt
- [ ] Empty project list in Make view

Blocks https://github.com/mozilla/webmaker-app/issues/1456

edit: moving first launch to #2353

**Comment by xmatthewx** [comment]
We might add Move a tile to the list. Of all the things you can do, this might be the least obvious affordance.

**Comment by thisandagain** [comment]
:+1: Added to checklist.

**Comment by xmatthewx** [comment]
- [ ] edit text string, button string

**Comment by xmatthewx** [comment]
Goal for this heartbeat:
 - revised list of mvp `v1` FTU touch points @flukeout 
 - copy for each item @flukeout 
 - UI for a basic tooltip @vazquez 
 - I think that a rich FTU experience is out of scope for now ... correct me if I'm wrong. 

@secretrobotron will drive this

**Comment by secretrobotron** [comment]
Clarification: very simple FTU experience for beta (e.g. popups like, "click here to add an new item! lol!"), not several slides of all the awesome stuff you can do (which could be part of SOW for illustrator cc @thisandagain).

**Comment by flukeout** [comment]
@secretrobotron I started some of this work, which you can check out in #1565

**Comment by flukeout** [comment]
Here's a list of FTU popups with a rough sequence & conditions for showing them:
[First Time Use Popups](https://dl.dropboxusercontent.com/u/109902/tiles/first-time-use-popups.pdf)

@vazquez @secretrobotron @LauraReynal - Let me know what you guys think and if anything seems missing or is too obvious to bother having a popup for.

**Comment by LauraReynal** [comment]
:+1: Great ! thanks @flukeout  

From what I could see with the interviews here, nothing is too obvious in the document you drafted. 
The major concerns are addressed, so It might be enough for beta. 

Then we can think of saving / sharing etc.

**Comment by xmatthewx** [comment]
@flukeout - This looks like a good set to test. Do you know the status on this? Was there any conversation on whether we have the capacity to implement this?

**Comment by LauraReynal** [comment]
Hey Folks, now that people are actually making stuff on the app, here are more FTU to consider, which are important. 

* Sign-up / sign- in / register : Most people failed to sign - in / register today. 
=> there was often a few mistakes and the yellow message was generally not read/ seen. Maybe a tucker jumping and saying : You forgot your capital letter . might be more effective ? I'll let you decide.
cc/ @vazquez 

* People dont name their projects and never click on project settings. Can we close the loop after we teach them how to make and give them some details about name/ settings and sharing ?

cc. @flukeout @xmatthewx @thisandagain

**Comment by xmatthewx** [comment]
@LauraReynal - some improvements to login are in process: gentler and more informative error messages; easier password requirements. 

Project naming might solve itself when people actually use Discover and Make. But it might not. I will file a separate bug so we can keep an eye on this and discuss options if necessary.

**Comment by thisandagain** [comment]
@xmatthewx @vazquez Is it reasonable to request that this be ready to implement by the end of the next sprint? I'd like to be able to include this in 1.0.3.

**Comment by vazquez** [comment]
Just a quick note that I'm on PTO today and tomorrow, July 1st is Canada
Day and away on July 8 - 10 talking at Cascadia conference.

On Monday, June 29, 2015, Andrew Sliwinski <notifications@github.com> wrote:

> @xmatthewx <https://github.com/xmatthewx> @vazquez
> <https://github.com/vazquez> Is it reasonable to request that this be
> ready to implement by the end of the next sprint? I'd like to be able to
> include this in 1.0.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-android/issues/1459#issuecomment-116740439>
> .
>


-- 
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by xmatthewx** [comment]
@vazquez - we'll essentially have 3 weeks to revisit the FTU contextual help already designed, refine it based on latest tests, and annotate the IxD for the build.

**Comment by vazquez** [comment]
:+1:

On Monday, June 29, 2015, matthew w <notifications@github.com> wrote:

> @vazquez <https://github.com/vazquez> - we'll essentially have 3 weeks to
> revisit the FTU contextual help already designed, refine it based on latest
> tests, and annotate the IxD for the build.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-android/issues/1459#issuecomment-116756367>
> .
>


--  [[unflagged]](http://plzkthx.herokuapp.com)
Ricardo Vazquez
UI Designer, Webmaker
Mozilla Foundation
@iamrvazquez <http://twitter.com/iamrvazquez>
IRC: ricardo

**Comment by xmatthewx** [comment]
Moving first-run experience to #2353

**Comment by xmatthewx** [comment]
@flukeout  & @vazquez - plan to meet next week to nail down the UI and spec IxD. Beyond the browser player, this is one of your top priorities.

**Comment by xmatthewx** [comment]
@flukeout - I saw a new spec by you on this. Can you drop a link or file here?

**Comment by xmatthewx** [comment]
@vazquez - Let's add your updated UI here.

**Comment by flukeout** [comment]
Here it is https://dl.dropboxusercontent.com/u/109902/tiles/ftu-editing.pdf

**Comment by vazquez** [comment]
The UI file is available on the Google Drive: https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_Z0puOExNTlFCOVU/view?usp=sharing

![screenshot 2015-07-13 10 56 13](https://cloud.githubusercontent.com/assets/1119821/8652660/d47a1f5c-294d-11e5-943f-393c56564ad9.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/33"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/33.
Please don't comment on it here.
