### ISSUE TITLE
Compat - Use crosswalk instead of WebView

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1467]
To get the app to run cleanly across versions of Android, we should replace the detail WebView API with [Crosswalk](https://crosswalk-project.org/). The APIs are very similar which is great, but we'll need to modify our build process to create both ARM and Intel APKs in embedded mode. More information here: 

http://developer.android.com/google/play/publishing/multiple-apks.html
https://crosswalk-project.org/documentation/getting_started/run_on_android.html#shared-vs-embedded-mode

**Landing crosswalk should coincide with the application supporting >= Android 4.2.**

**Comment by ryanw-ny** [comment]
@thisandagain Was there any reason why this was moved back to Alpha 2/2?

**Comment by thisandagain** [comment]
Nope! We just ran out of time and had to push it.

**Comment by thisandagain** [comment]
@jbuck Is this something you might have some time to help us with?

**Comment by k88hudson** [comment]
@jbuck @thisandagain are we still on track to do this for alpha?

**Comment by k88hudson** [comment]
Personally I would recommend pushing

**Comment by thisandagain** [comment]
@jbuck when do you think you'll have time to get this done. Happy to push to Beta 1/2 (next sprint).

**Comment by jbuck** [comment]
@thisandagain Yeah lets push it

**Comment by ryanw-se** [comment]
@thisandagain If nobody is currently working on this, I'd be happy to work on this!

**Comment by thisandagain** [comment]
@ryanw-se Awesome. I say go for it ... though we have a little bit of time pressure on this. Do you think we could look at a PR some time mid-next week? If not, we'll keep it with @jbuck .

@jbuck is that ok with you?

**Comment by ryanw-se** [comment]
@thisandagain Next week? I'll have a PR in tomorrow.

**Comment by jbuck** [comment]
@ryanw-se fine by me!

**Comment by jbuck** [comment]
Er, that's @thisandagain fine by me. :+1:

**Comment by thisandagain** [comment]
:boom: :smile:

**Comment by k88hudson** [comment]
Super exciiiiting

**Comment by thisandagain** [comment]
Landed in #1872
