### ISSUE TITLE
[MIGRATED] v1 - Add JS linting & style enforcement

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1469]
Integrate `mofo-style` with JSCS as per code on `master`.

**Comment by gvn** [comment]
Added js(x)hint. Still need to add JSCS...

**Comment by gvn** [comment]
https://gist.github.com/hahahana/3d5fa343f850f4c7fdc3

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/34"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/34.
Please don't comment on it here.
