### ISSUE TITLE
v1 - Re-Integrate Universal Analytics

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1472]
https://developers.google.com/analytics/devguides/collection/android/v4/

/cc @adamlofting

**Comment by thisandagain** [comment]
This should be a consideration while building the `router` @k88hudson

**Comment by ryanw-ny** [comment]
@thisandagain Is there anything that this is dependent on, before it can be implemented?

**Comment by thisandagain** [comment]
Nope! Would you like to take this one?

**Comment by thisandagain** [comment]
@ryanw-ny Nope! Would you like to take this one?

**Comment by ryanw-ny** [comment]
@thisandagain Sure! Will this be a basic setup or is there anything in particular that is going to be tracked? It'll probably take me a few days to do some solid research before I dive into this, since I haven't used google analytics before :smile:

**Comment by thisandagain** [comment]
Not a problem at all! Pretty basic for starters, we just need to track each activity view. :smile:

**Comment by adamlofting** [comment]
I've not had a chance to look at the app codebase yet, but in case it's useful or provides any prompts we have this library for instrumenting react websites: https://github.com/adamlofting/react-ga/

But if we're using the Android SDK, it will likely be a bit different. I'll be on leave next week, but happy to help review / feedback when I'm back online.

**Comment by thisandagain** [comment]
@ryanw-se Looks like your latest patch is coming through. Want to send along a PR for final testing / review?

![screen shot 2015-05-12 at 8 31 42 pm](https://cloud.githubusercontent.com/assets/747641/7603312/ecea73c2-f8e5-11e4-930c-4ba15039b133.png)

**Comment by ryanw-se** [comment]
@thisandagain Once I sort out some compatibility issues with older devices I will send a PR! :-)
