### ISSUE TITLE
Chicago - Feedback from testing

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1503]
Will share some feedback from the testing sessions here so that you can have regular updates. 
Feel free to add questions that we can ask while we are there. 
@xmatthewx @flukeout @sabrinang @vazquez @thisandagain @secretrobotron 

**Feelings / First impressions**
- This looks like Pinterest - where you can make your own collections (very often)
- It looks like Prezi ( almost each testing) -- *only one person did not mention it so far.*
- It looks like instagram
- It looks like a game
- It looks like a collection of photos 
- It looks like you make a website 
- It makes me think of Angry Bird 
- It looks like its for creating slideshows
- It reminds me of a mini blog 

**Features required**
- we should be able to have tags in the gallery, to find all the creations from Chicago
- Can we have this as a downloadable software ? so that it can work offline ?
- Can we add background colors ? Especially background photos (in the zoom out view ) That would motivate me, and also it's really YOU
- Add hashtags search
- Add search in the projects
- Let you search images on the web
- Possibility to add videos as a brick (and audio ) (each teen asked for it ) I would suggest integrating with Vine which is super popular and you tube 
- Ability to have audio playing when people arrive in your project (“I heard that once on a website and now I want to it for my hairstyle)
- Gaming features 
- Ability to draw with the paintbrush photos ( like on snapchat)
- Ability to add stickers and emoji ( That’s really MVF) 
- Ability to have a background image for your whole project ( like in Luke prototype its the dark blue, here it would be possible to replace it with a photo)

**Tinker Mode**
- Idea to call it the "advanced mode"
- idea to bring more graphic design learning into tinker mode
- Is there a prompt that leads you to the code editor ?
- "I love it, I would definitely use it instead of the colors because I want to be unique"
- Its similar to the way you choose colors in snapchat and word, yes i have seen it before, its pretty normal (not seen as learning, just seen as customization)
- People like it more in general (90 % ) rather than the other colors because of the customization possible. 
- Icon is mostly understood 

**Zoomed out view**
- It looks like there is a limit to the number of pages you can add
- I think I need to swipe to add pages
- Is this to make a website ? It looks like its too make a website but it's a bit confusing
- It's like prezi
- I really llike the zoom out, Its super nice. you can see everything (15 and 15 yrs old)

**Learning**
- - Its great that you do the "secret learning" (educators )
- Where do you access code editing? (mobile demo)(educators )
- You don't struggle enough in this scenario, there is no puzzle to solve, its too easy (educators )
- I knew about this way of picking colors already
- The color thing on tinker mode does not bring learning - teenagers know this already, they see it in word, and other products - they say its classic (laura's feedback)

**Remix**
- Can you edit someones’s project and built from that, I like that .
- If we can remix I would totally color this comic book and add something to the story (Luke's prototype)
- Its great if we can remix and we know who started the project
- Oh yes make me viral

**Users**
- Youth are more likely to start using with a prompt, and then they might keep having fun with it (prompt = event or specific project)
- Templates are seen as something that would prompt users to click, they like to see what is possible ( visible on all other product benchmarks as well)
- Definitely interesting for teens here - Older students don’t really see the need but I suspect it might be the tucker effect. 

**Areas of improvement**
This prototype is limited, you don't see the community, the sharing, It seems like you can't add much content. Can we have a full experience designed sketches so we can show it to users? We are currently demoing on both the intro deck (remixed) and Lukes prototype. So images only would be fine.

**Comment by flukeout** [comment]
Thanks Laura - I've updated the prototype you might have used earlier today.
http://flukeout.com/examples/tiles-nav-2/ prototype

It's now themed to be an example of a play/consume experience of a Yam Fries recipe.
Let me know if you have any questions about it and let's take some time to chat tomorrow when you're available.

**Comment by LauraReynal** [comment]
Hey @flukeout thank you for doing that :dancer: 
We will let you know how it comes out during testing. Ping me on skype if need to chat !

**Comment by LauraReynal** [comment]
Other links from Luke 

[14/04/2015 14:49:12] Luke Pacholski: http://flukeout.com/examples/tiles-nav-2/?project=yams
[14/04/2015 14:49:19] Luke Pacholski: http://flukeout.com/examples/tiles-nav-2/?project=atkins

**Comment by LauraReynal** [comment]
**Tinker Mode**
- Idea to call it the "advanced mode" 
- idea to bring more graphic design learning into tinker mode
- Is there a prompt that leads you to the code editor  ? 

**Zoomed out view**
- It looks like there is a limit to the number of pages you can add
- I think I need to swipe to add pages 
- Is this to make a website ? It looks like its too make a website but it's a bit confusing 

**Areas of improvement**
- as it is its too limited, you don't see the community, the sharing, It seems like you can't add much content

**Comment by xmatthewx** [comment]
@LauraReynal - social features (e.g. :heart: :speech_balloon: :horse_racing: ) will be added in a future release later this year.

**Comment by LauraReynal** [comment]
** Branding: from a 15 year-old: "I like Webmaker, its a cool name, but if you call it Makers of the Web, and I see that in Google play store. I would totally click it. Well because I want to make the web too!"

cc / @HPaulJohnson

**Comment by LauraReynal** [comment]
cc/ @cassiemc

**Comment by LauraReynal** [comment]
I put all of this on a google doc also, that we update every day or every couple day 
so maybe you'd like to use it to add comments on specific topics. One week left in Chicago, so shoot ! 
https://docs.google.com/a/mozilla.com/document/d/1EjcWaSi8J6tTeUTB1mSAa8y8xj8RK1YBzCWZL9f_FR0/edit?usp=sharing

**Comment by LauraReynal** [comment]
Also @flukeout a teenager asked me why you draw someone who receives acid on his face in the comic book ? :smile: :smiley_cat: It's definitely the favorite example.

**Comment by flukeout** [comment]
Great feedback so far @LauraReynal - we'll also be tracking some user testing stuff here - #1548

**Comment by LauraReynal** [comment]
OH ! Its great to see the user testing results on  #1548 thanks for sharing :) 

@sabrinang and I updated the Google Doc here https://docs.google.com/a/mozilla.com/document/d/1EjcWaSi8J6tTeUTB1mSAa8y8xj8RK1YBzCWZL9f_FR0/edit?usp=sharing with the feedback in preparation from our tuesday call. 
Feel free to ask questions beforehand.

**Comment by LauraReynal** [comment]
@HPaulJohnson there is a part on "What Webmaker makes you think of ?" in the above document.

**Comment by thisandagain** [comment]
Closing this for now pending feedback from Bangladesh. Thanks @LauraReynal !
