### ISSUE TITLE
Build - Sign In and Sign Up

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1522]
UX is largely complete for the experience within login and sign up (flow & error states). Let's draft wireframes to articulate where and when this starts, and what happens after.

**Comment by xmatthewx** [comment]
Here's a list of potential join/login scenarios. Flagged a few things `BETA` vs `RC`. All open for debate. 

#### Question
 - Will any of this impact services plan by @cadecairos @jbuck 

#### Make view
  - offers create new w/o auth
  - offers join/login
   - login --> make view
   - join --> make view `BETA` OR editor w/ FTU `RC??`

#### Editor
 - prompts join/login on share attempt
  - login --> share flow
  - join --> welcome `RC??` --> share flow `BETA`

 
#### Etcetera

 - I assume that a project in discover doesn't require auth to share.
 - Wonder -- should we prompt to login/join in editor after X minutes or edits? `RC??`


cc @secretrobotron @simonwex @thisandagain @k88hudson

**Comment by simonwex** [comment]
@xmatthewx on your assumptions, auth is required to share if we are sending anything on the user's behalf. -- it depends on the sharing UX

**Comment by thisandagain** [comment]
We ran into some issues with legal in our MWC build with allowing "guests" to create content. I propose we remove that requirement which also reduces the amount of UX surface area where we need to prompt sign-up (sharing).

**Comment by simonwex** [comment]
I actually think the anonymous publishing is why saving/publishing has historically been a confusing experience in Webmaker.

**Comment by xmatthewx** [comment]
Revised and clarified:

#### Make view
  - ~~new user can start project w/o auth~~
  - offers join/login
   - login --> goes to make view
   - join --> goes to editor w/ FTU

#### Editor
 - accessible only when logged in
 
#### Discover view
 - User A can view a project by User B w/o auth
 - User A can share User B's project via Android services w/o auth (nothing sent by us)

**Comment by thisandagain** [comment]
:+1:

**Comment by vazquez** [comment]
@flukeout - Do we have wireframes for this?

**Comment by flukeout** [comment]
@vazquez No, starting on it now - will ping you.

**Comment by flukeout** [comment]
First stab at Join & Sign In pages.

![image](https://cloud.githubusercontent.com/assets/25212/7379355/2fbdd600-eda9-11e4-94bf-24fd2271d5f1.png)

**Comment by xmatthewx** [comment]
For reference, here is UX for the guts of login. https://docs.google.com/presentation/d/1fkF7PBcvae3eDXTFVllLRz2Sk_gPPKqui9dsvuLY4h8/edit#slide=id.g63a9d7045_014

**Comment by flukeout** [comment]
Also, we're just basically following the flow from the teach site, check it out here:
https://teach.mozilla.org/

First pass at mobile UX:
![image](https://cloud.githubusercontent.com/assets/25212/7379798/3645a2b6-edac-11e4-9835-d49edd50318d.png)

Next up, treatment of the non-signed-in state of the Make page.

**Comment by xmatthewx** [comment]
@flukeout - Good to think about. A visitor who clicks remix would be a terrible person to lose. 

In an ideal world, they could start to play with remix before hitting the sign up flow. But, I think the team wants to avoid the complexity of anonymous projects (messy UX and engineering concerns). 

It seems like your Make view above could work for these people if we finesse the copy well. Let's remember to note this as we transition from UX to UI. 

Android back button would be required to return them to the project if they choose not to join.

**Comment by flukeout** [comment]
@xmatthewx Okay - will move Remix flow stuff to #1566

**Comment by xmatthewx** [comment]
@cassiemc - What UX concerns appeared while implementing login on the teach site? Anything that we will also need to tackle? Plz share any notes you've got. A link to your artwork for reference would also be useful.   

cc @secretrobotron

**Comment by xmatthewx** [comment]
@flukeout to add diagram here. then reassign to @vazquez for UI next heartbeat

**Comment by flukeout** [comment]
[Sign In Flow UX Diagram](https://dl.dropboxusercontent.com/u/109902/tiles/sign-in-flow.pdf)

**Comment by xmatthewx** [comment]
cc @k88hudson

**Comment by xmatthewx** [comment]
A few notes on Beta build
 - require sign-up/log-in on app launch (we can improve this experience in a future release)
 - app does not include means to change username or email (address in Q4)
 - lost password links to existing browser-based flow

@k88hudson will prep a spec based on @alicoding's work on teach site.  
@vazquez will draft UI based on UX above https://github.com/mozilla/webmaker-android/issues/1522#issuecomment-97201569

**Comment by vazquez** [comment]
## UI Progress

### Intro Screen

When app is launched, the user lands at the Intro screen.

![login intro](https://cloud.githubusercontent.com/assets/1119821/7596617/156d47c6-f8bd-11e4-96ab-e304f4629df3.png)

---

### Join Webmaker

If user taps `JOIN US`, we will present them with the Join Webmaker screen.

![join](https://cloud.githubusercontent.com/assets/1119821/7596903/5a3ea4de-f8be-11e4-981b-16c9bb1f0849.png)

---

### Sign In

If user taps on `SIGN IN`, we will show them the Sign In screen.

![sign in](https://cloud.githubusercontent.com/assets/1119821/7596908/5fd8548a-f8be-11e4-9397-2d4f9b889a58.png)

---

### Sign In (Active Textfield)

When a field is focused, the label and textfield opacity goes to 100%.

![username active](https://cloud.githubusercontent.com/assets/1119821/7596677/86097f90-f8bd-11e4-8b99-5698194ad4c7.png)

---

### Sign In (Password)

When in the Password field, if the user taps on the :eyes: icon, they can toggle password obfuscation.

![password active](https://cloud.githubusercontent.com/assets/1119821/7596715/cbe5fe12-f8bd-11e4-8480-f5a280e8f91b.png)

**Comment by vazquez** [comment]
@secretrobotron recommended to loop in @cadecairos. Welcome! :raised_hands:

**Comment by thisandagain** [comment]
2¢:
I'm not sold on the landing screen right now. That background texture seems foreign to the rest of the visual system and the "Join Us" / "Sign In" links don't read as strongly as buttons as they likely need to for FTU. 

I'm also curious about the form styles. Having a standard Android navigation / ActionBar with a back button seems consistent with the way we treat navigation throughout the application and having the form on a field of blue is low contrast / difficult to read.

**Comment by vazquez** [comment]
- Background texture can be removed. Since it was an intro screen I wanted to experiment with something a bit different.  
- I got the "Join Us / Sign In" idea from Evernote. I liked the way that the content of the page was so minimal that the actions didn't need to be treated as buttons, but just text. I will design a screen with buttons and we can decide which one is best. 
![2015-05-12 16 07 44](https://cloud.githubusercontent.com/assets/1119821/7597375/23f6877c-f8c1-11e4-9ec0-8cd8b58fb15c.png)
- The Android navigation back button is not something I see as a regular pattern during intro sign up/sign in experiences.
![2015-05-12 16 10 46](https://cloud.githubusercontent.com/assets/1119821/7597452/9d1368fa-f8c1-11e4-94e2-a6f75a828fca.png)
![2015-05-12 16 12 59](https://cloud.githubusercontent.com/assets/1119821/7597472/c4d42622-f8c1-11e4-96c6-a052059b1f73.png)
![2015-05-12 16 15 47](https://cloud.githubusercontent.com/assets/1119821/7597538/2c83f6bc-f8c2-11e4-8968-c07910b29244.png)
- I designed the form in a blue background because even though it steers away from consistency, I believe the introductory context warrants a dedicated UI. Something that didn't look like plain old Settings. However, the low/contrast comment is something I will investigate further.

**Comment by thisandagain** [comment]
- That works ... I think the combination of: textured background, bottom of the screen, plus not treating them as buttons buries them in the hierarchy.
- I'd greatly prefer to not build entirely new navigation styles just for sign-up / logi-in in the roadmap to v1.0.0.

**Comment by cadecairos** [comment]
FYI signing up from anywhere other than id.webmaker.org isn't possible due to it's CSRF protection

**Comment by thisandagain** [comment]
@cadecairos @jbuck @simonwex  Being able to have a sign-up form on Android in-app was one of the only major technical requirements that we had for login. If it isn't currently supported it will need to be modified to accommodate.

**Comment by cadecairos** [comment]
luckily it's just a configuration change to remove that limitation!

**Comment by xmatthewx** [comment]
Landing page feels out of scope, particularly before we have an app icon. 

How about we land on Join for now, following IF's approach? If so:
 - No headers or lorem ipsum required

I'm ok with the blue background for first impressions.

**Comment by vazquez** [comment]
I updated a lot of the UI and there are quite a few screens to show so I thought it best to make an InVision prototype.

Please visit http://invis.io/P62Z2HBMV for a Demo :movie_camera:

**Comment by vazquez** [comment]
Working on a diagram right now. :dancer:

**Comment by xmatthewx** [comment]
Discussed progress with @vazquez. Updates for review coming soon.

**Comment by thisandagain** [comment]
Nice. Great progress already this morning. Looking forward to seeing the updates.

**Comment by vazquez** [comment]
## UI Notes and Prototype

### Prototype
http://invis.io/P62Z2HBMV 

### Diagram and Notes

Also available as PDF: https://dl.dropboxusercontent.com/u/43783651/Mozilla/Android/Diagram.pdf

![diagram](https://cloud.githubusercontent.com/assets/1119821/7616779/1e0742fc-f975-11e4-82f1-b6b22e126e92.png)

**Comment by xmatthewx** [comment]
@k88hudson - now is a good time for a technical review. Thanks @vazquez

**Comment by k88hudson** [comment]
@vazquez @xmatthewx looks on track from a technical perspective. A couple of things:

* We need a comp/screen for terms/conditions
* Reset password flow needs to be designed/addressed

**Comment by thisandagain** [comment]
Couple small issues:
- Users need to be excepting both the TOS *and* the privacy policy
- The copy, "Already joined? Sign in" seems connected to the legalese and thus gets lost in a quick scan

**Comment by vazquez** [comment]
@k88hudson - 

- I will add the screen for TOS in InVision. It will be an external link to https://webmaker.org/en-US/terms.

![screen shot 2015-05-13 at 14 16 34](https://cloud.githubusercontent.com/assets/1119821/7617712/f4700748-f97a-11e4-9653-337953a3c27e.png)
- We are planning to leverage the work that has already been done on Reset password by Ali and Cassie.

@xmatthewx Please confirm that what I say is true.

**Comment by vazquez** [comment]
@thisandagain :+1: On it

**Comment by vazquez** [comment]
@thisandagain Done :fallen_leaf:

**Comment by secretrobotron** [comment]
:leaves:

**Comment by xmatthewx** [comment]
Can we leverage browser-based resources for secondary items to reduce what we need to build and maintain in app? (Avoid it when it will stink for a lot of users)

Here's what teach uses:
 - Pwd Reset
  - https://id.webmaker.org/reset-password/
 - Privacy
  - https://www.mozilla.org/en-US/privacy/websites/
 - Terms
  - https://webmaker.org/en-US/terms
  - On webmaker.org by design? Should, we move all of this to mozilla.org?

**Comment by thisandagain** [comment]
For privacy and TOS we don't really have a choice ... we should almost certainly point to the canonical documents.

Password reset is an interesting option. I'm :+1: on it as long as we do a pass on the mobile / responsive styles.

**Comment by xmatthewx** [comment]
Here's reset in Chrome on Android. Good enough for v1? I think yes. 

![screenshot 2015-05-13 15 48 41](https://cloud.githubusercontent.com/assets/53411/7619574/a81c05e2-f987-11e4-87b5-063ca3f08cec.png)

Button padding is weird. Logo is broken on FF. :disappointed:  Will poke id.webmaker.org.

**Comment by thisandagain** [comment]
@xmatthewx :+1: Thanks for pushing on this. :smile:

**Comment by k88hudson** [comment]
@vazquez just to confirm, https://projects.invisionapp.com/share/P62Z2HBMV#/screens/77984843?maintainScrollPosition=false has the final/correct versions of everything?

**Comment by vazquez** [comment]
Yes! I just double checked. InVision is up to date with the latest screens.

**Comment by thisandagain** [comment]
Resolved in #2085. Great work @k88hudson ! :smile:
