### ISSUE TITLE
[MIGRATED] UX for Profile

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1526]
Beta release profile will include username and possibly avatar. 

UX for Make view requires:
 - changing username
 - choosing or adding avatar

re: Avatars
 - There's discussion of having users select from a set of illustrated options. 
 - There's also the idea of page editor as avatar maker, though that's probably post RC1
 - Instead of illustrations, we could generate something with usernames like...
![250px-tribe_sticker](https://cloud.githubusercontent.com/assets/53411/7188979/a39ca7cc-e449-11e4-8a33-b3ef039c932d.png)

**Comment by xmatthewx** [comment]
@vazquez added a nice bit of flair above the user's profile. It's currently a bit out of place, but I think the app could use more details like this to liven things up. It could also appear:
 - discover beneath project username
 - in avatars (illustrated or like tribe above) 

We might also try this for a more interesting 'tinker bolt' 

What do you think of investing in a little flair generator?

![make view alt colour](https://cloud.githubusercontent.com/assets/53411/7283588/9a3513de-e905-11e4-8bbb-1469860bd3bd.png)

cc @thisandagain @flukeout

**Comment by flukeout** [comment]
Here's a rough idea - we use the same UI / UX as the tile editor, but we provide a circular canvas and change the tile element set to a series of face icons.

![profile-ux](https://cloud.githubusercontent.com/assets/25212/7309985/15061c64-e9da-11e4-83ba-6a21bb22cc63.png)

**Comment by flukeout** [comment]
Alternatively we can put a lot of elements around the outside of the visible area that people can drag in and rearrange.

**Comment by xmatthewx** [comment]
I like this direction. 

I think we stick with a standard page size ... but add a dotted circle in the center to represent profile image crop. 

I think this will be quicker to build than an avatar picker and more in line with the flavor of the app.

**Comment by xmatthewx** [comment]
Note to self: Profile at top of Make view should include a way to access user settings. A button next to edit profile button.

**Comment by xmatthewx** [comment]
@thisandagain - If we want an illustrator involved in this at the beginning of Beta, we should get that rolling now.

**Comment by thisandagain** [comment]
@xmatthewx Agreed. We now have access to [elance](https://www.elance.com/) and should start the search. @cassiemc is this something you can help us source?

**Comment by cassiemc** [comment]
@thisandagain Sure, can we post that shortlist here that we had a while back?

**Comment by xmatthewx** [comment]
Here's an iteration on @flukeout's idea to build an avatar, but using the same editor we're already building. User's would essentially remix a Page with a bunch of images already added to it. We would then crop to the center circle to generate their avatar. 

![avatar](https://cloud.githubusercontent.com/assets/53411/7358264/532b18a2-ed02-11e4-9838-798c2249d087.png)

**Comment by flukeout** [comment]
Simplified concept to match initial UX requirements:
![image](https://cloud.githubusercontent.com/assets/25212/7376146/9f9ff42e-ed92-11e4-8540-5dd42e68a51e.png)

**Comment by xmatthewx** [comment]
Moving this to the backlog. We can jump back in this when we revisit Discover and begin social features.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/35"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/35.
Please don't comment on it here.
