### ISSUE TITLE
Create testing plan

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1527]
Now that we've got [a roadmap](https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1ZvdNJLHuW0fIBt_-WcR7Ns6OhZgaMy6MI9kfjlXF-9o/edit#gid=0), let's add some targets for remote testing. 

@flukeout - add to the ideas in this etherpad. We can pull a clean list back here. https://etherpad.mozilla.org/webmakertests

Next week, I think we should test your play prototype. 

cc @LauraReynal @vazquez

**Comment by LauraReynal** [comment]
Does remote testing = user testing.com or does remote testing = reps testing with us supporting remotely? ( one of our multiple conversations so Im checking) 

Where can we see the play prototype ? Can I test in in Chicago ?

**Comment by xmatthewx** [comment]
I meant usetesting.com, but most tests for remote would be good for reps too. Let's sync efforts. 

The play prototype is Luke's tiles-2, which I think you've been using. Buttons for adding things are removed. Page header vanishes on single page view. Testing a few other things not yet resolved.

**Comment by xmatthewx** [comment]
cc @thisandagain

**Comment by xmatthewx** [comment]
Bumping to alpha 2 to continue the work

**Comment by xmatthewx** [comment]
continue in #2090
