### ISSUE TITLE
Implement - Choose image source

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1529]
When user taps Choose Image button on image edit view, they see options for source: 
 - "Take Photo" `beta`
 - "Gallery" `beta`
 - "Search Web" `v1.1 ??`

**Comment by vazquez** [comment]
I have two layouts, which one do you think is best?

Leave UI Feedback: http://invis.io/BK2M18Q28

![choose image source](https://cloud.githubusercontent.com/assets/1119821/7259188/9c30e8c4-e82f-11e4-878a-5eed5fabd5de.png)

![choose image source alt](https://cloud.githubusercontent.com/assets/1119821/7259189/9c31dee6-e82f-11e4-8201-d0e0ac7e1957.png)

**Comment by thisandagain** [comment]
I'm digging the giant touch targets in the first option. :smile: :point_up_2:

**Comment by vazquez** [comment]
Me too! Alignment is more even as well. :+1:

**Comment by vazquez** [comment]
Done! :star:

**Comment by vazquez** [comment]
### Design Documentation

*Scenario:* User taps on the Blue Plus button and selects image.

![screenshot 2015-05-05 08 28 44](https://cloud.githubusercontent.com/assets/1119821/7476194/d92a7976-f300-11e4-9e34-0fb8bfde40ec.png)

##### Choose Image Source Screen

As soon as the user taps on the image button, they are presented with an overlay screen, in which they can select three options.

1. Take Photo
2. Camera Gallery
3. Web Search

###### Notes

- As this is an overlay (modal), tapping anywhere in the grey area or pressing the system's back button will disclose this modal.
- Selecting `Take Photo` will open Android's camera
- Selecting `Camera Gallery` will open Android's photo gallery.
- Selecting `Web Search` will disclose more UI. This UI hasn't been designed yet. This feature is going to come later in Beta, so not to worry about now.

![choose image source 2](https://cloud.githubusercontent.com/assets/1119821/7477094/88e47650-f306-11e4-8a7a-87e3968b5ff3.png)

**Comment by xmatthewx** [comment]
Tracking in #1563
