### ISSUE TITLE
Design promo card or sticker for events

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1536]

**Comment by thisandagain** [comment]
This could be pushed to part of the RC milestones, correct?

**Comment by xmatthewx** [comment]
We'll share Beta with 500 youth at an event on June 11th. If we want users on Beta, something simple would be useful. If we don't, then we can definitely push back.

**Comment by thisandagain** [comment]
I was hoping we could use some existing swag for Maker Prom, but that sounds fine if it's not a distraction.

**Comment by xmatthewx** [comment]
Let's revisit when we land in the play store. Weigh the cost/benefit.

**Comment by xmatthewx** [comment]
tracking marketing here: https://github.com/mozilla/webmaker-launch/issues/8
