### ISSUE TITLE
UI for refresh & progress indicators 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1540]
Design indicators
 - http://www.google.com/design/spec/patterns/swipe-to-refresh.html#
 - http://www.google.com/design/spec/components/progress-activity.html#

depends on #1539

**Comment by xmatthewx** [comment]
We should include a notice for failure such as image upload.

**Comment by xmatthewx** [comment]
tracking UX in #1677 #1680 #1686

**Comment by vazquez** [comment]
I've created prototypes in Codepen and placed them in their corresponding tickets.
