### ISSUE TITLE
[MIGRATED] Implement Android back button to UX spec

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1546]
depends on #1545

**Comment by xmatthewx** [comment]
see #2306 and #2242

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/37"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/37.
Please don't comment on it here.
