### ISSUE TITLE
Build - Image source selector

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1563]
Depends on UI #1562 

Note: Alpha will use a placeholder URL dialog.

**Comment by xmatthewx** [comment]
![image source](https://cloud.githubusercontent.com/assets/53411/7569313/ed2f979c-f7d5-11e4-93f6-4f1181a41ad9.png)

Note: v1 does not include Web search on mobile

@vazquez - post icons

**Comment by vazquez** [comment]
Icons are available on Google Drive.

Google Drive > WMA > Version 2.0 > icons >

`take-photo.svg`
`camera-gallery.svg`
`web-search.svg`

**Comment by xmatthewx** [comment]
@thisandagain - Here's frontend for your image related tasks. Take a look so we can address any concerns.

**Comment by thisandagain** [comment]
:+1: :smile:
