### ISSUE TITLE
UX - first time use

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1565]
see list in #1459

**Comment by flukeout** [comment]
Here's a concept for a FTU experience as project:
![ftu-project](https://cloud.githubusercontent.com/assets/25212/7398554/ad570f4e-ee64-11e4-87f3-66dc90909440.png)

**Comment by flukeout** [comment]
Example 'helper tooltips' the actions listed in #1459 
If we're going to use this, we have to figure out when to show them and in what sequence.

Also, tapping on them or away from a helper dismisses it.

![image](https://cloud.githubusercontent.com/assets/25212/7399804/45c4980c-ee6d-11e4-8393-180fef14061d.png)

**Comment by flukeout** [comment]
From testing, maybe doing a better job to frame the type of content that a user will be experiencing and who it's made by and why will be important, more so than the interactions of browsing a project, which most people seem to grasp just fine without help.

**Comment by flukeout** [comment]
@xmatthewx As discussed, let's hold off on designing this flow and experience until we've got a good idea of what the friction points are from testing.

**Comment by xmatthewx** [comment]
cc @secretrobotron - here are ftu tooltips and project as tutorial

**Comment by thisandagain** [comment]
Tracking rest of this work in #1459

**Comment by xmatthewx** [comment]
@flukeout @secretrobotron - It would be interesting to build and test the project Luke designed above: https://github.com/mozilla/webmaker-android/issues/1565#issuecomment-97536071

**Comment by secretrobotron** [comment]
:+1: Agreed. That seems like a good place to start.
