### ISSUE TITLE
UX - remixing a project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1566]

**Comment by flukeout** [comment]
Currently, remixing is accessible from the Header menu, visible in the map views while viewing a project. We still have to consider if and how sharing and remixing is available in the zoomed in views.

Here's a rough flow for non signed-in users, which needs better copy and UI:
![image](https://cloud.githubusercontent.com/assets/25212/7396698/130affb0-ee58-11e4-8d10-4ecca363d87b.png)

We may want to add a FTU experience or overlay for Remixing, or could work it into the copy of the interstitial above - I'll try that first.

**Comment by xmatthewx** [comment]
I think a dialog works well in this case. Material design allows for simple dialogs, dismissed with back button or tap outside. http://www.google.com/design/spec/components/dialogs.html#

**Comment by flukeout** [comment]
Proposed treatment of the Play Mode header menu (with Share & Remix actions) in Aerial and Zoomed In Modes.

@vazquez Would like your feeback on this. What do you think of the placement and treatment of the menu below?

![image](https://cloud.githubusercontent.com/assets/25212/7403650/acbfd6ba-ee8c-11e4-9490-5edaa96afec8.png)

**Comment by davidascher** [comment]
@flukeout -- can you make sure to explain the flow for the vast majority of
users, who won't not be logged in, but won't have the app installed at all?

In general, we should remember the "viewing the make a web browser" users.

**Comment by flukeout** [comment]
Currently, we're not planning to have a web view published projects. But if we did, here's what that might look like.

![remix-flow](https://cloud.githubusercontent.com/assets/25212/7404005/c5008526-ee91-11e4-9919-566f6d99220c.png)

**Comment by vazquez** [comment]
@flukeout - I really like the treatment of the More Actions button in Play Mode. I think this is the way to go to have an unobstrusive header.

**Comment by xmatthewx** [comment]
- Web branch of the flow dependent on #1616
 - App branch looks good :+1: 
 - More Actions button on Play Page view :+1: (let's crop your zoom buttons from this thread)
 - Dialog to initiate remix :+1:
 - Dialog for FTU remix :+1:  

@flukeout - Let's drop a clean set of the comps below. I'll try and get someone for a quick copy review.

**Comment by flukeout** [comment]
@vazquez re treatment of the floating menu, we could even add a 'door exit' icon in the same fashion in the top left

**Comment by flukeout** [comment]
Pop-ups for Remix Action

![image](https://cloud.githubusercontent.com/assets/25212/7435882/b51aa6d4-effc-11e4-93bb-ab4ca2f3696a.png)

**Comment by xmatthewx** [comment]
@edrushka - mind doing a quick review of the copy in this dialog? You can ignore everything above Luke's most recent comment. 

Context: a user looking at a project clicks the menu item remix.

**Comment by edrushka** [comment]
For the First Time remix I'd just tweak the punctuation to: 
  You're free to change it as you please -- the original is unaffected. 
or 
You're free to change it as you please (the originial is unaffected). 

Not Signed In copy looks good.

**Comment by xmatthewx** [comment]
Thanks @edrushka for dropping by :eyes: .

@flukeout let's update your mockup and reference @vazquez's UI for the pop menu. We can then reassign for implementation.

**Comment by flukeout** [comment]
@xmatthewx I've updated the copy, here are the updated mocks.

![image](https://cloud.githubusercontent.com/assets/25212/7465321/ed99988e-f282-11e4-9829-c596ca86cc69.png)

@vazquez Has provided specs for the pop menu in #1640 - is that what you meant?

**Comment by xmatthewx** [comment]
This is good. Reassigning to @vazquez for confirmation on UI.

**Comment by vazquez** [comment]
I haven't done UI for remixing. I have created ticket #1659 for the UI.

**Comment by xmatthewx** [comment]
@flukeout - what does the transition look like for users? Does the title change?

**Comment by flukeout** [comment]
@xmatthewx Yes, I propose we add "Remix of" in front of the remixed project's title

**Comment by xmatthewx** [comment]
UI work continues in #1569
