### ISSUE TITLE
[MIGRATED] Build mvp profile 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1567]
Set username and avatar
Depends on #1526

**Comment by xmatthewx** [comment]
Profile for Beta will be simplified. 
 - No avatar
 - No color strip at top 

Edit profile view will just include
 - username
 - email
 - password

@vazquez - After you post screens here, edit issue title, label as `feature` and unassign yourself.

**Comment by vazquez** [comment]
@xmatthewx @flukeout - For password, do we just have a simple Change Password field or do we buff it up by asking:

1. Current Password
2. New Password
3. Verify new Password

**Comment by flukeout** [comment]
@vazquez  Good question! 
Hey @cassiemc, you've done the flow and screens for the sign in process already - how do we handle this right now on mobile?

**Comment by xmatthewx** [comment]
Looking at the teach site:
 - seems like it doesn't currently allow for changing your email address. 
 - seems like you can only change your password with the lost password link during signup 

Neither of these things are ideal. But, maybe they're good enough for v1.

**Comment by vazquez** [comment]
I just spoke to @alicoding and there is no feature for changing password, just reset password. Clicking on this will send an email with a link to reset pasword.

**Comment by vazquez** [comment]
### UI Design

For Beta, we are simplifying the UI for Make view.

#### Make View (Beta)

![make view beta](https://cloud.githubusercontent.com/assets/1119821/7573748/fc899e84-f7f5-11e4-9776-815135179167.png)

#### Edit Profile

When the user taps "Edit Profile" on the Make View they will arrive at this screen.

- We are only allowing the user to change usernames for now

![edit profile](https://cloud.githubusercontent.com/assets/1119821/7573793/5ce17928-f7f6-11e4-964e-e47fc164c477.png)

**Comment by xmatthewx** [comment]
:+1:  - bumping to implementation.

**Comment by flukeout** [comment]
**Questions & Concerns**
* The page where you change the Username has a `Project Settings` title, should it be `Edit Profile`

* The header for the `Edit Profile` page has a `Back` and a `Confirm` action:
![image](https://cloud.githubusercontent.com/assets/25212/7575594/c20342a2-f7ea-11e4-98f7-b66861de4f46.png)
* The header for the `Edit Project Title` page doesn't:
![image](https://cloud.githubusercontent.com/assets/25212/7575591/b950939e-f7ea-11e4-9803-dbf71043a135.png)
* They seem like a very similar action, so we should unify the UX

**Comment by xmatthewx** [comment]
@cadecairos - What are the requirements for username? Can you point me to a list of error/responses?

**Comment by thisandagain** [comment]
Based on our conversation today, we do not need to allow for user's to change their username in 1.0.0. @vazquez and @xmatthewx can you please update this ticket?

**Comment by xmatthewx** [comment]
@vazquez - let's post a new profile, removing both `logout` and `edit`, then relabel for implementation. Thanks!

**Comment by vazquez** [comment]
### UI Design

For Beta, we are simplifying the UI for Make view.

#### Make View (Beta)

![make view beta](https://cloud.githubusercontent.com/assets/1119821/7590551/2b576420-f897-11e4-82ef-3bcb3df721ed.png)

**Comment by thisandagain** [comment]
@vazquez We still need the logout button. This should destroy the session and point the user back to the "front" of the app (sign-up / log-in flow). /cc @xmatthewx

**Comment by vazquez** [comment]
@thisandagain Updated design above :arrow_up:

**Comment by xmatthewx** [comment]
:+1:

note: we're displaying the username field, not a name string.

**Comment by thisandagain** [comment]
Good catch @xmatthewx . In general, I'd like to mock up using more realistic data. We don't have a "name" for users in webmaker that supports spaces or capitalization... just usernames.

**Comment by cassiemc** [comment]
+1 to realistic data! Have noticed this in a few places. In general is a good idea not to use empty containers unless designing specifically for the first run experience.

**Comment by cassiemc** [comment]
(Hah, excuse the tardiness of my latest comment, just getting through my github mail)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/38"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/38.
Please don't comment on it here.
