### ISSUE TITLE
Implement remix flow

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1569]
depends on #1566

**Comment by vazquez** [comment]
Build UI as specified in https://github.com/mozilla/webmaker-android/issues/1566#issuecomment-98890892

**Comment by xmatthewx** [comment]
Note: 
 - All v1 users will be required to sign up / login. Design the sign-up prompt since we've already had copy review. But no need to implement now.  
 - Projects be names "Remix of Foo"
 - First-time remix prompt can be implemented to show every time until it proves to actually be annoying.

**Comment by xmatthewx** [comment]
Revising previous note for clarity: 

 - All v1 users will be required to login, so let's just implement the dialog below.
 - Projects will be named "Remix of Foo..."
 - I wonder if we should show this dialog the first time (unobtrusive), or every time (clarity). 

![screenshot 2015-05-12 18 06 02](https://cloud.githubusercontent.com/assets/53411/7599624/b274461e-f8d1-11e4-8d73-b9174bc0e95e.png)

**Comment by vazquez** [comment]
![remix](https://cloud.githubusercontent.com/assets/1119821/7634695/9da1edcc-fa2a-11e4-9aa9-5d7316b327ba.png)

**Comment by vazquez** [comment]
Or this one:

![remix copy](https://cloud.githubusercontent.com/assets/1119821/7635044/9b824116-fa2c-11e4-91fe-0393a82f9ba0.png)

**Comment by xmatthewx** [comment]
Revised copy:

> **Project Remix**
> This is your copy of **My Yam Fries Recipe**. You can add or change anything. The original by _fancyunicorn_ will stay the same. Have fun!

Your use of the hex icon prompted an idea: Remix is the tinker version of make. Let's match the tinker link dialog and icon with the phrase "Project Remix"
 
![screenshot 2015-05-14 13 13 03](https://cloud.githubusercontent.com/assets/53411/7637312/0d393888-fa3b-11e4-8fa6-e1be4ee948ec.png)

**Comment by vazquez** [comment]
:+1: Will do

**Comment by vazquez** [comment]
Updated treatment and copy.

![remix copy](https://cloud.githubusercontent.com/assets/1119821/7639468/2b46cb56-fa4a-11e4-84ec-c7ecce345404.png)

**Comment by xmatthewx** [comment]
:+1: on UI and copy

Scenario: 
 1. user triggers remix from project header ellipses menu
 1. project is copied with the name "Remix of Foo bear"
   - please trim "Remix of Remix of Remix of Foo bear"
 1. dialog appears
 1. user confirms. dialog disappears. project is already loaded.

**Comment by thisandagain** [comment]
:ok_hand: on the Creative Commons detail. :wink: 

Re: #1706

**Comment by gvn** [comment]
I think I've done what I can for now...waiting on API and Android stuff.

**Comment by gvn** [comment]
- [ ] user triggers remix from project header ellipses menu
- [ ] project is copied with the name "Remix of Foo bear" (please trim "Remix of Remix of Remix of Foo bear")
- [ ] dialog appears
- [ ] user confirms. dialog disappears. project is already loaded.
