### ISSUE TITLE
Schedule beta content sprint

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1576]
Generate content internally to provide examples for prospective creators/users (#1575).

- [ ] come up with dates (up-to and/or include whistler?)
- [ ] come up with goals (@flukeout + @xmatthewx)
- [ ] include @flukeout + @xmatthewx ( +@cassiemc ? + others?)

**Comment by cassiemc** [comment]
This could be a really fun thing to do in Whistler, if it can wait that long. Not sure your timing.

**Comment by secretrobotron** [comment]
Good call. Would be great to do there additionally with bigger group.

**Comment by secretrobotron** [comment]
Hoping to have one at end of May when most important beta features are implemented.
Should definitely have another for Whistler.

**Comment by secretrobotron** [comment]
Working on firmer schedule in launch playbook now. Whistler looks like a great opportunity to do internal content creation now.

**Comment by secretrobotron** [comment]
Moved to https://github.com/mozilla/webmaker-launch/issues/15
