### ISSUE TITLE
[MIGRATED] Gather prospective creator contacts 

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1577]
- [x] Draft intro email: https://etherpad.mozilla.org/content-email
- [ ] Send out requests to moz friends
- [ ] Brainstorm for each locale/demographic
- [ ] Compile list here (protected): https://docs.google.com/a/mozillafoundation.org/spreadsheets/d/1f2pTsEXtVm4qHiuafj3okbsItT3rRARs7b5Phy9fEgM/edit#gid=0

**Comment by secretrobotron** [comment]
Have done a lot of work with community and marketing teams this week. Putting this in next milestone to continue.

See playbook (ask me) for details.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/39"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/39.
Please don't comment on it here.
