### ISSUE TITLE
[MIGRATED] Implement community MGMT tools

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1580]
* File bugs/feature requests in https://github.com/mozilla/webmaker-firehose
* Should include gallery manipulation (e.g. featuring, curation) and moderation

**Comment by thisandagain** [comment]
:+1: Thanks for getting this rolling. One note on gallery manipulation is that the only control you'll need is featuring. Discovery galleries will be sorted by creation date.

**Comment by secretrobotron** [comment]
What about pinning objects in the gallery to allow for some curation? Otherwise, would be useful to implement some sort of grouping (like Make Lists), even if I have to tag things manually in a DB.

**Comment by thisandagain** [comment]
That's a pretty short-term need. Ideally we would be adding 5 - 10 new projects per day. Manually sorting is really not needed.

**Comment by secretrobotron** [comment]
Left some better notes in webmaker-firehose: https://github.com/mozilla/webmaker-firehose/issues/25

**Comment by secretrobotron** [comment]
@thisandagain @xmatthewx would love to look at this with you next week to see when/how we can work on it.

**Comment by secretrobotron** [comment]
@cadecairos do you mind dropping that list we wrote up today here?

I threw together a branch for moderation today. It's pretty easy to use the existing code. Don't need all the touch features that the phone has, so browser view is fine.

https://github.com/secretrobotron/webmaker-android/tree/moderation

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/41"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/41.
Please don't comment on it here.
