### ISSUE TITLE
[MIGRATED] Add icon component

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1584]
We need this to support multiple colours, maintain consistent size etc.

**Comment by k88hudson** [comment]
I would love to have an icon font, but a component will do for now.

**Comment by Pomax** [comment]
Why not both? We can make an <Icon> component that serves up "whatever works" while we work on it, so we can use a JSX syntax like `<Icon type="eyeball" />` and have that either generate an svg image or, once we find a nice one, text span with an icon font.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/42"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/42.
Please don't comment on it here.
