### ISSUE TITLE
[MIGRATED] Add user:select none wherever possible

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1591]
We should add this to prevent accidental selection of elements/the copy paste menu popping up.

**Comment by Pomax** [comment]
I wonder if it makes sense to do this as a mixin, e.g.:

```
module.exports = {
  componentDidUpdate: function() { 
    var lnode = this.getDOMNode();
    lnode.style.userSelect = "none";
  }
}
```

+ 

```
var Thing = React.createClass({
  mixins: [
    require('unselectable')
  ],
  ...
});
```

Or, alternatively, set up a universal class in our LESS and wrap the `classnames` lib so that we can call it as:

```
webmakerClasses({
  ...: true,
  ...: thing.state
}, true);
```

and end up with the second argument determining whether text selection of content is possible or not.

**Comment by secretrobotron** [comment]
I was able to select some stuff in tinker mode a couple days ago.

**Comment by xmatthewx** [comment]
Impacts destination selector as well: https://github.com/mozilla/webmaker-android/issues/2212

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/43"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/43.
Please don't comment on it here.
