### ISSUE TITLE
[MIGRATED] Work on active states for buttons and controls

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1592]
We should figure out and nail down the right active states for things such as the color-group component, the circular action buttons (+ element, etc.)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/44"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/44.
Please don't comment on it here.
