### ISSUE TITLE
[MIGRATED] Make ColorSpectrum component functional

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1593]
it should bind to a given value and compute new colours based on the touch position.

**Comment by k88hudson** [comment]
@flukeout can you post the updated designs here?

**Comment by flukeout** [comment]
We're rolling with the circle & triangle picker, shown here:
https://projects.invisionapp.com/d/#/console/3236838/75741128/preview

How does this feel from an implementation standpoint?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/45"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/45.
Please don't comment on it here.
