### ISSUE TITLE
Funnel segment of Adwords/Facebook traffic to content development ask

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1598]
* We know some demographic information about people who clicked on Adwords/Facebook ads
* Let's use that to our advantage to wrangle people who are most likely to be enthusiastic about creating early content
* Can build atop of content created earlier through more direct relationships
* Can reach out via email, or put something on the splash page (a check box? some words?)

cc @HPaulJohnson

**Comment by xmatthewx** [comment]
@secretrobotron - task still open? relevant?

**Comment by secretrobotron** [comment]
This is something we can actually set up now, @HPaulJohnson.

Should we still try it?
