### ISSUE TITLE
Provide a simple way for devs to reset SharedPreferences

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1610]
To reset state currently, you need to delete and then reinstall the app.

**Comment by ncalexan** [comment]
Presumably you can also just clear the App data using *Android Settings > Application Manager*.  A few of my colleagues use https://github.com/tunitowen/DevDrawer to expose this in their home screens.

**Comment by thisandagain** [comment]
True! Moving this to the backlog. Thanks for the tip on DevDrawer @ncalexan !
