### ISSUE TITLE
Hire illustration contractor

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1614]
We need to write-up an SOW for the illustration contractor based on the work needed to complete #1459

**Comment by xmatthewx** [comment]
@flukeout @vazquez - add ideas today and tomorrow. Everything is fair game. We can cut back when we draft the scope next week. 

 - FTU
 - Dialog header (ex: Link tinker selector [1] )
 - Empty Make view placeholder
 - Discover not yet loaded
 - App icon
 - App landing page background img

[1] thats a weird phrase

**Comment by vazquez** [comment]
- Power Link Modal illustration

**Comment by xmatthewx** [comment]
Revised List:
 - loading spinner and error state for any network image asset
 - pull to refresh indicator
 - swag (sticker, pins, shirts)
 - button link icon
 - App icon

Not in this scope:
 - FTU
  - empty make view
  - discover welcome 
 - Empty Make view placeholder
 - Discover not yet loaded

**Comment by xmatthewx** [comment]
[Draft SOW](https://docs.google.com/document/d/1fX7PaLT6r8VO7Nbww0GRDbjggvANy3zPxOmykeockVU/edit). Some details to discuss.

**Comment by xmatthewx** [comment]
@thisandagain - let's review and discuss draft so we can get this out today.

**Comment by xmatthewx** [comment]
Started a doc to orient contractor and review icon benchmarks. In [google drive](https://docs.google.com/presentation/d/17GIntGX--znIaTOj--F5JKNH70LvhaaAF1QtEGfB-z0/edit#slide=id.gafe60cfb4_0_209). 

I think the SOW should focus on this icon and its application to a loading/landing screen and to swag.

**Comment by xmatthewx** [comment]
@vazquez - can you review this doc? Make sure the second half is a good review of all the icons within the app.

**Comment by thisandagain** [comment]
Tracking in https://github.com/mozilla/webmaker-launch/issues/8
