### ISSUE TITLE
UX - Sharing experience across platforms / devices

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1616]
Based on our conversation today, we should expand our initial thinking on how projects are shared to make it a reasonable experience for users on platforms other than Android. Because we've done such a stellar job of using native Android code sparingly this shouldn't be *too* huge of a challenge for us to tackle in v1. I'd like to look at options for an extremely lightweight play-only experience that would work on web browsers. Because our schedule is already pretty stretched, let's strive to keep this as simple as is possible with a prompt for user's to download / install the app on Google Play to remix.

/cc @flukeout @xmatthewx @vazquez @davidascher

**Comment by xmatthewx** [comment]
Excellent. To clarify: are we committing to this now, or exploring the idea to make sure it fits our schedule? Here's a first pass on the specs: 

 - Play in browser (desktop & mobile)
 - Minimal wrapper includes:
  - App logo
  - Button to Play store
  - Share ???
  - No footer with links to other things

"Get the App" could be framed as: 
 - Play this on Android
 - Make your own
 - See more like this

UX-wise, @flukeout or I can explore how Page view translates to a wide screen. I'm wondering if we need a frame to contain the project. 

Keep this minimal, the Player could be shared as an embed.

**Comment by thisandagain** [comment]
No commitment yet, we'll need to sanity check the scope against the roadmap. Just need a proposal so we can get an idea of the workload.

Let's keep this an minimal as possible: so I'd say ditch share (embedded within almost every mobile browser already) and anything else ... just have player and logo w/ link to Play Store. Doing an embed is usually more work rather than less.

**Comment by xmatthewx** [comment]
Next step:
a) @flukeout - does a simple set of wires of this player with user origin(s) and exit(s)
b) devs assess work to build

Pushing to Beta 1/2

re: embed. Not suggesting we generate them. Just that webloggers _could_ drop an iframe in their weblogs.

**Comment by xmatthewx** [comment]
@flukeout - for sharing, we need a diagram (similar to [this](https://cloud.githubusercontent.com/assets/25212/7404877/da409a72-ee9e-11e4-84f1-6c7ef0c60b1c.png)) to map out what happens after a user shares their URL (#1713). 

- iOS user
- Android user without App
- Android user with App

Probably good to map scenarios assuming we DO and DONT have a browser-based player.

**Comment by flukeout** [comment]
First stab at a flow diagram assuming we **do** have a browser player. Should I map out the Sign In / Create Account requirement for viewing projects?

![image](https://cloud.githubusercontent.com/assets/25212/7598746/6be58b1a-f8b1-11e4-996a-3babdbcfccbd.png)

**Comment by xmatthewx** [comment]
This is great @flukeout. Eases my mind. I no longer think we need a 2nd diagram.
 - Until we have a browser-based player, non-android can fwd to our landing. 
 - Initially, login will be required to `Play in App`. That's fine as a footnote on the two arrows leading there.

**Comment by flukeout** [comment]
@xmatthewx Updated diagram to account for Sign In

**Comment by xmatthewx** [comment]
:+1:

**Comment by flukeout** [comment]
Basic desktop browser-based project viewer

![image](https://cloud.githubusercontent.com/assets/25212/7599954/91839bf0-f8bb-11e4-91ca-00dd1ba641b6.png)

**Comment by thisandagain** [comment]
Thanks folks. I'm wondering if we need the "Landing page / Want to install" flow ... many apps simply direct to the Google Play or App Store install page and I'm thinking that might be the best course for us as well.

**Comment by flukeout** [comment]
@thisandagain +1 on reducing steps / complexity. Do you mean we should have a landing page that provides context and a Play Store button or to simply redirect immediately to Play Store?

**Comment by thisandagain** [comment]
Detect if Android: if so direct to Play Store. If not, direct to web player.

**Comment by flukeout** [comment]
@thisandagain Updated diagram above to match new flow.

**Comment by thisandagain** [comment]
LOL :ok_hand:

**Comment by xmatthewx** [comment]
UX for browser-based player continues in https://github.com/mozilla/webmaker-desktop/issues/57

**Comment by flukeout** [comment]
@xmatthewx Is there anything missing from this flow? I've updated it to include all of the latest feedback.

**Comment by xmatthewx** [comment]
Closing this. Filed an issue specific to android users with link back to your diagram. Everyone else would be handled by https://github.com/mozilla/webmaker-desktop/issues/57
