### ISSUE TITLE
[MIGRATED] UX - Undo actions

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1629]
Someday, let's list things that would benefit from the power of `undo`.

![delete](https://cloud.githubusercontent.com/assets/53411/7436796/df4bfce2-f01e-11e4-895e-73584d9f14dd.png)

Android specs: http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/47"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/47.
Please don't comment on it here.
