### ISSUE TITLE
[MIGRATED] Animation - Move to center and zooming animations are little too slow

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1630]
Our animations are starting to feel really solid, but one place where they could use some improvement is in the map view. Specifically, the animations for:
- Centering a tile on tap
- Zooming in
- Zooming out

are a little too long (`0.3s`) and ease-in (`ease-in-out`) which makes taps / buttons presses feel sluggish even though the performance is solid. After playing around in inspector my recommendation is to switch to:
```css
transition: transform 0.2s ease-out;
```

/cc @flukeout @k88hudson @gvn

**Comment by thisandagain** [comment]
Special thanks to @autonome for his blog post here:
https://hacks.mozilla.org/2015/04/firefox-os-animations-the-dark-cubic-bezier-of-the-soul/

**Comment by flukeout** [comment]
@thisandagain I used ```.2s ease-in-out``` for the Play prototype which felt good on fast devices. I like the idea of ease-out as a way to make things seem snappier though, so :+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/48"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/48.
Please don't comment on it here.
