### ISSUE TITLE
Design UX for how to handle elements that are moved off of the tile

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1636]
Currently, it's possible to move an element off of a page and when you release your finger, there's no way to get at the element.

Ideas
* Limit how far you can move an element so that it never gets to an invisible state
* Move the element just slightly back into view after a move that would have otherwise hid it

@Pomax Can we make it so that the touch / drag gesture doesn't register beyond the visible edge of the page? Once your finger crosses the page bounds, the move stops?

**Comment by xmatthewx** [comment]
Let's sync this to minimum element size on pinch to scale. If we use 40px there, we can use 40px as the minimum 'crop' before an element disappears off the page.

**Comment by xmatthewx** [comment]
This is resolved, though maybe too aggressively. see #2323
