### ISSUE TITLE
UX to handle minimum element size

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1637]
Currently, you can scale an element down with pinching to the point that it becomes basically invisible. This makes it impossible to select in the future. 

Ideas
* Add a minimum size to elements (ie. height or width of an element cannot be smaller than 40px)
* Preserve a minimum touch-target size around elements, so that even if they are tiny, you'd be able to select by tapping in an area around it.

@Pomax thoughts on these approaches from a technical standpoint?

**Comment by xmatthewx** [comment]
This is resolved.
