### ISSUE TITLE
[MIGRATED] Text and element selection border get blurry when element is scaled to large size

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1638]
When you deselect and reselect the scaled text element, the border comes back crisp. I think we should take a cue from this and try redrawing the element and border at the end of a scale gesture, this will probably fix the blurriness.

Apparently this has to do with the fact that the transform is hardware accelerated, and the text is being treated like a bitmap. Maybe just hiding & showing the text after the scale will force it to re-render and look sharp.

Alternatively, we can try to turn off the hardware acceleration for this by making sure we're not using a 3d transform? Not sure.

@Pomax Let me know what you think or if you want me to do some more research etc.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/49"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/49.
Please don't comment on it here.
