### ISSUE TITLE
Build - Play View

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-android#1640]
Update Play View as per Luke's UX in #1566

**Comment by vazquez** [comment]
Refining the Play View UI.

##### Play Map View

![play map view](https://cloud.githubusercontent.com/assets/1119821/7461583/15b13462-f260-11e4-9bb2-61bec296bfc3.png)  

##### Play Map View More Actions Menu

![play map view more actions](https://cloud.githubusercontent.com/assets/1119821/7461591/17f69258-f260-11e4-8fa8-860c1560fd15.png)  

##### Play Page View
After tapping the Zoom In button, the user enters the page specific play view. Notice that the header disappears (it slides up, out of view). We do, however, introduce a floating more actions button. 

![play page view](https://cloud.githubusercontent.com/assets/1119821/7461593/19b8b968-f260-11e4-83b9-4b6a15b11929.png)

##### Play Page View More Actions
When the user taps on the floating more actions button, they disclose the following menu.

![play page view more actions](https://cloud.githubusercontent.com/assets/1119821/7462278/1aead12c-f265-11e4-9563-5bfb1203c9b1.png)

cc: @xmatthewx @flukeout - Anything I'm missing?

**Comment by thisandagain** [comment]
Why is the play UI orange? Seems disconnected from the visual language of the rest of the product.

**Comment by vazquez** [comment]
Luke has been exploring in his prototypes having custom project colours (dark blue, orange, all black, white), but I can always bring it back to default blue.

**Comment by thisandagain** [comment]
I don't think that is in scope for v1 ... let's keep it consistent for now.

**Comment by flukeout** [comment]
@vazquez @thisandagain @xmatthewx Let's leave default blue for now. The play prototype simulates authors being able to set the header / UI color - but we'll tackle that later.

**Comment by vazquez** [comment]
Changing to blue

**Comment by vazquez** [comment]
Refining the Play View UI.

##### Play Map View

![play map view](https://cloud.githubusercontent.com/assets/1119821/7462681/54840ab8-f268-11e4-8151-ee8be5010d8d.png)


##### Play Map View More Actions Menu

![play map view more actions](https://cloud.githubusercontent.com/assets/1119821/7462683/57492062-f268-11e4-873a-44f7bf5b2d3c.png)


##### Play Page View
After tapping the Zoom In button, the user enters the page specific play view. Notice that the header disappears (it slides up, out of view). We do, however, introduce a floating more actions button. 

![play page view](https://cloud.githubusercontent.com/assets/1119821/7462689/5d059918-f268-11e4-91e7-fe77aa335d21.png)


##### Play Page View More Actions
When the user taps on the floating more actions button, they disclose the following menu.

![play page view more actions](https://cloud.githubusercontent.com/assets/1119821/7462692/60c17748-f268-11e4-890d-219144327bd6.png)

**Comment by xmatthewx** [comment]
@flukeout @vazquez - as we head toward the v1 finish line, we should post true v1 UI. For a quick explanation, lo-fi wires will be better than non-v1 UI to avoid confusion. Let's assume a volunteer with little context will build the thing you're posting.

**Comment by xmatthewx** [comment]
Thanks for the speedy fix. I'm going to clean up thread above.

**Comment by thisandagain** [comment]
:+1:

**Comment by flukeout** [comment]
@vazquez I'm concerned about the spacing and border treatments of the tiles...

* In map view, spacing between top and sides of tiles is not the same
* When zoomed in, the tiles are closer together than in the map view, relatively
* In map view the white borders are way thicker than in the zoomed in view

Thoughts?

**Comment by vazquez** [comment]
@flukeout - I have updated the screens above :arrow_up:. Mainly, I have modified the Map View. Take a look.

- [x] In map view, spacing between top and sides of tiles is not the same
- [x] When zoomed in, the tiles are closer together than in the map view, relatively
- [x] In map view the white borders are way thicker than in the zoomed in view

**Comment by xmatthewx** [comment]
- remove the plus-zoom icon
 - single tap to open page
 - pinch to zoom range is limited just like editor
 - exit/zoom out with zoom out icon
 - map view - use full header
 - page view - floating ellipses in top right

@vazquez - post final clean artwork then reassign to `Beta 1/2` `Build` or file new issue.

**Comment by vazquez** [comment]
#### Play Map View
![play map view](https://cloud.githubusercontent.com/assets/1119821/7570984/7aa7075c-f7e2-11e4-910d-73ec6c1259c7.png)  

---

#### Play Map View (More Actions)

If the user taps on the vertical ellipsis, they will disclose the more actions menu.

![play map view more actions](https://cloud.githubusercontent.com/assets/1119821/7571038/d20c8594-f7e2-11e4-8cac-5cf071c3753b.png)

---

#### Play Page View

After tapping the Zoom In button, the user enters the page specific play view. Notice that the header disappears (it slides up, out of view). We do, however, introduce a floating more actions button. 

- The user arrives here by single tapping the page from the map view.
- Zoom out button will zoom out the view. System back button also zooms out the view.

![play page view](https://cloud.githubusercontent.com/assets/1119821/7571070/f5ea0e00-f7e2-11e4-8f41-c225d0d4d723.png)

---

#### Play Page View (More Actions)

If the user taps on the vertical ellipsis, they will disclose the more actions menu.

![play page view more actions](https://cloud.githubusercontent.com/assets/1119821/7571115/675990ec-f7e3-11e4-82d6-9263f9698a02.png)

**Comment by xmatthewx** [comment]
A few notes:
 - Modified header/nav is not possible for Beta given the difficulty involved with edits to the android wrapper.
 - pre-login, we can route fake content like so:
  - discover --> player
  - make --> editor

**Comment by thisandagain** [comment]
We still need to change it so discover directs to play, but otherwise I think this is good for beta.

**Comment by gvn** [comment]
I think this is good to close. What do you think @thisandagain ?

**Comment by thisandagain** [comment]
Yup!
