### ISSUE TITLE
Text editor: content-editable

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1644]
We need a solution for editing actual text content in the editor view.

This is probably going to be some implementation of content-editable.

**Comment by Pomax** [comment]
content-editable has no events associated with it though, making it virtually impossible to do anything useful with. A generic edit dialog along the lines of tinker mode might be more reliable

**Comment by xmatthewx** [comment]
If possible, it's much nicer for the user to see the results as they type. A dialog is fine for Alpha.

![text options edit text](https://cloud.githubusercontent.com/assets/53411/7463986/701f99c6-f28c-11e4-92e9-f4272d4dab14.png)

**Comment by k88hudson** [comment]
@Pomax Unfortunately while `contentEditable` is a bit of a beast we're likely going to have to do some kind of implementation/wrapper around normalizing its behaviour. It might be helpful to read https://medium.com/medium-eng/why-contenteditable-is-terrible-122d8a40e480, http://www.theguardian.com/info/developer-blog/2014/mar/20/inside-the-guardians-cms-meet-scribe-an-extensible-rich-text-editor, http://jakiestfu.github.io/Medium.js/docs/

**Comment by k88hudson** [comment]
As for alpha, a compromise seems reasonable. Edit dialog probably makes sense.

**Comment by k88hudson** [comment]
I'm gonna move this ticket over and file a new one

**Comment by flukeout** [comment]
@pomax - The latest version of this view includes an `Edit Text` button:
https://projects.invisionapp.com/d/main#/console/3236838/77590132/preview

**Implementation Details**
When `Edit Text` is tapped:
* Hide the `Edit Text` button
* Display the OS keyboard (which include a `Done` button)
* Place the caret at the end of the text string in the preview
* To stop editing the copy, user taps the `Done` button on the OS keyboard

**Validation**
I think we should only allow exiting the Edit Element view if the text string has at least 1 character. We can do this by disabling the Save action checkmark.

@vazquez What do you think about the above. Do we have a disabled state for the checkmark in this view and do we have a treatment for error copy?

**Comment by flukeout** [comment]
Some more thoughts, currently the preview doesn't match how the element actually displays on the page, noted here: #1833 

**Interim Solution**
* We should allow the user to add line-breaks to the text field
* We should not word wrap in the preview

This means we couldn't use @Pomax's proposed 'swap with input field' solution, but maybe we could use a text area instead?

I think ultimately whatever we build right now, we should be able to extend to the 'resizable text bounding box' UX that we initially came up with. This current style of adding text is very limited and doesn't lend itself to anything but short phrases.

**Comment by Pomax** [comment]
solution #2 as discussed with @xmatthewx is to not allow linebreaks for beta 1, and put a nowrap on the page (to match the single line that Project's "page preview" and the editor already do).

For now, that's the approach taken in https://github.com/mozilla/webmaker-android/pull/1839

**Comment by flukeout** [comment]
@xmatthewx @Pomax Since the PR associated with this ticket is merged in already, can we go ahead and close this issue? We can start another issue for a future UX improvements (like multi-line text, etc).

**Comment by xmatthewx** [comment]
Sure. If the <input> approach works for now, we can revisit content-editable if needed later.
