### ISSUE TITLE
[MIGRATED] Adding a custom colour to colour group

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1646]
The design spec is for custom colours that get chosen in tinker mode to get added to a second row of colours (this would be in the `colour-group` component)

**Comment by thisandagain** [comment]
I recommend this go to the backlog.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/50"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/50.
Please don't comment on it here.
