### ISSUE TITLE
[MIGRATED] Swiping to adjacent pages in page editor view

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1648]
Swiping left, right etc. should open the page editor view.

**Comment by xmatthewx** [comment]
Anyone want to tackle this? It'd be good to discover any problems soon. 

@flukeout mentioned: 
>  I'm concerned with swipes conflicting with Element manipulations, so I'd like us to tackle this...

@Pomax @k88hudson

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/51"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/51.
Please don't comment on it here.
