### ISSUE TITLE
[MIGRATED] Transition to from /map to /project (page editor)

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1650]
Right now the transition when zooming into the page editor (/project) is not to spec. It should automatically open the page editor.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/52"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/52.
Please don't comment on it here.
