### ISSUE TITLE
[MIGRATED] Set Link destination URL edition

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1671]
Tinker mode for links includes the option to set a URL. 

 1. In link element editor, user taps 'set destination'
 1. In map page picker, user taps 'tinker bolt'
 1. Dialog appears, offering to set destination:
   - page in another project
   - web url
 1. User taps web url
 1. View appears with field to set destination. View includes some helpful info about URLs and links.
 1. User taps checkmark
 1. Return to element editor

WIP UI in #1549

**Comment by xmatthewx** [comment]
Nice to have: include a way to access browser's bookmarks or top sites. @flukeout will see if there's any good precedent for this on Android. Likely out of scope for v1.

**Comment by vazquez** [comment]
### Design Notes

*Scenario:* User taps on Add Content and chooses Button

#### Button Added to Page (No Destination)

- As soon as the user chooses to add a Button, the UI shows a button element selected.
- A small popup appears with `Set Link Destination`.

##### Notes

- When tapping `Set Destination`, the user will immediately go to `Pick Destination Page` (shown below)
- When user taps on the `Edit` button, they will enter `Button Options` (shown below)

![button add to page](https://cloud.githubusercontent.com/assets/1119821/7504843/26721af2-f402-11e4-89e2-be43a474027b.png)

---

#### Button Options

- This is the screen that the user arrives after tapping on the `Edit` button.
- This screen allows the user to modify the following:
  1. Set Link Destination
  2. Corners (what we refer to border radius)
  3. Font-family
  4. Background color

##### Notes

- The user is presented with sliders that allow for the modification of values. At the right hand side of the slider, an updating value is shown in px values. The opacity of the value changes if it's not the minimum. As an example, if the Corners value is set at 0px, then we reduce the opacity of the number to decrease the cognitive load of the user. However, as soon as Corners is set to 1px/5px/any value, we change the opacity of the number to 100%.

- To confirm changes, the UI uses the Element Options Navigation in which the user needs to tap the check-mark to confirm changes.

- Border Color has a small circle inside the colour that is presently selected.

- Nice to have: In the case that the options are too long to fit in the screen, it would be really nice if we could hide the content underneath the Preview screen.

![button options](https://cloud.githubusercontent.com/assets/1119821/7505199/5a1a1c8a-f405-11e4-869a-1ed5d026d1a4.png)

---

#### Pick Destination Page and Confirm Destination Page

- This is the screen that the user arrives after tapping on `Set Destination`.

##### Notes

1. The current Page is shown with a marker in the center of the page.
2. Tapping on a page will draw a dotted line to its destination.
3. The destination page will show a flag in the center of the page.
4. Once a destination page is shown, a confirmation checkmark appears at the top right hand side.

![button pick destination page](https://cloud.githubusercontent.com/assets/1119821/7505333/4f7b101c-f406-11e4-8654-1e0d35715ebc.png)  

![button set destination page](https://cloud.githubusercontent.com/assets/1119821/7505335/52f8eb24-f406-11e4-9634-e995881ffa6a.png)

---

#### Button Tinker Mode

- When in the `Pick Destination Page` screen, if the user taps on Tinker mode :zap:, they enter Button Tinker Mode.

##### Notes

- User is able to:
  1. Link a Page within a project
  2. Link to an external web page
- The modal will disclose if the user taps on the system back button or taps anywhere in the grey area.

![button power link](https://cloud.githubusercontent.com/assets/1119821/7505408/04a5093e-f407-11e4-9f31-ee07b0355844.png)

---

#### Link To Web

- The user will arrive at this screen after tapping on `The Web!` in the previous screen.

##### Notes

- The user is able to enter a URL into the textfield.
- When there is a valid entry, the blue checkmark at the top right hand side will appear.

![button link to web](https://cloud.githubusercontent.com/assets/1119821/7505485/d6b7cc90-f407-11e4-8c09-d462075b544a.png)

---

#### Button Added to Page (Destination Set)

- Having confirmed all changes, the user can now return to the Page View.

##### Notes

- The text in the small popup modal now reads `Follow Link`. This signifies that a link has already been established.
- If the user taps `Follow Link` they will go to the URL that they previously specified.
- Android browser will take over at this point. Pressing system back button will return the user to this screen.

![button add to page link exists](https://cloud.githubusercontent.com/assets/1119821/7505564/cabe02d2-f408-11e4-9ebb-23ff9146f1a4.png)

**Comment by xmatthewx** [comment]
Context: User taps `set destination` in the link editor and then `tinker` :zap:  in the page picker. See #1670 more info.

## Tinker Mode

- User taps :zap: 
- Dialog appears. User can:
  - link to page in another project (#1672)
  - link to URL
  - tap outside dialog to dismiss
  - tap android back to dismiss

![button power link](https://cloud.githubusercontent.com/assets/1119821/7505408/04a5093e-f407-11e4-9f31-ee07b0355844.png)


## Set URL

 - User taps Web in dialog
 - Show URL settings view
 - User enters URL
   - If valid, tap checkmark confirms
   - If invalid, tap checkmark reveals helpful notice (TBD)
 
![button link to web](https://cloud.githubusercontent.com/assets/53411/7523351/2bf711e0-f4c9-11e4-86fd-42fc75875aa3.png)

**Comment by xmatthewx** [comment]
Context: User taps `set destination` in the link editor and then `tinker` :zap:  in the page picker. See #1670 more info.

## Tinker Mode

- User taps :zap: 
- Dialog appears. User can:
  - link to page in another project (#1672)
  - link to URL
  - tap outside dialog to dismiss
  - tap android back to dismiss

![button power link](https://cloud.githubusercontent.com/assets/1119821/7505408/04a5093e-f407-11e4-9f31-ee07b0355844.png)


## Set URL

 - User taps Web in dialog
 - Show URL settings view
 - User enters URL
   - If invalid, tap checkmark reveals helpful notice (TBD)
   - If valid, tap checkmark confirms
 - Go to element editor
 
![button link to web](https://cloud.githubusercontent.com/assets/53411/7523465/f2d14fce-f4c9-11e4-8b39-0ce585798a35.png)

**Comment by xmatthewx** [comment]
Note: header should match tinker colors. If that's not possible, we will need to revisit how we identify that a view is a tinker view.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/53"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/53.
Please don't comment on it here.
