### ISSUE TITLE
[MIGRATED] Implement Link destination to another project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1672]
Tinker mode for links includes the option to point to a page in another project. 

 1. In link element editor, user taps 'set destination'
 1. In map page picker, user taps 'tinker bolt'
 1. Dialog appears, offering to set destination:
   - page in another project
   - web url
 1. User taps '...another project'
 1. View appears with Discover and Make tab
 1. User navigates and tap to open on a project
 1. User pans, selects page, taps checkmark
 1. Return to element editor

WIP UI in #1549

**Comment by xmatthewx** [comment]
@vazquez - see comment in inVision. Post final artwork here. Add notes like you see #1671. This is not urgent.

**Comment by vazquez** [comment]
*Context:* User taps set destination in the link editor and then tinker :zap: in the page picker. See #1670 more info.

## Tinker Mode

- User taps :zap: 
- Dialog appears. User can:
  - link to page in another project (#1672)
  - link to URL
  - tap outside dialog to dismiss
  - tap android back to dismiss


![button power link](https://cloud.githubusercontent.com/assets/1119821/7505408/04a5093e-f407-11e4-9f31-ee07b0355844.png)

## Choose a Project
 - User taps *A Page in Another Project* in dialogue
 - `Pick a Project` view appears
 - User selects Project
   - Checkmark does not appear. In other words, confirmation is not needed. The view automatically transitions on tap.


![button pick a project grey](https://cloud.githubusercontent.com/assets/1119821/7800025/d36043cc-02dc-11e5-9a15-bb7ca146a2ed.png)


## Choose a Page

 - User selects a page within the project
   - Bordered selection appears along with icon.
   - When page has been selected, checkmark appears.

![button set destination page within project](https://cloud.githubusercontent.com/assets/1119821/7800026/d79a9c8a-02dc-11e5-8361-ec89e0bb5226.png)

## Return to Options View

 - Upon confirmation, view returns to the Button Options.

![button options](https://cloud.githubusercontent.com/assets/1119821/7800034/0745e822-02dd-11e5-9555-4273f457e97d.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/54"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/54.
Please don't comment on it here.
