### ISSUE TITLE
[MIGRATED] Add Text background color option

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1674]
Text on photos is tricky. I think we should add an option for background color on text. It will greatly increase what you can make with this app while we don't have shapes and stickers. 

Requirements:
 - ~~toggle on/off~~ palette with none option
 - standard tinker

Thoughts?

cc @thisandagain @flukeout @vazquez

**Comment by flukeout** [comment]
+1 on this idea, and the color bar that @vazquez spec'd already has it:
![image](https://cloud.githubusercontent.com/assets/25212/7500435/80330a12-f3e2-11e4-82b2-aad66946ee9a.png)

**Comment by thisandagain** [comment]
:+1: Sounds like a good idea but we need to remove features from the critical path to v1 right now. Moving to backlog.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/55"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/55.
Please don't comment on it here.
