### ISSUE TITLE
Implement animation for loading projects on Discover page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1677]
![image](https://cloud.githubusercontent.com/assets/25212/7502059/179a738a-f3ee-11e4-8859-70e5dd48aeb7.png)

Splitting out from issues #1539 

@vazquez Thoughts on these?

**Comment by cassiemc** [comment]
If nothing new appears, opportunity to invite people to make something? I like the satisfaction of having something new appear, even if there is no new content.

**Comment by cassiemc** [comment]
Also, play! Something playful.

**Comment by xmatthewx** [comment]
@flukeout - this looks good and thorough. One question: initial load animates from the bottom?

Nice idea @cassiemc

**Comment by flukeout** [comment]
@xmatthewx Yeah, initial set of projects comes in from bottom - to suggest "there's more where that came from" and get users to scroll. 

We need to finalize the number that we want to load - how about 7?

**Comment by xmatthewx** [comment]
Let's look at how much tumblr and others load initially. I worry that loading from the bottom will create a moving target that's hard to tap.

**Comment by flukeout** [comment]
@xmatthewx I was thinking something [like this](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B0NGgBg38lWWTG5jYi1JV1MxSDg/components-progressactivity-behavior-061102_Loading_Files_Circular_xhdpi_002.webm) Where we load 6 projects, then animate them in all at once from the bottom.

**Comment by xmatthewx** [comment]
Ah. Gotcha. I thought you meant that we first show the bottom project, then the one before it bumps it down. Which would be weird. The link clarifies.

**Comment by vazquez** [comment]
I really like that animation @flukeout :+1:

**Comment by flukeout** [comment]
@vazquez [Swipe to refresh video from Material Design](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B8v7jImPsDi-TUMwQjBnZmYwcFE/070601_swipeToRefresh_xdpi_v14f.webm)

**Comment by vazquez** [comment]
We are now using native Pull to Refresh for this :+1:

**Comment by thisandagain** [comment]
We still need to execute the pagination (load more) UI, but this plan seems solid. I'm glad we were able to get the native pull to refresh UI working. :smile:

**Comment by thisandagain** [comment]
Native pull to refresh is complete. Tracking scrolling / loading in #2035
