### ISSUE TITLE
[MIGRATED] Implement animation for loading a project in Project Editor & Play views

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1680]
![image](https://cloud.githubusercontent.com/assets/25212/7505410/072e6ab0-f407-11e4-99b0-97ce41d19b72.png)

Splitting out from issues #1539 

**Question**
* This approach loads tiles all-at-once - would we rather load elements as they are available?
  * This would mean we could show text before images have loaded etc.
* There is no project-wide loading indicator, is this ok? Do we want one?

@xmatthewx @vazquez Thoughts on these?

**Comment by xmatthewx** [comment]
> There is no project-wide loading indicator, is this ok?

I think yes. Your indicators provide good coverage. A project-wide indicator would be distracting while looking at a page that is done. 

> ...would we rather load elements as they are available?

Unsure. It's a guess until we see and feel real projects. If yes, we'd want a placeholder for images. If no, I like the idea of quickly building the page by adding elements incrementing up z-index. 

Here's a nice pattern for visually "loading" an image after it has finished loading data-wise: http://www.google.com/design/spec/patterns/loading-images.html#loading-images-loading-images

**Comment by flukeout** [comment]
@vazquez For map view, lets try a more subtle treatment for the spinner? Maybe the pulsing dots or something like that?

**Comment by flukeout** [comment]
@vazquez [Indeterminate spinner example from Material Design](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B0NGgBg38lWWTG5jYi1JV1MxSDg/components-progressactivity-behavior-061102_Loading_Files_Circular_xhdpi_002.webm)

I think we can just do a straight up spinner without the fancy lengthening and shortening of the spinner line as a start.

**Comment by vazquez** [comment]
##### Project View - Page Loading Spinner

I have 2 options for this indeterminate spinner. 
- http://codepen.io/rvazquez/pen/gpMEdR
- http://codepen.io/rvazquez/pen/doXLov

##### Map View - Page Loading Spinner 

Showing so many spinners at once might get overwhelming. Because of this, the following spinner has less movement.
- http://codepen.io/rvazquez/pen/jPrRNX

Let me know what you think @thisandagain and @flukeout

**Comment by thisandagain** [comment]
The stroke feels a little thin, but I like the second option for the indeterminate spinner.

For adding a new page, I think that feels ok but fairly disconnected from the feel / animation style of the page load. From a user POV I feel like having some consistency would be more ideal.

**Comment by vazquez** [comment]
:+1: I will make some changes

**Comment by vazquez** [comment]
##### Project View - Page Loading Spinner

Doubled the stroke of the lines.

- http://codepen.io/rvazquez/pen/doXLov

##### Map View - Page Loading Spinner

A new iteration of the Map view spinner with a similar aesthetic and animation to the Project View spinner. Animation is not :100: yet.

- http://codepen.io/rvazquez/pen/Mwedab

cc @thisandagain @flukeout

**Comment by thisandagain** [comment]
Great! Looks like this is getting close. After looking at the page loading spinner for a while it seems to "reset" after about 10 seconds w/ a harsh position change.

Have you looked at the page loading spinner in context yet? That stroke will be awfully small I'm guessing.

**Comment by flukeout** [comment]
@vazquez Nice work, these are cool. Would be cool to see them in context. Can you slap them over a background image of where they would appear?

I like the second page loading spinner with the two segments.

One concern i have is that both page double rotating segment and the bouncing line spinner feel like they seem to imply something is 'going backwards' sometimes. This makes it feel like something is trying, but failing to load, as opposed to a steady (but indeterminate) march forward.

**Comment by vazquez** [comment]
@flukeout I hear you :+1: 

I have two options for the Project View Spinner:

- http://codepen.io/rvazquez/pen/doXLov
- http://codepen.io/rvazquez/pen/ZGpbrm

Working on the Map View Spinner now.

**Comment by vazquez** [comment]
Map View Spinner: http://codepen.io/rvazquez/pen/pJEjGQ

**Comment by thisandagain** [comment]
Awesome. Really digging the first option for the project view spinner. :+1:

**Comment by vazquez** [comment]
Final Project View: http://codepen.io/rvazquez/pen/doXLov

**Comment by Pomax** [comment]
With the full-screen spinner actually working in the app now, it actually feels really wrong. If I create a new project, and get a blank page with the four "+" on each edge, and press one of them to create a new page, suddenly going into a full screen blue page with a spinner to indicate "it's taking a little longer" actually instead signals "this app has encountered a terminal error". This kind of hooks into the whole "we shouldn't be blocking the UI for actions that can take effect user side immediately": we shouldn't need a load screen to add a new page, we should have a "sync taking longer than expected" notification instead, with the UI first updating, but the page not being available for editing until sync succeeds

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/56"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/56.
Please don't comment on it here.
