### ISSUE TITLE
Conduct testing in London 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1684]
cc / @vazquez @xmatthewx @flukeout @thisandagain 

*Goal* : conduct interviews in London to complete feedback from Chicago, and test the alpha. 

the dates and times of the interviews are regularly updated on the webmaker calendar (look for british timezone)

the participants will be : 
- 13 teenagers - mixed of socio-economic background and locations - London 
- 2 art students = bachelor level - London 
- + a design workshop with bunch of artists on the 21st of May - in Leeds, Northen England. aka Not london

**Comment by LauraReynal** [comment]
Actual time frame of the project 
Monday May 11th - first interview 
Thursday 21st - last interview 
Bangladesh departure 1 week after. 

Notes from meeting are here https://etherpad.mozilla.org/webmakertests

**Comment by thisandagain** [comment]
@LauraReynal Post-mortem? Can this be closed?

**Comment by LauraReynal** [comment]
Testing complete. Github issues related have been submitted. 
Im yet to do the reporting but this can be closed.
