### ISSUE TITLE
[MIGRATED] Implement "Assets Uploading" indicator in Project & Discover views

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1686]
![image](https://cloud.githubusercontent.com/assets/25212/7521860/fb60ec72-f4a5-11e4-9e1f-31f4bad32d3d.png)

Splitting out from issue #1539 

@vazquez @xmatthewx Thoughts?

**Comment by xmatthewx** [comment]
This looks good UX-wise. UI-wise, Make view will have title bar on the bottom of project. Project title bar will include vertical ellipses.

**Comment by vazquez** [comment]
We could hide the vertical ellipses while image is uploading to accommodate the progress indicator.

**Comment by xmatthewx** [comment]
Interesting idea, but I'd rather not block project deleting and sharing or bother with the code.

**Comment by flukeout** [comment]
@xmatthewx As discussed, assigning to you. UX here is final.

**Comment by vazquez** [comment]
@xmatthewx - Looking at this it seems like we should disable the sharing option. I understand that sharing is too valuable, but sharing a project that has broken images seems to defeat the purpose of the share itself.

**Comment by flukeout** [comment]
@vazquez [Material Design Upload Spinner](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B0NGgBg38lWWbTlSaHdQZEMtalk/components-progressactivity-typesofindicators-061101_Circular_Aspirational_xhdpi_002.webm)

This one is a good guideline I think.

**Comment by flukeout** [comment]
Btw, in #1450 matthew added a couple of links which contain all of the Material Design refresh & progress indicators.

**Comment by xmatthewx** [comment]
@vazquez - the image isn't broken, just uploading.
 - I'd rather not introduce friction for people who want to quickly make and share a thing. 
  - Odds are good that uploads will complete before share is received and opened
    - When they aren't, we should have a nice progress indicator on the other end
      - b/c unfinished uploads will also impact edits to previously shared projects with lots of viewers
        -  
          - 
              -

**Comment by vazquez** [comment]
Prototype: http://codepen.io/rvazquez/pen/doXLov

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/57"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/57.
Please don't comment on it here.
