### ISSUE TITLE
[MIGRATED] Maintain the FAQ 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1687]
Here are a few questions potential users and educators regularly asked during the research, that would be interesting combining into an FAQ and in the intro deck 

1- What is this ? an app ? A website ? I am lost 
2- Where does my data / content go ? Where is it hosted ? (ie. what is our privacy policy )
3- Can I control who gets to see my projects ? (selecting private etc)
If I want to share it with only a few person ? or make it just for me ?
4- What does remix mean ? 
5- Can I decide who can remix my project ? 
6- Can I control who comments on my projects ? Are comments monitored ? 
7- Can I choose my URL ? Can I remove the webmaker domain ? 
8- Can I get help ?

Somewhere in this list, we should probably explain "Open source" if we mention it in one answer. 

cc / @thisandagain @xmatthewx

**Comment by xmatthewx** [comment]
I started a draft. This needs discussion and review before it can be published anywhere. 
https://docs.google.com/document/d/1OlxSxYwvFWp8D5z7f_8SfCOp5YQXsRG9QrdFZP-4SPI/edit

cc @secretrobotron

**Comment by LauraReynal** [comment]
Will this go into the app itself ?

**Comment by xmatthewx** [comment]
Not in the app, but we could link to an FAQ page on the desktop site. I defer to @thisandagain whether we need this for v1 launch or not. If so, we should file a desktop issue to build the page.

**Comment by thisandagain** [comment]
I don't think this is needed for v1. I'd rather start to build this up as actual questions come in from users post-launch (thus the "FA" in "FAQ").

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/58"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/58.
Please don't comment on it here.
