### ISSUE TITLE
[MIGRATED] Provide helpful validation on Link URLs

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1691]
When users add a link, they can tinker to add any URL (#1671). We should provide some proactive and helpful validation.

Option A
 - Rather than disabling the confirmation checkmark, clicking it validates and reveals tips if needed.
 - Pro: it doesn't nag you to add a TLD until you've had a chance

Option B
 - Checkmark disabled. List of URL requirements appear and disappear as needed
 - Pro: teaches as you go

@flukeout - let's start by listing the things that make or break a URL

Question: should we ping the URL to make sure it responds okay?

![button link to web](https://cloud.githubusercontent.com/assets/53411/7523766/a5712fea-f4cb-11e4-99d6-422dc361ba17.png)

**Comment by xmatthewx** [comment]
Also, we need a destination for our `learn more`. Something brief, inspiring, accessible. MDN?  

This isn't right, but it's better than most on a quick first search: https://themanual.org/read/issues/3/jeremy-keith/article

cc @vazquez

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/59"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/59.
Please don't comment on it here.
