### ISSUE TITLE
[MIGRATED] project view: Set origin of pinch to centre of touches

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1697]
Right now the origin is always `center`. We'd like to be able to center in the center of the pinch gesture.

**Comment by xmatthewx** [comment]
In addition to origin, our pinch seems amplified. 
 
Google maps seems to have a 1:1 ratio between pinch gesture and view scale. Streets stay relatively aligned with your fingers. Our zoom seems to be 1:1.5 between gesture and view. Pages scale more than my gesture. It's amplified.

**Comment by k88hudson** [comment]
I might need a bit of help on the translations/dilations formulas for this one, but i'll give it a go.

**Comment by thisandagain** [comment]
Needed to roll back this patch due to #2009

**Comment by k88hudson** [comment]
As we discussed, Pomax is going to try a different implementation in the next heartbeat

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/60"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/60.
Please don't comment on it here.
