### ISSUE TITLE
project view wrong button icons/ordering 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1698]
Should match this comp:

 ![](https://cloud.githubusercontent.com/assets/1119821/7501331/0e910868-f3e8-11e4-9dae-0e76f6dfcb4c.png)

**Comment by k88hudson** [comment]
@Pomax mind taking this one?

**Comment by Pomax** [comment]
Do we have the icons for this anywhere? @vazquez

**Comment by thisandagain** [comment]
Correct in latest minus support for setting page background color. Tracking in #1702
