### ISSUE TITLE
Better selected page state UI

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1699]
Can we get something more prominent than this? The shadow doesn't stand out enough when the grid is filled.

![image](https://cloud.githubusercontent.com/assets/1455535/7540738/eb45f9f8-f57d-11e4-8d34-510195dd67db.png)

**Comment by xmatthewx** [comment]
In the comp we see shadow on 3 sides. In the build it's more transparent and only below the page. Pages also feel closer in the build by a few pixels, a bit crowded.

**Comment by vazquez** [comment]
@flukeout @xmatthewx - What do you think of this?

![tile map view tile selected](https://cloud.githubusercontent.com/assets/1119821/7574272/1208d56e-f7fa-11e4-8160-389bcc230bda.png)

**Comment by flukeout** [comment]
I like this treatment!
Is it worth mocking it up against a darker background to future-proof it?

**Comment by vazquez** [comment]
Perfect, will do

**Comment by vazquez** [comment]
@flukeout What do you think? I think we're still good :)

![screenshot 2015-05-11 16 36 02](https://cloud.githubusercontent.com/assets/1119821/7574521/eb552902-f7fb-11e4-8e33-8ce1d0a21780.png)

**Comment by thisandagain** [comment]
WFM. Big improvement over existing selection indicator. :+1:
