### ISSUE TITLE
[MIGRATED] Map jumps after specific scale & pan actions

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1700]
Steps to reproduce:
* Place your index finger down and pan the map
* Place your thumb down and pinch to zoom the map
* Release your index finger
* Pan the map with your thumb
* Place index finger down and pinch zoom
* The map jumps

Something about switching fingers triggers this.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/61"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/61.
Please don't comment on it here.
