### ISSUE TITLE
[MIGRATED] Map pan animation jumps when adding a new page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1701]
When adding a new page by tapping a Plus tile, the map pan jumps a bit before finishing the animation that puts the new page closer to the center of the viewport. The animation should pan the map over smoothly.

I think this i best observed when you're zoomed in to about the 3-up view.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/62"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/62.
Please don't comment on it here.
