### ISSUE TITLE
[MIGRATED] UX - Page background image

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1703]
'Tinker' for page background could offer the option to add an image. Draft UX by @flukeout 

![screenshot 2015-05-08 13 57 29](https://cloud.githubusercontent.com/assets/53411/7542391/6b81e6ca-f58a-11e4-969a-3bc7fe2efcbe.png)

I would probably default to 'cover' having the image proportionally fill the image. 

depends on #1702

**Comment by flukeout** [comment]
Yeah, I think "cover" is a good starting position for the image.

I'll think about putting it into tinker mode, we could also put gradients into tinker mode, which we haven't thought about.

**Comment by flukeout** [comment]
Updated diagram here:
https://dl.dropboxusercontent.com/u/109902/tiles/page-background.pdf

**Thoughts**
* Will take another stab via tinker mode still
* Do we always zoom in to the page when editing the background?
  * We can leave zooming just for when you're adding a background image

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/64"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/64.
Please don't comment on it here.
