### ISSUE TITLE
[MIGRATED] Implement Page view "zoom out" UI

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1705]
Page view currently includes a back button in the header to 'zoom out' to project view. Align this and other tools with the UI spec. 

@k88hudson - feel free to reassign or push back to Beta 1/2

 - [ ] header should not include any back or exit button
 - [ ] header includes title and moar vertical ellipses
 - [ ] tools include `zoom out` on the left, `add` in the middle
 - [ ] if element is select, tools include `edit` & `delete` to the right of `add`
 - [ ] system back button should act like `zoom out` if there is no other activity to dismiss

![screenshot 2015-05-08 14 26 39](https://cloud.githubusercontent.com/assets/53411/7542867/484adc12-f58e-11e4-8f01-ef859d7d2078.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/65"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/65.
Please don't comment on it here.
