### ISSUE TITLE
[MIGRATED] UX for Editing Text

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1707]
Some thoughts around optimizing the UX for changing the copy in the text element, based on questions in #1227

**Key Points**
* When editing a Text Element for the first time, Edit Element view opens with keyboard visible
* Added a Pencil Icon to the Edit Element view for subsequent text edits

![image](https://cloud.githubusercontent.com/assets/25212/7543296/2880cda8-f578-11e4-8581-d0b563679eb3.png)

@xmatthewx Thoughts?

**Comment by vazquez** [comment]
I think this is an interesting approach. However, I fear that after tapping save and returning to page editor (Frame 4), the user won't know to tap Edit again to go to the Edit Element Attribute Page, as we've now trained the user that the Edit button (Frame 3) edits text only, not properties.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/66"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/66.
Please don't comment on it here.
