### ISSUE TITLE
[MIGRATED] Add true preview to Element editor

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1709]
Element editor currently shows the element on page background with transforms or other page content. This preview should show the page cropped in the preview window.  
 - centered on element
 - do not scale element or page
 - show other elements

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/67"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/67.
Please don't comment on it here.
