### ISSUE TITLE
Replace tucker

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1711]
@flukeout @vazquez to pick out candidate images, patterns, etc. 

things to consider
 - default image
 - intro deck
 - video

**Comment by xmatthewx** [comment]
We need a small set of photos. Cat? mountain? brick wall? cc @flukeout

**Comment by flukeout** [comment]
What about a cat, a speech, bubble and a ball of yarn? Then we could create some kind of storytelling scenario.

**Comment by xmatthewx** [comment]
I had thought a speech bubble, star, and an arrow could be useful. I like the cat and yarn as narrative props. Theatre stage? Starry night?

**Comment by Pomax** [comment]
http://xkcd.com/1525/

**Comment by vazquez** [comment]
In the same vein as cat and yarn, what about also having bear and salmon?

![tile view copy](https://cloud.githubusercontent.com/assets/1119821/7749875/905cf764-ff9e-11e4-84a1-2ebbac6ffa1c.png)

**Comment by vazquez** [comment]
Bears and salmon smelled too fishy. I replaced salmon with honey!

![tile view copy](https://cloud.githubusercontent.com/assets/1119821/7756202/b20ce2b0-ffc7-11e4-9f15-d9a7a4ec7223.jpg)

**Comment by vazquez** [comment]
I've gotten a few +1's, so let's run with the bear and honey :smile:

**Comment by Pomax** [comment]
is it too late to -1? Or at least vote for "let's make this prettier than that mockup?"

**Comment by vazquez** [comment]
@Pomax - One of the drawbacks of the Tucker mockup was that it was too unrealistic. The app couldn't accurately replicate Tucker with a landscape, perfectly centered speech bubble, etc. This design, albeit less attractive, is more akin to the real abilities of the app. We don't want to stylize the image with borders, or corners, as we want the user to discover those options.

When a user adds an image, we will add a placeholder image of a bear. If they add another image, we will add a honey pot. If they add a third image, we will add a speech bubble image. Essentially, we will rotate between these three images. Another goal of this is to give the user visual clues regarding the narrative aspect the app is geared towards.

**Comment by xmatthewx** [comment]
This will have a big role in first impressions. Let's take another minute to get this right. I will loop back later today with some options.

**Comment by Pomax** [comment]
Just pointing out that bears are scary as hell, and not everyone has heard of Winny the Pooh (possibly most so in the regions we intend to target?)

**Comment by xmatthewx** [comment]
## landscape

A few images someone might like to use in the background. All via wikimedia.

![dulmen _wildpark_--_2013_--_4](https://cloud.githubusercontent.com/assets/53411/7847308/a79cb0f8-0490-11e5-9bb7-5a33df3b27a1.jpg)
![earth_eastern_hemisphere](https://cloud.githubusercontent.com/assets/53411/7847311/a7a0709e-0490-11e5-95cf-755d37c08057.jpg)
![moon_with_22 _halo](https://cloud.githubusercontent.com/assets/53411/7847309/a79e04f8-0490-11e5-95a1-b8871a9b4b5e.JPG)
![odrapold_sooru_kulas](https://cloud.githubusercontent.com/assets/53411/7847312/a7a87bfe-0490-11e5-8ebb-f2556219b02c.jpg)
![cosmic_heavyweights_in_free-for-all-_one_of_the_most_complex_galaxy_clusters _located_about_5 4_billion_light_years_from_earth](https://cloud.githubusercontent.com/assets/53411/7847310/a79e49d6-0490-11e5-8379-08d6334090b9.jpg)
![country_road_and_yellow_field](https://cloud.githubusercontent.com/assets/53411/7847307/a79c462c-0490-11e5-829f-0a3f24a113c3.jpg)

**Comment by xmatthewx** [comment]
## Texture

All via wikimedia 

![blank_papyrus_paper](https://cloud.githubusercontent.com/assets/53411/7847527/1962d770-0492-11e5-997c-eb5bc92e2c58.jpg)

![rasen](https://cloud.githubusercontent.com/assets/53411/7847528/19655da6-0492-11e5-8549-4eb28a3e922d.jpg)

![brick_wall_close-up_view](https://cloud.githubusercontent.com/assets/53411/7847561/57e891e2-0492-11e5-9dcd-7553b23fd12a.jpg)

**Comment by xmatthewx** [comment]
## Adorable

Via wikimedia

![2009-08-16_puppy_at_duke_east_1](https://cloud.githubusercontent.com/assets/53411/7847582/74cab06a-0492-11e5-94f2-ce482741d3be.jpg)
![alfredo_-_o_gato](https://cloud.githubusercontent.com/assets/53411/7847581/74c955ee-0492-11e5-8373-24a188d89916.JPG)

**Comment by xmatthewx** [comment]
## Stickers

Transparent PNGs

![heart](https://cloud.githubusercontent.com/assets/53411/7847619/9ed5022a-0492-11e5-9411-7382cd2f1052.png)
![star](https://cloud.githubusercontent.com/assets/53411/7847620/9ed550cc-0492-11e5-8ffd-a6aa78f0d6de.png)
![talk](https://cloud.githubusercontent.com/assets/53411/7847622/9ed8b410-0492-11e5-8a4d-46ede8cec83a.png)
![think](https://cloud.githubusercontent.com/assets/53411/7847621/9ed668c2-0492-11e5-9002-02fb3fa8480e.png)

**Comment by xmatthewx** [comment]
These defaults help remedy the blank canvas and give people some variety to play with as they test the app, especially during our demos.

**Comment by xmatthewx** [comment]
@thisandagain -- What are ideal specs for default photos?

cc @LauraReynal @secretrobotron - [images above](https://github.com/mozilla/webmaker-android/issues/1711#issuecomment-106072035) are proposed replacements for tucker. App will randomly pick one when user adds the image element.

**Comment by thisandagain** [comment]
@xmatthewx Let's go with 640px wide and use SVGs where possible for the stickers.

**Comment by xmatthewx** [comment]
I was fairly aggressive with compression. We can dial it back if any feel too crunchy. Dülmen Wildpark is narrower than the rest to avoid excessive bytes. 

https://drive.google.com/open?id=0B_rbDAen9prkR3VDOXZsNmlHazg&authuser=0

**Comment by xmatthewx** [comment]
@vazquez - we will need to replace tucker your comps with a variety of the defaults linked above. We don't need to update all your comps, but should hit the important screens that might be used in marketing.

**Comment by xmatthewx** [comment]
@vazquez - as you update views, drop them in the intro deck: https://docs.google.com/presentation/d/1fdb6gJ1XMY7UJdh9Ac5r8_Ic0PAnimEKVXkj9w7wD6w/edit#slide=id.g98178a36f_0_19

**Comment by xmatthewx** [comment]
@vazquez - will this be done this week or should we push back to next week?

**Comment by LauraReynal** [comment]
:+1: :space_invader:  :heartbeat: :sun_with_face: 

Guys these new images are awesome. It's really fun to to see which one will come up, and it creates a nice surprising effect. 

Would it be possible to have more cultural diversity in the selection ? Given our market priorities I would add at least one image with each continent's flavor. 

Some propositions for Asia and Africa 
Asia 
https://www.flickr.com/photos/laura_nk/16434201101/in/album-72157650633495175/
https://www.flickr.com/photos/laura_nk/16409973356/in/album-72157650633495175/
https://www.flickr.com/photos/laura_nk/15815903853/in/album-72157650633495175/
https://www.flickr.com/photos/laura_nk/15522520817/in/album-72157649063963096/
Kenya / Africa 
https://www.flickr.com/photos/laura_nk/15715813428/in/album-72157647756136177/
https://www.flickr.com/photos/laura_nk/15892575036/in/album-72157647756136177/
Black and white could be interesting too ? https://www.flickr.com/photos/laura_nk/15901347361/in/album-72157647756136177/

Let me know what you think. will also test this new feature with teens next week

**Comment by xmatthewx** [comment]
Closing. Tucker is replaced in the app. @vazquez is updating artwork as needed for marketing. Adding defaults for other locales in a new issue.
