### ISSUE TITLE
Implement call to Android API for sharing action sheet

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1713]
![screenshot 2015-05-08 17 16 55](https://cloud.githubusercontent.com/assets/53411/7545860/7d6d8a1c-f5a6-11e4-9e7a-7d104eca7949.png)

![screenshot 2015-05-08 17 16 34](https://cloud.githubusercontent.com/assets/53411/7545861/7d728e4a-f5a6-11e4-8bcc-467e3e3accab.png)

**Comment by xmatthewx** [comment]
native sharing #1714

**Comment by secretrobotron** [comment]
Blocks #1665
