### ISSUE TITLE
Implement project settings view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1715]
Project settings only include `title` for v1. Accessed via ellipses in header. 

![screenshot 2015-05-08 17 16 55](https://cloud.githubusercontent.com/assets/53411/7546229/92fe285c-f5a9-11e4-8270-9cbe15f436dc.png)
![screenshot 2015-05-08 17 16 34](https://cloud.githubusercontent.com/assets/53411/7546230/930207b0-f5a9-11e4-82ff-7209bc1a5941.png)

![project settings focus](https://cloud.githubusercontent.com/assets/53411/7327313/3d0e452c-ea9a-11e4-8955-1bfdcc5ee9d9.png)

**Comment by flukeout** [comment]
Concerns
* What parameters do we validate this against?
  * Min / max length?
  * Special characters?
* When do we do validation on the name?
  * As you type?
  * When you submit?
* Do we have designs for error messages / states?

Ping @xmatthewx

**Comment by xmatthewx** [comment]
We don't have those details. Drop in some opinions. We'll design error message/states for login and can pull those in here. I also wondered if we were going to require unique project titles or if urls would include a project ID.

**Comment by flukeout** [comment]
**Proposal**
* Project title must be 4-25 characters in length
  * We should add a length indicator somewhere on the page as guidance
* Project can include special characters
* We trim leading and trailing spaces from the title
* We should change it so that there is a `Confirm` checkmark in the header
  * `Confirm` attemps to change the name
  * `Back` disregards your changes and returns to project
* We validate validate the name when user hits `Confirm` action

Aternatively we can validate as the user types, this would let us have a `Confirm` checkmark that becomes enabled only when the name is valid.

Thoughts @vazquez @xmatthewx

**Comment by vazquez** [comment]
- I agree on displaying a length indicator as per material design (i.e. `12/25`)
- I agree on adding a `Confirm` checkmark in the header
- I agree on validation upon pressing `Confirm`
- Material design input caret colour cannot be recreated in CSS, which is why I kept it the standard black.

**Comment by xmatthewx** [comment]
Let's whittle this back a bit to the essentials: 
 - ~~display length indicator~~
 - Add `Confirm` checkmark
 - Add validation (but only if it's critical for the API and project URLs)
 - ~~input caret~~

**Comment by vazquez** [comment]
### Design UI

#### Project Settings

![project settings 2](https://cloud.githubusercontent.com/assets/1119821/7591116/f5e6ad98-f899-11e4-80d0-77dfa22dd616.png)

#### Project Settings Active

When tapping on the textfield, the line changes from grey to blue.

![project settings active](https://cloud.githubusercontent.com/assets/1119821/7591117/f5f30e58-f899-11e4-939e-db146feb6bd9.png)

**Comment by xmatthewx** [comment]
@gvn - UI for project title / settings is in the comment above https://github.com/mozilla/webmaker-android/issues/1715#issuecomment-101321158

 - set a character limit
 - trim leading and trailing spaces 
 - no need for any validation in v1

I'm curious whether we will use project titles in links and if we need to limit titles to a character set, or just strip them.

**Comment by gvn** [comment]
It actually is possible to color the caret, and I've already coded a display length indicator, so I'll keep those in unless you don't want them. :wink:

**Comment by gvn** [comment]
I'm also enforcing max length by preventing additional characters from being typed once you're at maximum. That's the standard UX for native text inputs with a max length.

**Comment by vazquez** [comment]
Awesome @gvn!! :hand:

**Comment by gvn** [comment]
This still needs:

- [ ] Persistence (can now connect to newly landed API!)
- [ ] Checkbox moved into Android navbar

**Comment by gvn** [comment]
Unassigning since this is broken into sub-tickets...

**Comment by xmatthewx** [comment]
Since we can't put the confirmation button in the header this heartbeat, we need a better temp solution. It currently looks like a checkbox input. 

Alternate solution - Use the back arrow to save and exit.

Proposed soution - Move button below the title field and use a label instead of checkmark.

R? @vazquez @flukeout @thisandagain  

![project settings](https://cloud.githubusercontent.com/assets/53411/7820983/c0b2ad54-03b9-11e5-8548-5d5a60f85154.png)

**Comment by thisandagain** [comment]
:+1: I should be able to get this knocked out tonight. Thanks for catching this.

**Comment by flukeout** [comment]
@vazquez @thisandagain I like just using the back arrow to save. Edit element and edit project views already have that behavior.

**Comment by thisandagain** [comment]
Resolved in #1909
