### ISSUE TITLE
failure to install app

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#1721]
uninstalled the old (MWC) app
used Android file transfer to move the app to the Download folder
used the Downloads manager to find the apk
tried to install it
got the following screenshot at the end of the process
tried again by downloading w/ firefox (file didn't download, because maybe of a bad mimetype from the AWS bucket?)
downloaded w/ chrome, tried to install from its download notification, got the same dialog
![2015-05-09 05 27 26](https://cloud.githubusercontent.com/assets/51278/7548888/615c0382-f60d-11e4-96bc-b7647346504e.png)

**Comment by thisandagain** [comment]
Hmm... I wish Android would give you some more detail than "App not installed". Did you per chance ever try to install the v1 branch using Android Studio? I'm wondering if you might still have an old debug build floating around. If not, would you mind hooking your phone up to your computer and running `adb logcat`? The system logs should give us some details during the installation process.

**Comment by davidascher** [comment]
I had a zombie app installed already (from the studio, as you predicted).  Removing it fixed the problem. Closing.
