### ISSUE TITLE
[MIGRATED] Add height to discover view items while images are loading

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1738]
When loading the discover view projects, the cover images don't load right away to the items are small. Let's add a minimum height to the image wrapper as a start.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/69"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/69.
Please don't comment on it here.
