### ISSUE TITLE
Project previews in make & discover views are different sizes

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1739]
Let's pick a standard size and use the same for both views.

**Comment by vazquez** [comment]
Yes, I agree :+1: 

Should we move this to implementation for `Beta 1/2`? cc @xmatthewx 

##### Updated Design

![make view](https://cloud.githubusercontent.com/assets/1119821/7588854/8f26335a-f88d-11e4-8572-65039d8616a5.png)

**Comment by xmatthewx** [comment]
To clarify: 
 - Projects in Make view will now match project card in discover.  
 - In Make view they gain the more actions ellipses, future home of `delete` and `share`

**Comment by thisandagain** [comment]
:+1:

**Comment by xmatthewx** [comment]
resolved
