### ISSUE TITLE
[MIGRATED] Create a Project button doesn't work when long-pressed

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1741]
If you press and hold, and then release the create a project button it has no effect. If you tap it quickly you end up in the project editor. Let's make it work for long presses too.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/70"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/70.
Please don't comment on it here.
