### ISSUE TITLE
[MIGRATED] Image element is not cropped by the page boundaries in the Page Editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1742]
If you drag the default Toucan image beyond one of the edges of the page in the Page Editor, it doesn't get clipped by the page boundary. It's totally visible always.

**Comment by flukeout** [comment]
Causing me trouble and slowin' down my authoring process a lot when I try to line things up

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/71"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/71.
Please don't comment on it here.
