### ISSUE TITLE
[MIGRATED] Inconsistent two-finger pan behavior between map and element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1743]
If you two-finger pan the map (move two fingers together) the map pans, but if you do the same to an element in the Page Editor, it doesn't move.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/72"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/72.
Please don't comment on it here.
