### ISSUE TITLE
Page thumbnails don't reflect content arrangement on the pages when zoomed in

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1745]
If you add three text elements and arrange them on a Page, they appear differently arranged on the page thumbnail.

**Comment by Pomax** [comment]
a secondary STR:
- Go to an empty page in a project
- hit edit
- add a text element
- element shows as living in the middle of the page
- go back to project view
- element is shown in upper left corner.
- go back to page view
- element is in the same place as before
- drag element around and drop it in the center of the page
- go back to project view
- page preview now shows the correct positioning

**Comment by k88hudson** [comment]
After refactoring the page view in the API patch I this should be resolved.
