### ISSUE TITLE
UI when element is selected in Page Editor isn't to spec

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1746]
Spec is here
https://projects.invisionapp.com/share/BK2M18Q28#/screens/71287112?maintainScrollPosition=false

App shows different buttons at the bottom of the Page Editor

**Comment by thisandagain** [comment]
@vazquez Can you please drop in the canonical reference to this UI as well as the sketch file?

**Comment by xmatthewx** [comment]
details tracked in #1705
