### ISSUE TITLE
[MIGRATED] Element Edit page doesn't include the element name in the title

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1747]
The spec shows that the Edit Element view includes the element type in the title, ie Text Options, Image Options:
https://projects.invisionapp.com/share/BK2M18Q28#/screens/71860137?maintainScrollPosition=false

The app just says "options" in the title.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/73"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/73.
Please don't comment on it here.
