### ISSUE TITLE
[MIGRATED] When text size is set to 10px, the value becomes gray

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1748]
Steps to reproduce
* Add a text element
* Edit it
* Change the text size value to 10px (lowest value)
* The number indicating the value turns light grey

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/74"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/74.
Please don't comment on it here.
