### ISSUE TITLE
[MIGRATED] Implement font-family dropdown

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1750]
* It's got too much left padding
* Doesn't have a little arrow indicator on the right side
* The dropdown options don't use the corresponding fonts to display the names
* The dropdown has radio buttons as the selection metaphor

Compare to spec below (and next page showing dropdown treatment and selected state)
https://projects.invisionapp.com/share/BK2M18Q28#/screens/72332476?maintainScrollPosition=false

**Comment by thisandagain** [comment]
@vazquez Can you please drop in a reference PNG and link to sketch file?

**Comment by vazquez** [comment]
### Design Documentation

##### Text Attributes Screen

###### Text Dropdown Sketch File

https://www.dropbox.com/s/8px5x6vx4o20psc/Text%20Dropdown.sketch?dl=0


###### Notes

- The Font Family selector acts as a [Material Design dropdown list](http://www.google.com/design/spec/components/menus.html#menus-behavior). It's pretty much the same as a normal dropdown except it looks just a little bit different.
- The user has the freedom to select the text to be bold AND italicized AND underlined.
- The user can only select one text alignment property. As an example, the text cannot be left aligned AND right aligned.
- Selected states for Text Style and Text Alignment is represented by a blue 'active state', as shown below.

![text options 2](https://cloud.githubusercontent.com/assets/1119821/7462955/79d643a6-f26a-11e4-8727-f9c3b53ae50c.png)

##### Text Options with Dropdown selected

- Every font shown here is accessible through Google Fonts.

![text options dropdown](https://cloud.githubusercontent.com/assets/1119821/7463148/d1d6d1aa-f26b-11e4-8dda-17e85a7e6f99.png)

**Comment by Pomax** [comment]
This issue is going to need more work after beta, because we can't style option elements inside select dropdowns in WebView.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/75"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/75.
Please don't comment on it here.
