### ISSUE TITLE
Text element color doesn't match any of the available color options it has

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1751]
The font color is black, but that isn't one of the available options in the "Color" option when you edit the text element.

Let's choose a font color that is actually available (or add black) and have it be selected in the text options page.

**Comment by flukeout** [comment]
@vazquez What do you think the default color should be?

**Comment by vazquez** [comment]
Thanks for pointing that out man. I had it one screen and not in the other. I have updated all screens in InVision. This is what it looks like:

We are removing the no colour option and replacing it with black.

![text options 2](https://cloud.githubusercontent.com/assets/1119821/7592875/013fe808-f8a4-11e4-8ccf-63657ab43172.png)

**Comment by thisandagain** [comment]
Tracking in #1751
