### ISSUE TITLE
[MIGRATED] Element - Keep preview fixed to top of view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1753]
When scrolling the Edit Element page, we should persist the element preview and just scroll the options, otherwise it's hard to see the effect of your changes.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/76"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/76.
Please don't comment on it here.
