### ISSUE TITLE
[MIGRATED] Element updates 'jarringly' when returning from the Edit Element view to the Page Editor view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1754]
Make some changes to a text element then return to the page editor, the old text element treatment is visible at first, then it suddenly takes on the new properties - let's make it have the new properties as soon as you see it.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/77"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/77.
Please don't comment on it here.
