### ISSUE TITLE
Edit text prompt header says "The page at 'file://' says:" which is pretty awkward

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1756]
Can we just have it say 'Edit text' or something similar?

**Comment by Pomax** [comment]
baked in Android behaviour for the JS `prompt()` call. We'll be solving this by writing a component for text input instead of the placeholder `window.prompt` for beta.

**Comment by thisandagain** [comment]
Specific to interim (alpha) text editor. Tracking in implementation of spec.
