### ISSUE TITLE
[MIGRATED] Map view title bar doesn't show the project title

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1762]
It says "Project" instead of "The Birds of the Amazon"

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/81"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/81.
Please don't comment on it here.
