### ISSUE TITLE
[MIGRATED] When deleting a page that isn't in view, pan there first, then delete it

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1763]
Right now you can select a tile, pan somewhere else, and delete the selected page without seeing it. I think it would be good to pan back to the page you're acting on to reinforce what just happened.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/82"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/82.
Please don't comment on it here.
