### ISSUE TITLE
[MIGRATED] When deleting a page, map view should auto-select an adjacent page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1764]
If you delete a page, no page is selected. We should auto-select an adjacent page right after. We should select the adjacent tile that is closest to the center of the viewport and persist the "Edit" and "Trash" UI.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/83"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/83.
Please don't comment on it here.
