### ISSUE TITLE
[MIGRATED] Element preview doesn't show the transformations applied to an element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1765]
For example..

* Add a text element
* Scale and rotate it
* Edit the Text Element
* The preview doesn't show the scale and rotation you just applied

This also makes changing the Font Size a little tricky since you're not really seeing an accurate representation of how it will appear.

**Comment by thisandagain** [comment]
Do we really want to show scale and rotation here? Seems like this view would need to be redesigned a bit to accommodate allowing arbitrary scaling. /cc @vazquez

**Comment by vazquez** [comment]
I think this would cause some strange edge cases :alien:. The original idea was to show the preview of the text with the background colour behind it, but I fear that adding rotation and transformation preview might cause the text to be unclear, especially when editing.

What about adding a `Full Preview` button that displays a modal? The modal's content would be a complete page preview (text + rotation and scale)

@thisandagain is right however. If we add scale and rotation preview, this view would need to be redesigned.

**Comment by flukeout** [comment]
Initially we were planning to have the preview be scrollable and to show the element as it appears in the context of the page. Let's hold off on that for now - we can revisit if we feel the previews need to be enhanced.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/84"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/84.
Please don't comment on it here.
