### ISSUE TITLE
[MIGRATED] Element Edit preview should show the element in the context of the page, not just against the page background color

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1766]
The edit element view isolates the current element and hides all other elements on the page. This makes it harder to make changes that depend on other elements. 

Let's try it with all other elements visible, and if that is too cluttered and confusing we can try knocking down the opacity of the non-selected elements, or some other approach.

**Comment by thisandagain** [comment]
Same as #1765 it seems like this would cause some pretty strange edge cases and I'm not convinced that adding that context / noise is helpful to the end user. /cc @vazquez

**Comment by vazquez** [comment]
I agree with @thisandagain on this one. My comment on #1765 relates to this:

> I think this would cause some strange edge cases :alien:. The original idea was to show the preview of the text with the background colour behind it, but I fear that adding rotation and transformation preview might cause the text to be unclear, especially when editing.

> What about adding a Full Preview button that displays a modal? The modal's content would be a complete page preview (text + rotation and scale)

**Comment by xmatthewx** [comment]
Hmm. Scenario: 
 1. place a large image
 2. place some text on top of it
 3. edit the text and pick a color
 4. confirm, view page, see text that lacks contrast on photo

Isn't it better to compose and style your text with a true preview?

I don't remember discussing a preview that was anything but the real page centered on the element, cropped in the preview box. 1-1 scale.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/85"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/85.
Please don't comment on it here.
