### ISSUE TITLE
Editing the text element copy isn't obvious

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1767]
Currently you have to tap the Text element inside of the Edit Element view to bring up the prompt for changing the copy - I think we should add a little edit pencil icon near the preview somewhere or an explicit action like we have for the "Set Destination" link for the button element.

**Comment by thisandagain** [comment]
Major :+1:
Getting this feedback quite a bit from testers as well.

**Comment by vazquez** [comment]
Yes :+1: I have changed these views already in https://github.com/mozilla/webmaker-android/issues/1792#issuecomment-100984352

**Comment by xmatthewx** [comment]
@vazquez resolved this for button labels as well in https://github.com/mozilla/webmaker-android/issues/1792#issuecomment-101302677. Closing this. Tracking there.
