### ISSUE TITLE
[MIGRATED] Poor range slider performance in Edit Element view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1772]
I don't know exactly why or when this happens, but I'd say my success rate on the range sliders noticing I'm trying to slide them is about 50%.

**Comment by xmatthewx** [comment]
@flukeout - Nexus 4 or 5 with Android 5?

**Comment by flukeout** [comment]
@xmatthewx Nexus 4 with Android 5

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/86"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/86.
Please don't comment on it here.
