### ISSUE TITLE
[MIGRATED] Text Element is pixelated / blurry when scaled to very large sizes

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1773]
Especially noticeable for the text element.

**Comment by Pomax** [comment]
fascinating behaviour: totally pixelly, but if you hit "back" to get to the project view, then edit the page again, it's magically no longer pixelated.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/87"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/87.
Please don't comment on it here.
