### ISSUE TITLE
[MIGRATED] Hard to tell when you've added the same element twice, since they appear right on top of one another

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1775]
Right now if you add 5 text elements in a row, they go directly on top of each other so you don't really get any feedback that you've added a new one until you drag one and realize there are other ones underneath it.

Ideas
* We can use randomized copy & attributes for the elements to make them distinct
* We can add a little animation to indicate which element was just added
* We can randomize the starting position within a small area near the center

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/88"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/88.
Please don't comment on it here.
