### ISSUE TITLE
Text edit - You can't edit **existing** text

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1777]
Currently in order to "edit" text, you have to start over and type your new text from blank. 
It should offer to actually edit your previously typed text. 
![screenshot_2015-05-11-10-33-26](https://cloud.githubusercontent.com/assets/8261945/7562155/fa44c558-f7c9-11e4-857a-27e0f22a7bc1.png)

**Comment by k88hudson** [comment]
Note: this is a consequence of the interim text editing solution, it should be resolved when we replace with the real text editor.
