### ISSUE TITLE
Tinker mode disapeared

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1778]
Nexus 5 
latest build 
No tinker mode - in any space

![screenshot_2015-05-11-10-40-12](https://cloud.githubusercontent.com/assets/8261945/7562182/4f138e02-f7ca-11e4-93fd-b4f3970b76e7.png)

**Comment by thisandagain** [comment]
Tinker mode was hidden in the latest build because it hasn't been hooked-up / completed yet. Tracking in #1729
