### ISSUE TITLE
[MIGRATED] Build swipe between pages

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1779]
Right now you can 
- View map 
OR
- View a page 
But you can't swipe to get to the next page in your project. It feels wrong not to be able to swipe your own project. It is frustrating to be obligated to go back to Map view.

**Comment by xmatthewx** [comment]
@thisandagain - your list of blockers includes “merge page & project + swipe.” Is that this feature? Or, something else?

**Comment by thisandagain** [comment]
That would fall firmly in "enhancement" territory. :wink:

**Comment by Pomax** [comment]
this is a considerable amount of work that I don't think we can get done before friday.

**Comment by thisandagain** [comment]
Moving to the 1.0.0 sprint.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/89"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/89.
Please don't comment on it here.
