### ISSUE TITLE
Text editor - default typing is bold and underlined 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1781]
Text editor is in bold by default and underlined when typing. 
After typing it is still bold but no longer underlined. 

![screenshot_2015-05-11-10-51-33 1](https://cloud.githubusercontent.com/assets/8261945/7562657/023fa4e0-f7ce-11e4-8c82-a5b26750c19f.png)

**Comment by k88hudson** [comment]
Note: this is a consequence of the interim text editing solution, it should be resolved when we replace with the real text editor.
