### ISSUE TITLE
[MIGRATED] Smooth out page loading visuals when opening image heavy pages in the Page Editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1783]
When you load a page with very large images (Tuckers) they are rendered in a quick top-to-bottom loading pattern that isn't very attractive.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/90"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/90.
Please don't comment on it here.
