### ISSUE TITLE
[MIGRATED] When an element is very large, there's no way to tell that it is selected.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1784]
If you scale Tucker to be really large, way bigger than the Page, you can't tell if that it is selected anymore because the selection border is beyond the edges of the viewport.

It's a bit of an edge case though - not sure if we should care yet.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/91"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/91.
Please don't comment on it here.
