### ISSUE TITLE
Able to select Image Element in Page Editor by tapping on empty space on a page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1786]
Steps to reproduce:
* Add tucker
* Move him (her?) to the top right 
* Add a text element and move it to the bottom left
* Select the text element
* Now, tap the empty space in the center of the page a few times
* Tucker will become selected

**Comment by flukeout** [comment]
This is related to #1790

**Comment by k88hudson** [comment]
@flukeout this may be related to the rectangular bounding box surrounding the image. Can you confirm if that's the case?

Unfortunately, if so, there's not much we can do about it. Luckily, however, the vast majority of images people are likely to add are going to be rectangular (at least, from a camera/gallery)

**Comment by flukeout** [comment]
@k88hudson No, it's definitely not caused by tapping within the bounding box around a transparent image. Were you not able to reproduce with the steps above? What it seems like is even if you move an element, it leaves a phantom, tappable area in the center of the page.

I'll get on the latest build, attempt to reproduce and let you know.

**Comment by flukeout** [comment]
Can't reproduce anymore! :+1:
