### ISSUE TITLE
"Delete Element" and "Edit Element" actions visible even when no element is selected.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1791]
Steps to reproduce:

* On a blank page, add a text element
* Tap it to select it
* Tap beside it to deselect it
* Look below, the element manipulation UI is still there

**Comment by k88hudson** [comment]
I think this is a consequence of #1790, since elements cannot currently be deselected

**Comment by k88hudson** [comment]
Resolved as #1790 is resolved.
