### ISSUE TITLE
Add explicit option to edit text string and button labels

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1792]
In the Edit Element view...
* For the image element, you have to tap the "Change Image" button.
* For the Text Element, you have to tap the element itself
* These seem like related actions, let's have a consistent UI

@vazquez What do you think?

**Comment by vazquez** [comment]
For sure, I agree. I have made the changes in InVision. Posting artwork.

![text options 2](https://cloud.githubusercontent.com/assets/1119821/7570792/db0073d8-f7e0-11e4-8b8a-19fcebb3d2a3.png)

@xmatthewx Should we make this a build issue?

**Comment by flukeout** [comment]
@vazquez Awesome thanks - related to #1707

**Comment by xmatthewx** [comment]
Thanks. These `feedback` issues should be triaged before we invest time on them.

**Comment by xmatthewx** [comment]
I really like this solution, but it won't work for editing text on a button, since we already have set destination in that position.

**Comment by xmatthewx** [comment]
Maybe they could be side by side button. Maybe not.

**Comment by vazquez** [comment]
Made those changes too. Looks good.

![button options](https://cloud.githubusercontent.com/assets/1119821/7589771/c8148ca2-f892-11e4-8e44-9dc3bf5a7e95.png)

**Comment by Pomax** [comment]
crosslinking this to https://github.com/mozilla/webmaker-android/issues/1644, would the "edit label" button result in the in-place editing as comped in that issue?

**Comment by xmatthewx** [comment]
@pomax - Yes, let's add that explicit button for editing both text strings and button labels.

If content editable proves too complicated for v1, our plan B will leverage that button and an input field. Inline is better for preview, in a dialog is probably easier to design, use, and implement.

**Comment by Pomax** [comment]
whether editing kicks in from a button or from a tap is basically the same complexity, I was thinking of not using the contentEditable property at all but overlaying a transparant background input element, making the "real preview"s color `transparent` and then people can type intuitively.

**Comment by xmatthewx** [comment]
@Pomax - looks good for text element. Let's add this for link element as well. omp above https://github.com/mozilla/webmaker-android/issues/1792#issuecomment-101302677
