### ISSUE TITLE
[MIGRATED] Transparency slider values have different number of digits after the decimal, causing little jumps

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1793]
When you adjust the transparency of an Image Element, the value shifts around a bit when you switch between values like .81 and .8

We can solve this by left-aligning the value or by always having a two digit value, .80 instead of .8 (with special exceptions for 0 and 1).

@vazquez What do you think?

**Comment by vazquez** [comment]
I would propose left aligning the values.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/92"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/92.
Please don't comment on it here.
