### ISSUE TITLE
[MIGRATED] Page Editor always starts with one of the elements on the Page selected, but shouldn't

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1794]
I think we're auto-selecting the last-added (or modified) element on a page, but let's not auto-select anything.

**Comment by Pomax** [comment]
without commenting on whether it's good or bad: it's restoring the component's state as it was when a user navigated away from it, which includes the information on which element was selected at the time

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/93"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/93.
Please don't comment on it here.
