### ISSUE TITLE
Tapping an already selected page on map view seems like it should bring up the Page Editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1795]
Often, I find myself tapping an already selected page in order to edit. Should we add this an additional method to get to the Page Editor?

@xmatthewx Thoughts? Might be a good testing issue.

**Comment by thisandagain** [comment]
I'd say let's test it. I've seen a bunch of user's double tap today.

**Comment by flukeout** [comment]
Closing as solved by #1925
