### ISSUE TITLE
[MIGRATED] In map view, I'm able to pan really far away from the project pages and get lost.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1796]
Let's limit the panning so that something is always just barely visible.

**Comment by thisandagain** [comment]
:+1: getting similar feedback from testers.

**Comment by xmatthewx** [comment]
Spoke with @LauraReynal in the field. This has actually been a blocker. Might be good to tackle in Beta 1/2 if possible. 

It sometimes happens while doing a pinch to zoom. I checked against google maps to see if it allows pan during zoom. It does, but... it's pinch to zoom maps 1:1 between gesture and view. Streets stay relatively aligned with your fingers. Our zoom seems to be 1:1.5 between gesture and view. Pages expand more than my gesture.

**Comment by thisandagain** [comment]
The behavior you are describing is being tracked here for Beta 1/2: #1697

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/94"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/94.
Please don't comment on it here.
