### ISSUE TITLE
[MIGRATED] Add a "maxed out zoom animation" to indicate max zoom has been reached.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1797]
I think on either end of the zoom spectrum we should add a little bounce to indicate that you can't go further. I can provide detailed spec for this but something to this effect:

* Put map in fully zoomed out state
* Attempt to zoom out more
* The map will zoom just a tiny bit more out but will stop after that even if you continue zooming
* When you release your fingers the map will bounce back to the fully zoomed out state

I think these 'rubber boundaries' will help users realize that they're at the max zoom level. Right now there is just a hard stop and I find myself trying to zoom out beyond it just thinking my gestures aren't registering.

@vazquez Thoughts?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/95"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/95.
Please don't comment on it here.
