### ISSUE TITLE
[MIGRATED] Add animation to newly added tiles and newly generated plus tiles.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1798]
We need some kind of little pop or "ba-doop!" animation for newly created tiles. Just showing them suddenly is a little jarring. Maybe a little sound might be nice as well?!

**Comment by thisandagain** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/96"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/96.
Please don't comment on it here.
