### ISSUE TITLE
"Exit Editor" action icon in header isn't correct

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1799]
App is using a back arrow. Spec shows a back arrow going through a box:
https://projects.invisionapp.com/share/BK2M18Q28#/screens

**Comment by xmatthewx** [comment]
This "exit" icon appears in the header of project view and page editor. It returns to origin (discover, make). It's important to distinguish it from the back arrow used on simple views. 

![tile map view empty deleted tile](https://cloud.githubusercontent.com/assets/53411/7576362/c330a67c-f80a-11e4-92b9-87565ca92ada.png)

**Comment by thisandagain** [comment]
Tracking in #1604
