### ISSUE TITLE
Glitchy scale & rotate behavior

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1800]
Here's a way to produce unexpected element rotation behaviour:

* Add an image element
* Start scaling and rotating it
* Drag your second finger off of the edge of the screen to the right
* Now add take that same finger and drag onto the screen from the outside of the phone on the left
* This often causes a glitch in the rotation, snapping the image to an unexpected angle

Try it a few times from both sides of the phone, happens to me fairly consistently on my Nexus 4

* Another way to induce it is to take your second finger and pan it off the bottom right of the page, then bring it up to the top right and pan it in from there.

@Pomax Can you reproduce?

**Comment by Pomax** [comment]
Hm, I cannot reproduce that on my Nexus 7

**Comment by flukeout** [comment]
Nexus 7?! O_O!!
Anyone with a Nexus 4 able to do this?

**Comment by k88hudson** [comment]
I'm unable to reproduce this :S

**Comment by thisandagain** [comment]
I'm in the same boat. No luck reproducing on:
Nexus 4 running Android 5.0.1
Nexus 5 running Android 5.1

**Comment by flukeout** [comment]
Vined it https://vine.co/v/em0UWPveQdp
