### ISSUE TITLE
We need to figure out the UX of displaying a selected Tinker color

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1803]
Tinker isn't implemented yet, but we need the UX & UI for showing a Tinkered color being used on an element. I think our assumptions right now are:

* Tap tinker to open tinker mode for color
* Choose a fancy color and confirm
* On the Edit Element view, we add the newly chosen color below the row of stock colors with a 'selected dot' on top of it

@vazquez @xmatthewx Thoughts on this?

**Comment by vazquez** [comment]
Is this what you mean?

https://github.com/mozilla/webmaker-android/issues/1541#issuecomment-96669830

**Comment by flukeout** [comment]
@vazquez Yes, perfect! Is it worth mocking up as well inside of the Edit Element view for something like text color? I don't want to make it seem like it's just for page backgrounds.

**Comment by vazquez** [comment]
Matthew and I thought that when the row gets full, the older colour is bumped out to make room for the new colour.

**Comment by vazquez** [comment]
Now that I think of it, I think someone might want to save the colour, right? I think that is backlog at this point, but I think we can see if @LauraReynal sees it necessary during the qualitative tests.

**Comment by xmatthewx** [comment]
Unlikely to land in v1, but we could add this to a list of nice-to-have summer features flagged for community contributions.
