### ISSUE TITLE
[MIGRATED] Color tinker mode icon is too close to the other color options.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1805]
In the spec, there is quite a large gap between the color options and the Tinker Mode icon:
![image](https://cloud.githubusercontent.com/assets/25212/7572023/5c5f1b3e-f7d0-11e4-85f8-72aa9799aec6.png)

Let's keep the app consistent with the spec.

**Comment by xmatthewx** [comment]
That space in the spec never felt resolved to me. It felt like an accident. I'd rather close this and readdress after we get other feedback about color and tinker.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/97"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/97.
Please don't comment on it here.
