### ISSUE TITLE
[MIGRATED] Range - Tapping label causes slider to move

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1806]
For example, edit an Image element, there are two attributes controlled by sliders, transparency and border width. If you tap either of those labels, it will move the slider to just below your finger. This seems a bit over-sensitive and unexpected.

We can make the tap zone a little smaller, or maybe move the labels a little higher for breathing room.

@vazquez What do you think, can you reproduce this?

**Comment by vazquez** [comment]
I can reproduce this. I think the label is bound to the input. Therefore when tapping the label, it modifies the slider input. I would call this a bug. What do you think?

**Comment by thisandagain** [comment]
My recommendation is to just resolve the label-as-bound-to-slider problem. The handles feel the right size.

**Comment by vazquez** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/98"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/98.
Please don't comment on it here.
