### ISSUE TITLE
[MIGRATED] Padding around a selected element is uneven.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1807]
Steps to notice:
* Add an image element
* Give it a think white border
* Go back to the Page Editor and scale it up
* The padding between the selected border and image border is bigger on the bottom of the element

It should be consistent all around.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/99"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/99.
Please don't comment on it here.
