### ISSUE TITLE
[MIGRATED] "make" view "create a project" button is the wrong color

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1809]
It's a very jarring teal

**Comment by thisandagain** [comment]
Matches spec.

**Comment by Pomax** [comment]
reopning for that cc - if it's per spec, the spec probably needs changing.

**Comment by vazquez** [comment]
The colour looks like it's up to spec, but not the shadow.

The button in the App has a solid shadow:

![2015-05-12 11 13 07](https://cloud.githubusercontent.com/assets/1119821/7590736/fa34788c-f897-11e4-9bc7-63bfc0451b7f.png)

The button in the UI specification has a light shadow, as per Material design:

![screenshot 2015-05-12 11 17 11](https://cloud.githubusercontent.com/assets/1119821/7590848/77c33e14-f898-11e4-99e1-11861819f360.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/100"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/100.
Please don't comment on it here.
