### ISSUE TITLE
[MIGRATED] Increase maximum border thickness.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1810]
For the Image Element, a 10px (current max) border isn't thick enough, especially when an element is scaled down, we should provide a larger range - let's try 25px?

@vazquez Thoughts?

**Comment by vazquez** [comment]
I agree. I was playing with this and 10px doesn't feel substantial. I was thinking doubling to 20px. But why not go the extra 5 pixels? :)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/101"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/101.
Please don't comment on it here.
