### ISSUE TITLE
[MIGRATED] Consider 'Projects' as label for 'Make' tab

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1811]
as part of the "make" view, I would not expect this to point to anything.

**Comment by xmatthewx** [comment]
I'm not sure I understand. Make view is a list of the user's project, where they tap to open and edit.

**Comment by Pomax** [comment]
in that case the "make" view may not be intuitive. If it lists all the things I've made, then "make" is not the header I would associate with what I can do there. Following android parlance, "my projects" would make more sense.

**Comment by xmatthewx** [comment]
- `Make` matches the MWC app and aligns with the Webmaker name. 
 - `Projects` might better align with user expectations. 
 - `My` will always give me flashbacks to Windows XP. :frowning: 

cc @LauraReynal

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/102"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/102.
Please don't comment on it here.
