### ISSUE TITLE
[MIGRATED] flick-swiping in the project view swipes and then does an odd little slow-repositioning

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1812]
when fast flickr-swiping in the project view to quickly get to some "far away" pages, the content swipes fast, but then has a (seemingly) superslow little end animation

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/103"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/103.
Please don't comment on it here.
