### ISSUE TITLE
Sort out UX for the mode in which you open your own project for editing

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1813]
Currently, if you zoom in and pan the map, then leave the project and then open the project again, the map isn't *quite* in the same place as you left it.

Let's decide how we want to handle this for the editor. Some options...
* Start exactly where you left the map (same zoom and pan values)
* Start at a fixed zoom level (3-up ish?) centered on the start page  (Once we have a way to set that)
* Zoomed in to the start tile in the Page Editor (Again, once we have a start tile)

I kind of like starting off exactly where you last left your project as the author - I think that's what the editor is trying to do now, it just doesn't get it quite right. @k88hudson Is that right?

For play mode, let's start zoomed in to the start page.

@xmatthewx Thoughts?

**Comment by thisandagain** [comment]
Agreed to the two behaviors you descibe. @flukeout can you file a bug specific to the editor zoom / position restoration?
