### ISSUE TITLE
Font Size attribute for Text Element seems pointless since I can pinch-scale

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1815]
Since for now we're not using a 'bounding box' approach to text elements, there doesn't really seem to be a need for the Font Size setting.

**Comment by xmatthewx** [comment]
Slider should at least reflect changes made with pinch transform. 

Until we're ready to implement bounding box, 
 - we can hide font-size setting
 - we should alignment

**Comment by thisandagain** [comment]
Agreed that we should remove the font-size slider. Confirmed by quite a few test users today as well (via backchannel).

**Comment by xmatthewx** [comment]
> we should aligment

Ack. We also should removed text alignment options
