### ISSUE TITLE
New Feature Milestone

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1816]
Plan a release for small incremental features that won't fit in v1. Uncomplicated, bite-sized things like background color on text.

**Comment by xmatthewx** [comment]
We have two bugfix releases scheduled to coincide with Maker Party. Can we align this with the second one? Or should this follow those two? It could serve as excuse for a nice announcement.

 - 1.0.1 - 7/3 - Maker Party - Bugfix release
 - 1.0.2 - 7/17 - Maker Party - Bugfix release + features??
 - 1.0.3 - 7/31 - Features??

@thisandagain @secretrobotron

**Comment by thisandagain** [comment]
Having one solid stabilization release before adding additional features I think is needed. As long as the feature additions are small, introducing them during the second half of makerparty or immediately afterwards works well from my POV. I just want to make sure this doesn't distract from making progress on desktop.

**Comment by xmatthewx** [comment]
Ok. Adding [1.0.3](https://github.com/mozilla/webmaker-android/milestones/1.0.3) for the end of July after two bugfix releases.
