### ISSUE TITLE
[MIGRATED] Tapping the Page Editor header while dragging an element "freezes" the element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1817]
To reproduce
* Add an image
* Drag it around, stop, but don't lift your finger
* Tap the header
* The element will no longer be draggable or rotateable

Sometime, it doesn't freeze, but instead rotates suddenly to a strange angle.

**Comment by thisandagain** [comment]
LOL. I love this edge case. :bug: :beetle: :space_invader: :smile:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/104"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/104.
Please don't comment on it here.
