### ISSUE TITLE
Map pinch zoom exhibits unexpected behaviour at maximum and minimum zoom

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1818]
**Steps to reproduce**
* Zoom out as far as possible and remove fingers
* Now, try to zoom out some more, and then zoom in 
* The map won't zoom in again until it has overcome a *phantom* zoom out
* The map should zoom in again as soon as you start to move your fingers apart
* This also happens in reverse when you try to zoom in past the maximum zoom level and then out again

Also, when the map is fully zoomed out, and you try to zoom out some more, it starts panning instead along with one of the fingers in the pinch gesture.

@k88hudson Let me know if you have trouble reproducing this or if the description doesn't make sense.

**Comment by thisandagain** [comment]
:+1: Getting a few matching user reports as well.

**Comment by LauraReynal** [comment]
:+1: 

Big bug noticed during all interviews here.
