### ISSUE TITLE
[MIGRATED] Release Delete while holding element position glitch

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1819]
Neat little glitch:
* Add an image and select it, release finger
* Press and hold the delete element icon
* With second finger, press and hold the image
* Release first finger from delete button
* Image will jump upwards, about 1/4 of the page height

**Note** - this also happens with the Edit Element & Add Element buttons.

**Comment by Pomax** [comment]
:whale2:

**Comment by Pomax** [comment]
Sooo... reason for this is that, technically, a touch event registers as "second finger was released", despite the fact that the "a second finger was placed" never got registered.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/105"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/105.
Please don't comment on it here.
