### ISSUE TITLE
I can move selected elements no matter where they are if I start my drag gesture in the center of the page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1820]
Steps to reproduce:
* Add a text element
* Move it up to the top of the page
* Release finger
* Tap and drag with your finger from the center of the page
* Text Element will move as if you were dragging it directly

*insert spooky music here*

**Comment by flukeout** [comment]
Seems like maybe we have a phantom remembered position set to the starting point of the element that we never update? @Pomax - can you reproduce?

**Comment by Pomax** [comment]
hm, I can totally reproduce this, although I'm not sure why it would do this... except for "webview bug" where both the original and CSS transformed region counts as active region...

**Comment by flukeout** [comment]
Can't reproduce any longer - seems to have been fixed.
