### ISSUE TITLE
[MIGRATED] Add some kind of indicator for images with 0 opacity in the Page Editor view to make them easier to select. 

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1821]
When you make an image with 0 opacity and deselect it in the Page Editor - you have no idea that it's there. Should we add some kind of faint dashed border to those elements with maybe a crossed out eyeball icon or something like that? 

@vazquez What do you think?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/106"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/106.
Please don't comment on it here.
