### ISSUE TITLE
[MIGRATED] Allow navigating between pages in Page Editor by swiping and show adjacent page edges.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1823]
Page editor should show the adjacent page edges, including diagonal neighbors too and allow swiping to navigate to other pages.

**Comment by thisandagain** [comment]
This is a fairly large technical lift. Adding to backlog for now but something we should address in 1.0.1 IMO.

**Comment by flukeout** [comment]
@thisandagain For now, let's just remove the edges from this view altogether. I'll file a separate issue.

**Comment by Pomax** [comment]
this totally got teh dones

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/107"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/107.
Please don't comment on it here.
