### ISSUE TITLE
[MIGRATED] Run usertesting.com tests on creating experience

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1826]

**Comment by LauraReynal** [comment]
Do you have results So far @flukeout - curious to compare with London experience .

**Comment by flukeout** [comment]
No, I don't - I will launch a test tomorrow.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/108"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/108.
Please don't comment on it here.
