### ISSUE TITLE
Add Element open after going back to map view and then editing a Page again

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1832]
Steps to reproduce
* Edit a tile
* Tap "Add Element" button
* Tap the "Back" arrow
* You will return to the map view
* Edit the Page again
* Add Element view will still be open

I think we should hide it when you leave the Page Editor

**Comment by thisandagain** [comment]
:+1: this is related to the way in which we restore state currently.

**Comment by k88hudson** [comment]
This is resolved after the API refactor landed.
