### ISSUE TITLE
[MIGRATED] Implement multi-line text editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1833]
### Implementation

Replace single-line text editor with multi-line text editor

**STATUS**: Design in progress

#### Original notes (filed by flukeout):

Steps to reproduce
* Add a text element, and edit it
* Change the text to "asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf" or "asdfasdf asdfasdf asdfasdf asdfadsf asdfadsf" or maybe even "asdfjjak kdjf ldkjf k dlfkj dlkfj adsklf jas"
* Or anything that has a lot of words and spaces!
* You'll notice that the preview will wrap the words across multiple lines
* Confirm the changes and return to the Page Editor
* The Text Element displays the text you typed all on one line

I know we're replacing the text editor, but this issue may still persist so we should be aware of it. We need to figure out how to handle the UX of wrapping and line breaks.

**Comment by Pomax** [comment]
should be fixed with https://github.com/mozilla/webmaker-android/pull/1877

**Comment by secretrobotron** [comment]
Just tried this with latest nightly.
Text doesn't wrap in editor either, and is always slightly misaligned.

**Comment by secretrobotron** [comment]
Blocks #1665

**Comment by secretrobotron** [comment]
cc @k88hudson

**Comment by k88hudson** [comment]
@vazquez can you add a comp/design spec for the multiline text editor?

Notes from our discussion:

* text editor should be vertically centered in preview window
* pressing enter should add a line break instead of exiting the editor
* users should use the hide keyboard button to dismiss keyboard

Note that if the editor is styled appropriately, there shouldn't really be a reason to ever hide it/replace it with a non-editable version (it can just always be shown)

**Comment by k88hudson** [comment]
cc @Pomax

**Comment by xmatthewx** [comment]
Will we implement resize of text container in the page view? Getting that to feel right is the bit that concerns me.

**Comment by k88hudson** [comment]
@xmatthewx If you think it would bee easier, having the textarea fill the entire preview and have text top-aligned would be better than nothing -- however, I was hoping we could go for something like this http://codepen.io/desandro/pen/gICqd

**Comment by vazquez** [comment]
So something like this:

![text options multiline](https://cloud.githubusercontent.com/assets/1119821/8064474/f733e790-0ea8-11e5-8597-a4d1782a7909.png)

**Comment by k88hudson** [comment]
@vazquez awesome, thanks!

**Comment by xmatthewx** [comment]
@k88hudson - I trust your plan for the preview area. 

I'm wondering about transforms on the Page view. Does a pinch still scale multi-line font-size? Spec includes a handle to allow users to resize the container and change the flow of text. Do you think implementation of that handle will be easy? If so, then we're golden. If not, we do we have a plan B?

**Comment by k88hudson** [comment]
@xmatthewx in this case, we decided on manual line breaks (with enter) and keeping resize the way it is as an interim solution,  since implementing a new resize paradigm is too much for the remaining time we have. Is that OK with you?

**Comment by xmatthewx** [comment]
:+1: Works for me as an interim solution. Sorry if I missed that detail somewhere.

**Comment by k88hudson** [comment]
No worries! There is a surprising amount of complexity here, thanks for following up :)

**Comment by k88hudson** [comment]
As discussed we are going to push this out of beta and go with a simple interim solution instead due to time constaints. https://github.com/mozilla/webmaker-android/pull/2149/files

**Comment by secretrobotron** [comment]
:+1: yay!

For followup: still unable to justify text and use an enter button for newlines.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/109"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/109.
Please don't comment on it here.
