### ISSUE TITLE
Surprising behaviour when tapping back arrow on Add Element screen

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1834]
When you are in the add Element View, tapping the back arrow takes you back to the map view. Tapping anywhere else on the page just dismisses it and returns you to the Page Editor.

This behaviour seems slightly surprising since I don't think of myself as being in the Page Editor but rather in the Add Element view. Should the back arrow just cancel the Add Element view?

@vazquez Thoughts?

**Comment by thisandagain** [comment]
:+1:

**Comment by vazquez** [comment]
Yes! :100:

**Comment by Pomax** [comment]
hm, that would imply it's an actual "screen", to be saved as a history entry. Does that make sense?
