### ISSUE TITLE
[MIGRATED] Pages become slightly smaller when they get the selected border

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1835]
Let's make all pages appear the same size.

**Comment by thisandagain** [comment]
Tried resolving this by moving the `border` from the `selected` class to the base class for each page, but it caused major performance problems. Not sure why, need investigation but any potential fix for this should be tested for perf.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/110"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/110.
Please don't comment on it here.
