### ISSUE TITLE
Release to Google Play as "Mozilla"

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1836]
For the public beta and release of Webmaker, we need to co-ordinate with MOCO the ability for us to package and release the app under the existing "Mozilla" account that is used for Firefox and Firefox Beta:

![screenshot_2015-05-12-13-56-45](https://cloud.githubusercontent.com/assets/747641/7598455/2919ab1a-f8af-11e4-89df-47cc67ff965a.png)
![screenshot_2015-05-12-13-57-32](https://cloud.githubusercontent.com/assets/747641/7598454/2918e27a-f8af-11e4-8fcc-69075e3f6adb.png)

@simonwex is this something you could lead for us?

/cc @hpauljohnson @davidascher

**Comment by ncalexan** [comment]
The challenge here is getting access to MoCo's signing keys.  I'd start talking to release management now because I know of no such out-of-band APK signing precedent.

**Comment by thisandagain** [comment]
Update: We have an email thread started with the release engineering team. 
/cc @sylvestre @simonwex

**Comment by thisandagain** [comment]
Received access this morning. Thanks @sylvestre!
