### ISSUE TITLE
[MIGRATED] Security Review

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1837]
We need to undergo a pre-release security review for both the app as well as [api.webmaker.org](https://github.com/mozilla/api.webmaker.org). @simonwex is this something you can take the lead on?

/cc @k88hudson @cadecairos

**Comment by simonwex** [comment]
There'll be some uncharted territory here for us as this is the first app with some native aspects to it. I've reached out to Yvan to see if there are any people on the app sec team that can lend hand. :raised_hands:

**Comment by thisandagain** [comment]
Woot! Thanks @simonwex :+1:

**Comment by thisandagain** [comment]
With login landed, we are now ready to go. @k88hudson and @simonwex can the two of you meet early next week to get this moving?

**Comment by k88hudson** [comment]
@thisandagain can do

**Comment by k88hudson** [comment]
@jbuck and I will be filling out an RRA this afternoon as per @simonwex's request

**Comment by k88hudson** [comment]
@simonwex  RRA completed for api.webmaker.org: https://docs.google.com/spreadsheets/d/1tKyU3xhurCSnyCOKB6J0V3Z673PA8ilJBLBam1Ni6QI/edit#gid=0

**Comment by thisandagain** [comment]
@simonwex @k88hudson Any updates?

**Comment by xmatthewx** [comment]
Ping. Any updates @simonwex @k88hudson @jbuck?

**Comment by k88hudson** [comment]
RRA is done, @simonwex is going to weigh in later today on next steps

**Comment by simonwex** [comment]
@k88hudson could you make the RRA writable? I think in addition to conducting load testing we should run through the sec review checklist. I'll do this this afternoon.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/111"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/111.
Please don't comment on it here.
