### ISSUE TITLE
[MIGRATED] Android keyboard blends into app UI when editing the Text Element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1840]
Hey @vazquez - what do you think about this? I feel like the keyboard grey clashes here with the underlying UI, which makes things confusing.

What do you think of hiding the other UI while the keyboard is open and leaving more room for the text editing? Let me know your thoughts - the screenshot is from a WIP build by @Pomax 

![image](https://cloud.githubusercontent.com/assets/25212/7600335/0a689fe0-f8bf-11e4-86ad-a56f19b9f75b.png)

**Another question** - what do you think is a good UX for dismissing they keyboard? I suggest we have an explicit action for it, maybe we can replace the "Edit Text" button with "Done"?

![image](https://cloud.githubusercontent.com/assets/25212/7600486/79fe3a08-f8c0-11e4-8f8d-f07fc422c7c4.png)

If we do that, we should probably change the color to green or blue or something, so that it stands apart from the keyboard and also changes from the "Edit Text" button.

**Comment by thisandagain** [comment]
I believe @vazquez spec-d the holo dark keyboard, correct?

**Comment by flukeout** [comment]
@Pomax is investigating wether we have control over the color scheme, the dark theme would help.

**Comment by thisandagain** [comment]
Just ran a test by switching the theme from `android:Theme.Material.Light.DarkActionBar` to `android:Theme.Material` to see if the webview would inherit the dark keyboard ... it doesn't. :frowning:

**Comment by vazquez** [comment]
:crying_cat_face: 

That is a bummer. However, I don't think this is critical. Re-skinning the keyboard is one of the first things an Android user does to their device. Therefore I would be hesitant to modify the UI so much based on an easily customizable user setting.

**Fleksy:** 1,000,000 - 5,000,000 Installs
**Swift:** 10,000,000 - 50,000,000 Installs
**GO Keyboard Lite + Emoji:** 50,000,000 - 100,000,000 Installs

What about, instead of hiding UI, making the preview the size of the remaining viewport when the user has the keyboard open?

![screenshot 2015-05-14 10 07 05](https://cloud.githubusercontent.com/assets/1119821/7633241/fdd2b2b2-fa20-11e4-807b-2aa182014049.png)

**Comment by vazquez** [comment]
Regarding dismissing the keyboard: When the keyboard is open, the bottom bar changes a bit. The System back button now becomes a hide keyboard button.

![screenshot 2015-05-14 10 09 39](https://cloud.githubusercontent.com/assets/1119821/7633317/67a67c64-fa21-11e4-8a02-e27bee656ce8.png)

Also, the keyboard would have a "Done" button

![screenshot 2015-05-14 10 11 55](https://cloud.githubusercontent.com/assets/1119821/7633373/a92fad36-fa21-11e4-8fc7-9e2f60790567.png)

I think we should leverage off the user's learned behaviour of the above actions. Do you think we need more ways of showing a 'submit' action?

**Comment by flukeout** [comment]
@vazquez Have a look below and let me know your thoughts. 
@Pomax Are we able to add an "Enter" key to the keyboard to support line breaks?

![image](https://cloud.githubusercontent.com/assets/25212/7638178/daa43bce-fa27-11e4-8737-162835661d3c.png)

**Comment by vazquez** [comment]
Yes, I think that would work for the grey issue + the interface would also allow for more focus when typing. :+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/113"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/113.
Please don't comment on it here.
