### ISSUE TITLE
Text Editor - Opening keyboard seems to push contents of webview to the left

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1842]
![screenshot_2015-05-12-17-19-26](https://cloud.githubusercontent.com/assets/747641/7601455/1eb24774-f8cb-11e4-9ccc-84c05fe3c23a.png)

**Comment by Pomax** [comment]
I can't reproduce this on either my Nexus 7 or an Android 5 AVD.

**Comment by thisandagain** [comment]
Looks like @secretrobotron is seeing this as well as per #1848

**Comment by secretrobotron** [comment]
Yup. On a moto g.

**Comment by thisandagain** [comment]
Cool. So that's confirmed on:
- Nexus 4 on 5.0.1
- Nexus 5 on 5.1.0
- Moto G on 5.0.2

**Comment by thisandagain** [comment]
Resolved by #1846
