### ISSUE TITLE
Project - Text elements are selectable

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1843]
STR:
- Create a page that has a text element
- Go back to the project view
- Tap on the text element in the page thumbnail

Expected
- Page is selected

Actual
- Keyboard comes up and text is editable

**Comment by Pomax** [comment]
this will be fixed with https://github.com/mozilla/webmaker-android/pull/1846, which changes the signal to edit to a button in the editor instead of the text itself.
