### ISSUE TITLE
Detect device & send Android users from browser to play store

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1849]
Android users who open a shared project link should be sent to the app in the google play store.

Reference diagram by @flukeout https://github.com/mozilla/webmaker-android/issues/1616#issuecomment-101424066

**Comment by thisandagain** [comment]
This will need to be handled by the web service. Mind moving this to `webmaker-desktop`?

**Comment by xmatthewx** [comment]
whoopsies
