### ISSUE TITLE
[MIGRATED] Padding below Button Element when it is selected is too large

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1850]
Bottom padding between selected border and the button should be the same on all sides. 

Currently, the bottom padding is too large:
![image](https://cloud.githubusercontent.com/assets/25212/7622461/8fe2dd32-f984-11e4-9020-6f9dcd4dc0bd.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/114"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/114.
Please don't comment on it here.
