### ISSUE TITLE
Remove "Text Align" option from Text Element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1851]
Currently, we don't support multi-line text, which means that changing the text alignment of the Text Element has no noticeable effect on the Text Element when it's on a Page, even though it changes what you see in the Element Editor.

**Comment by k88hudson** [comment]
@flukeout is this a long-term change or a short term fix

**Comment by k88hudson** [comment]
like, are we intending not to ever allow multi-line text?

**Comment by flukeout** [comment]
@k88hudson We are planning to support multi-line text, but until we do, the text-align property has no visible effect on what's on a page.
