### ISSUE TITLE
Discover & Make header doesn't match design in the spec

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1852]
Currently, it looks like this

![image](https://cloud.githubusercontent.com/assets/25212/7623276/3bec3814-f98d-11e4-969f-abefc4c9cdee.png)

How it's supposed to look - [Invision](https://projects.invisionapp.com/share/BK2M18Q28#/screens/71287111?maintainScrollPosition=false)

![image](https://cloud.githubusercontent.com/assets/25212/7623297/76cc221e-f98d-11e4-969f-4b49ecf13119.png)

**Comment by thisandagain** [comment]
Tracking in #1604
