### ISSUE TITLE
New projects should start with one blank tile centered at the 3-up zoom level

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1853]
Currently if you tap the `Create New Project` button, you see whatever you saw last when you were in the editor, but you should start in a view that:

* Has one single, selected Page
* Is zoomed to the 3-up level

**Comment by flukeout** [comment]
I'd like to get this fixed before running usertesting.com tests.

**Comment by thisandagain** [comment]
Tracking in #1825 

Though this will likely take the majority of the heartbeat to complete @flukeout. I recommend proceeding as best you can with user testing.
