### ISSUE TITLE
Hitting the back arrow when editing my own project should return to Make view not Discover

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1855]
Steps to reproduce
* Go to the Make view
* Create a new project
* Hit the back arrow to finish editing
* You will return to the Discover view

You should return to the Make view

**Comment by Pomax** [comment]
The mind boggling thing is that the OS back button works fine. Somehow, the nav bar's back button does not do the same thing

**Comment by Pomax** [comment]
after an app uninstall and retesting on several devices, this bug seems fixed. If you still see it: uninstall your webmaker app on android first, then rerun android studio build.
