### ISSUE TITLE
[MIGRATED] Add animations or touch states to button UI elements in Page Editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1857]
Let's add some touch state styles (pressed down) or pressed animations to these guys:

![image](https://cloud.githubusercontent.com/assets/25212/7623524/f3b0a546-f98f-11e4-8c74-584e0ee1fd70.png)

**Comment by thisandagain** [comment]
:+1: 
@vazquez do we have touch states spec-d for these buttons?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/115"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/115.
Please don't comment on it here.
