### ISSUE TITLE
Button - Change the text you see when you implement a button

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1860]
I am on the nightly apk, so I think I have the latest, forgive me if duplicate. 

When inserting a button now, it is written : "tap me"
...which makes people tap on the button. 

I saw one that has "mozilla" as a text. None of these options tell you it is actually a link. 

Proposed:
- "This is a button"
- "This is a link, change me ! "
...
Thoughts ? 

@flukeout @vazquez @xmatthewx

**Comment by vazquez** [comment]
We changed the text on the button in the designs to say "Ready? Go!" but something more explicit would be nice.

We already have a "Set Destination" popup below the button which I think addresses the "change me" vocabulary. What about saying "This is a button" on the button text like you suggest? Can't get clearer than that :)

![screenshot 2015-05-14 09 47 32](https://cloud.githubusercontent.com/assets/1119821/7632810/49a22356-fa1e-11e4-8c12-49bbb6fad354.png)

**Comment by xmatthewx** [comment]
Thanks. This will be addressed without default text and colors in #1860.
