### ISSUE TITLE
[MIGRATED] Remove "Done" button from Text Element editing flow

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1861]
Let's hide the "Change Text" button after it's pressed. When a user wants to finish typing, they will either:
* Tap anywhere outside of the editable text area & keyboard
* Hit the done arrow on the keyboard

@Pomax Sorry for making you build the button!

**Comment by Pomax** [comment]
I don't quite understand. Either we have an "edit" button and a "done" button, or we have no buttons at all, but I don't understand why we'd have a button to initiate edit, but then no button to finalise. This sounds like something that needs a bit of discussion

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/116"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/116.
Please don't comment on it here.
