### ISSUE TITLE
Disable user-select in map view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#1868]
You can do some funky things selecting content while in the project map view. Content starts to move around within the pages. 

STR: 
 1. tap and hold to trigger android content select/copy feature
 2. drag select handles
 2. no idea how i got the thing to blink

![selected-blink 3](https://cloud.githubusercontent.com/assets/53411/7641519/3cbfe378-fa58-11e4-8d72-8d715b258050.gif)

![screenshot_2015-05-14-16-41-25](https://cloud.githubusercontent.com/assets/53411/7641529/5aa0d866-fa58-11e4-8310-ae11a28fe48f.png)

**Comment by thisandagain** [comment]
Glitch art easter egg! :stuck_out_tongue_winking_eye: :space_invader:

**Comment by flukeout** [comment]
Awesome! You get the glitch :crown: @xmatthewx

**Comment by Pomax** [comment]
that's pretty glorious (also, that's the text cursor btw)
