### ISSUE TITLE
[MIGRATED] Too few color options

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1870]
I think we should revisit our current color choices...

![image](https://cloud.githubusercontent.com/assets/25212/7642698/0cfc9506-fa48-11e4-8915-ac6febc80f4d.png)

Since we're removing Transparent and the Yellow will make the text invisible against the stock page background, this only leaves 4 usable options for Text Color.

If we add more options to this bar, it also makes us less reliant on Tinker mode initially.

@vazquez Thoughts?

I was digging through some of our older UX and found some examples of designs with more starting colors: 

![image](https://cloud.githubusercontent.com/assets/25212/7642755/86db0178-fa48-11e4-95e8-e3adfe713ca1.png)

![image](https://cloud.githubusercontent.com/assets/25212/7642771/9a646608-fa48-11e4-9b55-2c0c6cb7e9a4.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/117"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/117.
Please don't comment on it here.
