### ISSUE TITLE
Android - Poor performance when using Data URIs in SharedPreferences

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1873]
The `SharedPreferences` APIs are starting to show some weaknesses when used across Java & JS. Most notably due to the lack of a good async pattern which causes us to block the main thread when restoring / saving state. In addition, because `SharedPreferences` is essentially an XML file that is persisted to disk, we are taking a pretty serious hit with data URIs. Because of the way we have `SharedPreferences` encapsulated this should be a fairly trivial change.

**Comment by thisandagain** [comment]
http://developer.android.com/reference/android/database/sqlite/package-summary.html
https://github.com/satyan/sugar

**Comment by ncalexan** [comment]
Re: "good async pattern", `SharedPreferences` are automatically synchronized across multiple threads by the Android backend.  So it's actually much easier to do the right thing asynchronously using `SharedPreferences` than if you rolled your own.

Re: writing data URIs to `SharedPreferences`, this is an issue -- but I wouldn't expect your performance to be better with SQLite.  Marshaling data to and from a DB in this way is not much better than marshaling to and from the XML file that `SharedPreferences` writes.

What is the nature of the data you are storing as data URIs?  If it's image captures from the camera, for example, you might be better served by actually storing image files.

**Comment by thisandagain** [comment]
@ncalexan Really good point re: `SharedPreferences`. I'll take a look at persistence / access from the JS to images on disk vs. data URIs today to see if that helps resolve some of the performance issues. Recasting this ticket based on your feedback. Thanks!

**Comment by thisandagain** [comment]
This seems to have been mitigated quite a bit by @k88hudson 's API patch #1869 . Moving to backlog.

**Comment by ryanw-se** [comment]
@thisandagain SharedPreferences does provide some options that allows you to save/write data in the background instead of blocking the main thread. Might be worth looking into.

**Comment by thisandagain** [comment]
This can be closed now that we are using `MemStorage` for most things. Generally when we use `SharedPreferences` we want to have a transaction guarantee.
