### ISSUE TITLE
[MIGRATED] Identify additional opportunities for interface sounds

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1875]
Currently the app only makes a sound when you use the back arrow and open the 3-dot project menu. What are some other places where we can use sound?

* Adding & Deleting pages
* Adding & Deleting elements
* Opening a project
* Opening a Page to edit
* Swiping between pages in zoomed-in view (when available)
* ...
* others?

@gvn @vazquez

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/118"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/118.
Please don't comment on it here.
