### ISSUE TITLE
maxlength not working on TextInput

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#1879]
This seems to be a bug in Android's webview implementation, but `maxlength` isn't being enforced on device.

**Repro Steps:**
1. Type more than the character limit

**Expected:** Once limit is reached, any further character input is blocked.
**Actual:** Additional characters can be entered beyond the limit.

**Comment by thisandagain** [comment]
Can you give this another shot w/ the latest on `develop` (Crosswalk)?

**Comment by gvn** [comment]
The behavior is a little less wacky, but you can still type past the character limit...

**Comment by thisandagain** [comment]
Boo! Alright js hacky-time it is.

**Comment by gvn** [comment]
From the desk of Mr. @flukeout ...

Steps to reproduce

In the Project Settings view, start editing the Title
Just add one character at a time until you get close to the limit
When you get to 26/25 characters, the line and indicator turns red, good!
When you get to 27/25 (and above) the line indicator turn blue again, bad!
Now, start backspacing one character at a time
The line and indicator turn red again only at 24/25 (bad)
