### ISSUE TITLE
[MIGRATED] Deleting a tile is too easy and painful without undo

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1880]
Deleting is the second-most emphasized action and both @Pomax and myself have pressed it a few times by accident. Would be great to have an UNDO - or some way to make it a bit harder to mis-tap. Maybe a different color icon or slightly different placement?

@vazquez Thoughts?

**Comment by LauraReynal** [comment]
:+1: happenned to me a lot

**Comment by thisandagain** [comment]
Happens to me quite a bit too. I'm wondering if we should have a confirmation in the near-term.

**Comment by Pomax** [comment]
we should pick up on explitives via the microphone after a delete, and if there's a volume spike, undo.

**Comment by xmatthewx** [comment]
this _is_ painful. @pomax's approach would be ideal. in the short-term, we could follow material design's snackbar + undo pattern.

![delete page undo](https://cloud.githubusercontent.com/assets/53411/7999256/5e8a2d8c-0b16-11e5-86c9-325c8ffba331.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/119"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/119.
Please don't comment on it here.
