### ISSUE TITLE
Button position shifts unexpectedly after changing the label.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1882]
Say I'm going to edit this button:
![image](https://cloud.githubusercontent.com/assets/25212/7661888/895ca226-fb0b-11e4-975b-2ecc2c254a99.png)

I'm going to change the label to something longer. The element stays centered in the preview...

![image](https://cloud.githubusercontent.com/assets/25212/7661858/53a168ec-fb0b-11e4-925a-3d1f63a1cf47.png)

![image](https://cloud.githubusercontent.com/assets/25212/7661864/5ea436c0-fb0b-11e4-9b8d-6be7cd9ec4f1.png)

But when I return to the Page, the suggested behaviour in the Element preview makes this positioning a little unexpected:

![image](https://cloud.githubusercontent.com/assets/25212/7661899/a45f2e54-fb0b-11e4-94fe-5ec8544bfef4.png)

**So, two bad things**
* I feel like the button should have stayed centered (so we track the x,y position from the middle of the button not the top left)
* The Button Label shouldn't have wrapped, it should stay one line and run off of the page

**Comment by Pomax** [comment]
https://github.com/mozilla/webmaker-android/pull/1877 adds `pre` whitespacing to the app, so the text wrapping should no longer happen with that.

**Comment by k88hudson** [comment]
Hm, this is a tricky one. Currently we are using the "web" paradigm of positioning, where `0, 0` top left corner. Do we want to change this to a custom system where coordinates are relative to the centre instead?

**Comment by k88hudson** [comment]
@thisandagain what are your thoughts on this

**Comment by thisandagain** [comment]
@k88hudson Given the way we let elements move around in space, using the center as anchor point `0,0` makes a lot of sense to me.
