### ISSUE TITLE
[MIGRATED] investigate what the best follow-up is for "auto select an element when you delete one"

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#1887]
as followup to https://github.com/mozilla/webmaker-android/issues/1885, there are a few things we can do based on user testing, some more complex than others, and all open questions (disabled it again? autoselect the "nearest" element to the deleted on? How do we deal with zindex conflicts etc).

**Comment by Pomax** [comment]
Also, from the PR review:

>what to do when we auto-select an element that is totally obscured by another element (lower z-index). As it stands, the user won't be able to see which element the trash can will affect.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/120"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/120.
Please don't comment on it here.
