### ISSUE TITLE
Require a lower Android minSdkVersion

### ISSUE THREAD

**Issue by ncalexan** [mozilla/webmaker-android#1889]
Right now, `app/build.gradle` asks for `minSdkVersion = 21`.  I have lowered this to 13, which is the lowest trivially possible since we use some Android 13 things.  (It's not clear these 13 things are necessary: they may not be used or they could be provided by a compat library.)

Is there a reason to require such a modern Android?  Perhaps React Native sets a lower bound?  Perhaps you can't run in a non-Chromium web view?

**Comment by ryanw-se** [comment]
@ncalexan I'm not exactly sure what the reasoning was behind setting the minimum SDK so high, I don't think lowering it will be a problem once crosswalk is implemented and I'm not sure about react.

**Comment by thisandagain** [comment]
Because the `WebView` varies so much between versions of Android (particularly down to 4.2) we have the `minSdkVersion` set to 21 until #1872 lands as to allow us to have consistency.
