### ISSUE TITLE
Cannot drag/pan/zoom

### ISSUE THREAD

**Issue by ncalexan** [mozilla/webmaker-android#1890]
This may be my issue, because I'm running on an earlier Android version -- see #1889.

But I can't do anything with drag/touch events.  I do see events in the log, like:
```
05-17 12:45:30.259  23099-23099/mozilla.org.webmaker I/chromium﹕ [INFO:CONSOLE(171)] "touchmove", source: file:///android_asset/www/js/project.bundle.js (171)
05-17 12:45:31.009  23099-23099/mozilla.org.webmaker I/chromium﹕ [INFO:CONSOLE(156)] "start", source: file:///android_asset/www/js/project.bundle.js (156)
05-17 12:45:31.049  23099-23099/mozilla.org.webmaker I/chromium﹕ [INFO:CONSOLE(196)] "end", source: file:///android_asset/www/js/project.bundle.js (196)
```

**Comment by ncalexan** [comment]
Oh -- I'm running 95e65f1640de62b6a89381a0c061c3273efea2b0 with only the `targetSdkVersion` modified.

**Comment by thisandagain** [comment]
This is due to the inconsistencies in the way `WebView` performs between Android versions. This is being tracked in #1467
