### ISSUE TITLE
Many icons are not centered

### ISSUE THREAD

**Issue by ncalexan** [mozilla/webmaker-android#1891]
Many (but not all of the icons) are not centered, they appear too far to the left:

https://www.dropbox.com/s/53qbu0voygq9z37/webmaker.icons.1.png?dl=0
https://www.dropbox.com/s/vu2u4dz2annj3no/webmaker.icons.2.png?dl=0

I'm running 95e65f1640de62b6a89381a0c061c3273efea2b0 with only the `targetSdkVersion` modified (see #1889).

**Comment by thisandagain** [comment]
This is due to the inconsistencies in the way `WebView` renders between Android versions. This is being tracked in #1467
