### ISSUE TITLE
[MIGRATED] Deleting - Make it possible to select multiple pages for deletion 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1893]
It's incredibly annoying to delete the pages one by one when you have a lot of pages (which happens in a minute when tinkering)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/121"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/121.
Please don't comment on it here.
