### ISSUE TITLE
There is a gap at the bottom of the page when it is completely covered by a picture 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1894]
There is a weird picture misalignment between those 3 steps : 
- zoom out 
- edit page
- selected page 

My picture was perfectly fitting the whole page, then in zoom out there is this weird yellow gap, then when I select the page it looks okay. 

![screenshot_2015-05-18-14-01-37](https://cloud.githubusercontent.com/assets/8261945/7684522/9df9b29e-fd7e-11e4-8514-ba958c1a0616.png)
![screenshot_2015-05-18-14-02-03](https://cloud.githubusercontent.com/assets/8261945/7684521/9df96f3c-fd7e-11e4-9f6f-0144b958dd95.png)

**Comment by LauraReynal** [comment]
This happened 3 times with different pages and pictures

**Comment by xmatthewx** [comment]
pretty sure this is resolved
