### ISSUE TITLE
Deleting - creates whole in the zoom out view 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1895]
If you have 20 pages, and you start deleting only some in the middle. You end up with something like this, Which is surprising and bizarre because you dont know if you are loosing one of the 2 islands of pages. 
It seems impossible that there would be no connections between the 2 islands of pages ?

![screenshot_2015-05-18-13-45-34](https://cloud.githubusercontent.com/assets/8261945/7684598/45c30322-fd7f-11e4-8b0e-311b4ad6a90c.png)

**Comment by thisandagain** [comment]
This was by design so that users could create little "islands" of content and then link them together.
