### ISSUE TITLE
Text is visible in zoom out but invisible in edit - I can't find it and fix it 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1896]
Might be a duplicate but in doubt. This hello world text keeps appearing in zoom out but not in edit, no matter how much I move things around. 

![screenshot_2015-05-18-13-54-10](https://cloud.githubusercontent.com/assets/8261945/7684644/969d610c-fd7f-11e4-9246-bda2372bf82f.png)
![screenshot_2015-05-18-13-54-14](https://cloud.githubusercontent.com/assets/8261945/7684645/969f95b2-fd7f-11e4-92b8-9d65ddd16600.png)

**Comment by k88hudson** [comment]
Hm, I think this was due to incompatibility between old and new text block data and is fixed on the latest build.

**Comment by k88hudson** [comment]
This should be resolved now
