### ISSUE TITLE
[MIGRATED] Pictures get resized automatically 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1897]
Aside from the compression and pixels that @thisandagain warned us about, pictures get resized in a size that is slightly different from the page format, which is frustrating if you want it to cover the whole page.

**Comment by thisandagain** [comment]
It doesn't do any cropping ... I'm fairly certain that it just takes whatever size you give it (so depending on your phone, the images could be 16:9, 16:10, 4:3, etc.). Are you suggesting that we should crop images to the aspect ratio of the page?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/122"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/122.
Please don't comment on it here.
