### ISSUE TITLE
Page - Default background color

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1899]
@thisandagain @xmatthewx

**Comment by thisandagain** [comment]
:yellow_heart: :yellow_heart: :yellow_heart: :yellow_heart: :stuck_out_tongue_winking_eye:

**Comment by thisandagain** [comment]
Because we won't have the background color editor in v1.0.0 we should select a more neutral default.

**Comment by LauraReynal** [comment]
:yellow_heart: :sun_with_face: :sunflower: :sunny: :sunrise: :sunglasses:

**Comment by vazquez** [comment]
What about a very subtle blueish white? `#FAFCFF`


![tile view copy 2](https://cloud.githubusercontent.com/assets/1119821/7752628/7a22d01c-ffae-11e4-8a74-58ac6c063aca.jpg)

**Comment by thisandagain** [comment]
Oooh ... that's nice. :+1:
