### ISSUE TITLE
Refactor Link to pass data

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#1903]
We need a way to pass client-side data between activities/views.

I propose that we refactor the **Link** component to pass attached data to its target.

EG: `<Link payload={someData}...`

Most likely `someData` would be passed as a second param in `window.Android.setView`.

EG: `window.Android.setView(this.props.url, this.props.payload);`

When the target view is loaded it should have `someData` attached.

Ideally, this should work both on device and in browser... :dancers:

**Comment by gvn** [comment]
Blocks: #1670

**Comment by gvn** [comment]
CC: @thisandagain

**Comment by gvn** [comment]
We may also need a programmatic way to do this without a Link being clicked...hmm.

**Comment by thisandagain** [comment]
This is kind of tricky, but I suppose we could re-write the `Router` class to allow for a string (serialized JSON) to be passed along in addition to the URL. This could be added to the bundle (the same as what we do with route params now) which would in turn be passed back to React for de-serialization via a mix-in. @k88hudson @ryanw-se any thoughts?
