### ISSUE TITLE
[MIGRATED] Tablet & Desktop UI

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1904]
Dumping ground for a first pass on major Tablet & Desktop UX details. Will sort out once it's all collected. 

**Existing Views**
* [x] Map - play mode
* [x] Map - edit mode
* [x] Page - play mode
* [x] Page editor
* [x] Element editor
* [x] Selected element
* [x] Discover view
* [x] Make view
* [ ] Edit Profile (just change username for now?)

**Future Views**
* [ ] Code editor

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/7714469/a4ead730-fe33-11e4-964f-389b62f9425f.png)

**Comment by flukeout** [comment]
![desktop-and-tablet](https://cloud.githubusercontent.com/assets/25212/7713286/9cfc7d38-fe2b-11e4-9584-61c3ad2ffba6.png)

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/7716418/bf4c61f8-fe46-11e4-9251-7b5a7ac3cd88.png)

Not really sure on the zoomed in view on this one. Do we need to isolate the current page better?

**Comment by flukeout** [comment]
**Next Up**
* Add view for social features in sidebar for play mode

**Comment by thisandagain** [comment]
Great. I think with that plus a pass on the splash / login flow we should be good to move into the code editor and get @vazquez started on applying our UI styles.

**Comment by vazquez** [comment]
:baby_chick:

**Comment by flukeout** [comment]
Let it go @vazquez Tucker is dead... :baby_chick: :skull:

**Comment by vazquez** [comment]
Way to break my heart. Ruthless.

**Comment by ryanw-se** [comment]
Long live tucker! (In our hearts) :smiley:

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/7780966/f058ea22-009a-11e5-8e46-d4b2af62bcbe.png)

**Comment by flukeout** [comment]
![desktop-and-tablet-2](https://cloud.githubusercontent.com/assets/25212/7800725/b2ce86f4-02ce-11e5-9c08-14c009a9617a.png)

**Comment by flukeout** [comment]
Alternatively, assuming you can browse without having to have an account, we can do the following...

![desktop-and-tablet-2](https://cloud.githubusercontent.com/assets/25212/7800985/84b8ed50-02d2-11e5-802d-81bd366342bb.png)

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/7801738/7036e77c-02de-11e5-9f02-3d74be241d02.png)

**Comment by flukeout** [comment]
What's missing here is a desktop (and non-android tablet) splash page that lets your browse Featured Projects and also create an account and sign in.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/123"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/123.
Please don't comment on it here.
