### ISSUE TITLE
[MIGRATED] Move checkbox into navbar

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#1911]
We need to move the placeholder HTML button into the Android navbar for Project Settings.

**Comment by thisandagain** [comment]
I'm likely not going to be able to get to this during this sprint. Can we add a button within the webview or automagically trigger the `PUT` to the API?

**Comment by gvn** [comment]
Yep, there's another ticket to wire it up to the backend: #1909 

This is just to finish up the design-end of things, but not a functional blocker! :+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/124"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/124.
Please don't comment on it here.
