### ISSUE TITLE
Drag to pan is broken on first load

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#1912]
**Repro Steps:**
1. Go to discover tab
2. Tap 1st project
3. Try to pan

**Expected:** Page map pans as you drag it.
**Actual:** Nothing happens when you drag.

**Comment by gvn** [comment]
FWIW: If you go back home and then re-open the project it works as expected.

**Comment by k88hudson** [comment]
Hm. I'm having trouble reproducing this

**Comment by k88hudson** [comment]
Resolved
