### ISSUE TITLE
[MIGRATED] Implement Error states

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1922]
We need to have error states when creating / editing / deleting on projects, pages, and elements.

**Comment by flukeout** [comment]
**List of possible errors**

* [ ] Username too short or too long
* [ ] Username contains illegal characters
* [ ] Failed to create a new project
* [ ] Failed to delete a project
* [ ] Failed to load a project
* [ ] Failed to load list of projects in Make or Discover views
* [ ] Failed to load an image in a project
* [ ] Failed to load a page within a project
* [ ] Failed to upload an image when editing a project

**Comment by k88hudson** [comment]
Here is a list for each view:

### General

* [ ] User loses/has no network connection
* [ ] Network request times out

### Discover

* [ ] Discover gallery fails to load
* [ ] Discover gallery has no items

### Make

* [ ] Make gallery fails to load
* [ ] Make gallery has no items
* [ ] Create new project fails

### Project

* [ ] Project fails to load/not found
* [ ] Project is empty, attempt to create first page fails*
* [ ] Create new page fails
* [ ] Delete page fails

*Note: This is when a project is first created, has no pages, and the first page is created. This may need some specific behaviour here, like a prompt to re-try creating the first page... unless we can simplify creating the first page to a single request https://github.com/mozilla/api.webmaker.org/issues/53

### Page

* [ ] Page fails to load/not found
* [ ] Position update fails (scale, translation, etc.)
* [ ] Create new element fails
* [ ] Delete element fails

### Element editor

* [ ] Element fails to load/not found
* [ ] Style/attribute update fails

### Tinker mode

* [ ] Element fails to load/not found
* [ ] Style/attribute update fails

**Comment by k88hudson** [comment]
SO MUCH ERROR :warning:

**Comment by flukeout** [comment]
@k88hudson I started some work in [The Error States Diagram](https://dl.dropboxusercontent.com/u/109902/tiles/error-states.pdf) - please have a look over it and let me know your thoughts.

**Comment by flukeout** [comment]
@vazquez Has already done some work on [No internet in Discover mode](https://www.dropbox.com/s/m3mdb8782smp6iz/Screenshot%202015-05-21%2015.44.42.png?dl=0) state.

**Comment by xmatthewx** [comment]
@flukeout - your spec on these states looks great. You've nicely divided things we should report via
 - the view background
 - a snackbar notification ([material docs](http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage))

I think we need a review from an engineering perspective on what's feasible to build this heartbeat (and if we'll need to adjust design to fit that scope).  

cc @Pomax

**Comment by xmatthewx** [comment]
@Pomax - can you review this doc? [The Error States Diagram](https://dl.dropboxusercontent.com/u/109902/tiles/error-states.pdf) 

What do you think is feasible to build this heartbeat?

**Comment by Pomax** [comment]
this is going to depend on how much time solving https://github.com/mozilla/webmaker-android/issues/1946 leaves.

**Comment by Pomax** [comment]
started with implementing a tester for "snackbar" notification in https://github.com/mozilla/webmaker-android/pull/2080, which can then be used to move several of our "currently console.error" errors into

**Comment by Pomax** [comment]
Also wrapping:
[x] sign-in failure
[x] sign-up failure

**Comment by xmatthewx** [comment]
Are we in good enough shape for our next release? If so, let's close this and file any follow up necessary. @Pomax @thisandagain

**Comment by cadecairos** [comment]
> Also wrapping:
> 
>     sign-in failure
>     sign-up failure

@Pomax I recall seeing duplicate errors here when signing up, one on the page, and one "snackbar" style. is that still the case?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/125"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/125.
Please don't comment on it here.
