### ISSUE TITLE
Project - Enable double tap to zoom

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1925]
@flukeout @xmatthewx @thisandagain 

I never saw a user pinching, everyone spends all their energy double-tapping to zoom. Im wondering if you would be considering another zoom option.

**Comment by thisandagain** [comment]
Great feedback. Ok ... converting this into an implementation ticket.

**Comment by flukeout** [comment]
:+1: Awesome, we already had a similar issue in #1795 - which I've closed.
