### ISSUE TITLE
Change button label from "tap me" to "this is a button" or else, self explanatory

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#1926]
In today's buid, the button is called "Tap Me" 
which makes everyone tap... but nothing happens. Its akward. 

Aplogies I cannot seem to find the other issue but I understood we agreed on "this is a button" or something similar. But not "Mozilla" or "Tap Me".

cc @xmatthewx

**Comment by thisandagain** [comment]
Tracking this in #1863
