### ISSUE TITLE
[MIGRATED] Pull to refresh UX issues

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1927]
**Some notes on the pull-to-refresh feature on the Discover & Make page**
* Don't hide the list of projects while the view is checking for and loading new projects
* Don't hide the spinner until the view has finished loading

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/126"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/126.
Please don't comment on it here.
