### ISSUE TITLE
[MIGRATED] Make - Remove author link from project card

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1928]
All of the projects listed on the Make page are created by the person looking at the app, so we can ditch the author name link. For example, in this view the line that says "asliwinski" should be removed:

![screenshot_2015-06-29-13-02-27](https://cloud.githubusercontent.com/assets/747641/8417103/34746010-1e5f-11e5-9fb4-35dc86250b25.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/127"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/127.
Please don't comment on it here.
