### ISSUE TITLE
Tapping "Create Project" seems to create two project views

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1929]
When you tap Create Project on the Make view, the view switches to the Project Editor twice. Initially, we see a loading bar under the Project title header, and then when the project finishes loading, the view Jumps a bit again before showing the project contents.

It looks like the 'loading state' is a separate view, which is also shown when backing out of the project (which I'll file separately)

**Comment by thisandagain** [comment]
Tracking in #1930
