### ISSUE TITLE
When I create a new project, the center page of the project should be selected.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1934]
When the Project Editor opens the center page of the starting project should be selected. This lets the user act on a page immediately. Currently no page is selected.

**Comment by flukeout** [comment]
@k88hudson Just wanted to tack onto this - right now if I create a new project, there is no page selected, but I can see the delete and edit actions. If I tap delete, the app gets stuck in a loading state and nothing happens.

**Comment by k88hudson** [comment]
Ok, both of these issues are resolved.
