### ISSUE TITLE
[MIGRATED] Adding a page takes a very long time

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1935]
Adding a page to a project takes too long, can this be improved?

**Comment by k88hudson** [comment]
Not really, unfortunately. It depends on the speed of your network connection.

**Comment by thisandagain** [comment]
Though I think we should look at the performance on the API side as it seems like the ms response time may be a little slow. @cadecairos any thoughts?

**Comment by k88hudson** [comment]
That is unless you're seeing significant problems with the response time from api.webmaker.org, which is worth taking a look at

**Comment by cadecairos** [comment]
if we're talking about response times from our free-teir heroku resources, I'd say its too soon to try looking for specific optimizations...

**Comment by flukeout** [comment]
@k88hudson Can't we sync to the API in the background while editing seamlessly in the app front end?

**Comment by thisandagain** [comment]
@flukeout I'd like to hold off on that until a future release. That is a pretty huge lift and difficult to do well in an environment / API / models that are constantly changing / unstable.

**Comment by thisandagain** [comment]
@cadecairos We are running on two dynos.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/129"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/129.
Please don't comment on it here.
