### ISSUE TITLE
Loading/progress experience when adding a new page is confusing

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1939]
When I tap a plus tile to add a new page, the app shows a loader underneath the header of the project. This seems to suggest an app-level loading function because it's also used when the entire project is loading.

If it's necessary to show a progress indicator for this action, I'd rather see it in the place where the new tile is being added.

**Comment by k88hudson** [comment]
@flukeout definitely agree, this is spec'd in the latest designs from Ricardo (having trouble finding the ticket...). Closing as a dupe
