### ISSUE TITLE
[MIGRATED] Limit Pull-to-refresh action to the Discover & Make View

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1941]
Currently, I'm able to initiate the pull to refresh action in the Make, Page Editor and Edit Element views. It's only necessary on the Discover view.

**Comment by thisandagain** [comment]
Good catch!

**Comment by k88hudson** [comment]
@thisandagain @flukeout do we want to maybe remove this for all views? Seems to be a new feature in Chrome that refreshes the page.

If you're OK with default browser behaviour (i.e. white screen before things load) we'll leave it in, but what are your thoughts?

**Comment by flukeout** [comment]
@k88hudson I changed the issue to reflect this - we should only have this available in the Discover view.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/130"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/130.
Please don't comment on it here.
