### ISSUE TITLE
[MIGRATED] There is a flash of black screen when going back to the Page Editor from the Edit Element view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1942]
Steps to reproduce
* Edit an element
* Tap the back arrow
* Before the Page Editor appears, there is a flash of a black screen

The view shouldn't flash black, it should go directly back to the map editor.

**Comment by k88hudson** [comment]
I'm actually seeing this between every view. @flukeout can you confirm if that's the case?

**Comment by thisandagain** [comment]
Confirmed between the Element and Page views. I don't see it anywhere else though.

**Comment by flukeout** [comment]
@k88hudson Only noticed when returning from Element to Page view

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/131"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/131.
Please don't comment on it here.
