### ISSUE TITLE
[MIGRATED] Strange glitchy flash when starting and finishing editing text

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1943]
Steps to reproduce
* Add a text element
* Edit it
* Tap the "Edit Text" button in the Edit Element view
* When the keyboard opens, there is a glitchy flash that briefly shows the text element being stretched horizontally
* The same happens when you finish editing the text

**Comment by k88hudson** [comment]
Hehehe that's a pretty awesome glitch

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/132"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/132.
Please don't comment on it here.
