### ISSUE TITLE
Changing text element color has no effect on the element in the Page Editor view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1944]
Steps to reproduce
* Edit a text element
* Change the color
* The preview is updated above
* Tap the back arrow to return to the page editor
* Text element is color is still black
* When you edit the text element again, it is black, and there is no color set in the UI

What should happen
* Text should change color in the Page Editor view
* When edited again, the correct color should be selected in the UI

**Comment by flukeout** [comment]
Hm, looks like I'm unable to reproduce this now, the changes seem to be taking effect. Will leave open until someone else tries to reproduce.

**Comment by thisandagain** [comment]
I can't reproduce either.
