### ISSUE TITLE
[MIGRATED] Refactor api to handle errors and loading states

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#1946]
Some design work is being done in https://github.com/mozilla/webmaker-android/issues/1922 to define error states, as well as loading states.

When we have a better idea of what we want to do for both those states, we should refactor the `api` module to include functionality (probably mixins) for:

* Setting `this.state.loading`
* Showing/hiding loading UI
* Handing errors and empty states,
* Showing/hiding error UI with error message

**Comment by Pomax** [comment]
Given that the API only knows about getting and setting keys, I don't think the `api` module itself is the right place to put all this. Instead in keeping with separating concerns I'd recommend new components for each dialog type we need (overlay and snackbar, at least) and a new module or mixin that houses the save/load function for a component as well as the logic for triggering UI changes to notify users of errors during the save/load code paths.

**Comment by Pomax** [comment]
started with implementing a tester for "snackbar" notification in https://github.com/mozilla/webmaker-android/pull/2080, which can then be used to move several of our "currently console.error" errors into

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/133"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/133.
Please don't comment on it here.
