### ISSUE TITLE
[MIGRATED] Pan animation after adding a new page isn't smooth

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1947]
When adding a new page that would expand the bounds of a project (very left or right for example) the animation that brings the page into view after adding it is jerky.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/134"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/134.
Please don't comment on it here.
