### ISSUE TITLE
It's possible to add multiple elements from one 'add element view'

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1949]
Steps to reproduce
* Tap Add Element in the Page Editor
* Quickly tap the image icon as many times as you can before the Add Element view closes
* Check how many toucans you added, I'm able to add up to 4

You should only be able to add one element at a time.

**Update**
If you add two elements in this way, you will only ever be able to select one of them. You can move the one you can't select, but you can never delete or edit it.

**Comment by errietta** [comment]
@thisandagain :3
