### ISSUE TITLE
[MIGRATED] Deleting elements and pages is too slow and feels broken

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1950]
When I delete an image or a page in my project, it takes a little while for the deletion to take effect. I'm assuming that this is because we're syncing the state of my project to the database before reflecting it in the UI. If we're going to maintain this behaviour, we need some kind of indicator that my action took effect and that we're just waiting for it to actually happen - otherwise it feels broken.

Ideally, the app would reflect the change immediately, and we could sync my project to the database in the background.

The map view has a 'progress bar' when the app is deleting a page - but it's hard to notice and realize that it's related to your action. The Page Editor view has no such indicator for deleting elements.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/135"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/135.
Please don't comment on it here.
