### ISSUE TITLE
Element z-index is changed when exiting the Page Editor

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1951]
Steps to reproduce
* Add a toucan
* Add some text
* Position the text over the toucan
* Go back to the map view
* In the preview, you can see already the text is hidden behind the toucan
* Edit that Page
* The toucan now has a higher z-index than the text

It should have the original z-index that was shown when you left the page initially.

**Comment by thisandagain** [comment]
Confirmed.

**Comment by k88hudson** [comment]
I don't think we ever implemented setting z-index, AFAICT from to code. What was the design spec to determine what the z-index of things is?

**Comment by flukeout** [comment]
@k88hudson So far, I think we've just been increasing the z-index as each element is added and remember that order. We have some spec for changing the z-index, which I'll try to find right now.

**Comment by k88hudson** [comment]
@flukeout right now they're all getting set to 1

**Comment by flukeout** [comment]
@k88hudson Got it. I meant that in some previous iteration, they'd maintain the z-index according to when they were added (newer elements had higher z-index). Not by virtue of actually having a z-index property, but just by the order in which the markup was added to the page.

**Comment by thisandagain** [comment]
Resolved in #2067
