### ISSUE TITLE
Incorrect input field validation behavior when changing Project Title

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1957]
Steps to reproduce
* In the Project Settings view, start editing the Title
* Just add one character at a time until you get close to the limit
* When you get to 26/25 characters, the line and indicator turns red, good!
* When you get to 27/25 (and above) the line indicator turn blue again, bad!
* Now, start backspacing one character at a time
* The line and indicator turn red again only at 24/25 (bad)

@gvn - I think you worked on this, correct?

**Comment by gvn** [comment]
Yeah, there's already a ticket for this #1879
