### ISSUE TITLE
[MIGRATED] Specify UX for changing the z-index of elements

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1961]
We used to have a ticket, or at least the interaction was described somewhere. I can't find it so we'll do it again. Our previous assumption was that you would tap an already selected element to raise it to the top of the z-index pile among the other elements on the page.

**Comment by flukeout** [comment]
I've got a couple of options [here](https://dl.dropboxusercontent.com/u/109902/tiles/z-index.pdf).

@vazquez Thoughts? [[flagged!]](http://plzkthx.herokuapp.com)

**Comment by flukeout** [comment]
For the option with a button, we could use a small icon instead of a text label:

![image](https://cloud.githubusercontent.com/assets/25212/7775607/60159e1e-0069-11e5-9359-c23505f4544f.png)

**Comment by thisandagain** [comment]
:+1: on this last option.

**Comment by vazquez** [comment]
I also like the icon for bring button to front.

For icons, these are some benchmarks to visually connotate z-index:  

![screenshot 2015-05-22 13 50 12](https://cloud.githubusercontent.com/assets/1119821/7776543/b2e14f24-0089-11e5-9e3e-eabb098d2d13.png)

![screenshot 2015-05-22 13 52 54](https://cloud.githubusercontent.com/assets/1119821/7776589/e4b50ec8-0089-11e5-8899-88e976d6b44a.png)

![screenshot 2015-05-22 13 53 53](https://cloud.githubusercontent.com/assets/1119821/7776598/013db0c2-008a-11e5-924a-31f50ecee18d.png)

**Comment by flukeout** [comment]
@vazquez Thanks! Let's work on the treatment in the next phase. 

Here's an [updated z-index diagram](https://dl.dropboxusercontent.com/u/109902/tiles/z-index.pdf) with the option we liked.

**Comment by vazquez** [comment]
Solid diagram Luke :rocket:. I think we should run with this. I think the radical approach might be a bit too radical (I find it confusing to use 2 icons), but let's have it on the table! :)

**Comment by flukeout** [comment]
For the **Radical Mode** let's make it so that the overlapping toucan has a "down" arrow instead of hte invisible eyeball thingy on the button. I'll update the diagram.

**Comment by xmatthewx** [comment]
This could be a good candidate for an in-app prototype.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/136"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/136.
Please don't comment on it here.
