### ISSUE TITLE
Implement loading states for projects, lists, and pages

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-android#1966]
We need an indeterminate loader for actions that have API calls such as adding an element, deleting a page, etc. This loader will show when network connections are slow. Otherwise for fast connections, this will rarely be shown.

cc / @k88hudson

**Comment by vazquez** [comment]
#### Prototype

http://codepen.io/rvazquez/pen/xGELVZ?editors=110

Note: Use Firefox

What do you think @k88hudson, would this work?

**Comment by k88hudson** [comment]
@vazquez looks great!

**Comment by vazquez** [comment]
:rocket:

**Comment by k88hudson** [comment]
Resolved by https://github.com/k88hudson/webmaker-android/commit/b82342ddaafd8bee5b9c2baa7eb99b5e38fdc371
