### ISSUE TITLE
[MIGRATED] Page - Margin inconsistent across device aspect ratios

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1976]
When viewing the app on a Nexus S emulator (running Android 4.2) the margin surrounding the "page" is flush on the left and right sides. A margin of at least 10px should be applied regardless of the aspect ratio of the device / view.

![screen shot 2015-05-21 at 11 07 39 am](https://cloud.githubusercontent.com/assets/747641/7755577/f58cdc70-ffa9-11e4-9d42-2a30b9c7e524.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/137"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/137.
Please don't comment on it here.
