### ISSUE TITLE
[MIGRATED] Page - Change title when adding a new element

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1977]
Spec shows the dark overlay covering the entire page, but currently the header is not covered.

**Spec**
![image](https://cloud.githubusercontent.com/assets/25212/7757379/ad93a662-ffb6-11e4-9be3-dcbcc554063c.png)

**Comment by thisandagain** [comment]
This will likely be really difficult as transparent Crosswalk webviews aren't a thing. Alternate would be to rebuild this entire nav using native code. :worried:

**Comment by flukeout** [comment]
How about changing the header to say "Add an Element" while in this state?

**Comment by thisandagain** [comment]
That's totally do-able. :+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/138"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/138.
Please don't comment on it here.
