### ISSUE TITLE
[MIGRATED] Fun glitch on Add Element view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1984]
Steps to reproduce
* Tap Add Element
* Now, start tapping quickly anywhere else on the dark overlay
* You can get it to turn off and on indefinitely as long as you keep tapping!

cc @thisandagain

**Comment by errietta** [comment]
I think https://github.com/mozilla/webmaker-android/pull/2105 fixes that

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/139"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/139.
Please don't comment on it here.
