### ISSUE TITLE
Fun glitch on Add Element view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1986]
Steps to reproduce
* Tap Add Element
* Now, start tapping quickly anywhere else on the dark overlay
* You can get it to turn off and on indefinitely as long as you keep tapping!

cc @thisandagain

**Comment by thisandagain** [comment]
Dupe of #1984

**Comment by flukeout** [comment]
@thisandagain That's weird - I added this issue twice?! Damn
