### ISSUE TITLE
[MIGRATED] Map view moves in unexpected way after deleting a page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1987]
Steps to reproduce
* Create a new project
* Add a new page
* Zoom in a bit and center the view on the new page
* Select that page
* Tap "Delete"
* The view shifts a bit after removing the page

The view should stay where it was (same position and zoom level).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/140"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/140.
Please don't comment on it here.
