### ISSUE TITLE
[MIGRATED] Map view shifts after returning to it from the Project Settings view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1988]
Steps to reproduce
* In a new project, zoom in a bit
* Move the map a bit so that no tiles are perfectly centered on the view
* Enter the Project Settings view
* Tap the back arrow to return to the map view
* When the map view shows, moves to center on one of the tiles

It should just stay where it was when you left the map view.

**Note**: This happens when you delete a tile on the edge of a project.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/141"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/141.
Please don't comment on it here.
