### ISSUE TITLE
[MIGRATED] Button height changes when the label is blank

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1989]
Steps to reproduce
* Edit a button
* Remove all the text in the label
* Tap away from the button in the preview
* The button changes height

It should stay the same height, even with no content

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/142"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/142.
Please don't comment on it here.
