### ISSUE TITLE
[MIGRATED] Project / Play - Inconsistent zoom controls are confusing

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#1992]
The differences in how zoom is handled between the "Play" and "Project" views is really confusing. I often find myself switching back and forth and finding myself needing to pause to handle the context change. I'd like us to explore ways to unify here.

Thoughts @flukeout @vazquez @xmatthewx

**Comment by flukeout** [comment]
In particular, we need to address the discrepancy between what happens when you tap a page in the map mode in both views.

In **Edit** mode, the page becomes selected
In **Play** mode, the view zooms in to that page

This is quite a dramatic difference, how can we reconcile it when someone is switching between Edit & Play modes during authoring.

**Comment by flukeout** [comment]
Another issue, when editing and going into Play mode, should we:
* Swap out the UI only and keep the same map zoom level and position, or...
* Reload the project as if you were opening it from the discover view (start page zoomed in)

**Comment by flukeout** [comment]
Here's an attempt to reconcile some of the differences we're seeing right now:

![image](https://cloud.githubusercontent.com/assets/25212/7779934/0d7ac4e8-008e-11e5-814f-e90ecbe02ee7.png)

**Comment by xmatthewx** [comment]
@flukeout - review this with android/browser/desktop in mind.

**Comment by xmatthewx** [comment]
This is half addressed by the new project viewer UI (https://github.com/mozilla/webmaker-browser/issues/57#issuecomment-119373282). For the editor, we should likely:
 - Remove the pencil icon from the project view. Instead, users would tap a selected page to open it.
 - Move zoom-out to match the viewer.

I'm still not a fan of the selected state and would welcome alternate approaches to page delete so we could get rid of it. Three options:
 - Tap-and-hold to delete like apps on a home screen
 - More actions in page editor viewer
 - Trash in top right corner of page editor view

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/143"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/143.
Please don't comment on it here.
