### ISSUE TITLE
[MIGRATED] Double tapping an unselected page creates a strange effect

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1993]
**Steps to reproduce**
* Create a project and add some pages so you have 3 side by side
* In the map view, set the zoom to roughly 3-up
* Select the very left of these pages
* Double-tap the page to the right of the selected page (the middle page)
* The the very right page gets selected

It should select the 2nd, middle page. It's probably because the map state has already changed in the data model, but the animation hasn't caught up by the time you make the second tap.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/144"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/144.
Please don't comment on it here.
