### ISSUE TITLE
[MIGRATED] Possible to end up in Play mode with a higher than max zoom level

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1995]
Steps to reproduce
* Edit a project
* Enter play mode
* Tap a page to zoom in
* Exit play mode and go back to the editor
* Enter play mode
* The view is in "map view & pan mode", but the page size suggests the 'swipe zoomed in mode'
* When you attempt to zoom pinch from this state, the map zoom level immediately, and jarringly jumps back the max zoom level

We still have to sort out what zoom level and state we should start Play mode in though.

**Comment by thisandagain** [comment]
:+1: Good catch.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/145"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/145.
Please don't comment on it here.
