### ISSUE TITLE
Implement new page background colour

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#1996]
Hey @vazquez, what do you think - to me it feels like the white buttons get lost sometimes in the new, lighter color scheme. Like the trash icon here...

![image](https://cloud.githubusercontent.com/assets/25212/7779347/869176ac-0088-11e5-92d0-ad1c56842aed.png)

Hmm, when pasted into the issue here, it looks like it stands out a lot more than it does on the device. On the device you don't see the color contrast as much, just the little icon and shadow. Have a look on device.

**Comment by vazquez** [comment]
Let me take a peek on the :phone:

**Comment by flukeout** [comment]
Yeah man :mag: it out

**Comment by thisandagain** [comment]
:+1: I didn't notice it on the emulator at all and had to check it out on device. Might be worth dropping the tint back a little bit.

**Comment by vazquez** [comment]
Dropped it down to `#F2F6FC`

![tile view copy 2](https://cloud.githubusercontent.com/assets/1119821/7779931/2f348fa6-00a7-11e5-8e1e-7cb6c79eb3cc.jpg)
