### ISSUE TITLE
[MIGRATED] Elements are hard to position and rotate

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#1999]
My scenario:
* Using a wide image (or wide text)
* Trying to position it is difficult
* When resizing, rotation happens as well, often causing unwanted results
* Can't lock elements to horizontal alignment, so nothing looks crisp
 * Of course, I can meticulously align something under microscope, but often the resize+rotate problem prevents what I actually want

**Comment by secretrobotron** [comment]
Blocks #1665

**Comment by flukeout** [comment]
@thisandagain @secretrobotron This is a pretty deliberate choice on our part so I'm not sure that we should do anything about it other than wait for more feedback from other users. If the feedback mirrors your own frustration, we can examine a different layout model or maybe introducing some kind of alignment helpers.

**Comment by thisandagain** [comment]
Agreed. Thanks @flukeout

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/146"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/146.
Please don't comment on it here.
