### ISSUE TITLE
[MIGRATED] Very short tap on element shouldn't move it

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2001]
If you tap an element with some motion, the element will move.

Very short taps shouldn't move elements, since the user is probably just trying to select it, not move it (yet).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/147"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/147.
Please don't comment on it here.
