### ISSUE TITLE
[MIGRATED] Get ready for localization

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2002]
See https://github.com/mozilla/webmaker-android/issues/1599#issuecomment-103712914 for recommendations

- [x] Clean-up `strings.xml` resource - Andrew
- [ ] Provide JS API to Android string resource - Andrew
- [ ] Add filters to static files - K88
- [ ] Add filters to functional code (where necessary) - K88
- [x] Upload json files to Transifex - Bobby
- [ ] Shout-out on Transifex - Bobby
- [x] Alert launch teams
- [x] Create QA checklist (#2061)

Resources:
* webmaker-mailroom: https://www.transifex.com/projects/p/webmaker/resource/user_createdjson/
* webmaker-android: https://www.transifex.com/projects/p/webmaker/resource/webmaker-stringsxml/
* webmaker landing page
* play store?

**Comment by k88hudson** [comment]
@secretrobotron is there any action required from me during this heartbeat?

**Comment by thisandagain** [comment]
Assigning to self so I can get the first two items done.

**Comment by secretrobotron** [comment]
:+1: @k88hudson and I just spoke about that. If needed, when it's done someone (e.g. me) can hop in and replace strings with appropriate API.

**Comment by LauraReynal** [comment]
We have a team ready in Bangladesh, and we would like to know:

- How many string will be in the app for localization? 
- Is it possilbe to put the strings in the Pontoon localization tool ? 

cc / team members : @bellayet @tapuafrad 
Tracking in lauch repo here https://github.com/mozilla/webmaker-launch/issues/19

**Comment by LauraReynal** [comment]
some things might be of interest here https://github.com/mozilla/webmaker-launch/issues/28

**Comment by k88hudson** [comment]
@secretrobotron ok, i probably missed a few but most of them are in here:
https://github.com/k88hudson/webmaker-android/blob/intl/app/src/main/res/values/strings.xml

**Comment by secretrobotron** [comment]
@k88hudson yay! The comments you left `<!-- Make -->` are good indicators for localizers. Can we work on a [QA checklist ](https://github.com/mozilla/webmaker-android/issues/2061) now?

**Comment by k88hudson** [comment]
@secretrobotron yep, will do

**Comment by secretrobotron** [comment]
@k88hudson are you landing that today, btw?

**Comment by k88hudson** [comment]
@secretrobotron no, I want to wait until after launch

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/148"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/148.
Please don't comment on it here.
