### ISSUE TITLE
[MIGRATED] The app cannot be used without network connectivity, due to how api.js works

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2005]
We've tied a lot of calls to network connectivity by hook up the api.js function to first communicate the changes to the API server, and then allow them back through to the local client, instead of doing things the other way around. This might be easy to fix by being more permissive in terms of what to do on an error (still send the modification on as a success, for instance) but that feels like it'll leave us with a questionable design in terms of code flow. Ideally, ops should happen, and only then sent on to the API for syncing, caring about whether they sync only for the purposes of known whether we're in synced or desynced state.

**Comment by thisandagain** [comment]
Need to split this into three:
- Network loading state design / display
- Offline consumption (GET)
- Offline creation / production (POST, PUT, DEL)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/149"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/149.
Please don't comment on it here.
