### ISSUE TITLE
[MIGRATED] Element disappears when pinch zoomed quickly

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2006]
Steps to reproduce:
* Add a text element
* Pinch zoom it quickly

See https://vine.co/v/ebK0B7Ua3Px

**Note**: doesn't happen every time, but often enough 

@davidascher Can you add your device info?

**Comment by davidascher** [comment]
Nexus 5 running 5.1

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/150"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/150.
Please don't comment on it here.
