### ISSUE TITLE
Refactor WebAppInterface for performance / clarity

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2007]
The current `WebAppInterface` class exposes JS methods for a variety of things that share the same purpose (persisting state). This should be refactored to use the new `LRUCache`-based `MemStorage` class where reasonable.

**Comment by ryanw-se** [comment]
@thisandagain I'll take care of this tomorrow, if it hasn't already been assigned to someone!

**Comment by thisandagain** [comment]
Thanks @ryanw-se but I'm almost done with this one! :smile:
