### ISSUE TITLE
[MIGRATED] Ergonomics – Add browser polyfill for getRouteData binding

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2015]
The `getRouteData` method within `lib/router.jsx` does not provide a browser polyfill which makes testing / quick iteration more difficult. The `getRouteParams` method is a good reference for how this sort of testing polyfill could be implemented.

/cc @gvn

**Comment by gvn** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/151"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/151.
Please don't comment on it here.
