### ISSUE TITLE
When editing a block of content on a page it automatically selects another block of content

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2016]
Experience: 
- I add the following blocks of text 
- I touch "Hello Webmaker" it selects and moves "Let's launch you"
- I reposition elements how I wanted 
- it does it again and moves elements around without me asking. 
- I select an element, it gets bigger without me doing anything. 

Adding image: 
- I click on add image - I see tucker
- I change image and go back to page view 
- it remains tucker as if I did not do anything
- I go back to edit image: I see my own image 
Got it solved after a couple back and forth

![screenshot_2015-05-27-14-04-50 1](https://cloud.githubusercontent.com/assets/8261945/7843831/6573c6b4-047a-11e5-9683-66693d8dd370.png)

Blocks #1665

**Comment by secretrobotron** [comment]
This could wind up being the same problem as #1972.

**Comment by Pomax** [comment]
I suspect this is solved in the latest nightly/release, where we fixed the element select/ordering issue. Can you check whether this is still the case @LauraReynal?

**Comment by secretrobotron** [comment]
It felt a lot better for me this morning. Didn't happen to me at all.

**Comment by Pomax** [comment]
closing as resolved (please refile/reopen if we run into this again!)
