### ISSUE TITLE
UI - Placeholder for project thumbnail 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2020]
Scenario: User creates a new project and returns to Make view. Project thumbnail is generated via external service and isn't immediately available for display. 

Design a simple placeholder that will work for both the Make view and Project view (i.e. it shouldn't say "your" project).

**Comment by vazquez** [comment]
### Placeholder Project

Nondescript title, author, and image.

---

![make view with placeholder](https://cloud.githubusercontent.com/assets/1119821/7921106/27296008-0871-11e5-9f10-02c7e90bf71b.png)

@xmatthewx

**Comment by vazquez** [comment]
With a map silhouette, we can load them in randomly. Possibilities are endless!

Modified greys to make them more subdued.

![make view with placeholder copy 2](https://cloud.githubusercontent.com/assets/1119821/7922270/13c71f5c-0879-11e5-9f40-2182d081cc80.png)
![make view with placeholder copy 3](https://cloud.githubusercontent.com/assets/1119821/7922271/13c8ecd8-0879-11e5-82b2-6f4b20d09616.png)
![make view with placeholder copy 4](https://cloud.githubusercontent.com/assets/1119821/7922273/13ca3610-0879-11e5-87f8-be44dc892f77.png)
![make view with placeholder copy 5](https://cloud.githubusercontent.com/assets/1119821/7922274/13cb0f68-0879-11e5-8e6f-29a86ab16217.png)
![make view with placeholder copy](https://cloud.githubusercontent.com/assets/1119821/7922272/13c96852-0879-11e5-8299-c93f9b2cde84.png)

**Comment by xmatthewx** [comment]
These grays look better. 

These maps are probably too realistic and will likely prompt the confusion that it doesn't actually reflect the project map. We either need something more decorative, something you might use as an element in marketing assets ... or ... let's go back to your first instinct.

**Comment by vazquez** [comment]
Bringing it back to basics!

![make view with placeholder copy 6](https://cloud.githubusercontent.com/assets/1119821/7937656/6d2c1b42-090f-11e5-9187-daefa5cc5e58.png)

**Comment by xmatthewx** [comment]
This is okay to implement. Will file a separate ticket for implementation. Bumping this ticket back to next week for a chance at a more inspired thumbnail asset that  says "project" rather than "image"...

**Comment by thisandagain** [comment]
@vazquez @xmatthewx Can I get a link to the raw asset?

**Comment by vazquez** [comment]
@thisandagain Sorry about that, here you go - https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_anRyNkZ3RDVSdFE/view?usp=sharing

**Comment by gvn** [comment]
Is this the right aspect ratio? The current thumbs are much wider...

**Comment by gvn** [comment]
![screenshot 2015-06-10 15 37 11](https://cloud.githubusercontent.com/assets/206379/8095910/9ac840d0-0f86-11e5-9d15-4db2b090b54a.png)

**Comment by xmatthewx** [comment]
We should adjust the artwork to fit current implementation of thumbnails. I believe it is 320 x 198.
