### ISSUE TITLE
.jshintrc cannot be a symlink if we want to support devs on windows

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2026]
symlinks are great on unix, but don't work on windows: windows just sees a text file with a relative file location in it, which breaks `npm test` on windows when it tries to load the jshintrc file and just sees "text" instead of JSON. We can, however, just point to the node_modules/mofo-style version directly.

**Comment by gvn** [comment]
@Pomax This would be a great thing to add to the README for mofo-style!
