### ISSUE TITLE
Reveal and explain CC license

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2030]
All content on Webmaker is published under a Creative Commons Attribution-ShareAlike 3.0 Unported license. There are a few places we can reveal this info to app users. 

 - Project Settings - When a user adds a title to their project, they show intent to preserve their work. We have ample space here for a clear explanation. 
 - Remix - When one user remixes another users content, we should link to the license.
 - ~~Share~~ - the native android share flow doesn't give us space to do this. We also don't want to add friction to this activity.

**Comment by xmatthewx** [comment]
## Project Settings

This could benefit from a little UI love. 

![screenshot 2015-05-28 11 22 22](https://cloud.githubusercontent.com/assets/53411/7863717/d74087d0-052b-11e5-9211-b474016804a1.png)

**Comment by xmatthewx** [comment]
## Remix

![remix](https://cloud.githubusercontent.com/assets/53411/7863641/72c96362-052b-11e5-956a-526f859595b4.png)

**Comment by thisandagain** [comment]
Nice. Thanks for the update @xmatthewx . Let's talk about this on Monday with @vazquez but content-wise I'm happy to proceed.

**Comment by vazquez** [comment]
Made some minor updates @xmatthewx 

![project settings 2](https://cloud.githubusercontent.com/assets/1119821/7921018/943e8016-0870-11e5-8416-413afc985e4f.png)

@thisandagain Are we good to run with this?

**Comment by xmatthewx** [comment]
That is one seriously intense underline :smile:

**Comment by vazquez** [comment]
Toned it down. See :arrow_up:

**Comment by LauraReynal** [comment]
:+1: @xmatthewx 
I can't wait to see how users react to this. It has been one of the most confusing and important subject  during all interviews.

**Comment by xmatthewx** [comment]
:+1: Assigning to @thisandagain to review and assign for implementation. Would be good to get this in before the string freeze.

**Comment by thisandagain** [comment]
This looks good, though I think I'd like to keep it minimal and remove Tucker. Thoughts @vazquez @xmatthewx ?

**Comment by xmatthewx** [comment]
:+1: works for me

**Comment by vazquez** [comment]
Removing Tucker.

![project settings 2](https://cloud.githubusercontent.com/assets/1119821/7960662/2cb5e068-09d0-11e5-81ad-79441ba96b81.png)

**Comment by thisandagain** [comment]
:+1:
