### ISSUE TITLE
[MIGRATED] Textbox to view/edit project by ID (for debugging)

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2032]
I would like to be able to grab a project ID (from the DB or elsewhere), and use the app to visit that project to view it or continue to work on it.

Make sense to keep in debug build?

cc @thisandagain

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/152"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/152.
Please don't comment on it here.
