### ISSUE TITLE
[MIGRATED] Implement infinite scrolling / pagination for list views

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2035]
List views are currently limited to the first "page" of results. We need to implement something like https://www.npmjs.com/package/react-infinite-scroll to allow us to render all results.

**Comment by thisandagain** [comment]
Leaning towards https://github.com/seatgeek/react-infinite for implementation

**Comment by Pomax** [comment]
Do have to point out how annoying infinite lists are because it becomes impossible to jump back to "that one cool project you say an indeterminate amount of scrolling ago". I'd urge us to consider pagination, or at the very least infinite scroll with soft-pagination.

**Comment by thisandagain** [comment]
Not sure I follow @Pomax . 100% agreed in browser context, but do you have any examples of native mobile apps on Android that don't infinitely scroll infinite lists?

**Comment by xmatthewx** [comment]
@Pomax - keep in mind that future social features will make it easier to find things you found before (via profiles, likes, comment notifications, etc).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/153"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/153.
Please don't comment on it here.
