### ISSUE TITLE
[MIGRATED] npm is a devDependency

### ISSUE THREAD

**Issue by jbuck** [mozilla/webmaker-android#2038]
This seems odd: https://github.com/mozilla/webmaker-android/blob/1a2ef0bc55ad8feae76d6122f793db52274ca551/package.json#L49

**Comment by Pomax** [comment]
agreed, that should probably have been an engine requirement? @thisandagain?

**Comment by thisandagain** [comment]
Yeah. I think that's right ... I'm guessing @k88hudson had a good reason to add it though.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/154"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/154.
Please don't comment on it here.
