### ISSUE TITLE
Element - Updates to elements are often not reflected when returning to Page view

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2040]
STR:
https://www.dropbox.com/s/vapc2kysvoid36w/bug.mp4?dl=0
- Updates to element not reflected when returning to page view (0:14)
- Returning to the element editor and then going back will often resolve the issue (0:18 - 0:22)
- Two working attempts afterwards (inconsistent behavior)

/cc @secretrobotron @LauraReynal

**Comment by Pomax** [comment]
I'm looking into this bug but running into the fact that we may have engineered the solution for handling element updates in the [element view vs. element-editor vs. element component] construction that we use. I've filed https://github.com/mozilla/webmaker-android/issues/2046 as a ticket for us to discuss what we can do here, but initial investigations suggest that we might have to live with this bug until we rethink and then reimplement element updating through the editor view.

**Comment by thisandagain** [comment]
Thanks for the update and documentation @Pomax !

**Comment by k88hudson** [comment]
Underlying problem is documented here: https://github.com/mozilla/webmaker-android/issues/2053

The easiest fix here (for now) would probably be just to override `this.state.onBackPressed` in the parent component (`render.jsx`) to run the update code first instead of relying on the `pause` event. Do you think that's doable @Pomax?

**Comment by Pomax** [comment]
looking into that at the moment, it seems like it should be entirely doable to track whether the API has open calls, with a callback queue of things that need to be triggered once the queue's empty.

**Comment by Pomax** [comment]
properly closing this bug still depends on UI, currently being discussed in https://github.com/mozilla/webmaker-android/issues/2065

**Comment by k88hudson** [comment]
Confirmed, this was resolved by some previous commits, likely this one https://github.com/mozilla/webmaker-android/commit/addb83a822a7bbd7afc76d12b7ed0e0698b25497
