### ISSUE TITLE
[MIGRATED] Move Link element helper button

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2043]
**Context**: In the editor, a button element includes a helper button floating below it (button itself is disabled so that users can select and transform it.)

**Problem**: The helper falls behind tools and off the screen when moved too low on the page. 

**Solution**: Move the helper above the button when it is placed below a certain point (bottom quarter of page).

![screenshot 2015-05-29 16 10 11](https://cloud.githubusercontent.com/assets/53411/7891876/145c35ea-061e-11e5-8a1f-187398b6b077.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/155"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/155.
Please don't comment on it here.
