### ISSUE TITLE
[MIGRATED] clean up a bit of the confusion around element.jsx

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2044]
The element.jsx file is not actually an element, but the "element editor view", which wraps a text- or image- or link-editor, depending on what the user selected. Calling it "element", however, is rather confusing, especially when analysing which code kicks in where.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/156"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/156.
Please don't comment on it here.
