### ISSUE TITLE
[MIGRATED] rename all variables called "json" to something else, if they're not strings

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2045]
There's a few places where we're using the variable name `json` for already parsed strings. As JSON is a string serialization, this causes confusion while reading through the code to figure out where specific things happen, and these variables should be renamed to reflect the object they really are.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/157"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/157.
Please don't comment on it here.
