### ISSUE TITLE
[MIGRATED] analyse the element view <-> ...-editor <-> text/image/link component relations

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2046]
based on code diving done for https://github.com/mozilla/webmaker-android/issues/2040 it seems like we need to reevaluate how we're handling the way the element editor view, the editor component(s) and the actual element component(s) interact in terms of propagating state changes both locally and remotely (via api.js).

It is currently possible for an update to not get propagated in time, thus losing the update (visually, if not actually) and leaving the user with the element they were trying to modify in the same state it was before the user started modifying it.

**Comment by secretrobotron** [comment]
@Pomax considering you were just spelunking in the code, do you have a suggestion?

**Comment by Pomax** [comment]
it would help if I added that here in addition to #2040 wouldn't it. Basically the right way to do this as far as I can tell is to work with what React gives us, and have the elements be the only place where editable properties are set, using the ...-editor elements as pure UI veneer: they bootstrap based on the element they're loading, and then instruct the element to update their state with every user-initiated change in the editors.

The "element.jsx" needs a rename to reflect what it really is (tracked in https://github.com/mozilla/webmaker-android/issues/2044) since it's actually a wrapper around "some kind of element editor", so we might need to unify that in way that removes the separation between the element view and the "xyz-editor" components, but that's an engineering discussion.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/158"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/158.
Please don't comment on it here.
