### ISSUE TITLE
[MIGRATED] Border width scales with rest of element

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2051]
Borders scale with the rest of elements. They often become too small to see.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/159"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/159.
Please don't comment on it here.
