### ISSUE TITLE
Page thumbnails and play mode don't match actual content

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2052]
When I have lots of elements on a page, I can consistently dive into edit mode to manipulate those elements. However, thumbnails in zoomed-out mode or and pages in play mode don't appear to have all the elements.

e.g. 3 image and 4 text elements in edit mode becomes 2 image and 0 text elements in play mode.

**Comment by secretrobotron** [comment]
Check out the "Happy People" featured project. It's stuck in this limbo right now.

**Comment by thisandagain** [comment]
:+1:

**Comment by secretrobotron** [comment]
![screenshot_2015-06-01-13-06-35](https://cloud.githubusercontent.com/assets/403231/7918473/b25ad790-085f-11e5-909a-8a0a7445d47e.png)

**Comment by Pomax** [comment]
do we have an adb log that helps us debug this?

**Comment by secretrobotron** [comment]
Sorry; I just made it on my phone with a nightly build. Seems to happen often enough though. I'll see if I can reproduce in the emulator.

**Comment by secretrobotron** [comment]
Ah, I think I found a clue. After a whole bunch of messing about, I found that some images and text get moved behind each other irrespective of when they were added. This might be fixed by your z-index work, @Pomax .

**Comment by Pomax** [comment]
crosslinking to https://github.com/mozilla/webmaker-android/issues/2019

**Comment by Pomax** [comment]
this is definitely a z-indexing issue (both the image and text are z-index 0, and the image just happens to get drawn later, so it "wins" the round of z-index wars). Solving in #2019
