### ISSUE TITLE
Scale up api.webmaker.org heroku instance

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2054]
As part of an effort to improve the editing experience, I asked @jbuck to scale up the Heroku instance we're using for api.webmaker.org – he's also going to take a look at response times over the next few days.

While this won't solve all our problems it may make things a little faster.

cc @cadecairos @secretrobotron

**Comment by k88hudson** [comment]
This has now been completed

**Comment by secretrobotron** [comment]
:+1: woot. I'll test it out some more today to see if there's a positive difference.
