### ISSUE TITLE
Save button is weird in project settings

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2056]
As discussed, the save button is weird since the project is already saved. Better to just use the back button. That matches Material design pattern for settings.

**Comment by xmatthewx** [comment]
If that's more than a quick fix, changing the label from "Save" to "Save Title" would clarify things.

**Comment by k88hudson** [comment]
@xmatthewx @vazquez @thisandagain anyone have a good reference for what loading states would look like when pressing the back button

**Comment by xmatthewx** [comment]
@k88hudson - I don't think there would be anything new to load at this point. Sorry this ticket is unclear -- it was just a reminder for a fix discussed with @thisandagain.

Scenario - User edits a project. Taps settings menu. Edits the title. Taps `Save` to exit settings. View returns to project.

**Comment by k88hudson** [comment]
> As discussed, the save button is weird since the project is already saved. Better to just use the back button. That matches Material design pattern for settings.

@xmatthewx in this scenario, pressing back triggers the app to save the changes to the title -- so in the present implementation there might be a slight delay before that happens. Make sense?

**Comment by xmatthewx** [comment]
When we exit settings and return to the project, a delay in the display of the title _would_ be odd. Agreed. The title is in the UI spec, but not currently in the build. It seems like we can punt this concern for now.

Any delay in display of the project itself would be handled by @vazquez's loading indicator (#1966). Is this your concern?

**Comment by k88hudson** [comment]
Resolved by https://github.com/k88hudson/webmaker-android/commit/4ba595e2d1d30f62509fe8698803bce2531b4268
