### ISSUE TITLE
[MIGRATED] Need language dropdown (in debug mode?)

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2060]
Language will be picked up automatically from chosen device locale, but we should have a dropdown (preferably in a debug menu) that lets you override the selected language. This is helpful for debugging and for localizers that want to flip back and forth between languages.

Assigning @thisandagain because he's working on a debug menu.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/160"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/160.
Please don't comment on it here.
