### ISSUE TITLE
[MIGRATED] Provide qa checklist for localization

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2061]
Need a checklist to give to localization community so that they can make sure they cover all corners of the app in their translation effort. Useful to see how strings appear in context, and a guide/checklist can walk localizers through the app.

Most useful in an living/forkable document somewhere so localization teams can copy and edit for themselves.

Should it include a map for tokens -> strings to make it easy to find corresponding strings in Transifex?

Relies on #2002

**Comment by k88hudson** [comment]
Checklist in progress (mostly corresponds to the order/section of strings) https://gist.github.com/k88hudson/16e0b6a720f33e1f7c3e

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/161"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/161.
Please don't comment on it here.
