### ISSUE TITLE
[MIGRATED] clean up and refactor el.jsx

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2062]
`el.jsx` needs a renaming to "element" to keep things obvious for developers (consequently, pages/element may need renaming to pages/editor, because it's the view in which to edit elements, not the view in which to see an element), and needs some of its code written to be more verbose, as it's currently following some jQuery conventions that conflict with React's concept of writing complete code and letting minifiers do what they need to do.

There's also some querySelector work going on that needs to be rewritten to `this.refs` instead, as a component already knows everything about what it renders.

The sooner we do this, the easier it will be for people to understand and work with the element file.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/162"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/162.
Please don't comment on it here.
