### ISSUE TITLE
Update Webmaker logo 

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2063]
Refresh the Webmaker logo to work better across use cases: app icon, new site, marketing materials.

**Comment by xmatthewx** [comment]
current eps: 
https://drive.google.com/open?id=0BzfN9sXlOXt1b21XQW5ra2FaN1U&authuser=0

**Comment by xmatthewx** [comment]
app icon benchmarks:
https://docs.google.com/presentation/d/17GIntGX--znIaTOj--F5JKNH70LvhaaAF1QtEGfB-z0/edit#slide=id.g9b19de6cf_0_114

**Comment by xmatthewx** [comment]
@thisandagain - help me set a deadline on this. Design and review today and tomorrow. Final artwork delivered on Friday? End of day okay?

**Comment by thisandagain** [comment]
As per standup: Mockups to review by EOD Friday. Design critique face-to-face on Monday after stand-up w/ final assets by EOD Monday.

**Comment by xmatthewx** [comment]
Great kickoff with @lovegushwa. We (@vazquez @cassiemc me) agree that the thread and needle can be removed from the Webmaker logo. This change does not require a full rebrand process. 

@lovegushwa will explore new designs that could serve well as an app icon and revisions of the existing logo. If the icon doesn't show promise soon, we will shift full attention to an updated logo.

**Comment by thisandagain** [comment]
The only problem with that is going to be legal review IMO. See https://bugzilla.mozilla.org/show_bug.cgi?id=1159016 for context.

**Comment by xmatthewx** [comment]
Thanks for the link @thisandagain. Should have mentioned: We discussed that and will evolve the look of the thing with that in mind.

**Comment by thisandagain** [comment]
Perfect. :+1:

**Comment by xmatthewx** [comment]
Great progress this week. @lovegushwa did a thorough exploration on possible improvements to the current (M) logo. Simultaneously, he hit on a mark that offers a compelling alternative: an infinite path made with a joined `M` and `W`.

The team believes this design evokes various attributes of the app and will stand up well as an app icon. We chose to pursue this over iterations on the current (M). Next steps: 
 - explore color and details to find the right voice/tone 
 - examine resulting design in multiple contexts.

![mw](https://cloud.githubusercontent.com/assets/53411/8015368/f1b9d5be-0ba5-11e5-97f2-6d3dde79aed5.png)

**Comment by xmatthewx** [comment]
cc: @cassiemc

**Comment by cassiemc** [comment]
Cool thanks for the cc. *Loving* this new mark, it is so rad. Look forward to seeing the color variations. Will we also have some variations with a wordmark, @lovegushwa @vazquez?
@xmatthewx can you remind me what the timelines are for this?

**Comment by vazquez** [comment]
@cassiemc - We will focus on the icon first as we need to have a solid iteration finished by EOD today. We will then expand to address wordmark.

**Comment by xmatthewx** [comment]
Here's the plan as I see it. @thisandagain @cassiemc please confirm.
 - Today: complete design of logomark for review (applied in a few contexts)
 - Tomorrow: share proposal with Ops 
 - This week: finalize design and lock up with name
 - Friday: deliver final artwork

@thisandagain do you want to schedule with David and Mark?

**Comment by thisandagain** [comment]
I'll need the lock-up as part of the proposal (EOD today) but otherwise :+1: 
I'm guessing we can do this async but will confirm with @davidascher today and schedule if needed.

Started putting together a proposal deck here:
https://docs.google.com/a/mozilla.com/presentation/d/1dnjg8QfpbTWExUfEfwrVJ7lR2WBtXdlsIc7aSrt4_ME/edit?usp=sharing

**Comment by xmatthewx** [comment]
It seems like we have general consensus on the two options. I will try and sum up here and add a few more thoughts. 

### Option A

![screenshot 2015-06-11 13 17 43](https://cloud.githubusercontent.com/assets/53411/8113511/7b88666c-103c-11e5-8a05-55e7d37bc3aa.png)

 - softer edges and gradient are working great
 - some feel that green on blue feels a bit too dark and muddy
 - still loving everything this signifies
 - more vibrant color could yield a more friendly feel 

### Option B

![screenshot 2015-06-11 13 17 19](https://cloud.githubusercontent.com/assets/53411/8113512/7b8951a8-103c-11e5-9f35-fe29e452ab73.png)

 - this option unlocks lots of possibilities for the brand system
 - love the playfulness and spunk
 - logo feels too busy and less resolved. joints need attention. feels a bit dense in the middle. 
 - can the overlapping of the segments be emphasized more without introducing shadows?

**Comment by thisandagain** [comment]
Update: Logo is approved. :star: :star2: :+1: 
![webmaker-rorange-wins](https://cloud.githubusercontent.com/assets/747641/8121206/58aed9b6-105d-11e5-9a8a-f54317f23537.png)

Next steps:
- [ ] @lovegushwa to build final vector asset (due EOD tomorrow)
- [ ] @lovegushwa and @vazquez  to work on final type lock-ups (due EOD tomorrow)
- [ ] @thisandagain to update icon assets within APK
- [ ] @thisandagain to update icon assets within Google Play

Really nice work folks.

**Comment by k88hudson** [comment]
:fireworks: :fireworks: :fireworks: :fireworks: :fireworks: :fireworks:

**Comment by cassiemc** [comment]
BOOM. Fantastic work all, can't wait to see this out in the wild!

**Comment by xmatthewx** [comment]
That's the stuff. :clap: So glad the new colors worked.

**Comment by vazquez** [comment]
I took @mart3ll's type lockup found on DAM and applied it to the new logo mark.

![webmaker-lockup](https://cloud.githubusercontent.com/assets/1119821/8138568/04cfd166-111a-11e5-84df-f5ee5fcccd3a.png)

@mart3ll do you mind taking a look?

**Comment by xmatthewx** [comment]
@vazquez. Nice. Can you post an SVG or a bigger @2x PNG? 

It seems like the top of the shape is lower than the top of the word mozilla. Still think that we want the shape to align with bowls that break the baseline and x-height for optical alignment.

**Comment by vazquez** [comment]
No SVG yet since I'm using a png logo for now, but here is a 2x

![webmaker-lockup](https://cloud.githubusercontent.com/assets/1119821/8139197/b9550570-111f-11e5-9e0c-961275562fee.png)

and these are the guides:

![screenshot 2015-06-12 16 26 53](https://cloud.githubusercontent.com/assets/1119821/8139224/e4799f40-111f-11e5-9e89-3aa5b33bed3a.png)

**Comment by mart3ll** [comment]
Nice.  Looks good!

I actually have a spacing grid I can send along for all things wordmark (.ai file: http://cl.ly/1K3414291V03, preview: http://cl.ly/image/1O2z3W0E1a1Q), if you want to confirm the gutters: http://cl.ly/image/1s2P2U241f2Z

One thing I'd ask is it'd be interesting to see the what the swatch colors are for the brand, based on the new Mozilla palette (.ase files: http://cl.ly/352z213t3H0Z, preview: http://blog.seanmartell.com/2014/09/17/mozilla-id-project-palette-explorations/). All gradients within the logo here, but would be nice to see associated official color micropalette.

Beyond that, what would this logo look like in 1-color? We usually create a 1-color variant for all our logos based on external asks and to keep the brands flexible. Would be nice to see.

Thanks all!

**Comment by vazquez** [comment]
Thanks @mart3ll, the spacing grid helped a lot!

We will be iterating on creating some swatch colours for the brand, great point. I think it would be a nice activity for Whistler and we can tap into your expertise if you get a free moment :)

@lovegushwa has a very nice idea on a 1-colour version of this logo, this work is upcoming.

Partenered up with @lovegushwa to tweak the final details. Final lockup:

![webmaker-lockup](https://cloud.githubusercontent.com/assets/1119821/8140813/2e4bdae0-112d-11e5-996d-e314f8c1f8de.png)

AI file available on Google Drive: webmaker-icon-process > _FINAL > Webmaker-lockup.ai

**Comment by thisandagain** [comment]
Amazing work folks. @xmatthewx mind filing any follow-up work for this?
