### ISSUE TITLE
Auto refresh Make view on project exit

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2066]
When I create a new project, I expect to see that project in Make when I exit the project. Currently, I need to manually refresh.

**Comment by xmatthewx** [comment]
This also impacts remixes as noted by @gvn in https://github.com/mozilla/webmaker-android/pull/2141#issuecomment-110863555. A user will likely assume that their remix failed. 

Refresh would also be helpful for seeing updates to thumbnails and titles. Titles in particular feel like they failed to save. 

Seems important for v1.

**Comment by gvn** [comment]
Yeah, basically I think Make needs to always pull fresh data when it is focused. I'm not entirely sure how to get that to happen since it isn't being destroyed and rebuilt. Do we have some kind of focus event from Android that we can tap into? @k88hudson @thisandagain

**Comment by thisandagain** [comment]
Yup. We get Activity lifecycle events from the `MainActivity`. I can take this one.

**Comment by gvn** [comment]
:+1:
