### ISSUE TITLE
[MIGRATED] remove gaps from element zindexing

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2070]
as followup to https://github.com/mozilla/webmaker-android/pull/2069, when multiple elements have been placed, deleted, rearranged, clicked, and generally manipulated we can end up with a list of elements with "gaps" in the z-indexing, where we could have indices [2,3, 6, 12,13,14,15,28]. We can compress this ordering on save so that we'll never run into the issue of "running out of zindices" (despite that index being 2+ billion)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/163"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/163.
Please don't comment on it here.
