### ISSUE TITLE
Record project share activity

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2072]
We can gather some information sharing (and remixing) patterns by recording when a user attempted to share their project with someone else. It would also be great to understand who actually follows an share invitation.

* Can we ping api.webmaker.org when a user clicks the "share" button, and record it in the project table?
* When a user clicks on a share invitation link, can we record that too? I imagine we could use GA somehow to capture this when https://github.com/mozilla/webmaker-desktop/issues/69 is implemented.

cc @adamlofting @thisandagain

**Comment by secretrobotron** [comment]
cc @cecilepompei

**Comment by cecilepompei** [comment]
Emailed you the same funnily enough!
I would want to track:
 - how many times they send out their sharing link
 - how many times it gets converted and opened
 - how many active users are created
 - what kind of people share the most? are the most useful sharers (is there a way to know the profile of people??)

**Comment by secretrobotron** [comment]
Great. Let's hone in on those first two items here to start.

There *might* be an easy way to see how many users get created after having a project shared with them.

**Comment by thisandagain** [comment]
We now have event tracking in place for the "Share" intent as well as tracking when users hit the "Play" activity. I think this can now be closed. Anything I'm missing?

/cc @adamlofting

**Comment by adamlofting** [comment]
Just noting that our event tracking isn't tied to individual users. 

But I think the kinds of things we're hoping to understand will be measurable by looking at how often projects are remixed.
