### ISSUE TITLE
Add further GA tracking

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2073]
### Events
- [ ] Login
- [x] Create new project
- [ ] Share project

### Screen Views
- [x] Project by ID

**Comment by adamlofting** [comment]
By events, we mean these: https://developers.google.com/analytics/devguides/collection/android/v4/events

**Comment by thisandagain** [comment]
We've got screen views setup, but we can add events in the next heartbeat.

**Comment by thisandagain** [comment]
To track events we'll need a way to access this within JS. The Java API looks a little like this:
```java
// Get tracker.
Tracker t = ((AnalyticsSampleApp) getActivity().getApplication()).getTracker(
    TrackerName.APP_TRACKER);
// Build and send an Event.
t.send(new HitBuilders.EventBuilder()
    .setCategory(getString(categoryId))
    .setAction(getString(actionId))
    .setLabel(getString(labelId))
    .build());
```

Pseudo-code for a JS interface:
```js
if (window.Android) {
    window.Android.trackEvent('category', 'action', 'label');
}
```

**Comment by thisandagain** [comment]
@adamlofting Really simple JS API for tracking events the Android GA tracker has landed: https://github.com/mozilla/webmaker-android#google-analytics-event-firing

Just holler if you have any questions or concerns!

**Comment by adamlofting** [comment]
@thisandagain @ryanw-se that GA interface is wonderful! :boom: 

I've just got setup with a dev environment this evening and submitted this PR for tracking the 'Create new Project': https://github.com/mozilla/webmaker-android/pull/2089

**Comment by ryanw-se** [comment]
@thisandagain The Android label can probably be removed from this, since a JS API was landed and all that remains is for the events to be added on the JS side.

**Comment by thisandagain** [comment]
@ryanw-se Good catch. Removed! :boom:

**Comment by adamlofting** [comment]
Events for `login` and `share` should be covered here: https://github.com/mozilla/webmaker-android/pull/2159
