### ISSUE TITLE
Implement confirmation button

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2077]
Right now there's a placeholder confirmation button for setting a link destination floating in the upper right of the webview. Per design we need to put that into the navbar.

See #1670

**Comment by gvn** [comment]
![](https://cloud.githubusercontent.com/assets/1119821/7505335/52f8eb24-f406-11e4-9634-e995881ffa6a.png)

**Comment by xmatthewx** [comment]
Three options to finish current implementation. Seems important to execute one of them for v1. 

![screenshot_2015-06-04-15-07-58](https://cloud.githubusercontent.com/assets/53411/7992378/dfd2dd34-0acc-11e5-8024-1681e96c272e.png)

 1. Add checkbox to android wrapper (requires too much time?)
 2. Use back button to confirm (confusing to users in this unique scenario?)
 3. Design a floating confirmation button (ok as a temp solution?)

cc @thisandagain @vazquez @flukeout

**Comment by gvn** [comment]
@xmatthewx @thisandagain If we do want to just improve the design outside of the header I can definitely take that on. Just let me know. I can always use our standard button style for an easy improvement.

**Comment by xmatthewx** [comment]
@vazquez - do you think we should go with a back button since that's our pattern everywhere else? Or, does the uniqueness of this warrant a confirmation button like below?

![save destination](https://cloud.githubusercontent.com/assets/53411/8047232/917a9518-0e10-11e5-8c90-6d5bc60e1dd8.png)

**Comment by thisandagain** [comment]
@xmatthewx @vazquez Bump

**Comment by xmatthewx** [comment]
Discussed with @vazquez . Iteration coming very soon so this button doesn't get lost. We will: 
 - use green
 - have the button animate up into view after a destination is set << @vazquez's smarty pants idea :jeans:

**Comment by vazquez** [comment]
##### Notes

- As soon as you select a destination, the **Set Destination** button animates up from a hidden state. This is so that we bring the user's attention to the critical button.
- The teal colour value is our standard teal `#61D3C9`

![button set destination page interim solution](https://cloud.githubusercontent.com/assets/1119821/8087028/93f9fade-0f66-11e5-81e2-f5383dc4a993.png)

**Comment by k88hudson** [comment]
Resolved via https://github.com/k88hudson/webmaker-android/commit/6c7e7a890a53e2d049d0aee877ebacc7e961b874
