### ISSUE TITLE
[MIGRATED] Add dashed line between link source and destination

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2078]
This is a "nice to have" from #1670

![](https://cloud.githubusercontent.com/assets/1119821/7505335/52f8eb24-f406-11e4-9634-e995881ffa6a.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/164"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/164.
Please don't comment on it here.
