### ISSUE TITLE
Edits dont save 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2081]
1. Add text block
2. Edits " hello World" in green for example 
3. goes back to page view. Nothing saved. 
4. Goes back to edit text page, the "hello world" is green

Same with images 
1. Adds tucker 
2. Clicks on tucker to change it. Changes tucker with image from the gallery
3. Goes back on the page and it's still tucker. 

Maybe due to poor internet connection.

**Comment by thisandagain** [comment]
Tracking in:
https://github.com/mozilla/webmaker-android/issues/2040
https://github.com/mozilla/webmaker-android/issues/2053

/cc @k88hudson @Pomax
