### ISSUE TITLE
[MIGRATED] Text rendering is blurry

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-android#2084]
In Edit mode, when rotating and scaling text, the text box becomes very blurry.

![2015-06-04 10 24 32](https://cloud.githubusercontent.com/assets/1119821/7986253/6ef311e2-0aa4-11e5-85f3-3c1190199aa2.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/165"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/165.
Please don't comment on it here.
