### ISSUE TITLE
Android router doesn't include user id

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2088]
In order to make API requests, we need to know what the userId of a project is – however, this is not currently a parameter in the Android router.

Basically what would be involved here would be changing the URL schemes from

```
/projects/:project/pages/:page
```
to 
```
/user/:user/projects/:project/pages/:page
```

As well as any references in the app. A search for `/projects/` should probably show all the instances where that needs to be changed.

**Comment by k88hudson** [comment]
@ryanw-se want to take this one?

**Comment by ryanw-se** [comment]
@k88hudson Sure! :smiley:

**Comment by k88hudson** [comment]
E.g. in make.jsx around line 104,
```
 <Card
          key={project.id}
          url={"/projects/" + project.id}
          href="/pages/project"
          thumbnail={project.thumbnail[400]}
          title={project.title}
          author={project.author.username} />
```

Should become

```
 <Card
          key={project.id}
          url={"/users" + project.author.id + "/projects/" + project.id}
          href="/pages/project"
          thumbnail={project.thumbnail[400]}
          title={project.title}
          author={project.author.username} />
```

**Comment by k88hudson** [comment]
@ryanw-se arg, I had to finish this one up to get login ready for the build today, sorry! :cry: i owe you one
