### ISSUE TITLE
[MIGRATED] Run a remote Android beta test

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2090]
@flukeout - If you have time, it would be great to draft a test that we can run at the end of next week. 

would be good to include: 
 - creating an account
 - adding links

**Comment by thisandagain** [comment]
Haven't seen any movement on this in a while. Moving to backlog.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/166"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/166.
Please don't comment on it here.
