### ISSUE TITLE
[MIGRATED] Add header transition to login page 

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2095]
Design spec has the top header image change into a smaller wordmark when the user starts typing.

See:
https://projects.invisionapp.com/share/P62Z2HBMV#/screens/77984838?maintainScrollPosition=false

Note that the wordmark asset is already in the repo as `img/full-wordmark.svg`

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/167"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/167.
Please don't comment on it here.
