### ISSUE TITLE
[MIGRATED] Convert documentation to DocBloc style

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2096]
In 779fe1470bf85645e15d600c68a0d2380cdaa7b2, I added a lot of documentation that isn't in the right style. Needs to be converted.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/168"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/168.
Please don't comment on it here.
