### ISSUE TITLE
When elements overlap, the result is not the one that is expected from manipulating the elements 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2097]
When editing a page with multiple elements, the arrangements are confusing: 

Steps to Reproduce:
1. Add images 
2. Add text blocks
3. Try to move them around and organize them. Sometimes you might want the text to be laying over the picture, sometimes you want picture A to be over picture B. 
=> Tap and maintain the galaxy image and move it under the text box. It will appear as if the text overlapp and is in the front but when you release your finger it turns out it is the opposite, the image is over the text. 

The final outcome should be mirroring the handling. 

 Screenshot 1: When pressing the image 
![screenshot_2015-06-05-09-43-42](https://cloud.githubusercontent.com/assets/8261945/7999231/d54d27a0-0b69-11e5-99c5-5a13c2258c51.png)

Screen 2 - After releasing the image 
![screenshot_2015-06-05-09-43-47](https://cloud.githubusercontent.com/assets/8261945/7999221/98ecd954-0b69-11e5-9369-af5189f03826.png)

**Comment by LauraReynal** [comment]
I wanted my text to overlap the picture but I was not able to achieve this because I dont get how it works.

**Comment by xmatthewx** [comment]
This is related to the bug in #2101 and the feature in #2103.

**Comment by thisandagain** [comment]
Tracking in #2101
