### ISSUE TITLE
Border colors don't appear anymore

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2098]
In latest build, border colors have disappeared in editing page

![screenshot_2015-06-05-10-21-18](https://cloud.githubusercontent.com/assets/8261945/7999464/3912a1d6-0b6d-11e5-99c5-9da7ee2d8852.png)

**Comment by secretrobotron** [comment]
cc @thisandagain @xmatthewx 
think this one slipped through the cracks.

**Comment by xmatthewx** [comment]
@k88hudson - maybe introduced when you changed element defaults or the transparent color last week?

**Comment by k88hudson** [comment]
@LauraReynal @thisandagain after landing #2115 this appears resolved. Can you confirm?

**Comment by thisandagain** [comment]
Confirmed!
