### ISSUE TITLE
Swap placeholder project thumb

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2099]
Replace the gradient thumbnail in discover/make to be used when the real thumb is not yet generated or is broken. See the bottom of #2020.

**Comment by gvn** [comment]
Design needs revision for current aspect ratio.

**Comment by xmatthewx** [comment]
Thumbnail SVG 320x198 (that's the size we're getting from the thumbnail service)
https://www.dropbox.com/s/dk3lv6nqoodfqem/Thumbnail.svg?dl=0
