### ISSUE TITLE
[MIGRATED] Globalize image defaults

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2100]
Add an image or two relevant to each of our launch markets to the default image pool. As suggested by  @LauraReynal https://github.com/mozilla/webmaker-android/issues/1711#issuecomment-109163462

Note to self: fix the svg crops

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/169"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/169.
Please don't comment on it here.
