### ISSUE TITLE
maintain z-index during drag & transform

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2101]
An element drops behind other elements while being moved and transformed if initial z-index has changed. Unless I'm mistaken, this is a bug. 

STR: 
 - add some text
 - add a large image and move it to the side a bit
 - move the text over the image. it's now higher than the image. 
 - move it again, it falls below the image while moving, back on top when it is released.

**Comment by LauraReynal** [comment]
Same as this ? https://github.com/mozilla/webmaker-android/issues/2097 ]
@xmatthewx

**Comment by xmatthewx** [comment]
Note: this bug is persnickety. It does _not_ occur unless both elements have been repositioned _after_ both elements were created. 

 - Example A: Add an image element, but don't move it. Add a text element and move it a few times. `No bug`
 - Example B: Add an image element and move it. Add a text element and move it a few times. `No bug`
 - Example C: Add an image element. Add a text element. Move one and then other. `Bug!!!`
