### ISSUE TITLE
[MIGRATED] UX - "send to back" for zindex

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2102]
Can we implement a "send to back" feature for moving elements as far back as possible? Maybe press & hold?

Really difficult to quickly move small objects forward (like text on top of an image).

**Comment by xmatthewx** [comment]
Agreed. Current z-index seems to have a few bugs that need squashing, that make it a bit harder to user. #2101 #2103. Send to back would require some UX design.

**Comment by xmatthewx** [comment]
Here's is an option. Opinions @flukeout @vazquez ? 

![send to back](https://cloud.githubusercontent.com/assets/53411/8016058/a6baa744-0bac-11e5-9292-7194dc88c3ab.png)

**Comment by secretrobotron** [comment]
Just want to check: are you proposing a popup menu?

**Comment by xmatthewx** [comment]
Yep. A little pop up menu.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/170"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/170.
Please don't comment on it here.
