### ISSUE TITLE
Trigger z-index to front only on explicit tap

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2103]
**Current behavior**: interacting with an element in any way moves it to the top of the stack. 
**Preferred behavior**: tap a selected element to move it to the front. other transforms should not impact z-index.

I'm not sure if the current behavior is a bug or not.

**Comment by xmatthewx** [comment]
Is this a bug @pomax? I understand the other z-index issues are too complicated to tackle this week. This adjustment would be helpful in the interim. cc @secretrobotron

**Comment by secretrobotron** [comment]
Looks like you meant it to work this way anyway: https://github.com/mozilla/webmaker-android/blob/84c6bead3d5b3ea1e3e17bfaf43b2a50f28da469/www_src/pages/page/page.jsx#L167

**Comment by Pomax** [comment]
That code says that *any* modification should not affect z-index, only a true tap-without-changes-to-the-element should bump the z-index to "highest value"

**Comment by Pomax** [comment]
from what I can tell z-index behaves correct, except for "when dragging", when it has the problem filed in https://github.com/mozilla/webmaker-android/issues/2101 -- however, comparing z-index values based on manipulation when the user has finished manipulating, the correct z-index is used by all elements, so I'm closing this and will be focussing on https://github.com/mozilla/webmaker-android/issues/2101 instead
