### ISSUE TITLE
[MIGRATED] Images are empty/white until they load

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-android#2107]
on the newest develop, I added an image to a page on my project. It appears as empty with a blue border for a few seconds until it loads. Can we have some sort of 'loading' placeholder?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/171"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/171.
Please don't comment on it here.
