### ISSUE TITLE
[MIGRATED] Localize Welcome Email 

### ISSUE THREAD

**Issue by gauthraj** [mozilla/webmaker-android#2108]
When registering for webmaker account from the webmaker app still receving the same welcome mail received when registered from desktop - featuring X-ray googles, Thimble and Popcorn maker. Expected result - welcome email should hightlight and provide info about webmaker app
![photo_2015-06-07_10-43-55](https://cloud.githubusercontent.com/assets/11516300/8022696/3e5f38a2-0d02-11e5-8dc7-f92a30c52f24.jpg)

**Comment by LauraReynal** [comment]
The one I received was a different one from Mark

![screen shot 2015-06-07 at 12 09 46](https://cloud.githubusercontent.com/assets/8261945/8022827/2c70e8aa-0d0e-11e5-9397-37c5bae4dc44.png)

**Comment by thisandagain** [comment]
@secretrobotron @hpauljohnson Is this something the two of you can tackle this week?

**Comment by HPaulJohnson** [comment]
Yes - on my list for the next few days.

**Comment by HPaulJohnson** [comment]
Updated copy attached. Assumption is that we implement once we have a fully functional app - meaning people download/create an account. If we need something for the interim we can make some tweaks. 

https://etherpad.mozilla.org/webmaker-welcome-email

@thisandagain When does the /app page (and homepage redirect) go from lead gen to download the (beta) app?

**Comment by HPaulJohnson** [comment]
Also, would love to plug an additional email in for 5-7 days after install (maybe even 3 because, as I understand it, that's where the point of no return is for many new users). If we work up some copy is this something we can setup? This relates to: https://github.com/mozilla/webmaker-launch/issues/12

**Comment by thisandagain** [comment]
Nice. Copy looks :+1: 

We'll move from lead gen to Play Store when the beta goes live on Google Play (given the lag from the Play Store, let's say Wednesday next week). Work for you @HPaulJohnson ?

**Comment by LauraReynal** [comment]
How possible or crazy would it be to have a localized email according to the user ?
Do we know other apps / soft who does that ?

**Comment by HPaulJohnson** [comment]
If you mean localized as in language, I'd assume we can/will do that for this communication. 

If you mean personalization, I'd love to do that too though I don't think our current transactional email platform is well setup for that.

**Comment by secretrobotron** [comment]
:+1: to "localizing as in language". Should be able to get that going quickly.

**Comment by LauraReynal** [comment]
Yes as in language

**Comment by secretrobotron** [comment]
English version being done here: https://github.com/mozilla/webmaker-mailroom/pull/35

**Comment by secretrobotron** [comment]
Landed. Need to address https://github.com/mozilla/webmaker-mailroom/issues/34 next week with @cadecairos .

**Comment by LauraReynal** [comment]
Are you sure the english verison is landed ? 
I made a new account this morning and I received the same email by Surman
@HPaulJohnson @secretrobotron

**Comment by secretrobotron** [comment]
It's landed. Probably needs to be pushed up to production though. @jbuck ?

**Comment by jbuck** [comment]
```
Jons-MacBook-Pro-2:sawmill jbuck$ git push production master
Everything up-to-date
```

Uhhh lemme look into this

**Comment by jbuck** [comment]
Oh wait, @LauraReynal You received two emails; one from Bobby and one from Surman. The one from Surman is sent by BSD after you check "Tell me about Mozilla news & events"

**Comment by LauraReynal** [comment]
Oh Really ? @jbuck I did not see the one from @secretrobotron and I just asked Mozillians who dont remember getting one neither.

**Comment by LauraReynal** [comment]
ok I will ask others and let you know if there is anything. 
Thanks

**Comment by jbuck** [comment]
@LauraReynal When you get the new email it should look like this:

![screenshot 2015-06-15 10 45 39](https://cloud.githubusercontent.com/assets/578466/8162531/e1e9362c-134b-11e5-96e2-3d8cced99713.png)

**Comment by secretrobotron** [comment]
Uploaded this file to Transifex yesterday. Should be good to start.

**Comment by secretrobotron** [comment]
@cadecairos what do we need to do on id.webmaker.org to ensure the right locale is used?

**Comment by alicoding** [comment]
@secretrobotron do we call this done?

**Comment by secretrobotron** [comment]
I'd like it to be integrated with the app first, @alicoding . Make sense?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/172"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/172.
Please don't comment on it here.
