### ISSUE TITLE
Can't use spaces in login passwords

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2109]
Passwords with spaces in them aren't valid, but no (or wrong) error is reported.

Mine kept saying "must be 8-128 characters", but nothing about not using a space.

**Comment by ryanw-se** [comment]
@k88hudson Mind if I do this?

**Comment by secretrobotron** [comment]
@ryanw-se if you do, make sure you talk to @cadecairos about https://github.com/mozilla/id.webmaker.org/issues/318.

**Comment by cadecairos** [comment]
spaces will be valid soon

**Comment by thisandagain** [comment]
@ryanw-se This one is super complex / has lots of moving parts throughout our id, login, and android codebases. Probably not a great fit for you right now.

**Comment by ryanw-se** [comment]
@thisandagain @secretrobotron Okay.
