### ISSUE TITLE
Add "remix" to project dropdown

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2113]
Per #1569 we'll need "Remix" added to the ellipses dropdown for projects.

**Comment by gvn** [comment]
@thisandagain Can you take this?

I think it will just need to redirect to the Project edit view with an additional param that I can look for to show the modal window. Something like `isFreshRemix` that is only truthy the first time around...

**Comment by gvn** [comment]
I guess it will also need to trigger the copying and renaming of the target project as well...

**Comment by xmatthewx** [comment]
With this, let's add More Actions menu to Play view. 

Includes:
  - Remix
  - Share
  - Edit (author only)

**Comment by thisandagain** [comment]
I can handle the remix and share, but "edit" is going to need some extra work. Can you file another ticket @xmatthewx ?

**Comment by xmatthewx** [comment]
"edit" filed in #2128
