### ISSUE TITLE
Changing image does not work

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2119]
Latest built : 
- new page
- adds image
- changes image 
- selects from the gallery 
nothing happens 
goes back to project page 
do it again 
nothing happens

**Comment by LauraReynal** [comment]
Conditions : fully perfectly working wifi hotspot

**Comment by LauraReynal** [comment]
cc / @thisandagain

**Comment by thisandagain** [comment]
@k88hudson @Pomax Let's take look at this after stand-up

**Comment by LauraReynal** [comment]
Here is a screen cast

https://docs.google.com/a/mozillafoundation.org/file/d/0B0X05aIHuAbeSXdHbkdjUGVpZFE/edit?usp=docslist_api

I hope it works I'm afk

**Comment by thisandagain** [comment]
May be resolved in #2115

**Comment by k88hudson** [comment]
@LauraReynal @thisandagain after landing #2115 this appears resolved. Can you confirm?

**Comment by secretrobotron** [comment]
Just tried this on latest develop commit. Looks like a race condition.

**Comment by thisandagain** [comment]
I can still produce the problem (albeit less frequently). Almost seems to be a regression to the problem that was plaguing us two weeks ago.

**Comment by k88hudson** [comment]
What's happening is that when the editor activity is paused and resumed due to the camera, there is a race condition between data being reloaded from the API and receiving the `imageReady` call from Android.

**Comment by k88hudson** [comment]
This should now be resolved
