### ISSUE TITLE
Thumbnails aren't updating for existing apps

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2121]
I've been trying to generate thumbnails for existing useful apps to feature in the discover gallery, but they don't seem to be generated.

Tried generating for "Maker People" and "Riley the Cat" this morning. Latest nightly.

**Comment by toolness** [comment]
I think the app might currently be using webmaker-screenshot.herokuapp.com, which is a hobby app I set up a year ago with the "free" tier of the blitline addon. I think cade may have burned through the tiny allowance that the free tier is given when he stress tested the service a few days ago, so I'm *guessing* that's what's going on, but not sure.

We're currently in the process of transferring ownership of that app to the mozilla org, and at that point we can upgrade to one of the non-free blitline plans, which should hopefully make things work again.

**Comment by cadecairos** [comment]
webmaker-api is getting a 404 on the POST request to  webmaker-screenshot.herokuapp.com 
```
{
  "details": "Thumbnail service returned 404",
  "error": "Cannot POST /mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTUmcHJvamVjdD0zOTYmcGFnZT04NjQmdD0xNDMzODY1ODM1ODg4\n"
}
```

**Comment by cadecairos** [comment]
the page render endpoint seems to be functional - https://beta.webmaker.org/#/thumbnail?user=5&project=396&page=864&t=1433865835888 - that's the base64 string in the request above

**Comment by secretrobotron** [comment]
I've had to change the user id on some projects to be able to access them and force a thumbnail to be generated. Does that contribute to the problem?

**Comment by cadecairos** [comment]
@secretrobotron it shouldn't

**Comment by cadecairos** [comment]
Looks like when we updated the page render url on webmaker-api, we broke things, since webmaker-screenshot is using a hard-coded whitelist

**Comment by toolness** [comment]
Ah, it looks like it's because the origin of the page render endpoint changed. Fixed in https://github.com/mozilla/webmaker-screenshot/commit/7939a5e932076b273b81aec5a66169fdc77778f1, with https://github.com/mozilla/webmaker-screenshot/issues/19 filed to address a more long-term solution for this.

Unfortunately, though, while we're no longer 404'ing, we are getting the error I'd anticipated from blitline:

> Blitline error: Over usage limit. Either you have surpassed the free tier or have
 been rate-limited due to high usage. Please contact us for whitelisting options at support@blitline.com

So things still won't work, but as soon as we transfer the app to mozilla and upgrade our blitline plan, they should work.

**Comment by cadecairos** [comment]
@toolness Can you transfer that now?

I'll get in touch with @simonwex to get a blitline account/key and update the app as required.

**Comment by toolness** [comment]
Woot just successfully transferred it!

![screen shot 2015-06-09 at 12 37 11 pm](https://cloud.githubusercontent.com/assets/124687/8063692/486fe3ca-0ea4-11e5-822f-7a548be2bbf7.png)

**Comment by cadecairos** [comment]
Thanks!

**Comment by cadecairos** [comment]
Pretty sure we fixed this?

**Comment by cadecairos** [comment]
I'm going to call this resolved based on the Mofo Blitline account getting set up, and @jbuck's perf update to webmaker-screenshot
