### ISSUE TITLE
[MIGRATED] Permanently show outline of page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2123]
When placing large assets, it's hard to see where the edges of the page are (think huge picture and text on top).

It'd be useful to be able to see that boundary regardless of the assets covering the page.

**Comment by flukeout** [comment]
@Pomax had a cool thing where the parts of an element that weren't actually on the page were at a lower opacity. We could overlay a faint outline of the page instead though.

**Comment by secretrobotron** [comment]
Oh, no! That's perfect! What happened to it?

**Comment by xmatthewx** [comment]
related to #1742

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/176"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/176.
Please don't comment on it here.
