### ISSUE TITLE
Add "edit" to play activity

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2128]
Add "edit" to a project's more action menu in the play view. Edit option should appear for authors only.

**Comment by errietta** [comment]
dibs !

**Comment by xmatthewx** [comment]
Thanks @errietta! Let me know if you have any questions. 

If you create a project, you'll notice that the "more actions" menu (via vertical ellipses) offers "Play" as an option. From the Play view, you currently use the back arrow to return to the editor. For consistency, we will add "Edit" as an option in the menu there.

![toggle play edit](https://cloud.githubusercontent.com/assets/53411/8074639/456137ce-0f03-11e5-918a-e082a99c5347.png)

**Comment by errietta** [comment]
R? @thisandagain  :bowtie:
