### ISSUE TITLE
[MIGRATED] We should be able to organize your own projects 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2138]
Today you can't delete projects and it's very frustrating. 
Also could we move them within the page to have the ones we want to display first ?

**Comment by xmatthewx** [comment]
Delete is coming soon in #2018. The ability to organize your projects could be something we consider when we dig into profile and social later this year.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/177"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/177.
Please don't comment on it here.
