### ISSUE TITLE
Improved image defaults

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2143]
A few small fixes to the default image files. Fixed background color on heart. SVGs are now cropped to remove extraneous margins. Nice, but not critical.

[Zipped on gdrive](https://drive.google.com/open?id=0B_rbDAen9prkfk1oeFd6VEJwcVlONEw4RzFzNDRuUGtmdFp5RU5RaVhmekpFT3R2SVp2WVE&authuser=0)

These things belong in stuff dot webmaker. I'll get access if anything like this pops up again.

**Comment by k88hudson** [comment]
Ok, uploaded!
