### ISSUE TITLE
Update in-app configuration to point at production login server, api.webmaker.org

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2147]
We should point at the production login server now!

@cadecairos is this just a config switch?

**Comment by k88hudson** [comment]
@secretrobotron this depends on creating/deploying a production instance of api.webmaker.org, which is being tracked here https://github.com/mozilla/api.webmaker.org/issues/32

It will require some string changes in-app, but let's not do this 'til the production infrastructure is good to go and we're ready to coordinate the switch.

**Comment by xmatthewx** [comment]
Will we need to migrate news users? Or should we tell testers that they may need to recreate their account?

**Comment by cadecairos** [comment]
they'll have to re-create, or use their existing webmaker.org acocunts. (which may need passwords set)

**Comment by xmatthewx** [comment]
Will we switch to production before we launch Beta in the Play store? 
 - If yes: awesome. :sparkles:  You can stop reading. 
 - If no: we could screw beta users who just learned about Webmaker and invest in creating real projects. This is a terrible group to annoy if we want to reach our targets to retain users. We either need to make that wildly clear within the app or figure out a plan for migration.

**Comment by k88hudson** [comment]
@xmatthewx we will indeed!

**Comment by cadecairos** [comment]
https://api.webmaker.org is ready to accept traffic!

I need to generate a client id on id.webmaker.org for webmaker-android

**Comment by k88hudson** [comment]
This is done
