### ISSUE TITLE
[MIGRATED] refactor flatten/expand functions

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2151]
Based on https://github.com/mozilla/webmaker-android/pull/2136 it's probably best to put them on `Spec`

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/178"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/178.
Please don't comment on it here.
