### ISSUE TITLE
[MIGRATED] add some jitter resilience to "taps" on elements

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2152]
right now taps mean "no modification", but this should probably "translated by no more than a distance of ... units" to make it easier to tap elements even when your fingers aren't made of steel.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/179"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/179.
Please don't comment on it here.
