### ISSUE TITLE
More actions menu missing on 4.4.4

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2154]
Android 4.4.4
Samsung Galaxy

@ldecoursy just installed nightly and is missing the more actions ellipses menu from both the editor and player.

**Comment by thisandagain** [comment]
Great catch. On the case. :shipit:

**Comment by thisandagain** [comment]
Interesting. On latest `develop` I'm seeing the options menu on both a Samsung Galaxy running 4.0 and a Spice (Android One) running 4.4.4:

![screenshot_2015-06-10-16-53-04](https://cloud.githubusercontent.com/assets/747641/8096951/9d302ef4-0f91-11e5-99e5-4ad94e2cdd17.png)
![screenshot_2015-06-10-16-52-54](https://cloud.githubusercontent.com/assets/747641/8096952/9d323352-0f91-11e5-8c06-9c4ca1fe398e.png)

Could you take a screenshot for me?

**Comment by k88hudson** [comment]
I'm also seeing the menu with no problems on Nexus 4, Android 4.2.4

**Comment by HPaulJohnson** [comment]
I haven't been seeing the menu today either. The device I've been testing on is Galaxy S3, Android 4.4.2. Here's a screenshot

![app-screenshot](https://cloud.githubusercontent.com/assets/10078715/8097203/64808704-0f94-11e5-8484-f230e20d2f77.png)

**Comment by thisandagain** [comment]
@HPaulJohnson Woah! Alright ... can you install this APK and let me know if you still have trouble?
https://webmaker-dist.s3.amazonaws.com/v1/app-gh2154.apk

**Comment by HPaulJohnson** [comment]
installed and still no menu. 

(in my personal gallery of projects i do get a menu option with "share" and "delete." but nothing inside of the project itself.)

**Comment by thisandagain** [comment]
@HPaulJohnson Ok ... I think I found the issue. One more try?
https://webmaker-dist.s3.amazonaws.com/v1/app-gh2154.apk

**Comment by thisandagain** [comment]
This bug is specific to devices that have "hard" menu button which is used to display options by default. Totally silly that I missed this in the menu configuration and that `appcompat` doesn't take care of this, but I found a hack to resolve the issue.

I was able to reproduce and confirm the fix on a Samsung S3 running 4.2 here in the PDX office.

**Comment by thisandagain** [comment]
@HPaulJohnson Ok ... one more try (for real this time)?
https://webmaker-dist.s3.amazonaws.com/v1/app-gh2154.apk

**Comment by HPaulJohnson** [comment]
fixed!

**Comment by xmatthewx** [comment]
:v: nice sleuthing @thisandagain. thanks for stepping in @HPaulJohnson
