### ISSUE TITLE
Screenshot different than rendered page in app

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#2158]
Screenshot:  ![](https://cloud.githubusercontent.com/assets/438003/8098814/e441946e-0fc2-11e5-8017-c31002f9527a.png)

In app: ![screenshot_2015-06-10-22-32-22](https://cloud.githubusercontent.com/assets/438003/8098825/142ba688-0fc3-11e5-95ba-a16ab89863c8.png)

It looks like the elements are being scaled incorrectly/differently in the render endpoint.  Not sure if this is fixable. Could it be were rendering the page at an incorrect aspect ratio/size

**Comment by xmatthewx** [comment]
Appears stretched wide (see the roundness of the green 'O'). Also doesn't seem to have @2x resolution.

**Comment by cadecairos** [comment]
the scale of the image in the screenshot appears to be larger than in-app too.
