### ISSUE TITLE
[MIGRATED] Production optimizations

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2160]
For less, webpack, etc. if we have time

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/180"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/180.
Please don't comment on it here.
