### ISSUE TITLE
Relabel tinker mode Transparency slider

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2162]
Tinker mode slider is currently labeled Transparency, but behaves like Alpha/Opacity.

Let's label it to match opacity slider on elements.

Default value _seems_ to be 0 for image border color, 1 for text color. Border color should be set to 1 by default. Might be a bug. 

For the value, 0-100% is more intuitive than 0-1. Nice to have: let's relabel that for both tinker mode and element opacity ... unless this will break our margins/layout. In that case, skip this. 

R? @vazquez @k88hudson

**Comment by vazquez** [comment]
Checklist:

- [ ] In Tinker Mode, relabel "Transparency" to "Opacity"

Regarding value:
- I agree that 0 - 100% is more intuitive. It is actually spec'ed out as such in the designs. However, I think that this only makes sense in Element Options, not in Tinker mode. In Tinker mode, we want to provide a value as close as the code gets (decimal values 0.8 as per rgba syntax)

**Comment by k88hudson** [comment]
What is the use case for having transparent as a colour, actually?

**Comment by xmatthewx** [comment]
@vazquez - you're right. Labels in tinker mode should reflect code. Outside, they should reflect intuition. 

Full transparency on color? No use case. Partial transparency could be useful for image borders. We included transparency in color tinker for that and to teach rgba. We could, however, remove it, and then add opacity to text elements like we have for image elements.

**Comment by k88hudson** [comment]
Resolved by https://github.com/k88hudson/webmaker-android/commit/2439d37c03f75dc28c1dbd98d71f477afc3c32c2
