### ISSUE TITLE
[MIGRATED] z-index changes on pinch to scale

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2163]
z-index is behaving much much better. I see one problem remaining.

Elements move to the top on some transforms. 
 - does not happen with simple drag to reposition
 - does happen when you pinch to scale the lower element
  - could be too sensitive to accidental taps
  - could be how the pinch operation concludes 

STR 
 - add an image and a text element
 - move stuff around
 - put text above the image
 - pinch image while it's behind the text

cc @k88hudson @Pomax

**Comment by k88hudson** [comment]
I am also hitting this

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/181"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/181.
Please don't comment on it here.
