### ISSUE TITLE
[MIGRATED] Add commit hash/version number to style guide

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2166]
It would be great to have a commit hash for people to ensure they are on the right build when testing patches/filing bugs.

**Comment by xmatthewx** [comment]
major :+1:

**Comment by ryanw-se** [comment]
@k88hudson @xmatthewx Can I take this ticket over the weekend?

**Comment by xmatthewx** [comment]
Thanks @ryanw-se - sounds great to me. @thisandagain would know if there's anything more interesting or higher priority, but this seems like a nice bite-sized weekend project.

**Comment by xmatthewx** [comment]
Slightly related: Are we going to hide the button to access this guide on Beta release? Or, wait until v1?

**Comment by ryanw-se** [comment]
@xmatthewx It's only displayed if the APK is a debug build. Otherwise, unless it is set to a non-debug build (shipping to Google Play, Exporting APK) it will not appear for users.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/182"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/182.
Please don't comment on it here.
