### ISSUE TITLE
Elements sometime scale to 0

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2170]
Hard to reproduce.

Had two text elements on a page. Was in the middle of rotating+scaling one of them, and it suddenly disappeared. Luckily, it was right in the middle of the page. I can edit it, but not scale/rotate it (because it's too small). Inspecting the DOM revealed that it's actually `scale:0`.

**Comment by secretrobotron** [comment]
cc @k88hudson

**Comment by LauraReynal** [comment]
Same thing happened to me today with latest build. (red logo)

**Comment by secretrobotron** [comment]
Seems to happen with small objects pretty easily. e.g. A small, one-word text element.

**Comment by xmatthewx** [comment]
related to #2181

**Comment by Pomax** [comment]
good find, it's probably a good idea to prevent scaling past a certain size, so that user interaction can't lead to impossible-to-further-edit transform values. Taking.

**Comment by secretrobotron** [comment]
@Pomax what do you think of https://github.com/mozilla/webmaker-android/issues/2181#issuecomment-111533203 as a fix?

**Comment by Pomax** [comment]
that seemed to be addressing something completely different (relating to "if I make an inherently small thing, it's small!" rather than "if I scale something down, I can scale down too much"), and not an appropriate fix for this problem.
