### ISSUE TITLE
It's not possible to view a project shared 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2173]
Someone made a project today with latest built. 
Step 1 : shares on telegram 
STep 2: I click on it 
This is what I see. Navigator chrome. Nexus 5 Android 5.0

![screenshot_2015-06-12-11-52-01](https://cloud.githubusercontent.com/assets/8261945/8124262/abee550a-10fa-11e5-9f76-bbc6abd5318d.png)

**Comment by thisandagain** [comment]
Shoot. Great catch Laura. I'm not sure how this snuck by me last night. I have rolled back so the immediate issue is resolved, but now we will have a problem with thumbnails on the production release.



/cc @k88hudson

**Comment by LauraReynal** [comment]
In the future, will we be able to view the project on the web or is it just within app ? 
Right now I can't open this one on my desktop borwser(s) https://beta.webmaker.org/users/706/projects/611

**Comment by thisandagain** [comment]
Yup! Tracking in https://github.com/mozilla/webmaker-desktop/issues/57
