### ISSUE TITLE
Set destination green button does not do anything 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2174]
- add button

- click on set link destination 

You are then brought to the zoom out page to choose your destination 

- click on your destination 
at this point, you either click on the green button below or you want to click on the back arrow to save. 
nothing seems to be happening when you click on the green button that says "set link destination"

**Comment by LauraReynal** [comment]
4 users right now are confirming that links are not working

**Comment by Pomax** [comment]
PR merged.
