### ISSUE TITLE
Look at this first amazing project & smile.  

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2175]
Look at this great project from a teenager here - 16 years old.

He made a story about the 1971 war for Bangla. Used non linear structure, images from the web, and links (that are not working). It's pretty awesome and **local**. 
It might be our first "real" project that is not from a Mozillian ?

@secretrobotron @flukeout @xmatthewx @k88hudson @thisandagain @vazquez @benrito @cecilepompei @HPaulJohnson @davidascher 

:sparkles: :sparkles: :gift: :first_quarter_moon: :sparkles: :sparkles: 
User name shahedsappy5

https://beta.webmaker.org/users/706/projects/611 

![screenshot_2015-06-12-02-28-32](https://cloud.githubusercontent.com/assets/8261945/8124687/38b5eb7e-1100-11e5-8954-3a1c5887bb08.png)
![screenshot_2015-06-12-02-29-29](https://cloud.githubusercontent.com/assets/8261945/8124688/38bf93c2-1100-11e5-86d8-831d6313a02e.png)
![screenshot_2015-06-12-02-29-40](https://cloud.githubusercontent.com/assets/8261945/8124689/38c9540c-1100-11e5-99ef-7cec2011a446.png)
![screenshot_2015-06-12-02-29-57](https://cloud.githubusercontent.com/assets/8261945/8124690/38cc2a4c-1100-11e5-91c8-edd6b9b56604.png)

**Comment by LauraReynal** [comment]
Ps: He was working on a tablet so the zoom is not ideal.

**Comment by cecilepompei** [comment]
Amazing!!!!

On Fri, Jun 12, 2015 at 9:05 AM, Laura de Reynal <notifications@github.com>
wrote:

> Ps: He was working on a tablet so the zoom is not ideal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/webmaker-android/issues/2175#issuecomment-111386880>
> .
>



--  [[unflagged]](http://plzkthx.herokuapp.com)
Cécile POMPEÏ
Mobile Service Lead, Webmaker.org
+44 75 98 490 115

**Comment by vazquez** [comment]
A meaningful story, this is just what we set out to do. :blush:

**Comment by secretrobotron** [comment]
Very cool. :dancers: 

I'll feature it today and make sure it's on the prod server.

**Comment by thisandagain** [comment]
:+1: :+1:
