### ISSUE TITLE
The display on the Symphony Smartphone is not good 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2176]
- Android 4.4 
- Symphony W69Q -> this is the phone we used with 60 participants from Dnet Study. 
(Yes, I'm bringing this device to you in Whistler ) 

- Page does not fit in the screen 

- icons don't show properly 

- app crashed a few times. 

![screenshot_2015-06-12-16-03-56](https://cloud.githubusercontent.com/assets/8261945/8128522/be9eedfa-1121-11e5-82ed-8ad81b63c928.png)

![screenshot_2015-06-12-16-14-25](https://cloud.githubusercontent.com/assets/8261945/8128523/c12bf824-1121-11e5-8719-48dd9155b895.png)

**Comment by LauraReynal** [comment]
Aactually it's not just display - There are several bugs this morning 

- Elements don't save properly 
- Clicking back arrow leads to text disapearing 
- One participant lost a whole page while clicking back arrow.

**Comment by thisandagain** [comment]
Tracking in #2220
