### ISSUE TITLE
[MIGRATED] API - Batch requests to the API

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2179]
It has been a blocker to create content with people - a large number just gave up. 
We had good conditions and were on stable wifi. 

here is a screencast : 
https://drive.google.com/drive/folders/0B-1AZgKn5Nc7YldzMUtlOFhUVE0/0B0X05aIHuAbeQkphUkdGeHRjdjQ

I'm happy to try different suggestions, but it's been the same experience for users, no matter phones and versions. 
cc/ @thisandagain @k88hudson

**Comment by thisandagain** [comment]
Can you give a another look on the production APK today? I'd love to see how performance feels from the real datacenter.

**Comment by thisandagain** [comment]
Depends on https://github.com/mozilla/api.webmaker.org/issues/76

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/183"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/183.
Please don't comment on it here.
