### ISSUE TITLE
Brick - Drop-Down Menu

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#218]
Creation of a brick that allows a user to choose from a pre-determined list. Useful for surveys and order forms where app authors may want to allow for a enumerated options (see: HTML `select`). 

![screen shot 2014-09-19 at 12 10 38 am](https://cloud.githubusercontent.com/assets/747641/4331898/191da4ba-3fcc-11e4-9ff1-448c556ab708.png)

Attributes:
- List items
- Label

**Comment by k88hudson** [comment]
@thisandagain before I go investigate, do you happen to know what the status of this block is (i see code in the repo but it never got added to the /add view)

**Comment by thisandagain** [comment]
It works but UX is quite rough. I'd want to do a design (UX) pass before shipping.
