### ISSUE TITLE
Default text is too small to scale up

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2181]
When users add new text, it's sometimes too small to see and pinch to scale up. Let's set new defaults: Increase font-size 50% and set font-weight to bold.

**Comment by secretrobotron** [comment]
Potential solution which I've seen other apps do: if an element is selected when two fingers, do scale/rotate even if fingers are well outside boundaries. Often useful to spread fingers far apart to get better precision.

**Comment by thisandagain** [comment]
:+1:

**Comment by xmatthewx** [comment]
@flukeout had something like that in his spec. Wondering if we ran into trouble accidentally scaling the wrong element.

**Comment by xmatthewx** [comment]
Either way, bigger defaults shouldn't take more than a couple minutes to implement in the interim.

**Comment by secretrobotron** [comment]
Bigger defaults is a good idea to begin with. But, it's pretty easy to make something really small and hard to grab again.

**Comment by xmatthewx** [comment]
Agreed for sure. Just thinking about what we can and can't squeeze into v1.

**Comment by secretrobotron** [comment]
:+1:
