### ISSUE TITLE
[MIGRATED] Research - Project Titles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2182]
Project titles will be important for a solid Discover experience. Editing your title might be too hidden. Or, maybe not. We should keep our :eyes: on this. 

A few thoughts:
 - this might not be a problem after people see titles in Discover and in their Make list
 - titles are not common in social media. 
  - it would be weird to title your facebook post or your yik yak before posting 
  - forcing titles would add friction to sharing
 - titles could be a special page on the project map view.
 - titles are in the UI spec for the project header. not build that way yet. 
 - We should add a number to default titles. I'll file that now. 

cc @LauraReynal @vazquez @flukeout @secretrobotron

**Comment by secretrobotron** [comment]
Would love to see a couple benchmarks for how other apps show titles. Viewing an app by clicking on a share link doesn't show the app's title at all.

**Comment by xmatthewx** [comment]
@LauraReynal - something to think about as we prepare for social. cc @flukeout

**Comment by LauraReynal** [comment]
I remember writing somewhere that we should prompt people to add a title to their project when they are about to share it - If they haven't done so yet. This is definitely something I could see in Bangladesh, people did not think about adding titles.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/184"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/184.
Please don't comment on it here.
