### ISSUE TITLE
[MIGRATED] Increment default project title

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2183]
Add a number to default project titles so people can find a thing in their make view. Project ID probably works. Example: "Project 57" 

People aren't likely to edit the title on quick experiments as they get acquainted with the app.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/185"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/185.
Please don't comment on it here.
