### ISSUE TITLE
[MIGRATED] Login - Explore using onBlur for validation errors rather than onKeyUp

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2187]
We are currently really aggressive about displaying validation errors for `username` and `email` fields which is fairly jarring during the sign-up UX. I'd like to explore some options including only displaying validation errors onBlur.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/186"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/186.
Please don't comment on it here.
