### ISSUE TITLE
[MIGRATED] Make default page color white?

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2188]
Looking at some of the projects built so far, it strikes me that the slightly off-white looks sort of bad when images with white background are placed on a page...

![image](https://cloud.githubusercontent.com/assets/25212/8136779/7ba1f340-10f3-11e5-8a34-b425e3720280.png)

@vazquez What do you think? I think a lot of images that people will find on the web will have a white background, so it might make sense to optimize for that.

**Comment by vazquez** [comment]
@flukeout - I actually like it because it provides a good but subtle distinction between alpha and non-alpha images lol.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/187"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/187.
Please don't comment on it here.
