### ISSUE TITLE
Digest feedback from Maker Prom

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2191]
Feedback pile here. I will follow up with individual tickets on important things. 

Atmosphere was an interesting and challenging environment for testing. 
 - would have been great to have a big display with demo projects to draw people toward table (@secretrobotron !!!!! whistler !!!!)
 - tablets are bad for demo
  - page size isn't optimized yet
  - no flash for photos :disappointed: 
 - testing with iPhone lovers is harder b/c of platform patterns

Observations and feedback on the app
 1. **tap to edit** - so many people tap to edit a page or element. when that doesn't work, they double tap. 
   - is this behavior unique to US youth? (@LauraReynal ??) 
   - if it's universal we should nix the paintbrush/pencil
   - if not ??? localized UI ???
 1. **tap to deselect** - many people tried to tap outside of an element to deselect an element
 1. **pinch to scale** - some people didn't realize you could pinch to scale images. due to slightly awkward party demo environment? dunno
 1. **default photos** - were confusing. we should consider going directly to source selector (adding sticker option there)
 1. **back button** - target size seems a bit small. might be due to tablet size. some people clicked the header title next to it (@LauraReynal ??)
 1. **link icon** - this is so not clear even when prompted that button links exist. will plague us forever if we don't make these bigger and maybe label them.  
 1. **play mode buttons** - some people didn't realize these were tappable.  
 1. **default text size** - many people couldn't scale tiny default text 
 1. **edit text** - many people got stuck after adding text. didn't know how to edit. the decision to not going directly to the editor might be a legacy MWC app decision. 
 1. it is sad when you delete and then want undo
 1. **sharing is caring** - adding a share icon to header could intrigue new users who didn't guess this stuff was sharable. 
 1. youth LOVE **rounded corners** on images. like a lot. is too easy to miss in the UI?
 1. **link destination** - unclear that you need to create a second tile before you're able to set destination on a button. this should fail more gracefully

For v1, I think that these would be good to address:
 - tap to edit
 - back button target size
 - link icon bigger. maybe with label
 - ~~smaller~~ bigger default text size
 - share icon in header
 - link destination unavailable
 - maybe go straight to photo editor or picker

@vazquez @cassiemc @flukeout

**Comment by flukeout** [comment]
Awesome feedback @xmatthewx !!

Thoughts...
* I thought we agreed already to double-tap (or tap selected) to edit?
  * If we tap to edit, we need a new spot for page delete / color UI
* For the **button destination** we could show the plus pages so that you can add a page and set it as a destination in one go, that's what the original desktop interaction was
* Tap to **deselect element** seems good - I also thought we'd agreed to implement that
  * It would be one way to expose the page-level ui (like delete and color) if we take that away from the map view

**Comment by xmatthewx** [comment]
@flukeout - yes, some of the details were in the spec, but dropped during implementation. We just need to sort out what's critical for v1. Opinions welcome.

**Comment by xmatthewx** [comment]
details filed in other issues
