### ISSUE TITLE
Reset password flow goes nowhere eventually

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2192]
After resetting my password, I'm left at the login screen: https://id.webmaker.org/login?client_id=&state=&username=&response_type=&scopes=

Original URL was https://id.webmaker.org/reset-password?uid=secretrobotron&resetCode=25a34736ef19a52f664796548012b0a6b3a85acb9458baf91923306f6113c4e8

Not supplying the right clientID maybe?

**Comment by secretrobotron** [comment]
cc @cadecairos

**Comment by k88hudson** [comment]
Hm. We probably want to launch an Android intent here when we're done

**Comment by xmatthewx** [comment]
@cadecairos - take a look. Let's see if we can redirect resets that originate from the app, back to the app.  See also: https://github.com/mozilla/id.webmaker.org/issues/289#issuecomment-112561251

**Comment by cadecairos** [comment]
mozilla/id.webmaker.org#323 will add functionality that redirects to 'webmaker://login?mode=sign-in' if android=true is set on the reset link query

That means we need a patch here to simply update the reset link url with '?android=true'

**Comment by k88hudson** [comment]
Thanks to some work by @cadecairos cade this should now be resolved
