### ISSUE TITLE
Previous destination appear when setting new link destinations

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2194]
Probably not a critical bug, but it's a little confusing. 

STR:
 - add a button
 - set it's destination
 - add another button 
 - go to set destination view
 - look to see if destination icon is on previous destination 

cc @gvn

**Comment by gvn** [comment]
@xmatthewx I actually can't repro this now. Are you still seeing this problem?

**Comment by xmatthewx** [comment]
I don't see this problem anymore.
