### ISSUE TITLE
Elements in thumbnails are incorrect

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2195]
One of the thumbnails I generated came out with the right elements, but wrong dimensions:

It looks like this project isn't being rendered properly on desktop: https://beta.webmaker.org/#/thumbnail?user=424802&project=19&page=113:
![screenshot 2015-06-12 16 39 44](https://cloud.githubusercontent.com/assets/403231/8139446/dd5ac7e6-1121-11e5-8829-2c8a2896f6b8.png)

But, it's fine in the app (look for Freedom Fighters"):

![2015-06-12](https://cloud.githubusercontent.com/assets/403231/8139473/165e272c-1122-11e5-8381-95b61b16fba2.jpg)

cc @k88hudson

**Comment by k88hudson** [comment]
Likely needs some code updates / css missing from last few days

**Comment by secretrobotron** [comment]
What happened to this bug? Was it fixed?

**Comment by k88hudson** [comment]
@secretrobotron yep! sorry, wrote my bug reference wrong.

Resolved by https://github.com/mozilla/webmaker-desktop/commit/937461b6311f928d9cf95e5671d4e0c2925409af

**Comment by secretrobotron** [comment]
@k88hudson https://dgu16gle6my6q.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTg4JnByb2plY3Q9MjUmcGFnZT0xNjM= still looks pretty wrong. Is the server updated?
