### ISSUE TITLE
Links - Link buttons not working in Play mode

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2198]
Button links seem to be broken in all of the "discover" projects ported over from staging.

**Comment by secretrobotron** [comment]
cc @cadecairos

**Comment by cadecairos** [comment]
yeah that makes sense....

**Comment by cadecairos** [comment]
they'll have to be Manually fixed by looking at the original elements and pages and updating the new elements to point to the page at the right coordinates

**Comment by secretrobotron** [comment]
Ouch. Ok.
- [ ] Freedom Fighters of 1971
- [ ] How to Microwave a Dinner
- [ ] Street Children
- [ ] CRAZY CAR LOVERS
- [ ] Riley the Cat

**Comment by secretrobotron** [comment]
Followup: https://github.com/mozilla/api.webmaker.org/issues/89

**Comment by cadecairos** [comment]
Youre quick

**Comment by secretrobotron** [comment]
NO TIME TO SPARE :boom:
