### ISSUE TITLE
Update Webmaker Logo on Sign In/ Sign Up Screens

### ISSUE THREAD

**Issue by vazquez** [mozilla/webmaker-android#2201]
New logo!

Asset available here: https://drive.google.com/a/mozilla.com/file/d/0ByIoeeW0a3R_YlUyQnVaem1FNms/view?usp=sharing

UI for Visual Reference:

![join](https://cloud.githubusercontent.com/assets/1119821/8140893/053a609e-112e-11e5-92cc-ff4e62c9bbc0.png)

**Comment by thisandagain** [comment]
Resolved in https://github.com/mozilla/webmaker-android/pull/2203
