### ISSUE TITLE
[MIGRATED] Persist most recent tinker color on all edit views

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2204]
Scenario: user adds a custom color for a header on a page. They want to use this color on other pages as well. They need to recreate the color using tinker mode. (I guess it gives them a reason to memorize hex or rgb values). Ideally, most recent tinker color persists in all edit views.

**Comment by LauraReynal** [comment]
I would tend to see if they memorize the numbers. 

I feel the same thing when I play with tinker mode, but I like the challenge, as a user.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/188"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/188.
Please don't comment on it here.
