### ISSUE TITLE
Set Destination button does a little dance

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2205]
Whenever I push the "Set Destination" button when editing a button's destination, it jumps down when I push it, and back up when I let go. Sometimes it doesn't register a click.

It's not a useful button to have there in general, IMO. Can we just remove it and let the destination be the page with the flag on it when the user clicks "back"?

**Comment by k88hudson** [comment]
hm, sounds like a style regression.

**Comment by secretrobotron** [comment]
Makes the Button element almost unusable.

**Comment by secretrobotron** [comment]
(note: i'm on nightly)

**Comment by xmatthewx** [comment]
This button doesn't save and exit things on my end.

**Comment by xmatthewx** [comment]
I built within the last half hour or so.

**Comment by secretrobotron** [comment]
@xmatthewx it does for me, but I have to hit it a few times in a row.

**Comment by xmatthewx** [comment]
I just noticed that in the set destination view, I can tap and hold to trigger Android's select/copy UI. I believe we blocked this elsewhere with user-select. 

I can confirm that a quick double tap on the dancing button will trigger it.

**Comment by thisandagain** [comment]
@xmatthewx @secretrobotron Ok ... initial patch landed. Can you give it a try (`develop` branch)?

**Comment by xmatthewx** [comment]
yay. button works as expected. :+1:
