### ISSUE TITLE
[MIGRATED] Discover gallery has 0 height thumbnails

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2207]
After creating a new account and opening discovery for the first time, I was somehow able to get to a state where all the thumbnails were 0 height. After refreshing, they were fine. Not able to reproduce this a second time.

**Comment by xmatthewx** [comment]
I saw the same thing recently. I left Discover and saw the same thing in Make. Refreshed to fix it there, but I believe I returned to Discover and saw thumbnails without a refresh. Slow loading?

**Comment by thisandagain** [comment]
I wonder if this could be coming from the `react-imageloader`? I can only replicate on a totally fresh install (no state in-memory).

**Comment by LauraReynal** [comment]
Same thing here in Bangladesh at random moments.

**Comment by thisandagain** [comment]
Tracking in #2208

**Comment by jbuck** [comment]
@cadecairos and I think this is a different issue from #2208, so re-opening.

**Comment by jbuck** [comment]
@cadecairos dug into this a bit and it's a bug with react-imageloader where it's not updating the state of the image after loading it. Basically it loads the image with display:none set and doesn't update that until the React re-render comes along and re-renders it.

**Comment by cadecairos** [comment]
Digging deeper reveals that React's image component isn't firing an onLoad event. Indicates a bug in either that component or in how react-imageloader is adding the image component to the DOM

**Comment by cadecairos** [comment]
I can't reproduce this issue anymore, @jbuck perhaps your changes in #2208 made a difference somehow?

**Comment by jbuck** [comment]
But how....

The change I made should have only affected the behaviour of thumbnails that haven't been generated yet :tired_face:

**Comment by cadecairos** [comment]
I lied, It worked because I modified react-imageloader to use ```React.createElement('img', { src: this.props.src });```

**Comment by cadecairos** [comment]
cc @Pomax

**Comment by cadecairos** [comment]
I have zero ideas how to fix this beyond replacing react-imageloader

@jbuck @thisandagain @Pomax @k88hudson

**Comment by cadecairos** [comment]
I filed this upstream: https://github.com/hzdg/react-imageloader/issues/16

**Comment by Pomax** [comment]
looking at the node_modules/react-imageloader/lib/index.js, it seems like things might fail if onLoad on the image fires before the component has mounted (say, we load images *really fast*). Might be worth checking what happens on L53-54 in that react-imageloader file, to see if it returns early during a test run.

**Comment by cadecairos** [comment]
@Pomax That function doesn't even get called :/

**Comment by cadecairos** [comment]
What are the chances that the image tag is choking trying to detect the mimetype of the src

**Comment by thisandagain** [comment]
@k88hudson is still seeing this from time-to-time in the latest build. Re-opening in the 1.0.1 milestone.

**Comment by cadecairos** [comment]
That's unfortunate... if this isn't fixed upstream by the time we get back to it I think we should find an alternative image component.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/189"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/189.
Please don't comment on it here.
