### ISSUE TITLE
Thumbnail shows up as a broken image link

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#2208]
Image:
```
https://d5bds2ubg5m9p.cloudfront.net/mobile-center-cropped/small/webmaker-desktop/aHR0cHM6Ly9iZXRhLndlYm1ha2VyLm9yZy8jL3RodW1ibmFpbD91c2VyPTU5NCZwcm9qZWN0PTY1MyZwYWdlPTE5NzEmdD0xNDM0MTQ5MTEyMTgx">
```

**Comment by k88hudson** [comment]
![screenshot_2015-06-12-18-21-03](https://cloud.githubusercontent.com/assets/1455535/8141337/7ea1fe42-1133-11e5-9bd9-a0ec864003d2.png)

**Comment by k88hudson** [comment]
cc @jbuck

**Comment by thisandagain** [comment]
Did we forget to include the extension?

**Comment by jbuck** [comment]
I've seen that occasionally, but I'm not sure what triggers it...

**Comment by cadecairos** [comment]
Could the app not know how to handle 404s from cloudfront? also, that 404 image is an SVG, is that bad?

**Comment by jbuck** [comment]
Okay, if you'd like to attempt to recreate this issue:

1) Create a new project
2) Add an element to a page, I like text personally
3) Go back to the "Make" menu
4) Refresh frequently until you see the "broken image" image. If you refresh again after showing this image, it'll show the default thumbnail image.

**Comment by jbuck** [comment]
When we attach the Chrome debugger the only difference in the response that we can see is that the broken image is returned from a fresh 404, whereas the default thumbnail is served correctly on following requests from the cache. I'm going to have Cloudfront return a 200 Okay response instead of a 404 and see if that fixes things.

**Comment by jbuck** [comment]
Okay, by changing the Cloudfront response to an HTTP 200 and setting the Cache-Control header on the thumbnail to public, max-age=5 we get the desired no broken thumbnail behaviour :+1: .

**Comment by k88hudson** [comment]
hurray!
