### ISSUE TITLE
Device - Sony Xperia Z3 Compact (D5803)

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2209]
Current dev build is working on my Nexus 7 (5.1.1), but not my Sony. @thisandagain heard rumor of the same problem on Sony. Elements are stacked in the order they're created. No changes possible. 

Anyone testing on a Samsung? 

Android 5.0.2
Sony Model D5803

**Comment by thisandagain** [comment]
I've got a bunch of Samsung devices here. Unable to replicate but will try on some of the Sony and Sony Ericsson devices in the QA pile.

**Comment by xmatthewx** [comment]
Sony is uncommon in the US. The world really. We should confirm the bug is unique to to their hardware, but if it is, it's probably not critical.

**Comment by xmatthewx** [comment]
Correction: element goes to the top of the stack on pinch to scale. Does not do it on drag or on tap. So... it might be that Pomax's latest patch didn't fix things on Sony, but it also didn't make it worse. Is that possible? I manually deleted the app and rebuilt and installed via Android studio to be sure I truly have the latest dev version. #foggylateonfriday

**Comment by ryanw-se** [comment]
@thisandagain @xmatthewx Unable to replicate this on Sony Xperia Z2 running Android version 5.0.2, with build version ```23.1.A.0.690```.

**Comment by thisandagain** [comment]
Update:
The [Sony Xperia Z3 Compact](http://www.gsmarena.com/sony_xperia_z3_compact-6538.php) uses an Qualcomm MSM8974AC Snapdragon 801 (ARM) CPU and so it is most likely not related to the patch in #2227 re-X86 chipsets. This needs some further investigation.

**Comment by xmatthewx** [comment]
Note: this is the device for [Mozilla's foxfooding](https://mana.mozilla.org/wiki/display/PM/Foxfooding+Program#FoxfoodingProgram-Who?You%21) program. 

I tried it again this morning on release via the play store to make sure I'm not mistaken. I still can't tap-to-front. I'm not seeing any other bugs. Very odd.

**Comment by thisandagain** [comment]
Trying to find one of these so we can debug on-device. Worst-case scenario could you bring this to Whistler so we can hook it up to a debugger?
