### ISSUE TITLE
Camera doesn't pan to first page in play mode

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2211]
Often, when I'm editing something and then go into play mode, the camera will stay zoomed out and not pan to the first page. Sometimes, the page you were working on in edit mode will stay selected (blue outline) too.

In effect, Play mode doesn't really work, because you need to scroll to what you think is the beginning manually. Pretty confusing for some projects.

@k88hudson has a theory of why this is.

**Comment by thisandagain** [comment]
State restoration in play mode = :hankey:

**Comment by secretrobotron** [comment]
that emoji is too happy.

**Comment by secretrobotron** [comment]
Did https://github.com/mozilla/webmaker-android/pull/2214 close this?
