### ISSUE TITLE
Need a way to re-order/pin featured content

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2213]
Some featured content is better than others, and some we want to stay at the top for a long time. Can we add a "pin" feature or a rating system (better idea) to describe how high up the featured list projects should be.

**Comment by LauraReynal** [comment]
Should this pin feature be just for us and the database though ?

**Comment by secretrobotron** [comment]
Probably just the DB maestro to begin with. Could become a more elaborate feature for privileged users later on (good idea).
