### ISSUE TITLE
Device - Nokia XL

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2218]
Nokia XL -- Android OS, v4.1.2 (Jelly Bean)
http://www.gsmarena.com/nokia_xl-6148.php

Experience is similar to #2176 for blue frame of zoom but no problem for icons.

Other experiences:
- Does not scroll in edit page (needs to exercise pressure scrolling 5 times for the scrolling to actually happen)
- When scrolling it moves the sliders,  randomly provoking unwanted edits 
- Elements sized so tiny in the page that you can see a "line" instead of a word. 
==> Look for "hello" in the screenshot below   :eyeglasses:  :shipit: 

![img_20150613_165134](https://cloud.githubusercontent.com/assets/8261945/8144104/f6cd76ac-11ed-11e5-9bc9-6595c7070f35.jpg)

- Zoom is uncontrollable and very unexpected - when re-sizing image or text

- Play mode: swiping is painfully slow and irregular

**Comment by LauraReynal** [comment]
cc/ @thisandagain @k88hudson

**Comment by thisandagain** [comment]
Found it! For all three of these ... the issue is the chipset (x86 instead of the normal ARM) and an configuration issue with Crosswalk. New build on it's way!
