### ISSUE TITLE
Device - Symphony WD308

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2220]
This one is not critical, but still quite poor experience on this device 
: Symphony  WD308 running 4.2.2

- In discover, the navigation is really slow, you have to swipe several times to reach the next page
- In play view, a similar experience is observed

**Comment by LauraReynal** [comment]
New one  - Android 4.2.2  - Device Walton primo G5 
-> Scrolling does not work


cc/ @thisandagain @k88hudson

**Comment by thisandagain** [comment]
Resolved in #2227
