### ISSUE TITLE
Edits on the button labels don't save 

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2221]
- add buttons, 
- edits labels
- sees that labels are saved 
- one minute later, labels have disappeared and have been replaced by "button links"

Symphony phone - 4.2.2

cc/ @thisandagain @k88hudson

**Comment by xmatthewx** [comment]
@thisandagain - can you duplicate this?

**Comment by thisandagain** [comment]
Tracking in #2220
