### ISSUE TITLE
[MIGRATED] UX - 404 "page" not found

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2222]
- Users set a bunch of links
- He then comes to me to say "links don't work" and we spent 20 minutes trying to understand the problem until he tells me that. - One page of his project disapeared, and it happens that that page was the destination of lots of links. 

=> There should be an error message that tells you why your link is broken 

Thoughts ? @xmatthewx @vazquez @flukeout (FTU?)

**Comment by xmatthewx** [comment]
We could handle links to deleted pages in a few different ways: 
 - In player, we could nav to a 404 page or display a notice
 - In editor, we could test links on page load and change "follow link" to "set destination"

**Comment by vazquez** [comment]
I like the second option:

- In editor, we could test links on page load and change "follow link" to "set destination"

Maybe in this case it would be worthwhile to display an alert as in one of my initial iterations:

![screenshot 2015-06-15 10 27 50](https://cloud.githubusercontent.com/assets/1119821/8162110/3dad4582-1349-11e5-9bed-78dd3e163bcb.png)

**Comment by flukeout** [comment]
@vazquez Would that label/button only appear when the button is selected?

In the case of broken links caused by deleting pages, we'd probably want to let the user know without having to select the button first. Maybe we could put a little (!) bubble on the button somewhere even when it's not selected, and that then expands to the "No destination set" button after the button is selected?

**Comment by xmatthewx** [comment]
Good point @flukeout. Broken links could have a variation on our selected state appearance with a red/white dashed border. Then when selected, show @vazquez's notice.

**Comment by vazquez** [comment]
Great point @flukeout. @xmatthewx, it could also look something like this:

![screenshot 2015-06-15 11 42 28](https://cloud.githubusercontent.com/assets/1119821/8163866/9d223af4-1353-11e5-9261-61be119c5501.png)

I think I like this visual style better than showing a red/white dashed border, as I don't think the affordance is enough to the user. My assumption is that showing a symbol is better recognized by people using the app.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/190"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/190.
Please don't comment on it here.
