### ISSUE TITLE
Project no longer opens

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2223]
This project is empty when I open it, but I saw what she made and it definitely had pages ! 
https://beta.webmaker.org/users/759/projects/662
Are you able to see anything ?

**Comment by cadecairos** [comment]
According to the api

https://api.webmaker.org/users/759/projects/662

That user id doesnt exist

**Comment by LauraReynal** [comment]
ok - thanks @cadecairos it's really strange because she made an account + a project in front of me, and then shared it directly with me. 
Should we close this or is it a bug ?

**Comment by xmatthewx** [comment]
We should close this if we can't repeat it. 

@LauraReynal - users who created accounts before we launched beta will need to create a new account. Some projects are manually migrated by @secretrobotron.

**Comment by secretrobotron** [comment]
Let me check this out. Shouldn't be one that I migrated.

**Comment by secretrobotron** [comment]
@LauraReynal I migrated the project using my user id for now. Would you be able to get her to recreate her user? Looks like she was using a nightly release, which was hooked up to the staging DB.

**Comment by xmatthewx** [comment]
I believe this is resolved.
