### ISSUE TITLE
Look at new projects and see which ones we should put in the gallery

### ISSUE THREAD

**Issue by LauraReynal** [mozilla/webmaker-android#2224]
I'm going to paste projects here for now, because they are cool, and you should see them. 

*Action item*: Vote for the ones we put in the discover gallery ! @secretrobotron 

What we put in the gallery really changes the way users perceive Webmaker, so we should choose carefully in order to shape perception and stimulate desire to use. 

----

cc @k88hudson @flukeout @vazquez @xmatthewx @thisandagain @secretrobotron  @davidascher 

1- Bangladesh traditionnal cusinne 
https://beta.webmaker.org/users/425332/projects/113
2- About Cricket (in Bangla)
https://beta.webmaker.org/users/425201/projects/104
3- About me (about Nasim actually)
https://beta.webmaker.org/users/267900/projects/75
4- About Me (about Rume) in Bangla, very cool 
 https://beta.webmaker.org/users/424980/projects/61
5 - Momuments (in Bangla)
 https://beta.webmaker.org/users/273550/projects/53
6 - Protect the children of Bangladesh - Trisha - In Bangla - (it says: be carefull about our population  / say no to child labor / give the necessary means to education for our children )
https://beta.webmaker.org/users/424964/projects/63
7- The happiness of a children
https://beta.webmaker.org/users/425070/projects/57
8- Food list for cats according to their age - In Bangla
 https://beta.webmaker.org/users/425064/projects/45
9- Dog Care - in Bangla - superbe use of non Linear structure
https://beta.webmaker.org/users/424984/projects/42 
10- Musicians of Bangladesh - in Bangla
https://beta.webmaker.org/users/425247/projects/106

**Comment by LauraReynal** [comment]
In case anyone does not want to click, here is a temptation: 
![screen shot 2015-06-13 at 20 15 33](https://cloud.githubusercontent.com/assets/8261945/8144663/0216e7a6-120b-11e5-8b31-38bdf83df105.png)


@benrito @cecilepompei @APLSmith here are tones of local content, a bunch of those even come from Dnet participants. Some others in the demos pad.

**Comment by cecilepompei** [comment]
@LauraReynal -- none of the links open for me (on various browsers)

**Comment by LauraReynal** [comment]
@cecilepompei you have to open them on the app :gift:

**Comment by LauraReynal** [comment]
Here is another good one from today. It's actually great https://beta.webmaker.org/users/426973/projects/261
Worth opening through the app !

**Comment by xmatthewx** [comment]
Done @secretrobotron?
