### ISSUE TITLE
Zooming on large projects is frustrating 

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-android#2226]
STR:

1. stack a bunch of pages vertically 
2. Try to zoom to a top or bottom page

It seems to tend to zoom towards the middle if the project, instead of the center of the screen or between the fingers

**Comment by xmatthewx** [comment]
:+1:  during demo, I would sometimes lose a project off the screen, unable to find it and pull it back into view.

**Comment by flukeout** [comment]
Closing because it's already noted in #1697
