### ISSUE TITLE
Produce a few pieces of content to model user behaviour

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2228]
I need to work with someone (@vazquez ?) this week to create some great content to show off in our Discover gallery. Users will be able to see what can be made, and be inspired to copy.

cc @LauraReynal

**Comment by secretrobotron** [comment]
Will continue this through next heartbeat, but made some progress with @vazquez. See Critcket and Soccer "Keep Calm" projects in Discover gallery.

**Comment by jgmac1106** [comment]
Here are some ideas
- The scavenger hunt from whistler is a good idea. Remix that for other audiences.
- A "choose your own adventure" digital short story
- Some flashcards for learning English or learning basic phonics.
- An About Me set
- A Mozilla Club Bio set like Kevin posted.
- A Basic Meme Maker with Top and Bottom Text

One thing that happens is sometimes I want to use the default pictures (like the speech bubbles and arrows). I just keep deleting pictures until I get the one I want.

**Comment by secretrobotron** [comment]
Many of these have been created, thanks to our launch teams.
