### ISSUE TITLE
Go to editor when user adds new element

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2229]
Users are confused by the default content dropped on the page (true for text, image, and link). Would be better served by going directly to the element editor (still using the default content).

**Comment by adamlofting** [comment]
Can I also suggest that when adding a new image to a page, the first option is to pick between 'Take Photo' or 'Camera Gallery'.

Currently to get a photo onto the page, it's 6+ stages.

**Comment by xmatthewx** [comment]
Tracking in https://github.com/mozilla/webmaker-android/issues/2330
