### ISSUE TITLE
Disable links in 'set destination' view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2238]
Links placed by authors function on the set destination view. Try and select a page as your destination, and you might accidentally trigger the button. The view pans and adds the flag on the unintended destination.

I noticed this while making a table of contents page with a ton of buttons. It's nearly impossible to set this as a destination.

**Comment by thisandagain** [comment]
@gvn Could you take this one?

**Comment by gvn** [comment]
Sure!
