### ISSUE TITLE
[MIGRATED] Button label text resets with one order of events

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2241]
The label sticks in most scenarios, but I found one that repeatedly fails. 

STR
 - add a link
 - change the label and style
 - exit the link editor
 - tap set destination
 - set a destination
 - label resets to default

**Comment by xmatthewx** [comment]
Might be the cause behind #2221

**Comment by thisandagain** [comment]
Thanks for tracking down this STR!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/194"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/194.
Please don't comment on it here.
