### ISSUE TITLE
Authoring lots of buttons makes it hard to exit a project

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2242]
If you author a lot of links and use the editor's "follow link" button, this activity is include the soft header back button. This can get you stuck in the Page editor, unable to easily exit to the Project editor and Make view. 

There's no need to record this page history within the editor. Back button should always move from element editor > page editor > project editor > make.

**Comment by thisandagain** [comment]
Agreed though I'm not sure if this is the right long-term fix as we have a bunch of rough edges in the link destination UX. I'm going to flag this as "needs discussion" for Whistler.

**Comment by xmatthewx** [comment]
tracking #1546
