### ISSUE TITLE
Add a mini overview map to a project's main page

### ISSUE THREAD

**Issue by mmmavis** [mozilla/webmaker-android#2243]
(Feel free to rename the title of this ticket to make it more understandable)

Default view 
![photo 1](https://cloud.githubusercontent.com/assets/2896608/8172620/49dac928-1377-11e5-8f86-b5c5ff706c74.JPG)

After I messed around the screen with my fingers
![photo 2](https://cloud.githubusercontent.com/assets/2896608/8172619/49da6820-1377-11e5-94cb-1e1826da2f22.JPG)

I think it'll be helpful to add a overview map somewhere near the corner of the viewport so that users can easily locate where they are at on the entire canvas?

...ummm...... let me know if this ticket makes sense.  Obviously I'm having hard time choosing the right terms to describe UI elements.  :wink:

**Comment by thisandagain** [comment]
Yup! Totally makes sense ... @Pomax is working on a fix that should resolve the core issue (able to get lost!) in #2226
