### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by Sunnat** [mozilla/webmaker-android#2246]
Hey all,

I downloaded this from the Google Play Store. After I Opened and filled up the form for registration, this error is popping up "Login Database Error". Please fixed this problem or is there any alternative option to use this?

My Device is Samsung Galaxy S4 with 5.0.1 Lollipop.

Thank You...

![Login Database Error](https://cloud.githubusercontent.com/assets/5854791/8177205/31708f46-1424-11e5-921b-a8b6ab8ca432.png)

**Comment by ashickurnoor** [comment]
I have faced the same isseu.

**Comment by xmatthewx** [comment]
@Sunnat and @ashickurnoor - sorry that you ran into trouble. We are working to improve the login/signup error messages this week. 

Have you used this email address or username for Webmaker or teach.mozilla.org before? If so, try to sign in instead (link at the bottom the screen). 

cc @secretrobotron @cadecairos

**Comment by cadecairos** [comment]
This will probably be solved in #2216

**Comment by cadecairos** [comment]
Fixed by #2216
