### ISSUE TITLE
Some General Feedback

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/webmaker-android#2247]
Really spent some time with webmaker this morning. Some general feedback tha may already be included in the roadmap:

-h/t to the team. I gave the app to my four year old and my six year old and they could figure it out. Making something this powerful and that easy had to be hard.
-Portrait Pages: Most images are shot in Landscape. The pages in webmaker are set for portrait. Be nice if you could either choose or if the default was landscape. 
-Add images by url: I currently had to go to creative commons search (Flickr mobile site and app do not make CC image searching easy) and download photos. Adding images by url may help keep the data charges lower in places where that matters.

**Comment by jgmac1106** [comment]
Is there a link to roadmap (I can't find it)  so people don't leave feedback on stuff already planned. 

For example I am sure gif support is already planned.

**Comment by xmatthewx** [comment]
Thanks for the feedback @jgmac1106. Glad to hear your little ones were able to figure it out. :smile: 

We have a high level roadmap to add desktop support this summer, and then social features in the fall and winter. Next week, we will review what's been accomplished so far and figure out the details of what comes next. Image search is something we will likely consider as we dive into desktop features.

**Comment by thisandagain** [comment]
Thanks @jgmac1106 ! We keep our high-level roadmap in the Wiki:
http://wiki.webmaker.org/Product

**Comment by thisandagain** [comment]
Tracking the GIF and Image URL support feedback in #2250 and #2251. Aspect ratio is something we'll nail down during the desktop design process. Thanks again @jgmac1106 !
