### ISSUE TITLE
Device - Alcatel One Touch

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2248]
Katie, who is building some curriculum for Webmaker, has an Alcatel One Touch. She's seeing lots of freezing/performance problems on 4.1.1.

> this version is having some significant freezes
> it's not letting me add a button
> it is just slow - but it doesn't actually progress if I wait
> the only way to get it out of it is to hit the back button a few times, and then start from the start again.

**Comment by chighet1** [comment]
The circular buttons below (picture, words, buttons) are also blurry - it's had to make out what they are at a glance

**Comment by ryanw-se** [comment]
I believe @thisandagain found a issue with the crosswalk configuration which was causing a majority of device compatibility issues, however I'm not sure if this change was pushed to the play store yet. This may or may not be related to the issues you two are having.

**Comment by thisandagain** [comment]
@secretrobotron Is this person running on nightly or the version in the play store? If on the play store, it shouldn't be the X86 issue and we'll have to dig in. There are a TON of different Alcatel OneTouch models ... can you ask for a specific model number or a screenshot of the "About" view in settings?

**Comment by ryanw-se** [comment]
@thisandagain Quick question, how are we sending the different builds to each user? Like are we pushing two separate builds for both x86 and ARM and then detecting which one the user wants?

**Comment by secretrobotron** [comment]
@chighet1 can you give us a model number from the about screen in your settings? Would like to know more info about your phone.

@thisandagain I believe it's the play store version. @chighet1 can confirm.

**Comment by chighet1** [comment]
Hi all - thanks for you responses.
-It is indeed the play store version.
-Alcatel one touch 9978 Android 4.1.1
i've had the 'Webmaker stopped working' message twice in the last 30 mins.
Thanks again
K
