### ISSUE TITLE
[MIGRATED] Add ability to copy and paste items

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2249]
Are we able to use the clipboard to make it easier to copy and paste items inside of and in between projects?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/195"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/195.
Please don't comment on it here.
