### ISSUE TITLE
Image Elements - Add image by URL

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2250]
Re: #2247 - We have a spec for adding an image by URL that we dropped from the roadmap. Something for us to look at again as we move into desktop. @xmatthewx or @flukeout could you drop in a few screenshots?

**Comment by xmatthewx** [comment]
UI and notes in #1671

**Comment by xmatthewx** [comment]
Image by URL was just an interim solution before we accessed the device camera. Tracking desktop feature here: https://github.com/mozilla/webmaker-browser/issues/140
