### ISSUE TITLE
[MIGRATED] Image Elements - GIF Support

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2251]
We dropped GIF support (we currently transcode all images to JPG) while creating the image flow for performance reasons. It would be great to restore this functionality if we can find a way for it to work on less powerful devices (Android One, etc.)

**Comment by ryanw-se** [comment]
@thisandagain What exactly was tripping up the performance with the GIF support?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/196"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/196.
Please don't comment on it here.
