### ISSUE TITLE
[MIGRATED] Make - Deleting all projects leaves a phantom UI entry when deleting "the last project"

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2254]
Deleting all your projects works just fine, but if you only have one project in your make list, and delete that, it doesn't disappear from the UI for tapping, even though it deletes on the API side. Reloading the app will then also shows an empty list, so that's correct.

Not marking as critical as it seems unlikely many people will be deleting all their projects.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/197"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/197.
Please don't comment on it here.
