### ISSUE TITLE
[MIGRATED] Device - Nexus 7 (2012)

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2255]
So ... we support 3 of the 5 different versions of the Nexus 7, but apparently NOT the version that everyone at MOFO has. Yay. :stuck_out_tongue_winking_eye: 

![screen shot 2015-06-16 at 9 29 03 am](https://cloud.githubusercontent.com/assets/747641/8188343/35d2dcf2-140a-11e5-99b1-073dbf27404c.png)

**Comment by Pomax** [comment]
device info for my nexus 7, which sees no results for "webmaker beta" in the play store:
```
IC: 3568A-ME370T
Model: nexus 7
Android: 5.1.1
Kernel: 3.1.10-gf5d7b8b
Build: LMY47V
```

**Comment by omnignorant** [comment]
Adding a comment here to note that my Nexus 7 device cannot access Webmaker on the Play store: same device info as noted by @Pomax above.

```
IC: 3568A-ME370T
Model: nexus 7
Android: 5.1.1
Kernel: 3.1.10-gf5d7b8b
Build: LMY47V
```

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/198"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/198.
Please don't comment on it here.
