### ISSUE TITLE
Big Button Effect

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2256]
Currently you can "lock yourself out" of editing a page by either filling it with a giant button or too dense a group of smaller buttons. This is caused by buttons blocking the action of tapping a page to select it.

We need to come up with a way to reduce or remove this competition between UI.

As a short term solution I'd recommend at least limiting the maximum size of a button...

**Comment by gvn** [comment]
CC: @xmatthewx @vazquez @LauraReynal @thisandagain

**Comment by xmatthewx** [comment]
Works for me. It's easy to imagine wanting a full-width button. How about we allow full width and restrict height to 50% of page?

**Comment by flukeout** [comment]
I ran into this in issue #2260 on the Fire Island stock project. The first page has a ton of buttons, and it's hard to tap it to zoom in without being navigated away.

**Comment by xmatthewx** [comment]
Stock project? I'll take that as a compliment :wink:

**Comment by gvn** [comment]
We landed a bandaid for this, so I'm going to take it out of this sprint but leave it open for revisiting later.

**Comment by flukeout** [comment]
@gvn What's the bandaid?

**Comment by xmatthewx** [comment]
tracking in #2260
