### ISSUE TITLE
[MIGRATED] Network - App refresh onResume

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#2257]
STR:
 - open webmaker app
 - open a project, zoom in to a page
 - use task manager to swap to another app
 - use task manager to swap back to webmaker

--> Spinner shows up to do a refresh, while I don't know why it should.

**Comment by davidascher** [comment]
Same thing after device sleep / wake.

**Comment by thisandagain** [comment]
We should be able to remove the `onPause` and `onResume` handlers as we refactor the network architecture. Related to #2179 

/cc @k88hudson

**Comment by k88hudson** [comment]
This is blocked on #2179

**Comment by ryanw-se** [comment]
@k88hudson That ticket is primarily blocked by the uplift api.js ticket, I'll make sure to have that done in the next couple of days so we can move forward with this.

**Comment by k88hudson** [comment]
Great, thanks @ryanw-se

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/199"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/199.
Please don't comment on it here.
