### ISSUE TITLE
More projects in Discover

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2259]
For Whistler and in general, it would be good to increase the number of projects in Discover. If we can't add pagination to load more just yet, can we bump it up to 25?

cc @secretrobotron

**Comment by thisandagain** [comment]
:+1:

**Comment by LauraReynal** [comment]
In particular, le'ts make sure we have a wide variety of projects: 
- from different countries 
- Fun & light
- Serious 
- "about me"
- Tutorials 
... Would be good to have a game too if there is one already ?
And one that would involve geography if possible also ? 

we noted that the project people see in the Discover page truly shapes perception of the whole app.
