### ISSUE TITLE
[MIGRATED] Disable links on pages while in project view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2260]
Steps to reproduce
* Open a project that has a page with a button on it linked to another page
* Go to map mode
* Tap the page next to the button
  * Page zooms in
* Zoom back out
* Tap the page on the button
* You are transitioned to the destination page

This is a little bit confusing, especially on pages that have multiple buttons, which makes it hard to zoom in on that page.

Some ideas, 
* Disable buttons when zoomed out
* When a button is tapped in map mode, offer binary choice between zoom and navigate? 
* ...
* Leave as is?

@xmatthewx @vazquez

**Comment by xmatthewx** [comment]
I think links should only be enabled while in Page view. Active buttons muddle the project view with unexpected behavior. 

This seems like an easy fix and worth doing sooner than later.

**Comment by xmatthewx** [comment]
Users sometimes expect these buttons to work in the project view because we allow too much zoom: #2359

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/201"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/201.
Please don't comment on it here.
