### ISSUE TITLE
In Play Mode, navigating to a page via a button causes that page to become "selected"

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2261]
Steps to reproduce
* Open a project with pages and buttons
* Tap a button
* The view transitions to the destination page
* The destination page now has a blue "selected" border

It shouldn't. There is no selecting pages in Play mode.

**Comment by xmatthewx** [comment]
This isn't critical, but it is confusing and annoying. Only seems to happen if you tap the button from the project view. 

@flukeout - what do you think about disabling buttons altogether in the project view? This would resolve #2256.

**Comment by xmatthewx** [comment]
Let's pick a cutoff time to land this so we don't introduce bugs too late today.
