### ISSUE TITLE
[MIGRATED] Add an animation or effect when a button is pressed

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2262]
Currently, the button has a very subtle 'pressed' state. I think adding a fun and more obvious pressed effect before navigating away will help.
* It will reinforce that you pressed the button and make it more obvious that you are navigating because you pressed it
* When pressing buttons on the map view, it's not often obvious which one you pressed because they're quite small.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/202"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/202.
Please don't comment on it here.
