### ISSUE TITLE
[MIGRATED] Overlay between elemants in lower part of page and edit mode

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2266]
Having a button in the lower page will block you to enter the edit mode. 
Actual solution - move the button, edit it, move back
Expected solutions - the edit mode button shoul probably move up ( all set of buttons should maybe)

![img_2015-06-18 01 17 09](https://cloud.githubusercontent.com/assets/1391451/8220064/c534e19e-1557-11e5-8dc8-c6fb81beb79b.jpg)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/203"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/203.
Please don't comment on it here.
