### ISSUE TITLE
[MIGRATED] Add numbers to new project default titles

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2268]
Create several projects =. 
Actual results:
- all are name my projects

Expected result:
- I should have My projects, My projects (2) etc 
-> it is consistent to other projects in mozilla ( add new search engine in firefox/fennec)
-> I can have a overview where I am while panning otherwise looks like infinite

![811733264_1882518357838919385](https://cloud.githubusercontent.com/assets/1391451/8220146/737a50a4-1558-11e5-8b68-68efdef9173c.jpg)

**Comment by xmatthewx** [comment]
related to #2183

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/205"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/205.
Please don't comment on it here.
