### ISSUE TITLE
[MIGRATED] Save chosen new colors

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2269]
I am creating several pages with the same format - a button in the lower part for back
Set a custom color for it 

Actual result:
- I need to memorize the code color and set it manually to all same format button

Expected result:
- We should have an option to add new colors so we can be able to reuse it quicker

**Comment by ioana-chiorean** [comment]
![img_2015-06-18 01 29 27](https://cloud.githubusercontent.com/assets/1391451/8220243/7d2c6424-1559-11e5-9a8e-87dde670a6a1.jpg)

**Comment by xmatthewx** [comment]
related to #2204

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/206"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/206.
Please don't comment on it here.
