### ISSUE TITLE
[MIGRATED] Wording / Tips

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2270]
The app is really not intuitive for non technical persons. We should probably add some text bubbles that give some tips and trips.

Situations:
- how to set an image for a new project
- Page mode, projects mode 
- ability to change image set by default when adding new one 
- add picture to profile
- etc

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/207"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/207.
Please don't comment on it here.
