### ISSUE TITLE
Bug: Profile count of makes/projects

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2272]
In the mockup here: https://github.com/mozilla/webmaker-android/issues/1567#issuecomment-101312813 there is the text: " You've created 1 dashing projects! Keep goinf. 

Actual profile has no text beside the username

**Comment by xmatthewx** [comment]
@ioana-chiorean - Thanks. We will develop profile features later this year after we stabilize the mobile and desktop making and viewing experiences.
