### ISSUE TITLE
[MIGRATED] Enhacement Profile

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2273]
Enhacements:
- link to profile - it can be open in browser t
- desktop makes should be available to open in browser too
- SYNC - I should be able to see my mobile makes on desktop profile

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/208"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/208.
Please don't comment on it here.
