### ISSUE TITLE
[MIGRATED] Bug: Image blocking buttons

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2274]
In the case of adding an image over some buttons that will block the mobility/editing mode of the buttons
Actual solution:
- move the image outside the buttons are
- edit them
- move the image back

Expected Results:
- I should d be able to choose which to edit
- in this case  at a second tap I should be able to choose a button

![img_2015-06-18 01 58 07](https://cloud.githubusercontent.com/assets/1391451/8220597/9479c0aa-155d-11e5-96ee-fd3c72d835b9.jpg)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/209"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/209.
Please don't comment on it here.
