### ISSUE TITLE
[MIGRATED] When deleting a page, clear the target for any buttons that link to it

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-android#2279]
Currently if you delete a page, then click on a button that previously linked to the page you end up on a blank page.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/210"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/210.
Please don't comment on it here.
