### ISSUE TITLE
Selecting an image moves it in front of all other objects

### ISSUE THREAD

**Issue by adamlofting** [mozilla/webmaker-android#2280]
If you have a photo background, and accidentally move it while trying to move text or buttons, it jumps to the front of the ordering and you can't access the buttons and text any more, so need to recreate them.

**Comment by xmatthewx** [comment]
@adamlofting - are you seeing this on any move or possibly just pinch to scale as describe in #2163? What device and version of Android are you on? Are you on nightly or the beta release?

**Comment by ioana-chiorean** [comment]
Is this related to https://github.com/mozilla/webmaker-android/issues/2274?

**Comment by ryanw-se** [comment]
@ioana-chiorean Yes. This can probably be closed since its a dupe of #2274

**Comment by ioana-chiorean** [comment]
I will leave it up to @xmatthewx as he is triaging things around :+1:

**Comment by adamlofting** [comment]
Yep, happy to close this a s dupe. It's on pinch and scale (though scaling seems to happen unintentionally at times).

Also discovered you can bring the button back to the front doing the same thing. 

FWIW, it's a nexus 7 running beta from Play.
