### ISSUE TITLE
[MIGRATED] Text edits in progress are reset if user switches to another app

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2281]
Steps:
- add text to a page
- tap to edit the default text
- write new text 
- tap done
- let the app in background and go to other app
- return to webmaker app 

Expected results:
- the text is saved after pressing done ( it should save in  progress text too no matter if you tap done or not )

Actual results:
- the text is reset to the default salute text 

@xmatthewx can u reproduce this, is it known?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/211"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/211.
Please don't comment on it here.
