### ISSUE TITLE
[MIGRATED] Allow images with alpha channel

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2284]
When you upload a PNG with an alpha channel, you get a black background. Would be nice to use images that have alpha channels to do some interesting overlapping.

**Comment by xmatthewx** [comment]
I believe they're currently converted to JPGs. Related to GIFs in #2215.

**Comment by secretrobotron** [comment]
@xmatthewx #2215? Errors?

**Comment by xmatthewx** [comment]
typo fixed

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/212"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/212.
Please don't comment on it here.
