### ISSUE TITLE
[MIGRATED] UX - select project's start page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2287]
Sometimes, you're well into creating a project when you wish you could add a different first page. Otherwise, lots of prior planning needs to happen on the user's side.

**Comment by jgmac1106** [comment]
I would like to be able to move around all of the pages not just the first page. Though is that the reason some projects don't get a thumbnail image? I am not on the first page?

**Comment by secretrobotron** [comment]
@jgmac1106 no, that's because of a different (now fixed) problem.

But, it would be nice to move around pages. Do you mind filing that as a separate bug?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/213"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/213.
Please don't comment on it here.
