### ISSUE TITLE
[MIGRATED] Reposition pages in project

### ISSUE THREAD

**Issue by jgmac1106** [mozilla/webmaker-android#2288]
This originally mentioned in #2287 and #2247 but it would be nice to be able to move the pages around. I wanted to change my layout and had to delete all the pages and remake them.

I tried to figure out how to add the feedback label but couldn't.

**Comment by xmatthewx** [comment]
@vazquez has a UI comp for this. Needs a bit more work, but we also need to see where this fits in the roadmap relative to other features and fixes. 

![tile map view new location](https://cloud.githubusercontent.com/assets/53411/8261106/fc175db0-1695-11e5-946a-39bd99c2628a.png)

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/214"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/214.
Please don't comment on it here.
