### ISSUE TITLE
[MIGRATED] Beta landing page renders wrong on Firefox

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2292]
**Firefox** :fire: :x: 
![image](https://cloud.githubusercontent.com/assets/25212/8288960/3eb253a2-18ce-11e5-88a3-54634b88cc9e.png)

**Chrome** :ice_cream: :heavy_check_mark:
![image](https://cloud.githubusercontent.com/assets/25212/8288962/447c5a30-18ce-11e5-9950-b96b2e6f5c1b.png)

**Comment by flukeout** [comment]
Looks like this is because for me it shows two lines of subhead copy in Firefox and only one in Chrome, which alters the layout.

Is the copy we show browser-based, or are we doing some A/B testing and I just happen to load two different versions?

**Comment by HPaulJohnson** [comment]
@flukeout - there's a landing page test running in Optimizely that's the culprit.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/215"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/215.
Please don't comment on it here.
