### ISSUE TITLE
[MIGRATED] Label featured content to show users what 'kind' of projects there are

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2294]
Could use labels like 'blog' or 'shop' to let users know what kind of projects are in the discover gallery. Could be accomplished with tags (and search).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/216"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/216.
Please don't comment on it here.
