### ISSUE TITLE
[MIGRATED] Ship Webmaker with b2gdroid

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2295]
People who get b2gdroid should be exposed to Webmaker right away. Would be magnificent foxfooding.

**Comment by ioana-chiorean** [comment]
It this meant to be as default app/pre-installed app? 
Cause I have used Webmaker in b2gdroid.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/217"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/217.
Please don't comment on it here.
