### ISSUE TITLE
[MIGRATED] Make sure keyboard matches locale

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2296]
For non-english locales, the keyboard that pops up should be in the appropriate language.

**Comment by alicoding** [comment]
I don't know if that's true or is the case here? I often use two languages within an English only or Thai only application, so the the language of the keyboard or app shouldn't change based on the other.

**Comment by secretrobotron** [comment]
That's kind of what I thought too. This was something a user complained about.

So, what's the default keyboard that pops up when you open an app? How do you change keyboards?

**Comment by alicoding** [comment]
It really depends on the keyboard all you use as well. Let say it I use
Fleksy which doesn't support Thai but I use it as my default.

**Comment by alicoding** [comment]
I think its an OS design and we shouldn't control what language to display unless we are asking for number input or trying to get a specific input in English only then we should force them otherwise I don't think that's a good idea to do at all.

**Comment by secretrobotron** [comment]
OK, so basically, it's totally up to the user?

**Comment by secretrobotron** [comment]
:+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/218"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/218.
Please don't comment on it here.
