### ISSUE TITLE
entering tinker mode in photos stalls the app (blank screen)

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2297]
On some phones, entering tinker mode shows a blank screen (for images).

**Comment by toolness** [comment]
On my OnePlus One, I am experiencing this problem, with the following error logged:

```
Uncaught Error: Unable to parse color from string ""
```

Furthermore, after this error occurs, the app appears to be broken; clicking on the back button at the top-left of the screen logs the additional error:

```
Uncaught TypeError: Cannot read property '_currentElement' of null
```
