### ISSUE TITLE
[MIGRATED] Button name changes to default "Button link"

### ISSUE THREAD

**Issue by ankitgadgil** [mozilla/webmaker-android#2298]
1. Edit a project
2. Add a button
3. Edit the button - change name to <xyz>
4. Exit editing
5. Click set link, make the button link to a page.
6. The button text changes back to default "Button link".
Expected: The edited button text should persists.

**Comment by ryanw-se** [comment]
I'll look into this later today and see if I can find what's causing the issue, good catch @ankitgadgil!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/219"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/219.
Please don't comment on it here.
