### ISSUE TITLE
[MIGRATED] users need to create new project before they can remix

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2300]
I've seen a few new users try to remix something right away, but it didn't work. After starting from scratch, there fine. But can't remix from discover gallery as first activity with app. :(

**Comment by toolness** [comment]
I think I may have found the cause of this bug; if I'm correct, it's in api.webmaker.org, and I've filed https://github.com/mozilla/api.webmaker.org/issues/105 to address it.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/220"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/220.
Please don't comment on it here.
