### ISSUE TITLE
In play mode, when zoomed in, show users which directions they can go

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-android#2301]
We could have little arrows to show which directions are possible to go when zoomed in. I brought it up in the webmaker session and i was told it's a good idea and to file a bug :stuck_out_tongue:

**Comment by xmatthewx** [comment]
@flukeout will look into this as he designs for the browser-based player. tracking here: https://github.com/mozilla/webmaker-browser/issues/57#issuecomment-117298504
