### ISSUE TITLE
[MIGRATED] Should be able to duplicate a whole page

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2303]
Reproducing work over and over again is painful. Would be great to be able to duplicate a page.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/221"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/221.
Please don't comment on it here.
