### ISSUE TITLE
[MIGRATED] Top bar looks weird on tablets/bigger screens

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-android#2304]
![screenshot_2015-06-24-15-32-53](https://cloud.githubusercontent.com/assets/134585/8343090/94d58a42-1a86-11e5-8d7d-34e2d1e8545a.png)

**Comment by ryanw-se** [comment]
@errietta I'm unable to replicate this on a Nexus 7... however there was a large amount of empty space on the header bar when I tried this on my tablet, I think the best option would be to resize the menu options to both get 50 percent of the header bar.

**Comment by xmatthewx** [comment]
A refined header on tablets will require some design. An interim solution should follow material design patterns which is actually closer to this broken view than what I've seen on nexus 7. 

@errietta what's your device and version of Android?

**Comment by ryanw-se** [comment]
@xmatthewx How about spliting the button length evenly across the width of the device?

**Comment by errietta** [comment]
@xmatthewx Samsung galaxy tab 3, 4.4.2

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/222"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/222.
Please don't comment on it here.
