### ISSUE TITLE
[MIGRATED] Teaching Ideas 

### ISSUE THREAD

**Issue by smithisgeneric** [mozilla/webmaker-android#2307]
Write down teaching activity ideas for Webmaker App: https://teach.etherpad.mozilla.org/teachACTapp

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/223"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/223.
Please don't comment on it here.
