### ISSUE TITLE
[MIGRATED] Add color selector for button label text

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2308]
Steps to reproduce
* Add a button
* Use Tinker mode to change the background color
* The button label text changes from white to black

It should stay white.. or better yet, you should be able to set the button label color.

**Comment by xmatthewx** [comment]
Related to: #2240. Agreed. Not sure why we don't just allow people to set text color.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/224"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/224.
Please don't comment on it here.
