### ISSUE TITLE
[MIGRATED] snap to grid on edit mode

### ISSUE THREAD

**Issue by errietta** [mozilla/webmaker-android#2309]
There should be a grid in the edit mode which allows users to snap objects to it. Then they could actually align buttons

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/225"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/225.
Please don't comment on it here.
