### ISSUE TITLE
[MIGRATED] Review user tests at Whistler work week

### ISSUE THREAD

**Issue by jvallera** [mozilla/webmaker-android#2310]
https://teach.etherpad.mozilla.org/webmakerworkshop

**Comment by xmatthewx** [comment]
Thanks @jvallera. Any big discoveries from you or @secretrobotron?

**Comment by jvallera** [comment]
Biggest take-away for me was how the app works well to create short, snappy activities like the "pop quiz" / "yes or no" activity mentioned on the etherpad. Also, being able to duplicate pages (or having templates for pages) will help user flow tremendously. Instead of creating each page from scratch.

**Comment by xmatthewx** [comment]
cc @LauraReynal

**Comment by LauraReynal** [comment]
Thanks for sharing @jvallera ! 

:+1:  on duplicate / copying pages - definitely something important that we noticed in Bangladesh and elsewhere, once you get really into your project it makes the experience really slow for the user.
 cc /  @thisandagain => could we consider moving this feature up the list of priorities ?

**Comment by ioana-chiorean** [comment]
I +10000  for duplicate page - My projected included 20 same pages and was a time kill to do them ( 1 text, 3 buttons ) 3h total time worked . 
Happy to see it as a must feature!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/226"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/226.
Please don't comment on it here.
