### ISSUE TITLE
[MIGRATED] Poor UX when rotating elements

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2312]
Steps to reproduce
* Add a few elements
* Tap and hold one of those elements
* Rotate the element by moving your other finger around the page
* It works fine as long as you start your second finger gesture on a blank part of the page
* If you start your second finger gesture on an element however, you end up selecting that element and losing your original selection

This is bad, if you're holding an element with your first finger, your second finger shouldn't be able to select another element. You should be able to use your second finger for scaling and rotating no matter what is underneath it.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/227"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/227.
Please don't comment on it here.
