### ISSUE TITLE
[MIGRATED] When loading a project, I see two separate loading indicators.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2313]
First I see the blue bar under the header and then I see the big blue one right after.

We should just have one.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/228"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/228.
Please don't comment on it here.
