### ISSUE TITLE
[MIGRATED] Big blue loader is too intense.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2314]
When loading a project, the whole app turns blue and it feels a bit jarring, especially since the background color of the discover view and map view is grey. Can we do a similar animation, but on grey?

Thoughts @vazquez

**Comment by xmatthewx** [comment]
I can't find any UI comp that looks like that. @vazquez has some nice things in: https://github.com/mozilla/webmaker-android/issues/1680

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/229"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/229.
Please don't comment on it here.
