### ISSUE TITLE
[MIGRATED] Minimum text element size is too large

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2315]
I feel like given the size of the page, I want to make some of the text elements smaller, but can't

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/230"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/230.
Please don't comment on it here.
