### ISSUE TITLE
[MIGRATED] Change border-radius property on images to use % and increase maximum value to 50% to allow for circles.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2316]
Currently, the border radius property caps out at 32px - which is too small a range for large images taken by the camera. Let's change that to make better, rounder images!

**Comment by xmatthewx** [comment]
"Corner Radius" is below the other image options. You might not have noticed because of #2362.

**Comment by flukeout** [comment]
@xmatthewx Right right, it's there. I'll rename the issue to what I **REALLY** actually wanted.

**Comment by xmatthewx** [comment]
:+1:

**Comment by thisandagain** [comment]
:+1: :goat:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/231"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/231.
Please don't comment on it here.
