### ISSUE TITLE
[MIGRATED] Edit & Play mode headings could be improved

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2317]
Right now the heading titles for the two modes in the app are Project and Play, which I think aren't very descriptive. I think something like **Edit** and **Preview** would be better.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/232"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/232.
Please don't comment on it here.
