### ISSUE TITLE
[MIGRATED] Play mode swiping doesn't always go in the right direction

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2322]
I find that my swipe gestures get interpreted wrong about 10% of the time. I'll swipe down, and the page will transition right. Anyone else? Nexus 4/5

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/233"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/233.
Please don't comment on it here.
