### ISSUE TITLE
[MIGRATED] App blocks me from moving a photo more than about 40% off the page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2323]
Steps to reproduce
* Take a photo and add it to a page
* Move photo left or right to crop it
* The app prevents me from moving the photo prematurely

It should allow me to move the photo (or other elements) until there is just a small amount of the element visible. Currently, I can only hide about 40% of a photo that is as large as the page.

**Comment by xmatthewx** [comment]
Seems like we were too aggressive in how we prevent things from moving off the page. We should only require that a reasonable touch target remains on the screen.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/234"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/234.
Please don't comment on it here.
