### ISSUE TITLE
[MIGRATED] Not require login

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2327]
* Consider not needing login to create projects?
* Login is a big stumbling block for new users, lots of issues, let's revisit the sign up / sign in flow to reduce errors.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/235"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/235.
Please don't comment on it here.
