### ISSUE TITLE
[MIGRATED] Consider offline publishing / editing

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2328]
Right now, a constant connection is required to successfully edit a project. Can we reduce the number and frequency of network requests to make the experience better?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/236"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/236.
Please don't comment on it here.
