### ISSUE TITLE
[MIGRATED] Play, Project, Page and Link views are too similar and confusing.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2329]
These 4 views are very similar in appearance, but act very differently and accomplish different things. How can we differentiate them so that people aren't confused about what is going on?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/237"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/237.
Please don't comment on it here.
