### ISSUE TITLE
[MIGRATED] Reduce number of steps to add an image to a project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2330]
Right now it takes 8 taps or so, well - way too many. Let's look at this flow and make it simpler and apply our learnings to other flows.

**Comment by flukeout** [comment]
Here's a first pass.
Full PDF - https://dl.dropboxusercontent.com/u/109902/tiles/camera-flow-simplified.pdf

**Note** - For the image element in particular, I think it's okay to omit the "edit element" view, since the options there aren't as useful as for other elements. I think the flow would be slightly different for text elements, I'll create that next.

![image](https://cloud.githubusercontent.com/assets/25212/8579374/0db17970-2569-11e5-85a0-6aabf8bac3f3.png)

**Comment by xmatthewx** [comment]
Cool. I will miss the stickers, but this is the right way to go.

**Comment by flukeout** [comment]
@xmatthewx Shoot forgot about those - we can introduce them through another method?

**Comment by xmatthewx** [comment]
Add a third option: camera, gallery, stickers. But that'll require a spec of its own.

**Comment by flukeout** [comment]
Yeah, that's what i figured - or we could combine that with the 'web sources' or whatever.

**Comment by xmatthewx** [comment]
Right. We will definitely want image search on desktop since we essentially lose camera and gallery. We could explore stickers as a feature of that or a standalone thing.

**Comment by flukeout** [comment]
:star:

**Comment by flukeout** [comment]
![image](https://cloud.githubusercontent.com/assets/25212/8580804/6561f674-2571-11e5-894b-b9e7a34c61af.png)

**Comment by xmatthewx** [comment]
image :+1:  text :+1: link :+1:

**Comment by xmatthewx** [comment]
@k88hudson - can you give us a review of the design from a tech perspective?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/238"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/238.
Please don't comment on it here.
