### ISSUE TITLE
[MIGRATED] Build out a browser view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2331]
We need a way for desktop browser users to look at projects that are created.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/239"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/239.
Please don't comment on it here.
