### ISSUE TITLE
[MIGRATED] Figure out tapping and double-tapping actions.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2332]
A lot of people are double tapping elements to edit them, let's investigate this and add if appropriate. What other elements get double tapped?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/240"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/240.
Please don't comment on it here.
