### ISSUE TITLE
[MIGRATED] Add generic gesture listeners / GA events for various parts of the app.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2333]
Can we use Google Analytics to find out how people are interacting with the app? For example, we could attach event listeners for things like...
* Press & Hold
* Double Tap
* Pinch In/Out
* Swipe
* etc.
...to various parts of the app (elements, page editor, map view) and record it all in GA? We could use this data to see if people are interacting with the app in a way that we haven't anticipated. The goal would be to sort of do a metrics based usertesting.

@adamlofting thoughts?

**Comment by ryanw-se** [comment]
@flukeout As for the GA events part, a lot of progress was made on #2073, what did you have in mind for adding besides the ones already integrated?

**Comment by adamlofting** [comment]
We can definitely add this kind of instrumentation but we should also think about how we will use these results to make decisions (my gut says that the kind of understanding we're hoping to get from this can be achieved more easily via user testing at this point in the product life-cycle). 

For example, what % of users would you expect to record one or more `swipe` events based on the design of the app currently? I think to know this, we need to know about a users intent in a way we can't via GA (are they making, browsing, etc...). And without knowing what % of users have what intentions, it will be hard to know if the results are higher or lower than we anticipate.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/241"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/241.
Please don't comment on it here.
