### ISSUE TITLE
[MIGRATED] Add & support additional image formats

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2335]
What can we do about...
* GIFs
* Transparent PNGs

**Comment by ryanw-se** [comment]
@flukeout This needs the android label added, tickets regarding this matter are #2284 & #2251

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/242"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/242.
Please don't comment on it here.
