### ISSUE TITLE
[MIGRATED] Solve Z-index UX

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2337]
It's troublesome and gets in the way of creativity in projects that have large images. It's easy to get things stuck behind the big images.

**Comment by xmatthewx** [comment]
This includes the bug on pinch to zoom (#2163) and two proposals for new UX
 - "overlap" #1961
 - "send to back" #2102

**Comment by xmatthewx** [comment]
@flukeout - what do you think about pursing send-to-back option linked above?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/244"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/244.
Please don't comment on it here.
