### ISSUE TITLE
[MIGRATED] Figure out swiping between pages UX

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2338]
Right now, people don't swipe and it's hard to know that that's an option at all. How can we fix this and make navigation easier?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/245"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/245.
Please don't comment on it here.
