### ISSUE TITLE
[MIGRATED] Address precision of gestures

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2339]
Some of the gestures seem to be too sensitive and people move things by accident.

**Comment by toolness** [comment]
I noticed this when I was using the app yesterday--sometimes I would swipe down to go to the lower tile, but the app would think I was swiping left to go to the left tile.

**Comment by flukeout** [comment]
I second that, @toolness - I have a feeling I've filed that already, but I'll double check.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/246"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/246.
Please don't comment on it here.
