### ISSUE TITLE
[MIGRATED] Add ability to set the default / starting page for a project.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2340]
Right now we choose the first tile and don't let the user change it - let's figure it out.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/247"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/247.
Please don't comment on it here.
