### ISSUE TITLE
[MIGRATED] Add images to the gallery when I take a photo.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2341]

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/248"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/248.
Please don't comment on it here.
