### ISSUE TITLE
[MIGRATED] Resolve link behavior in map view

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2342]
Right now when you try to zoom in on a page while in Play mode, sometimes you hit a link and get taken somewhere else.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/249"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/249.
Please don't comment on it here.
