### ISSUE TITLE
[MIGRATED] Build moderation features

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2343]
@secretrobotron needs them and we need to figure something out.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/250"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/250.
Please don't comment on it here.
