### ISSUE TITLE
[MIGRATED] Add instrumentation to the app..

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2344]
What do we want to measure...
* ...
* ...

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/251"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/251.
Please don't comment on it here.
