### ISSUE TITLE
Sort out Code Editing UX

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2345]
Need to explore the code editor. Questions:

* At what level do users edit code?
  * Page Level (special coding page type)?
  * Element Level
* Do we have a separation of HTML, CSS & JS or just one page with all of the data?
* Do we allow users to 'break apart' existing elements to edit them
* How will we leverage Thimble to do this

**Comment by xmatthewx** [comment]
Tracking in https://github.com/mozilla/webmaker-desktop/issues/17
