### ISSUE TITLE
[MIGRATED] Explore social features

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2346]
* Follow people
* Favorite projects and pages
* Comments

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/252"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/252.
Please don't comment on it here.
