### ISSUE TITLE
[MIGRATED] Add ability to search projects

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2347]
By tag? How else?

**Comment by jgmac1106** [comment]
If localization is the goal do you get any kind of data that would allow
you to search by region?

**Comment by jgmac1106** [comment]
Language?

**Comment by ryanw-se** [comment]
This issue was moved to mozilla/webmaker-core#7

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/253"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/253.
Please don't comment on it here.
