### ISSUE TITLE
[MIGRATED] Asset library

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2348]
Add a way for people to access and store assets within their projects?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/254"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/254.
Please don't comment on it here.
