### ISSUE TITLE
[MIGRATED] Explore Animations & Transitions

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2349]
* Between pages?
* For elements?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/255"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/255.
Please don't comment on it here.
