### ISSUE TITLE
[MIGRATED] Investigate additional tinker modes.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2350]
What other tinker modes can we add to make things more customizable.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/256"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/256.
Please don't comment on it here.
