### ISSUE TITLE
[MIGRATED] UI - First launch experience

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2353]
Design a series of screens to introduce new users to app. 
 - [ ] gather benchmarks
 - [ ] prioritize key messages for wm
 - [ ] make it purdy
 - [ ] test, localize, rinse and repeat

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/259"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/259.
Please don't comment on it here.
