### ISSUE TITLE
[MIGRATED] Network - Move API calls to Android

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2354]
Related: #1946 #2005 #2179

All API calls are currently handled by `./lib/api.js` which is nice and simple but has one major drawback in that API requests need to complete prior to the current webview being dismissed / destroyed. This leads to issues in which long-running API requests can not be run in the background which blocks the UI and leads to performance issues (**particularly** on 2G and 3G cell networks). In addition, having the network layer exist in JS makes it more difficult to detect and manage network state effectively.

I recommend that we attempt to port the existing `./lib/api.js` API over to Java with as minimal changes as possible as a starting point. Tracking this specific SOW in #2355 

- [ ] Port existing `./lib/api.js` to Java (#2355)
- [ ] Add network availability detection
- [ ] Implement global network queue

**Comment by Pomax** [comment]
As first step, let's tackle the parity refactor, so the code does the same thing it does now, except through Java rather than JS.

- [ ] https://github.com/mozilla/webmaker-android/issues/2354

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/260"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/260.
Please don't comment on it here.
