### ISSUE TITLE
Android - Rename `window.Android`

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-android#2356]
As we move into new platforms, we need to rename `window.Android` to `window.platform` as to make it consistent / less confusing on browsers, iOS, etc.

**Comment by Pomax** [comment]
thinking about this in terms of namespace pollution, if we're doing this, can we figure out a way to somehow make this not hook into `window`, but "magically" work as a require module?

**Comment by thisandagain** [comment]
That makes a lot of sense to me as well. Having that contained within a module that provides the needed functionality when in a browser environment but otherwise defers to Android with the needed safety check (no more `if (window.Android)`) would be great.

@gvn Any thoughts?

**Comment by gvn** [comment]
Yeah +1 for making it a module even if that module is just using globals under the hood anyway. :wink:

It'll be nice to have all the business logic of platform detection/shimming abstracted away!

**Comment by gvn** [comment]
Would `device` make more sense as a name?

**Comment by thisandagain** [comment]
Options: `device`, `platform`, `engine`, etc. etc. Any strong options? I'm totally flexible as long as it isn't platform-specific (`window.Android`, `window.iOS`, `window.gecko`, etc.).

**Comment by gvn** [comment]
Either `device` or `platform` seems pretty legit.

**Comment by Pomax** [comment]
we went with platform
