### ISSUE TITLE
[MIGRATED] Whistler roadmap recap

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2358]
Here's a recap from our meeting in Whistler to ensure that our minds are aligned and that we catch any missing pieces.

#### 1.0.1 (Android) 7/3
- Bug / feedback triage
- Localization
- Image quality improvements

#### 1.0.2 (Android) 7/17
- Bug / feedback triage
- Additional instrumentation
- Batch API requests for project editing
- v1 browser-based view
- First-time use `design`

*/ / / / Snippet Launch / / / /*

#### 1.0.3 (Android) 7/31
- First-time use `build`
- No login required
- Image format support (PNG & GIF)
- Z-indexing UI implementation

#### 1.0.4 (Android) 8/14
- Reduce # of steps to add/upload elements
- UX refinement of views and nav: play, project, page, link destination (header and view titles)
- Set default start page `design`
- Tap elements vs tap UI `design`

#### 1.0.0 (Browser)
 - Feature parity w/ Android
 - Link tinker mode (URL, across user/project)

#### 1.1.0 (Browser & Android)
- Community / Social Features
    - Public profiles
    - Following
    - Favorites
    - Comments
    - Tighter Facebook Integration (mobile + desktop ??)

----

#### Backlog
 - refined gesture recognition (low pass filter)
 - moving pages
 - swipe between pages
 - search `design`
 - additional tinker modes `design`
 - asset library `needs discussion`
 - animation/transitions `needs discussion`
 - phone integrations (sms etc.) `needs discussion`
 - copy elements/pages `design`
 - page background color
 - code editor (to follow platform social)

cc @Pomax @flukeout @gvn @k88hudson @vazquez @secretrobotron @LauraReynal @thisandagain @cassiemc @cadecairos @toolness @ashleygwilliams @alicoding

**Comment by xmatthewx** [comment]
I've probably made some mistakes above. Correct me.

**Comment by xmatthewx** [comment]
Concerns on my mind: 
 - Views & nav
   - Resolving the views and android header requires a bit more clarity on the problems. Is the spec ok as designed? Do we have engineering capacity to redo headers pre-snippet?  
  - Back button behavior
 - Tinker link destinations
   - These were a v1 goal. URLs and cross-project/user links make the platform much more interesting and viable.  We have UI and most UX done. Is this a heavy lift to build?

**Comment by thisandagain** [comment]
I made some small changes above. Mostly just clarifying the limited scope of 1.0.1 (this Friday) and 1.0.2 (next sprint).

**Comment by flukeout** [comment]
Concerns o mine...

* Zooming
  * Limit max zoom in map mode - max zoom should be roughly a 2-up view, or the same size as when immediately after zooming out in Play mode.
  * Fix zoom origin to a point centered between the two fingers that are zooming
* Image quality pre-snippet - my sketches are barely recognizable at the current quality settings

**Comment by thisandagain** [comment]
Great points @flukeout 

Do we have a bug filed for the first issue? Getting image quality bumped is easy ... we can easily get that done this week.

**Comment by xmatthewx** [comment]
Note: Android release line up with heartbeats. Roadmap toward Browser release TBD. 
 - 1.0.1 
 - 1.0.1 
 - 1.0.1

**Comment by xmatthewx** [comment]
Great. Views and nav refinement in 1.0.4 seems much more doable. I filed an issue for zoom.

**Comment by flukeout** [comment]
I wanted to call out another one that I'm running into a lot.

I can't see the edges of the page when I'm using a big image - I have to jump back and forth a lot to see if I got the right 'cropping /clipping' effect 

**Solution** - Add a faint border overlay to demarcate the edges of the page I'm editing when an image is being scaled beyond the confines of the page.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/262"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/262.
Please don't comment on it here.
