### ISSUE TITLE
[MIGRATED] Limit max zoom in project view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2359]
Problem: currently, the map can be zoomed in too far, creating ambiguity between the project view and the page view. 

Solution: set the limit to fit two pages across, the scale used after exiting a page in play mode.

**Comment by Pomax** [comment]
counter point: "what is a page?" two pages across on a 4" device is extremely unsuited for what a 7" device will show - we're already seeing rather different sizing between those two screen sizes for current project zooms.

**Comment by xmatthewx** [comment]
Good point. 

We haven't addressed tablet yet, from a design, build, or roadmap perspective. 

Some of our choices should be absolute (zoom out requires a minimum tap target), some should be relative as you've noted. Are we ready to audit this across the app? Not yet from my perspective. But, I'm curious to hear how you think we could approach this better. 

cc @flukeout

**Comment by flukeout** [comment]
I think the limit should be based on a 1:2 ratio (or something similar) between the two sizes (max zoom vs pull page). Since we have different UI & capabilities in those two modes, we need to make the sizes distinct enough to know which one you're in.

Another reason for a strong distinction might be that we disable button links on the map view.

**Comment by Pomax** [comment]
second counter point: while it makes "not losing the project" easier, we'd now force people to do a lot of swiping just to get from one end of their big project to the other, which feels like we're simply trading one inconvenience for another. 

Would it make more sense to allow zooming out as far as you like until "all your pages are in view", at which point zoom lock occurs, with a translation restriction so you can never move your project "off screen" (you should always at least be able to see a [+] tile?)

**Comment by xmatthewx** [comment]
A quick visual to clarify this issue:

![zoom too much](https://cloud.githubusercontent.com/assets/53411/8439458/3d325db6-1f3a-11e5-962a-3ee362a23ae9.png)

![zoom improved](https://cloud.githubusercontent.com/assets/53411/8439461/3ef6588c-1f3a-11e5-9a5b-dd85533aeee5.png)

> If the idea is to not lose sight of your project, it seems the solution to that would be to ensure you can't lose sight of your project,

Totally agree @Pomax. Zoom out is a separate issue worthy of its own issue.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/263"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/263.
Please don't comment on it here.
