### ISSUE TITLE
[MIGRATED] Add contributing guidelines (again?)

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-android#2360]
It seems like a `CONTRIBUTING.md` was added in #1160, but I see no sign of the file anymore... Where did it go?

For reference, we've got a decent [`CONTRIBUTING.md` on teach](https://github.com/mozilla/teach.webmaker.org/blob/develop/CONTRIBUTING.md). I could use it as a basis for our own contribution guidelines, though I'd need some help with the Android-specific stuff.

**Comment by thisandagain** [comment]
:+1:

**Comment by ryanw-se** [comment]
:+1: Definitely think this would be a good idea, would be good to include contact information for the IRC and forums somewhere in it as well.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/264"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/264.
Please don't comment on it here.
