### ISSUE TITLE
[MIGRATED] Scrolling in element editor is difficult

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2362]
It's difficult to scroll vertically in the element editor because a gesture that begins on a slider isn't read as a scroll even if it's vertical. Slider sometimes jumps.

Is it possible to constrain the range or angle of gestures read as an attempt to use the slider?

**Comment by flukeout** [comment]
:+1: running into this too

**Comment by LauraReynal** [comment]
:+1: seen this too !

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/265"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/265.
Please don't comment on it here.
