### ISSUE TITLE
[MIGRATED] I often start "signing in" on the "sign up" page.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2366]
I think we need a title above each of the sign in and sign up pages. I think it's too hard to tell which action you're performing. Also, generally - which page is more likely to be useful by default? Sign up should probably only be the default for first time users.

**Comment by errietta** [comment]
dibz!

**Comment by xmatthewx** [comment]
@errietta - I believe that sign-up currently shows by default for new users on a new installation. Can you confirm? Beyond that, I think this is a design task for @vazquez when he has a spare moment.

**Comment by errietta** [comment]
@xmatthewx not ONLY for new users tho, if you log out and kill the app/reboot it shows sign up instead of sign in

**Comment by xmatthewx** [comment]
Great. Thanks. That's okay -- we should emphasize sign up, though I do think the sign in link get's lost down on the bottom. This needs to be improved via a designer before we adjust the build.

**Comment by errietta** [comment]
Yus, designs  plz then maybe I can write pwetty code :cat:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/267"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/267.
Please don't comment on it here.
