### ISSUE TITLE
Image element border radius appears differently in element preview and on page

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2367]
Steps to reproduce
* Add an image element
* Change it's source by taking a photo with your camera
* In the element view, max out the corner radius to 32px
* Look at the overall appearance of the preview photo, it's VERY rounded
* Go back to the page
* It's not VERY rounded anymore.. IS IT????

I think we're using an absolute px value on both elements here, so the preview looks a lot rounder than the final product. Should be addressed when we make the change outlined in #2316 - but a bug for now nontheless.

**Comment by thisandagain** [comment]
Tracking RC fix in #2316
