### ISSUE TITLE
[MIGRATED] It's too easy to move elements by accident.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2368]
When I select an element to edit it on a page, it often moves. We can solve this in two ways:
* **Cool way** - Add a threshold to the move gesture, so that I actually have to move my finger a bit before the element starts moving. 
* **Lame way** - Have it so that the first tap only selects it, and doesn't move it, the second tap can start a move

Let's do the first solution?

@xmatthewx @thisandagain Is this what you guys meant by the low-pass filter?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/268"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/268.
Please don't comment on it here.
