### ISSUE TITLE
[MIGRATED] device photographs may end up with the wrong orientation

### ISSUE THREAD

**Issue by Pomax** [mozilla/webmaker-android#2371]
taking an on-device picture can lead to taking a picture in portrait mode, but having webmaker-android add it to the page in landscape mode.

Perhaps we should add an orientation control, so we can do 90 degree turns clockwise/counter clockwise in the editor view, in addition to the far less precise finger rotation?

**Comment by xmatthewx** [comment]
:+1:

**Comment by thisandagain** [comment]
The OS should detect the orientation of the photo and return is appropriately. It seems to do this most of the time (confirming on a Nexus 5) but we likely have a missing edge-case. I'd rather fix it at the device level that add complexity to the page editor.

**Comment by xmatthewx** [comment]
Ah. Glad to hear it works on other devices. Doesn't work on my Sony. They have proprietary camera software you can't replace w/o root. I believe that Sony is getting out of the mobile business ( :confused:  ), so I wouldn't hustle to fix it here. 

Sony Xperia Z3C 
model D5803 
Android 5.0.2

**Comment by ryanw-se** [comment]
I'm trying to think of the best way to tackle this issue, does anyone know if there is an existing implementation for setting the orientation of a photo? If there is I could easily add a JS interfacable method for retrieving the orientation of a photo, however I would need to conform the result to the current implementation (if there is any).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/270"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/270.
Please don't comment on it here.
