### ISSUE TITLE
[MIGRATED] Text element starts out smaller than the minimum allowed size, creating strange behaviour

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-android#2373]
Steps to reproduce
* Add a text element
* Start scaling it
* Immediately it jumps up in size a little bit
* You can't make it smaller than the size it jumped to
* You can't make it as small as when you first added it to the page

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/271"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/271.
Please don't comment on it here.
