### ISSUE TITLE
[MIGRATED] Can i get my project back?

### ISSUE THREAD

**Issue by viswanathamsantosh** [mozilla/webmaker-android#2377]
I made my project in nightly build and here goes the link https://beta.webmaker.org/projects/447 

Can I get my project back ?

**Comment by xmatthewx** [comment]
cc @secretrobotron

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/272"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/272.
Please don't comment on it here.
