### ISSUE TITLE
[MIGRATED] Remotely test link and destination UX

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2380]
We should run a remote test specifically around links. There's room for improvement. We should also clarify the back buttons ideal behavior. see #2306 and #2242

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/273"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/273.
Please don't comment on it here.
