### ISSUE TITLE
[MIGRATED] Regression: Links don't work

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2381]
**Repro Steps:**
1. Add link button
2. Set link button's destination
3. Enter play mode
4. Tap button

**Expected:** Focus shifts to link's destination
**Actual:** Nothing happens

**Comment by Pomax** [comment]
I'm at Cascadia this week, and will not get to this.

**Comment by xmatthewx** [comment]
This is busted on the public build? This should have blocked the last release. Let's make this a top priority when people return next week.

**Comment by ryanw-se** [comment]
As a side note, we really should add a regression label so users don't have to make a label as a title. It would also help us keep track of all regressions.

**Comment by gvn** [comment]
@toolness is this something you can take?

**Comment by toolness** [comment]
Sure, I can try! (Am unfamiliar w/ the code itself but am happy to acquaint myself with it, etc.)

**Comment by gvn** [comment]
Awesome! Yeah, I think it's a decent chunk of debugging, but self contained and a good way to get started on the app. :+1:

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/274"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/274.
Please don't comment on it here.
