### ISSUE TITLE
[MIGRATED] react loader-mixin needs to be required explicitly for npm 3+

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/webmaker-android#2385]
not urgent, but an easy fix

```
npm WARN peerDependencies The peer dependency react-loadermixin@* included from react-imageloader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/275"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/275.
Please don't comment on it here.
