### ISSUE TITLE
[MIGRATED] Update documentation to include the use of webmaker-core

### ISSUE THREAD

**Issue by ryanw-se** [mozilla/webmaker-android#2392]
I get a error when running ```npm run build```, it says "webmaker-core isn't installed" but the documentation is rather vague about the process on how to install webmaker-core.

**Comment by xmatthewx** [comment]
https://github.com/mozilla/webmaker-core/

**Comment by ryanw-se** [comment]
@xmatthewx Thanks, it works now. That documentation should definitely be put in the webmaker-android repository as well, or mentioned to prevent confusion!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/276"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/276.
Please don't comment on it here.
