### ISSUE TITLE
[MIGRATED] Able to set title longer than maximum

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2394]
1. Go to project settings
2. Type in super long title
3. Press back button

Title should be set to something lengthy now. Go back to settings to check.

cc @flukeout @cadecairos (does this affect the DB?)

**Comment by secretrobotron** [comment]
cc @xmatthewx anybody working on bugs?

**Comment by xmatthewx** [comment]
Does it just get truncated? Or does everything break? We don't have any hands tackling bugs this week.

**Comment by cadecairos** [comment]
it won't take down the db,  since the title column is defined with varchar without a length specifier (synonymous with the text datatype). Also, we didn't add any joi validation for title , so it's basically just client side validation right now. 

I think if we're limiting length client side we want to do the same server-side, since it's trivial to intercept and modify requests with a proxy.

**Comment by secretrobotron** [comment]
Doesn't get truncated, and doesn't *seem* to break anything. Just weird because we have a limit and it's not enforced.

**Comment by flukeout** [comment]
Let's nuke the limit as long as well handle the long names well in the UI. The name only seems to appear in the make and discover views for the time being anyway.

**Comment by xmatthewx** [comment]
Let's set a generous limit. 140 characters? 256? Otherwise, someone will drop War & Peace in there just because they can.

**Comment by cadecairos** [comment]
my thoughts exactly. can we file a bug on api.wmo to add validation to that param? clientside validation is easy to step around

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/278"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/278.
Please don't comment on it here.
