### ISSUE TITLE
[MIGRATED] QA/Testing scripts

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2395]
Prior work by @k88hudson here: https://gist.github.com/k88hudson/16e0b6a720f33e1f7c3e
Some more brainstorming here: https://etherpad.mozilla.org/webmaker-qa-stuff-vectors

* How do we split this up into small, repeatable tasks that people can jump in and test?
* Does it cover localization, QA, and user-testing?

cc @flukeout

**Comment by secretrobotron** [comment]
QA Checklist for Localization: https://github.com/mozilla/webmaker-android/issues/2061

**Comment by secretrobotron** [comment]
Would rather use https://github.com/mozilla/webmaker-core/issues/16, but there are no milestones. Help, @xmatthewx ?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/279"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/279.
Please don't comment on it here.
