### ISSUE TITLE
[MIGRATED] Share links should open Android app immediately when possible

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2396]
beta.webmaker.org links open projects in mobile browser. User has to click on thumbnail in browser to open in app. Should skip that step and go right into app.

**Comment by ryanw-se** [comment]
@secretrobotron This seems pretty straight foward to implement on the android side of things, do you mind adding the android label to this?

**Comment by secretrobotron** [comment]
@ryanw-se this is a regression, right? Any reason it changed?

**Comment by ryanw-se** [comment]
@secretrobotron Possibly, I'd have to look into it further to confirm. Its most likely do to a change in the URL or something of that sort, the Android code base is relatively stable.

**Comment by secretrobotron** [comment]
@ryanw-se were you able to make any progress on this?

**Comment by ryanw-se** [comment]
@secretrobotron Its most likely a issue of some sort regarding webmaker-browser/#123

**Comment by secretrobotron** [comment]
:+1: thanks @ryanw-se

**Comment by secretrobotron** [comment]
@k88hudson looks like https://github.com/mozilla/webmaker-browser/pull/136 may have broken the experience for native app users. I'm no longer dropped straight into the app, but pushed to browser first (on Android).

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/280"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/280.
Please don't comment on it here.
