### ISSUE TITLE
[MIGRATED] Add `npm run build` to gradle

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2397]
Right now you have to run `npm run build` before compiling in Android Studio to ensure you have the latest version of the core compiled as well (most likely npm linked for local dev).

We should remove this extra step by just programatically running `npm run build` as part of the AS compilation process...I'm assuming this is a gradle thing.

**Comment by gvn** [comment]
@ryanw-se this might be a good one for you if you're interested!

**Comment by ryanw-se** [comment]
@gvn I believe something like this was implemented a while back, it must have broken. Anyways, I can definitely try to take a look over the week and see what broke if there is a previous implementation.

**Comment by gvn** [comment]
I wonder if it will work now that I aliased `npm start` to `npm run build`. My Android device is charging, but I can test that out soon...

**Comment by ryanw-se** [comment]
@gvn If you test it and it works let me know, otherwise I can take a look at it sometime this week.

**Comment by gvn** [comment]
K. Thx!

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/281"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/281.
Please don't comment on it here.
