### ISSUE TITLE
Alias `npm start` to `npm run build`

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#2398]

**Comment by ashleygwilliams** [comment]
lol wat even are these tags

**Comment by gvn** [comment]
`¯\_(ツ)_/¯`

**Comment by ryanw-se** [comment]
@ashleygwilliams ```tech-debt``` are issues that require further technical discussion before things can move forward, ```Things that are cool``` was a tag created to show off some awesome projects that are being created with webmaker and the ```first bug``` tag is for users who want to get started contributing to the web maker project and are looking for easy things to start off on.

**Comment by gvn** [comment]
That's a better answer. :)

**Comment by ashleygwilliams** [comment]
much appreciated @ryandang :)
