### ISSUE TITLE
[MIGRATED] Feedback on Webmaker from Bangladesh -- July 2015

### ISSUE THREAD

**Issue by cecilepompei** [mozilla/webmaker-android#2399]
Here are the comments we heard again and again:

 - No internet available to play on the app - hard for people to use the App
 - The app is too data heavy >> people see when it starts to download and rush to stop it
 - too slow process to create 
 - No email login is a big problem - we heard to do Facebook login or mobile phone login
 - Video add on would be great
 - Monetization — could we add a way to link up with mobile money from the app at some point
 - Can what we create appear on the web and could be searched in google?

Good feedback as well on the fact that you can see what is around you and it is localised (very important) !

**Comment by kumarrishav** [comment]
Point No: 4 is fixed now.
+1 for Point No: 3 . This is one of the major issue 
User don't have much patience to create any makes as it takes too much time to create. i think it is possible on very high speed data.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/282"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/282.
Please don't comment on it here.
