### ISSUE TITLE
[MIGRATED] SSL Certificate Error

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-android#2400]
Error while opening the app:

<img src="https://cloud.githubusercontent.com/assets/1391451/8618752/bcb817e2-2719-11e5-9b87-6c51d76e1433.jpg" width="300">

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/283"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/283.
Please don't comment on it here.
