### ISSUE TITLE
[MIGRATED] Update placeholder text on sign-in to include email

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2401]
Sign-in now accepts Username or Email. Update placeholder text accordingly.

**Comment by cadecairos** [comment]
When did app sign in start accepting emails?

**Comment by xmatthewx** [comment]
Unsure. Just tried it and it worked.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/284"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/284.
Please don't comment on it here.
