### ISSUE TITLE
[MIGRATED] Display project title in header

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-android#2402]
Android header should display project title in the project viewer and editor.

**Comment by ryanw-se** [comment]
WIth our current architecture I don't think this is possible, the current way allows us to send data from Android across the JS bridge, we'd have to reverse that and create a way to send data from JS to the Android side of things to properly implement this and other title tickets.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/285"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/285.
Please don't comment on it here.
