### ISSUE TITLE
[MIGRATED] Sharing on whatsapp - the project does not come as a link

### ISSUE THREAD

**Issue by cecilepompei** [mozilla/webmaker-android#2403]
We have people sendingus their project on whats app and it does not appear as a clickable link - no way to check it out

**Comment by ioana-chiorean** [comment]
<img src="https://cloud.githubusercontent.com/assets/1391451/8625634/bad6e168-2748-11e5-88c0-b4e4310b4a94.jpg" width="300">

**Comment by ryanw-se** [comment]
@cecilepompei Do you have anymore information? What does the outut look like? Does it happen ocassionally or all of the time? Does it only happen when you send it a certain way?

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/286"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/286.
Please don't comment on it here.
