### ISSUE TITLE
[MIGRATED] Standardize the naming convention for issue tags

### ISSUE THREAD

**Issue by ryanw-se** [mozilla/webmaker-android#2406]
Some of our tags start with upper case, while others start with lower cases, some tags also use dashes as a replacement to spaces, while others do not. We also have some tags that are hardly used and can be consolidated.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/288"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/288.
Please don't comment on it here.
