### ISSUE TITLE
[MIGRATED] Google Play Store translations are wrong

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-android#2407]
Looks like the Play Store was translated, but according to our localization teams, it's not quite right.

* How did it happen? Are we paying for it?
* How can we change it? Would like to give our localizers access to it.

/cc @fauzanalfi @kelimuttu @maktrix @panaggio @peiying2 @bellayet

See https://github.com/mozilla/webmaker-launch/issues/47#issuecomment-120825046 for specifics.

**Comment by peiying2** [comment]
according to Google Play website:
https://www.google.co.id/intl/id/mobile/play/ - Google Play remains in English.  Although there is no Bengali in the language dropdown menu (bottom right corner of the screen), it seems the convention if you switch to another language.  

However if the text is Google Play Apps (Books, Games, Music, etc), the "product" name is translated.  In this case, the word "Apps"  would be translated: https://play.google.com/store?hl=id

Where does the Google Play Store phrase appear? Or does it say Google Play Apps?  Regardless, from the official site, it looks like Google Play remains in English, the rest can be translated.

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/289"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/289.
Please don't comment on it here.
