### ISSUE TITLE
[MIGRATED] feedback from a UX expert in Africa

### ISSUE THREAD

**Issue by cecilepompei** [mozilla/webmaker-android#2408]
Had the opportunity to sit with a human centered design / UX expert in Africa (and local!) that is super cool and knowledgable. I got him to use Webmaker and give us some extra pointers!

It is a mix of feedback, ideas and questions from looking at Webmaker together:

UX Webmaker
People want something locally relevant, even in Emerging Markets

Overall feedback
- We need to think of whether people want or not other people to remix their content
- if the understanding of what Webmaker is trying to do is clear, there could be an interest > not necessarily super clear from just looking at it
- the competition are Facebook, pinterest
- not much themes to find out other people s stuff (like Pinterest) — can we index what we want? can we create categories/themes?
 - with technology, people need more very fast in terms of functionality > how does Webmaker upgrade? does more for the user?
 - long term idea: suggest of what you should look at on Webmaker
 - instead of deleting, you can archive projects
 - can we search for a project? 
 - can work on something without people seeing and then only publish when it is ready?

feedback on Images:
a) why pre found images?
b) editing could be more intuitive - you expect to click on + to add images
adding other images - how do i choose the standard images - how do I get them?
c) database of images could be good: custom images / stencils or choose your own image
d)another idea could be library of all images that people are using: opt in or out to decide which images people want to share or not

Feedback on localization & sharing 
- so far no localization of the projects around me - is that coming? @secretrobotron - I thought it was a feature?
 - technology with identity > can i see at what people in other parts of the world has done (similar person in london, somewhere else)?
 - how do I connect with people? need to fall part of a community and interact
 - collaborating with people in other country: can you collaborate on a project together?

**Comment by secretrobotron** [comment]
cc @flukeout @k88hudson @gvn @xmatthewx

**Comment by k88hudson** [comment]
This would be great to go over during the San Fran workweek

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/290"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/290.
Please don't comment on it here.
