### ISSUE TITLE
Image uploading: Compress images locally

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#750]
Before we upload to images, we will want to compress them.

We may be able to use on-device APIs to get smaller images anyway, or we might have to go with a web/js solution such as https://github.com/jimmynicol/image-resizer

**Comment by k88hudson** [comment]
Strategy should work on Android 4.2

**Comment by thisandagain** [comment]
Would be hugely helpful if we can push to the device APIs. Resizing images on the main thread is killer for performance on Android (and iOS).

**Comment by k88hudson** [comment]
So it turns out that cordova definitely gives us access to on-device compression settings on Android and iOS. For FFOS unfortunately I don't think that's the case

**Comment by thisandagain** [comment]
Awesome. I wonder if we could add a canvas-based polyfill for Firefox OS as using the OS-specific implementations will no-doubt be more performant.
