### ISSUE TITLE
CPU Spiking in Firefox

### ISSUE THREAD

**Issue by gvn** [mozilla/webmaker-android#782]
I've been noticing some CPU spiking behavior in Firefox (36 OSX) running the app.

![screenshot 2015-01-22 10 48 31](https://cloud.githubusercontent.com/assets/206379/5862167/647fec14-a224-11e4-9ef0-5addf73aa52b.png)

![screenshot 2015-01-22 10 48 01](https://cloud.githubusercontent.com/assets/206379/5862169/689b0892-a224-11e4-8868-9436848c03b5.png)

**Comment by Pomax** [comment]
are there specific steps that stably reproduce this for you? On windows, at least, there does not appear to be any spiking at all (trying OSX today)

**Comment by thisandagain** [comment]
I've been working in Firefox Developer Edition (Mac OS 10.10) for the past couple weeks and haven't experienced it. I suggest that this be moved to the "Tech" milestone.

**Comment by Pomax** [comment]
@gvn if the same is true for you, let's move it.

**Comment by gvn** [comment]
I'll give it a shot in FFDE...

**Comment by gvn** [comment]
Still running pretty hot...

![screenshot 2015-02-23 11 25 30](https://cloud.githubusercontent.com/assets/206379/6335226/d1e7fdc6-bb4e-11e4-953e-d6a14905c8af.png)

**Comment by Pomax** [comment]
I'm going to have to see what this does on OSX for me. On windows at least, I don't see it going about 5~7% -- got any STR that let you guaranteed run into this?

**Comment by gvn** [comment]
1. Open app + dev tools + responsive mode.
2. Wait.
3. Profit!

**Comment by Pomax** [comment]
those seem rather unreliable STR. I'll work with them, but just having something "sit for 10 minutes" seems less efficient than taking some actions that lead to more CPU usage =P

**Comment by gvn** [comment]
Yeah, I know that sucks, but that's seriously the best I can give you. If I figure out a more specific path to repro I'll definitely put it here.
