### ISSUE TITLE
npm name doesn't match repo name

### ISSUE THREAD

**Issue by k88hudson** [mozilla/webmaker-android#906]
@cadecairos pointed out it's kind of weird that the npm package is called `webmaker` and the repo is `webmaker-app`. Although this isn't hugely uncommon (a lot of things have different repo names from npm names) it is a bit unintuitive.

**Comment by k88hudson** [comment]
also i would be 100% ok with changing it

**Comment by cadecairos** [comment]
It took me a while to figure out how to properly link webmaker[-app] to webmaker-app-cordova because of the subtle title difference.

**Comment by gesa** [comment]
Is this as simple as changing this line? <https://github.com/mozilla/webmaker-app/blob/master/package.json#L2> Or does it actually open a whole big can of worms?
