### ISSUE TITLE
[MIGRATED] Publishing requires connectivity

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-android#954]
AFAIK, the current UI blocks the user until the publishing is done.  This means that on very slow networks, publishing renders the app useless until the upload is complete.  

Ideally we'd detect slow upload conditions, let the user go on w/ their life, do publishing in the background, and tell the user through some notification that the publishing was done.

(similar note on being able to declare the intent to publish even while offline)

I don't know how to deal w/ the implications for the share flow, etc. -- real UX work to figure out here.

**Comment by k88hudson** [comment]
This is definitely an important one

**Comment by thisandagain** [comment]
The new publishing flow is now async and has nicer error states which reduces a little bit of pressure here. #1051

**Comment by thisandagain** [comment]
Related to #1460

**Comment by toolness** [comment]
<a href="https://github.com/mozilla/webmaker-core/issues/24"><img src="https://raw.githubusercontent.com/toolness/learning-issue-migrator/master/img/migrated.png"></a>
This issue has been moved to https://github.com/mozilla/webmaker-core/issues/24.
Please don't comment on it here.
